### ISSUE TITLE
update shows error on some png files

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1005]
![image](https://user-images.githubusercontent.com/48617390/165775807-421b1c9d-686a-4038-8840-e70313e047d6.png)
while updating uba from 28.72 to 29.04 more than 50 errors came.. App is updated though 

material layout looks like this
![image](https://user-images.githubusercontent.com/48617390/165777539-fdd750b1-ee6a-418d-8e7a-f153060e4178.png)

**Comment by eliranwong** [comment]
oh, I will check.  thanks for reporting it.

**Comment by eliranwong** [comment]
The easiest way for you to fix:

1) download the following zip
https://github.com/google/material-design-icons/archive/refs/tags/4.0.0.zip

2) unzip it

3) rename the folder to "material"

4) move it to UniqueBible/htmlResources/

**Comment by eliranwong** [comment]
@onegladiator4u please try update to version 29.14 and kindly let me know if it works or not. many thanks.

**Comment by onegladiator4u** [comment]
> @onegladiator4u please try update to version 29.14 and kindly let me know if it works or not. many thanks.

it's working now brother . Thanks .
