### ISSUE TITLE
Material layout reference button 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1009]
Hey brother , 
i noticed that only reference button of bible version is opening min-control. Book reference (Eph 6:10) is opening differently. Is there an option to change it to mini-control ?
![image](https://user-images.githubusercontent.com/48617390/166193066-99588dcc-c2c3-42fb-bb56-19dea0f422d0.png)

Also noticed that there are two set config flag options in menu. One is in UBA Preference and other one is outside 
![image](https://user-images.githubusercontent.com/48617390/166193510-041500f2-b3e0-4e7e-be0a-37e236b07a0d.png)

**Comment by eliranwong** [comment]
What do you want to open when you click the reference button.  Please note that there are currently two buttons open mini control about bible navigation.

<img width="192" alt="Screenshot 2022-05-02 at 10 41 09" src="https://user-images.githubusercontent.com/25262722/166215324-a6714a64-c382-43fe-adf0-aab23fbc7a3e.png">

See the screenshot above, the left one opens mini control for bible version, the right one opens for bible book selection.  I don't see what else can be opened about bible navigation.

Thanks for reports of duplication of set Config Flags options.

**Comment by onegladiator4u** [comment]
> What do you want to open when you click the reference button. Please note that there are currently two buttons open mini control about bible navigation.
> 
> <img alt="Screenshot 2022-05-02 at 10 41 09" width="192" src="https://user-images.githubusercontent.com/25262722/166215324-a6714a64-c382-43fe-adf0-aab23fbc7a3e.png">
> 
> See the screenshot above, the left one opens mini control for bible version, the right one opens for bible book selection. I don't see what else can be opened about bible navigation.

Oh, i didn't notice the button for bible book selection . Thanks

**Comment by eliranwong** [comment]
duplicated item removed in the latest version https://github.com/eliranwong/UniqueBible/commit/14895efa3aba48c74e610008e0d4ed7da5cdcb55

also, there is a gui for changing colour button, @onegladiator4u from your screenshot, I can see you changed the button colour nicely.

**Comment by onegladiator4u** [comment]
> there is a gui for changing colour button,

That's great bro. Thanks
