### ISSUE TITLE
Share won't open unknown Bible versions

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1011]
I clicked on the address in share window. it opened like this
![image](https://user-images.githubusercontent.com/48617390/166869326-7de9b6df-a520-409d-998c-57d0a75b23ba.png)
I think here should be some filter to change the Bible version if its not found on server

**Comment by eliranwong** [comment]
> I think here should be some filter to change the Bible version if its not found on server

Good idea.  If not installed, I can redirect to KJV.

btw, what is full name of MOV?  Is it copyrighted?  If it does not have copyright issue.  I can upload to my server.

**Comment by onegladiator4u** [comment]
its Malayalam Old Version . I don't know whether it's copyrighted or not. I found it here
https://www.ph4.org/b4_1.php?l=ml&q=mybible

**Comment by eliranwong** [comment]
in the latest update: https://github.com/eliranwong/UniqueBible/commit/a4a74520e2b631356342836cd71fc6c95821bcda

Redirect to config.favouriteBible, if bible version requested is not installed.
