### ISSUE TITLE
Couldn't update webtop 

### ISSUE THREAD

**Issue by frank4532** [eliranwong/UniqueBible#1024]
Hi,
I could not update webtop Uba from 2.49 to 2.51. the update window says ok you have updated but after the restart I am still on version 2.49. I use SparkyLinux (Debian) openbox.

**Comment by otseng** [comment]
Can you run update again and see if the issue still exists?

**Comment by frank4532** [comment]
I tried to update again but the issue is still there. Thanks.

**Comment by eliranwong** [comment]
Can you try if manual update is ok or not:

1) Exit the UBA

2) On webtop, right-click and select "Konsole"

<img width="241" alt="Screenshot 2022-05-14 at 09 31 34" src="https://user-images.githubusercontent.com/25262722/168424106-cb6bc8a1-b7ff-4789-9a1e-03a18a8f91cd.png">

3) Enter the following two commands:

> cd UniqueBible

> git pull

4) Restart UBA when update finished.

Please kindly let me know if it work or not, many thanks.

**Comment by frank4532** [comment]
The manual update works. Many thanks.

**Comment by eliranwong** [comment]
Thanks for checking.  Can you check one more thing?

1) Please go to menu UniqueBible > Config Flags

<img width="374" alt="Screenshot 2022-05-14 at 16 04 37" src="https://user-images.githubusercontent.com/25262722/168432661-61ce975a-7f24-449d-b863-adbb44e47c31.png">

2) In search field, enter "git"

<img width="604" alt="Screenshot 2022-05-14 at 16 04 17" src="https://user-images.githubusercontent.com/25262722/168432681-254c6166-6e30-44aa-b932-587e411bd7e3.png">

3) Is the item "updateWithGitPull" selected on your side as my screenshot indicated?

**Comment by frank4532** [comment]
No it isn't.

**Comment by eliranwong** [comment]
I suggest you to check this option, so to update via UBA

**Comment by frank4532** [comment]
Hi Eliran,
Thank you very much. I did what you suggested and now Uba update works well.
Best regards
Lorenzo
