### ISSUE TITLE
Add ability to import/export Bible Collections

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#1028]
Add ability to import/export Bible Collections

**Comment by eliranwong** [comment]
@otseng  For export file, please do not use ".txt" extension, to avoid important other text files by mistake.

Please consider to use "*.filter" for live filter and "*.collection" for bible collections.

I use "*.color" for exporting colour settings.

**Comment by otseng** [comment]
> Please consider to use "_.filter" for live filter and "_.collection" for bible collections.

Changed.
