### ISSUE TITLE
Downloading does not work... 

### ISSUE THREAD

**Issue by jajpater** [eliranwong/UniqueBible#103]
I can only download one module or I have to restart the programm.
It gives the following error: 

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.8/threading.py", line 870, in run
        self._target(*self._args, **self._kwargs)
      File "/home/user/UniqueBible-master/gui/Downloader.py", line 81, in downloadFile
        self.parent.moduleInstalled(self.databaseInfo)
      File "/home/user/UniqueBible-master/gui/MainWindow.py", line 445, in moduleInstalled
        self.parent.isDownloading = False    
    AttributeError: 'builtin_function_or_method' object has no attribute 'isDownloading'

**Comment by jajpater** [comment]
It seems to have to do with graphics. When clicking the download ok button I now get a seg fault... 

    qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve 
    property: #linearGradient4205
    qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve 
    property: #linearGradient4205
    qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve 
    property: #linearGradient4205
    qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve 
    property: #linearGradient4205
    QObject::setParent: Cannot set parent, new parent is in a different thread
    qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve 
    property: #linearGradient4205
    qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve 
    property: #linearGradient4205
    QWidget::repaint: Recursive repaint detected
    QWidget::repaint: Recursive repaint detected
    QBackingStore::endPaint() called with active painter; did you forget to destroy it or call 
    QPainter::end() on it?
    qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve 
    property: #linearGradient4205
    [1]    426431 segmentation fault (core dumped)  python main.py

I am on Ubuntu 20.10

**Comment by otseng** [comment]
Can you try changing lines 445 and 450 in MainWindow.py to?
```
       self.isDownloading = False
```

**Comment by otseng** [comment]
I'm also seeing error:
QObject::setParent: Cannot set parent, new parent is in a different thread

**Comment by eliranwong** [comment]
> Can you try changing lines 445 and 450 in MainWindow.py to?
> 
> ```
>        self.isDownloading = False
> ```

Does it work?

**Comment by eliranwong** [comment]
I m checking and will try to fix it.

**Comment by jajpater** [comment]
> > Can you try changing lines 445 and 450 in MainWindow.py to?
> > ```
> >        self.isDownloading = False
> > ```
> 
> Does it work?

This only yields a SyntaxError: invalid syntax

**Comment by jajpater** [comment]
> > Can you try changing lines 445 and 450 in MainWindow.py to?
> > ```
> >        self.isDownloading = False
> > ```
> 
> Does it work?

No it does not.

**Comment by eliranwong** [comment]
fixed in this commit: https://github.com/eliranwong/UniqueBible/commit/39ef5e9a0dc3606f96048df5462cc920db69a95c

@jajpater sorry for the trouble.

**Comment by eliranwong** [comment]
@jajpater could you try again and kindly let me know if it works for you now?

I tried on Debian 10 with a fresh installation and it works.  Just want to make sure if it works for others too.

thanks for reporting the issue.

**Comment by jajpater** [comment]
It works like a charm! Thank you so much!
