### ISSUE TITLE
Jump directly to part of mp3 when playing a chapter file

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#1034]
Hi guys,
I got mp3 files for my language Bible . I also have the information on the starting and ending of the timing for the verse of the Bible chapter.
Is there a chance that you could make files that can be used along mp3 files that import timings like these to play each verse than full chapter. Otherwise we have to cut each chapter mp3 to verses mp3.
i have html that has info like this

var timings = [
    { label: "1", start: 3.5, end: 21.05 },
    { label: "2", start: 21.3, end: 32.35 },
    { label: "3", start: 32.6, end: 36.83 },
    { label: "4", start: 37.08, end: 47.33 },
    { label: "5", start: 47.58, end: 57.55 },
    { label: "6", start: 57.8, end: 68.59 },
    { label: "7", start: 68.84, end: 79.59 },
    { label: "8", start: 79.84, end: 85.91 },
    { label: "9", start: 86.16, end: 96.63 },
    { label: "10", start: 96.88, end: 101.51 },
    { label: "11", start: 101.76, end: 110.99 },
    { label: "12", start: 111.24, end: 122.35 },
    { label: "13", start: 122.6, end: 132.91 },
    { label: "14", start: 133.16, end: 158.95 },
    { label: "15", start: 159.2, end: 168.27 },
    { label: "16", start: 168.52, end: 179.83 },
    { label: "17", start: 180.08, end: 192.03 },
    { label: "18", start: 192.28, end: 198.59 },
    { label: "19", start: 198.84, end: 215.79 },
    { label: "20", start: 216.04, end: 225.59 },
    { label: "21", start: 225.84, end: 234.31 },
    { label: "22", start: 234.56, end: 240.79 },
    { label: "23", start: 241.04, end: 249.19 },
    { label: "24", start: 249.44, end: 258.67 },
    { label: "25", start: 258.92, end: 269.91 },
    { label: "26", start: 270.16, end: 289.19 },
    { label: "27", start: 289.44, end: 298.75 },
    { label: "28", start: 299, end: 314.35 },
    { label: "29", start: 314.6, end: 324.03 },
    { label: "30", start: 324.28, end: 334.79 },
    { label: "31", start: 335.04, end: 350.03 },
    { label: "32", start: 350.28, end: 362.99 },
    { label: "33", start: 363.24, end: 382.35 },
    { label: "34", start: 382.6, end: 402.11 },
    { label: "35", start: 402.36, end: 411.87 },
    { label: "36", start: 412.12, end: 426.03 },
    { label: "37", start: 426.28, end: 442.53 },
    { label: "38", start: 442.78, end: 448.71 },
    { label: "39", start: 448.96, end: 457.05 },
    { label: "40", start: 457.3, end: 469.83 },
    { label: "41", start: 470.08, end: 481.31 },
    { label: "42", start: 481.56, end: 488.59 },
    { label: "43", start: 488.84, end: 503.79 },
    { label: "44", start: 504.04, end: 520.31 }
];
If this is very a big job don't need to look into this.

_Originally posted by @onegladiator4u in https://github.com/eliranwong/UniqueBible/discussions/128#discussioncomment-2795006_

**Comment by otseng** [comment]
@onegladiator4u Looking at this, it might be possible to start at a particular time in a chapter mp3 file, but I cannot find a way to stop at a particular point.  It'll just start at the correct place, but will play until the end of the chapter.

If you want to just play a particular verse, it would be better to use a program to split a single chapter mp3 file into verse files.

Can try this:
https://gist.github.com/Ashwinning/a9677b5b3afa426667d979b36c019b04

**Comment by onegladiator4u** [comment]
> If you want to just play a particular verse, it would be better to use a program to split a single chapter mp3 file into verse files.

Oh, ok. 


> I can perhaps modify this program to create the verse files:
> https://gist.github.com/Ashwinning/a9677b5b3afa426667d979b36c019b04

Did you mean to split the chapter mp3 to verse using timings?
I have tried and split one chapter to verse using Audacity . I noticed that some verses don't play completely when playing verse by verse. last one second misses. it occurs rarely i think. Could that be because of programming ? I tried to play the file outside app. it plays fully.

**Comment by otseng** [comment]
> Did you mean to split the chapter mp3 to verse using timings? 

Yes.  I'll create a program to split the mp3 file.

> I have tried and split one chapter to verse using Audacity . I noticed that some verses don't play completely when playing verse by verse. last one second misses. it occurs rarely i think. Could that be because of programming ? I tried to play the file outside app. it plays fully.

I've seen this problem if the audio was computer synthesized.  Not sure why that happens.

**Comment by onegladiator4u** [comment]
> I've seen this problem if the audio was computer synthesized. Not sure why that happens.

oh ok.


> Yes. I'll create a program to split the mp3 file.

ok brother

**Comment by onegladiator4u** [comment]
> I've seen this problem if the audio was computer synthesized. Not sure why that happens.

i converted that verse mp3 using vlc again . That plays perfect

**Comment by eliranwong** [comment]
would it be easier to produce a new set of verse-by-verse audio of your bible audio?  may I ask what is the language and what is the bible version?

**Comment by onegladiator4u** [comment]
It won't be easy , but it'll take time. It's possible. Only problem is some verses skips at the end when playing. My language is Malayalam and bible version is MOV. (Malayalam Old Version).

**Comment by otseng** [comment]
@onegladiator4u Can you send me a sample chapter mp3 file along with the datafile with the timings in it?

**Comment by onegladiator4u** [comment]
[41.zip](https://github.com/eliranwong/UniqueBible/files/8768328/41.zip)

Actually its not a datafile. i got the information from it's html. i cropped out unwanted codes except 
this
    { label: "1", start: 6, end: 10.99 },
    { label: "2", start: 11.24, end: 16.75 },
    { label: "3", start: 17, end: 30.15 },
    { label: "4", start: 30.4, end: 37.87 },
    { label: "5", start: 38.12, end: 49.27 },
    { label: "6", start: 49.52, end: 59.83 },
    { label: "7", start: 60.08, end: 66.43 },
    { label: "8", start: 66.68, end: 76.63 },
    { label: "9", start: 76.88, end: 83.99 },
    { label: "10", start: 84.24, end: 92.11 },
    { label: "11", start: 92.36, end: 97.87 },
    { label: "12", start: 98.12, end: 103.67 },
    { label: "13", start: 103.92, end: 113.71 },
    { label: "14", start: 113.96, end: 121.07 },
    { label: "15", start: 121.32, end: 129.71 },
    { label: "16", start: 129.96, end: 139.43 },
    { label: "17", start: 139.68, end: 145.51 },
    { label: "18", start: 145.76, end: 148.63 },
    { label: "19", start: 148.88, end: 158.19 },
    { label: "20", start: 158.44, end: 164.95 },
    { label: "21", start: 165.2, end: 170.55 },
    { label: "22", start: 170.8, end: 179.27 },
    { label: "23", start: 179.52, end: 184.43 },
    { label: "24", start: 184.68, end: 196.07 },
    { label: "25", start: 196.32, end: 201.55 },
    { label: "26", start: 201.8, end: 207.27 },
    { label: "27", start: 207.52, end: 221.35 },
    { label: "28", start: 221.6, end: 225.71 },
    { label: "29", start: 225.96, end: 232.75 },
    { label: "30", start: 233, end: 238.87 },
    { label: "31", start: 239.12, end: 245.87 },
    { label: "32", start: 246.12, end: 254.07 },
    { label: "33", start: 254.32, end: 257.55 },
    { label: "34", start: 257.8, end: 269.03 },
    { label: "35", start: 269.28, end: 274.39 },
    { label: "36", start: 274.64, end: 278.47 },
    { label: "37", start: 278.72, end: 283.31 },
    { label: "38", start: 283.56, end: 293.11 },
    { label: "39", start: 293.36, end: 299.23 },
    { label: "40", start: 299.48, end: 306.87 },
    { label: "41", start: 307.12, end: 310.03 },
    { label: "42", start: 310.28, end: 316.35 },
    { label: "43", start: 316.6, end: 318.75 },
    { label: "44", start: 319, end: 331.39 },
    { label: "45", start: 331.64, end: 353.11 }

**Comment by eliranwong** [comment]
I am aware that your language is supported by Google Cloud tts service, I think you can easily produce a whole set of verse-by-verse audio with the plugin below.  You may just need to leave the computer unattended for a few hours for that to be completed.

<img width="293" alt="Screenshot 2022-05-25 at 14 19 30" src="https://user-images.githubusercontent.com/25262722/170271644-fec8c767-2c5a-4996-9bc3-30e2342d93ee.png">
<img width="1440" alt="Screenshot 2022-05-25 at 14 19 20" src="https://user-images.githubusercontent.com/25262722/170271658-cb9df9be-5af9-4943-8187-db32d10d6e99.png">

**Comment by eliranwong** [comment]
I attached a zip file here.  The zip file contains two plugins.  Both can be used to produced verse-by-verse audio of MOV in your language.  One uses female voice, another uses male voice.

Steps you may need:

1) Create a credential key for Google Cloud text-to-speech service and download it.  Read for details at https://cloud.google.com/text-to-speech/docs/before-you-begin
2) Rename the credential key file to "credentials_GoogleCloudTextToSpeech.json"
3) Place the credential key file "credentials_GoogleCloudTextToSpeech.json" in UniqueBibleApp folder.
4) Unzip this file and place both files in folder plugins/menu
5) Restart UBA, and choose one of the plugins to run.  UBA freezes during audio creation, so you expect to wait for a few hours before the process complete.

[MOV_audio_plugin.zip](https://github.com/eliranwong/UniqueBible/files/8772394/MOV_audio_plugin.zip)

**Comment by otseng** [comment]
Can you unzip this into your audio/bibles folder and try it?
[MOV.zip](https://github.com/eliranwong/UniqueBible/files/8775576/MOV.zip)

**Comment by onegladiator4u** [comment]
> You may just need to leave the computer unattended for a few hours for that to be completed.

Can we create it book by book?

**Comment by onegladiator4u** [comment]
> Can you unzip this into your audio/bibles folder and try it? [MOV.zip](https://github.com/eliranwong/UniqueBible/files/8775576/MOV.zip)

ok

**Comment by onegladiator4u** [comment]
> Can you unzip this into your audio/bibles folder and try it? [MOV.zip](https://github.com/eliranwong/UniqueBible/files/8775576/MOV.zip)

@otseng  I tried it . It's working .

**Comment by eliranwong** [comment]
> > You may just need to leave the computer unattended for a few hours for that to be completed.
> 
> Can we create it book by book?

Yes

**Comment by onegladiator4u** [comment]
> > > You may just need to leave the computer unattended for a few hours for that to be completed.
> > 
> > 
> > Can we create it book by book?
> 
> Yes

Ok brother . Will check out

**Comment by otseng** [comment]
Follow this instruction to split a chapter mp3 file:
https://github.com/eliranwong/UniqueBible/wiki/Split-chapter-MP3-audio-chapter-file-into-verse-files

**Comment by onegladiator4u** [comment]
Got this error 

PS F:\BIBLE STUDY\App\UniqueBible> python -m tools.SplitMp3File audio/bibles/MOV/default/41/41_Mark001.mp3 data/mal-41-MRK-001.html MOV 41 1
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python39\lib\runpy.py", line 158, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "F:\BIBLE STUDY\App\UniqueBible\tools\SplitMp3File.py", line 79
    os.mkdir(directory)
IndentationError: unexpected indent

**Comment by otseng** [comment]
Can you replace with this and retry?
[SplitMp3File.zip](https://github.com/eliranwong/UniqueBible/files/8789254/SplitMp3File.zip)

On Windows, might have to run command as:
`python -m tools.SplitMp3File audio\bibles\MOV\default\41\41_Mark001.mp3 data\mal-41-MRK-001.html MOV 41 1`

**Comment by onegladiator4u** [comment]
now error is this


PS F:\BIBLE STUDY\App\UniqueBible> python -m tools.SplitMp3File audio\bibles\MOV\default\41\41_Mark001.mp3 data\mal-41-MRK-001.html MOV 41 1
MP3 file: audio\bibles\MOV\default\41\41_Mark001.mp3
Data file: data\mal-41-MRK-001.html
Bible: MOV
Book: 41
Chapter: 1
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\BIBLE STUDY\App\UniqueBible\tools\SplitMp3File.py", line 103, in <module>
    ExtractTracks()
  File "F:\BIBLE STUDY\App\UniqueBible\tools\SplitMp3File.py", line 63, in __init__
    for line in lines:
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 77: character maps to <undefined>

**Comment by otseng** [comment]
Can you try this?
[SplitMp3File.zip](https://github.com/eliranwong/UniqueBible/files/8789407/SplitMp3File.zip)

**Comment by onegladiator4u** [comment]
It's working bro. great job. Thank You .

**Comment by otseng** [comment]
Excellent!
