### ISSUE TITLE
Save file as markdown

### ISSUE THREAD

**Issue by mooru** [eliranwong/UniqueBible#1037]
Is there any possibility to add markdown in the save file as option?

**Comment by eliranwong** [comment]
I will try

**Comment by eliranwong** [comment]
I think I will try both:

1) open markdown file and display in UBA

2) save UBA content in a markdown file

3) In addition, I will try to support the use of markdown in UBA note editor

**Comment by eliranwong** [comment]
Changes in 30.03:
* Added support of Markdown:
1) Open markdown file and display on Study Window
2) Save Bible Window / Study Window content in a markdown file
3) Added "Convert from Markdown" feature in Note Editor

**Comment by eliranwong** [comment]
You can also select Markdown Export heading style via Material menu layout "Other Preferences"
