### ISSUE TITLE
Add config flag to hide chapter navigation at top and bottom of window

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#1057]
Hey guys,
Since material layout now have easy access to chapter on toolbar like this
![image](https://user-images.githubusercontent.com/48617390/171992485-b9e476ea-faa1-4559-9add-4a59059c2cfa.png)

Does this layout need chapter numbers on top and bottom of main window like this? May be you could add option to hide it.
![image](https://user-images.githubusercontent.com/48617390/171992579-4d558b99-4b1e-46c0-8da9-a4df111d6652.png)

What do you guys think?

_Originally posted by @onegladiator4u in https://github.com/eliranwong/UniqueBible/discussions/128#discussioncomment-2882357_

**Comment by eliranwong** [comment]
Added in ver 30.33; https://github.com/eliranwong/UniqueBible/commit/cd6f5e4fd13f7ee30366b7c06d869ddba335a7d1

<img width="643" alt="chaptermenu" src="https://user-images.githubusercontent.com/25262722/171997535-c4a3863d-3501-43b1-a072-d3c0e67c9824.png">
