### ISSUE TITLE
can "Live Filter" filter book or books

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#1062]
@otseng 

can "Live Filter" filter book or books?

e.g. filter out all verses in John and Matthew only

**Comment by eliranwong** [comment]
or create two tabs on Live Filter window

one for word filter

another one for book filter?

**Comment by otseng** [comment]
I think there'd be value in adding it as additional buttons above the "clear/add/remove/edit" buttons.  Can then filter out by "OT", "NT", or specific books.

Right now I have this filter for NT:
<ref.*>Matt .*</ref>|<ref.*>Mark .*</ref>|<ref.*>Luke .*</ref>|<ref.*>John .*</ref>|<ref.*>Acts .*</ref>|<ref.*>Rom .*</ref>|<ref.*>1Cor .*</ref>|<ref.*>2Cor .*</ref>|<ref.*>Gal .*</ref>|<ref.*>Eph .*</ref>|<ref.*>Phil .*</ref>|<ref.*>Col .*</ref>|<ref.*>1Thess .*</ref>|<ref.*>2Thess .*</ref>|<ref.*>1Tim .*</ref>|<ref.*>2Tim .*</ref>|<ref.*>Titus .*</ref>|<ref.*>Phlm .*</ref>|<ref.*>Heb .*</ref>|<ref.*>Jas .*</ref>|<ref.*>1Pet .*</ref>|<ref.*>2Pet .*</ref>|<ref.*>1John .*</ref>|<ref.*>2John .*</ref>|<ref.*>3John .*</ref>|<ref.*>Jude .*</ref>|<ref.*>Rev .*</ref>
And this for OT:
<ref.*>Gen .*</ref>|<ref.*>Exod .*</ref>|<ref.*>Lev .*</ref>|<ref.*>Num .*</ref>|<ref.*>Deut .*</ref>|<ref.*>Josh .*</ref>|<ref.*>Judg .*</ref>|<ref.*>Ruth .*</ref>|<ref.*>1Sam .*</ref>|<ref.*>2Sam .*</ref>|<ref.*>1Kgs .*</ref>|<ref.*>2Kgs .*</ref>|<ref.*>1Chr .*</ref>|<ref.*>2Chr .*</ref>|<ref.*>Ezra .*</ref>|<ref.*>Neh .*</ref>|<ref.*>Esth .*</ref>|<ref.*>Job .*</ref>|<ref.*>Ps .*</ref>|<ref.*>Prov .*</ref>|<ref.*>Eccl .*</ref>|<ref.*>Song .*</ref>|<ref.*>Isa .*</ref>|<ref.*>Jer .*</ref>|<ref.*>Lam .*</ref>|<ref.*>Ezek .*</ref>|<ref.*>Dan .*</ref>|<ref.*>Hos .*</ref>|<ref.*>Joel .*</ref>|<ref.*>Amos .*</ref>|<ref.*>Obad .*</ref>|<ref.*>Jonah .*</ref>|<ref.*>Mic .*</ref>|<ref.*>Nah .*</ref>|<ref.*>Hab .*</ref>|<ref.*>Zeph .*</ref>|<ref.*>Hag .*</ref>|<ref.*>Zech .*</ref>|<ref.*>Mal .*</ref>

**Comment by eliranwong** [comment]
> I think there'd be value in adding it as additional buttons above the "clear/add/remove/edit" buttons. Can then filter out by "OT", "NT", or specific books.
> 
> Right now I have this filter for NT: <ref._>Matt ._|<ref._>Mark ._|<ref._>Luke ._|<ref._>John ._|<ref._>Acts ._|<ref._>Rom ._|<ref._>1Cor ._|<ref._>2Cor ._|<ref._>Gal ._|<ref._>Eph ._|<ref._>Phil ._|<ref._>Col ._|<ref._>1Thess ._|<ref._>2Thess ._|<ref._>1Tim ._|<ref._>2Tim ._|<ref._>Titus ._|<ref._>Phlm ._|<ref._>Heb ._|<ref._>Jas ._|<ref._>1Pet ._|<ref._>2Pet ._|<ref._>1John ._|<ref._>2John ._|<ref._>3John ._|<ref._>Jude ._|<ref._>Rev ._ And this for OT: <ref._>Gen ._|<ref._>Exod ._|<ref._>Lev ._|<ref._>Num ._|<ref._>Deut ._|<ref._>Josh ._|<ref._>Judg ._|<ref._>Ruth ._|<ref._>1Sam ._|<ref._>2Sam ._|<ref._>1Kgs ._|<ref._>2Kgs ._|<ref._>1Chr ._|<ref._>2Chr ._|<ref._>Ezra ._|<ref._>Neh ._|<ref._>Esth ._|<ref._>Job ._|<ref._>Ps ._|<ref._>Prov ._|<ref._>Eccl ._|<ref._>Song ._|<ref._>Isa ._|<ref._>Jer ._|<ref._>Lam ._|<ref._>Ezek ._|<ref._>Dan ._|<ref._>Hos ._|<ref._>Joel ._|<ref._>Amos ._|<ref._>Obad ._|<ref._>Jonah ._|<ref._>Mic ._|<ref._>Nah ._|<ref._>Hab ._|<ref._>Zeph ._|<ref._>Hag ._|<ref._>Zech ._|<ref._>Mal ._

In case someone use other language abbreviations, say Chinese abbreviations, do these filters above still work?

**Comment by otseng** [comment]
I'll modify it to filter by books, including Chinese abbreviations.
