### ISSUE TITLE
Color hover not working 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1066]
hey guys,
i have set Widget foreground  color hover. But it's not working on icon buttons. It works only in text buttons 
![image](https://user-images.githubusercontent.com/48617390/172544519-7744fce1-d993-43e5-85fa-1dfe943fedd9.png)

![image](https://user-images.githubusercontent.com/48617390/172544615-12b7264e-e6f1-4e3d-8a03-6df94812db34.png)
![image](https://user-images.githubusercontent.com/48617390/172544671-944c5e56-02e7-472f-9085-0fe77490fa1e.png)
![image](https://user-images.githubusercontent.com/48617390/172544742-9cbf3c24-315e-43cb-8693-c1e8be34221e.png)
![image](https://user-images.githubusercontent.com/48617390/172544846-277898fb-4dad-4e81-a916-cd4f7c2c96e3.png)

**Comment by eliranwong** [comment]
This is a known issue.  As different icon buttons use different icons, it is a bit complicated to work on hovering of individual icons.  So, I don't think I will make a change about it.

**Comment by onegladiator4u** [comment]
ok bro

**Comment by eliranwong** [comment]
@onegladiator4u 

as an interesting exercise, I am working on it, it looks not difficult as I thought.
<img width="239" alt="Screenshot 2022-06-09 at 09 32 23" src="https://user-images.githubusercontent.com/25262722/172802478-73aa505f-b1fe-4eed-9a3d-e9555baa24fd.png">

**Comment by eliranwong** [comment]
uploaded, @onegladiator4u @otseng please help to see if it works on your devices.  thank you.

**Comment by onegladiator4u** [comment]
it seems to be working . but is this the effect you intended?
![python_tdpBxNFQSy](https://user-images.githubusercontent.com/48617390/172879534-6abceb60-4ce9-414d-af9e-c4c212a27988.gif)

Text monitoring icon also didn't show up.

**Comment by eliranwong** [comment]
@onegladiator4u 

No, the codes you downloaded is not working.

The latest one is not working on Windows.

All icons disappear, I will upload a fix soon.

@onegladiator4u please help test version 30.55, not 30.54.  thank you.

I am uploading 30.55 soon

**Comment by eliranwong** [comment]
uploaded, please test on Windows.  @onegladiator4u thank you.

**Comment by eliranwong** [comment]
This is how it looks like on macOS.  both hovered and pressed colours work.

https://user-images.githubusercontent.com/25262722/172957074-5bbed2e2-03fb-4b58-8654-7b4d2fc21826.mov

**Comment by onegladiator4u** [comment]
I think it works perfectly. Great job brother .
There is still problem of `Text Selection Monitoring` button image is not showing
![python_FLr4vh6KOA](https://user-images.githubusercontent.com/48617390/173002929-c302a608-1349-44e3-a026-a6993dc0580f.gif)

**Comment by eliranwong** [comment]
Fixed text selection monitoring icon download.  Please try and let me know. Thank you.

**Comment by onegladiator4u** [comment]
@eliranwong Its working brother. Thank you very much.
