### ISSUE TITLE
Note editor not opening 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1073]
After the last update i couldn't open note second time after closing editor once.. It occurs in one note only. others seems working.
Also could you make toolbar lockable? Whenever moving note editor it's trying to dock. I don't want to dock when i move the note editor. is this possible ?
Thank You
![python_0u6nibKD5b](https://user-images.githubusercontent.com/48617390/173225506-6b889f81-b31f-491c-a4a4-6b333a244da1.gif)

**Comment by eliranwong** [comment]
I will fix it.  May I ask did you set the value of config.dockNoteEditorOnStartup on your side.

In Set Config Flags Window, is this value turned on or not.

This may help me to duplicate the issue on my side.

**Comment by onegladiator4u** [comment]
> I will fix it. May I ask did you set the value of config.dockNoteEditorOnStartup on your side.
> 
> In Set Config Flags Window, is this value turned on or not.
> 
> This may help me to duplicate the issue on my side.

yes, i turned off to not dock.

**Comment by eliranwong** [comment]
@onegladiator4u I managed to reproduce the issue.  I will fix it.

Meanwhile, use the following button to call back the Note Editor or show / hide the Note Editor.

<img width="854" alt="callNoteEditor" src="https://user-images.githubusercontent.com/25262722/173249197-b10e99f5-0dbf-4d85-8580-ce4f296ee7ec.png">

**Comment by eliranwong** [comment]
@onegladiator4u 

Changes in 30.64:
* Fixed displaying Note Editor when "edit" note button is clicked twice.
* Added config.doNotDockNoteEditorByDragging, configurable via "Set Config Flags" window.
    When it is set to True, Note Editor does not dock around main window by dragging.

**Comment by onegladiator4u** [comment]
Hey bro, thanks for the update, Dragging off works.
Now there's a new problem. note opens but it opens previously opened one.
![python_8j7RbUBJo2](https://user-images.githubusercontent.com/48617390/173287746-2389d4ac-8e57-4ac0-80c9-10b9a1ab12d4.gif)

**Comment by eliranwong** [comment]
It seems fine on my side.  Different notes are opened correctly.  Can you give me some steps that I may reproduce the issue?

https://user-images.githubusercontent.com/25262722/173300384-938e3ae9-2a03-4bbc-8051-e8286e1d753d.mov

**Comment by onegladiator4u** [comment]
> It seems fine on my side. Different notes are opened correctly. Can you give me some steps that I may reproduce the issue?
> opening.differentnotes.mov
i couldn't replicate it. May be i can show you another one that may be related to it. 
After we edit a note and close without saving , it will close without asking to save it.
Then try opening another note. It will show as if last note is opened.


https://user-images.githubusercontent.com/48617390/173307623-087e81e9-cb21-4665-a07b-04e973b0b401.mp4

**Comment by eliranwong** [comment]
> > It seems fine on my side. Different notes are opened correctly. Can you give me some steps that I may reproduce the issue?
> > opening.differentnotes.mov
> > i couldn't replicate it. May be i can show you another one that may be related to it.
> > After we edit a note and close without saving , it will close without asking to save it.
> > Then try opening another note. It will show as if last note is opened.
> 
>  al4q5xLqTb.mp4

Your video shows that notes of Mark 13:1 and Mark 13:2 are displayed correctly.  When you chose "Continue", it means open another note anyway without saving.  The Note Editor woks as expected.

**Comment by onegladiator4u** [comment]
> > > It seems fine on my side. Different notes are opened correctly. Can you give me some steps that I may reproduce the issue?
> > > opening.differentnotes.mov
> > > i couldn't replicate it. May be i can show you another one that may be related to it.
> > > After we edit a note and close without saving , it will close without asking to save it.
> > > Then try opening another note. It will show as if last note is opened.
> > 
> > 
> > al4q5xLqTb.mp4
> 
> Your video shows that notes of Mark 13:1 and Mark 13:2 are displayed correctly. When you chose "Continue", it means open another note anyway without saving. The Note Editor woks as expected.

if you look at the video in the beginning i edited one note by adding yuo at 15th second of the video. I closed without saving, It didn't ask to save the note. Warning should first come when we close the note we edited. But it's not.

**Comment by eliranwong** [comment]
@onegladiator4u 

I changed the way how warning appears.

When you close the Note Editor, it is actually hidden rather than closed.

Warning of unsaved changes appear only when users quit UBA or change to another note, just like you did in your video.

**Comment by onegladiator4u** [comment]
@eliranwong 
[note.zip](https://github.com/eliranwong/UniqueBible/files/8899591/note.zip)
Can you back up your note somewhere and replace it with this and check Mark 13:1 notes with verse 2,4 and 8. by opening for editing and closing. i couldn't open to edit 13:1 after once I close it now.

**Comment by onegladiator4u** [comment]
I just recreated the problem again from the startup of the app. It's not saving note too.

https://user-images.githubusercontent.com/48617390/176623089-9c38e0e7-ebab-481a-a792-1d1bcdcd0f30.mp4

**Comment by eliranwong** [comment]
I will deal with not-saving issue.

**Comment by eliranwong** [comment]
Saving notes issue is now fixed.  https://github.com/eliranwong/UniqueBible/commit/814c43a364bb599b5dba28c86f249479b21e50b7

**Comment by eliranwong** [comment]
as the note saving error is now fixed.  I am closing this issue.  thanks.
