### ISSUE TITLE
Modules bug

### ISSUE THREAD

**Issue by Franstv99** [eliranwong/UniqueBible#109]
I installed UniqueBible on my laptop, no problem. When I try on my Desktop, I get the Window but I can't download or update modules it stays on stand by  (application doesn't respond), I try to reinstall 3 times, same problem.

**Comment by eliranwong** [comment]
Hello, sorry to hear the difficulty you encountered.

Is it possible you provide more information to us, so we may help?  e.g.

what platform: Windows / macOS / Linux / Chromebook?
what version: the latest one is 21.25
do you launch the app from terminal / console?  can you copy and paste the error message here?

We fixed a download issue earlier today.  Did you install the latest version?

thanks.

**Comment by otseng** [comment]
I think I duplicated this.  I deleted the indexes2.sqlite file.  Clicked on Smart Index to force it to redownload the file.  When I clicked on "Download and Install", the program just hangs and doesn't do anything.

**Comment by eliranwong** [comment]
thanks, I will take a look into it.

**Comment by eliranwong** [comment]
fixed failure to download indexes2.sqlite

https://github.com/eliranwong/UniqueBible/commit/f65da80613bff0ab468c6497c699035e53065098

**Comment by Franstv99** [comment]
I stay with my problem : I can't donwload any module (message NOT RESPONDING) on my laptop and my PC (Win 10). At similar problem #163 you say you can send email links. I am looking for all the LXX modules. Thanks for your help.

Today I update to v.21.60 and at restart I got errors :

J:\Religion\Bibles\UniqueBible>cd \religion\bibles\uniquebible.\venv\Scripts\activate & python main.py
Nom de répertoire non valide.
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    ConfigUtil.setup()
  File "J:\Religion\Bibles\UniqueBible\util\ConfigUtil.py", line 498, in setup
    config.lastAppUpdateCheckDate = str(DateUtil.localDateNow())
AttributeError: type object 'DateUtil' has no attribute 'localDateNow'

**Comment by Franstv99** [comment]
Thanks ! All it's good now with v.21.69 ! I can dowload ressources correctly.
Good job.
