### ISSUE TITLE
Workspace Issue?

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#1096]
I have 5 windows open in my workspace. One of them I no longer want, so I delete it. The deleted window space. The deleted window shown in the first attachment,  is not released until UBA is restarted.

![deleted workspace](https://user-images.githubusercontent.com/11500764/176347301-5477e76e-1a23-47f1-a25d-05b082f057ec.png)

![released window](https://user-images.githubusercontent.com/11500764/176347347-29650386-33ab-42ac-8a98-01c1996824ef.png)

**Comment by eliranwong** [comment]
You don't need a restart.  You can always tidy up workspace windows by clicking the button indicated below:

<img width="956" alt="Screenshot 2022-06-29 at 07 26 38" src="https://user-images.githubusercontent.com/25262722/176366892-4188f810-50e0-4bb4-9229-69b715d67ecc.png">

after clicking the button:

<img width="961" alt="Screenshot 2022-06-29 at 07 26 56" src="https://user-images.githubusercontent.com/25262722/176366835-fac3ca19-0d2d-486f-8e1f-663c6189dfcf.png">

**Comment by darrelwright** [comment]
Ah, great! Thanks so much. This tool really does replace the multiwin 
tool you gave me previously.

Just one question that may have already been answered. Can I rearrange 
the windows in any order I want?

**Comment by darrelwright** [comment]
I answered my own question! Thanks for a really good tool.

**Comment by eliranwong** [comment]
> Ah, great! Thanks so much. This tool really does replace the multiwin tool you gave me previously. Just one question that may have already been answered. Can I rearrange the windows in any order I want?
> […](#)

Yes, you can order differently, read https://github.com/eliranwong/UniqueBible/wiki/Workspace#auto-save-and-saving-order
