### ISSUE TITLE
Bible display Issue

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#1101]
The four Bible selection buttons do not appear to work correctly. The first screen shows how I have master control set:

![bible selection 1](https://user-images.githubusercontent.com/11500764/177139376-52f41ce1-5ac2-4eab-baac-962c62b9442a.png)

When clicking on Single Version display button it should display verse Matt 2:1 in the AFVx bible. When clicking Parallel Versions button it should display the AFVx, KJVx and NASBx bibles. Instead it displays:

![bible selection 2](https://user-images.githubusercontent.com/11500764/177140481-05c0bbe6-500b-4b1e-b436-8c8780c54efa.png)

Side by Side Comparison and Row Comparison also display the same three bibles rather than the ones set in Master Control.

Am I missing something?

**Comment by eliranwong** [comment]
this is not an issue at all.

you just need to understand how to use it.

the parallel buttons on material menu work with multiple bible selection button on the same toolbar

<img width="485" alt="Screenshot 2022-07-04 at 12 32 13" src="https://user-images.githubusercontent.com/25262722/177146675-e22641a0-0645-4419-8a6b-39eab0a027de.png">

the parallel buttons on master controls work with multiple bible selection dropdown menu on master control.

<img width="595" alt="Screenshot 2022-07-04 at 12 32 26" src="https://user-images.githubusercontent.com/25262722/177146788-83d6577f-3213-4a78-ac9a-2036679d3e07.png">

closing now.

**Comment by darrelwright** [comment]
Thank you! You are correct, I do need to learn! I appreciate what you 
are doing!
