### ISSUE TITLE
Previous/Next Chapter buttons when reading a book

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#111]
When reading a [third-party book](https://github.com/darrelwright/UniqueBible_Books), display previous/next chapter buttons to easily go between chapters.

**Comment by otseng** [comment]
Note, buttons have only been added to the Aleph menu.  Feel free to add to Classic menu.

**Comment by eliranwong** [comment]
> Note, buttons have only been added to the Aleph menu. Feel free to add to Classic menu.

sure, thanks.
