### ISSUE TITLE
Saving note is slow.

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1119]
Saving note became slow , probably because of refreshing page after save . It's not opening note after save also.

https://user-images.githubusercontent.com/48617390/178119559-4bb0a155-d457-4d59-84d5-4cc62e0f0403.mp4
Opennoteaftersave is on in config

**Comment by eliranwong** [comment]
Is it faster if opennoteaftersave set to False?

**Comment by onegladiator4u** [comment]
Not much difference after changing brother .

**Comment by onegladiator4u** [comment]
[config.zip](https://github.com/eliranwong/UniqueBible/files/9137715/config.zip)

**Comment by otseng** [comment]
A finding so far is it's not saving a note that's slow, but displaying the Bible.  Just going to the next chapter is slow too.  So, now need to figure out what displaying the Bible is slow with your config...

**Comment by onegladiator4u** [comment]
Could it be refreshing the page after saving note?

**Comment by otseng** [comment]
Yes, it's refreshing the page after saving note.

**Comment by onegladiator4u** [comment]
ok. it also explains why note is not opening after save

**Comment by otseng** [comment]
I'll add a config flag to disable refreshing after saving a note.  Later, it would also be good to figure out how to in general load windows faster.

**Comment by otseng** [comment]
You can now disable the refreshWindowsAfterSavingNote config flag to make note saving faster.

**Comment by onegladiator4u** [comment]
ok brother . Thanks

**Comment by onegladiator4u** [comment]
@otseng Note is not opening after saving . Can you do something for that too? it should have worked after turning off refresh but it's not

**Comment by otseng** [comment]
I'm assuming you have the note in the study window and the note also in the editing window.  If so, you can't have it both ways to be fast and also refresh the study window.

**Comment by onegladiator4u** [comment]
> I'm assuming you have the note in the study window and the note also in the editing window. If so, you can't have it both ways to be fast and also refresh the study window.

note is a floating editing window .
![python_TI7Sig0pEp](https://user-images.githubusercontent.com/48617390/180498584-e350dc12-a3bc-4e7d-a084-04cea66c05ab.gif)

**Comment by otseng** [comment]
Not sure why that is happening for you.  Can you try a few things.  Can you update code to latest and try again?  Can you also try toggling dockNoteEditorOnStartup config flag and try saving?

**Comment by onegladiator4u** [comment]
updated the app. it's working now bro. thanks
