### ISSUE TITLE
Chinese-to-English word definition

### ISSUE THREAD

**Issue by Enockng** [eliranwong/UniqueBible#1124]
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
INFO: Could not find files for the given pattern(s).

**Comment by otseng** [comment]
Where do you see this?  
Are you able to run the app?

**Comment by Enockng** [comment]
> Where do you see this? Are you able to run the app?

The app just launches and hangs (Not Responding)

**Comment by otseng** [comment]
Can you try running this in command line in the UBA directory and see what happens?
`pip3 install chinese-english-lookup`

**Comment by Enockng** [comment]
> 



> Can you try running this in command line in the UBA directory and see what happens? `pip3 install chinese-english-lookup`

Tried so, The issue remains the same.

**Comment by otseng** [comment]
Can you unzip this file and replace util/checkup.py and try to restart?
[checkup.zip](https://github.com/eliranwong/UniqueBible/files/9128757/checkup.zip)

**Comment by Enockng** [comment]
> 
python download.py util.checkup
Traceback (most recent call last):
  File "C:\Users\*****\UniqueBible-main\download.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Added disabled_modules.txt in uba dir

Still NO Change! Same Problem!

**Comment by otseng** [comment]
What happens when you run `pip3 install requests`?
