### ISSUE TITLE
Add hymn lyrics

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#113]
Add hymn lyrics from:
https://play.google.com/store/apps/details?id=com.ecodia.android.hymnlyrics

**Comment by otseng** [comment]
You can download "Hymn Lyrics.book" below.  It contains the lyrics of over 2000 public domain English Christian hymns.

https://drive.google.com/file/d/1F8J8dBzBkD7vbKNX-LO6_io5ijf7UvJw/view?usp=sharing

**Comment by eliranwong** [comment]
@otseng  When I click the link, it requires permission, stating "You need access".

Will you consider adding it to menu layout under resource download.  it appears you stored it in google drive, you may use gdown, so user can download directly through menu?

**Comment by otseng** [comment]
Changed link to available to public:

https://drive.google.com/file/d/1F8J8dBzBkD7vbKNX-LO6_io5ijf7UvJw/view?usp=sharing

Yes, I can add it to the menu.
