### ISSUE TITLE
INFO: Could not find files for the given pattern(s).

### ISSUE THREAD

**Issue by Enockng** [eliranwong/UniqueBible#1135]
Some of your files are old.  We are helping you to upgrade those files.  You will receive another message when the operation is done.

The app just stuck on not responding.

**Comment by eliranwong** [comment]
It is a bit strange, as requests is a very common module. May I ask wgat is your python version and pip version?

**Comment by Enockng** [comment]
> 

PS C:\Users\xxxxx\UniqueBible> pip -V
pip 22.1.2 from C:\Users\xxxxx\AppData\Roaming\Python\Python310\site-packages\pip (python 3.10)

**Comment by otseng** [comment]
Does the app work if you do NOT run the update?  

Can you also try unzipping this file and replacing util/UpdateUtil.py with it?  Then rerun the update and see what the console prints out.
[UpdateUtil.zip](https://github.com/eliranwong/UniqueBible/files/9136395/UpdateUtil.zip)

**Comment by Enockng** [comment]
> Does the app work if you do NOT run the update?
> 
> Can you also try unzipping this file and replacing util/UpdateUtil.py with it? Then rerun the update and see what the console prints out. [UpdateUtil.zip](https://github.com/eliranwong/UniqueBible/files/9136395/UpdateUtil.zip)

The app just hanging and not responding.
Even after replacing UpdateUtil.py the problem remains the same.

**Comment by otseng** [comment]
Do you see anything being printed out in the console window?

**Comment by otseng** [comment]
It works on my Windows 11.  Can you send a copy of your `config.py` file?

**Comment by Enockng** [comment]
> It works on my Windows 11. Can you send a copy of your `config.py` file?

config.py from which folder because the one in UniqueBible-main folder is 0KB

**Comment by otseng** [comment]
Can you try deleting the config.py file and restart UBA?

**Comment by Enockng** [comment]
> Can you try deleting the config.py file and restart UBA?

Deleted it, on restarting  uba it creates another config.py with 0KB again.
I have tried using Microsoft Store Python and displayed this;
'INFO: Could not find files for the given pattern(s).
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.'

**Comment by Enockng** [comment]
> It works on my Windows 11. Can you send a copy of your `config.py` file?

What version of Windows 11 for I'am in Windows 11 Pro  22H2_22621.1

**Comment by otseng** [comment]
> What version of Windows 11 for I'am in Windows 11 Pro 22H2_22621.1

Edition	Windows 11 Home
Version	21H2
Installed on	‎7/‎12/‎2022
OS build	22000.675
Experience	Windows Feature Experience Pack 1000.22000.675.0

Since your graphics has issues, can you try running in http server mode?  `python3 uba.py http-server`, then access it from browser with url that is printed

**Comment by Enockng** [comment]
> Since your graphics has issues, can you try running in http server mode? `python3 uba.py http-server`, then access it from browser with url that is printed

On running python3 uba.py http-server no any url printed.
Is there  any way to bypass graphics checkup?

**Comment by otseng** [comment]
I don't think there's any specific graphics check...

To help debug, can you replace uba.py and main.py with the below and rerun and see what it prints out?
[main.zip](https://github.com/eliranwong/UniqueBible/files/9163905/main.zip)
[uba.zip](https://github.com/eliranwong/UniqueBible/files/9163906/uba.zip)

**Comment by Enockng** [comment]
> 



> I don't think there's any specific graphics check...
> 
> To help debug, can you replace uba.py and main.py with the below and rerun and see what it prints out? [main.zip](https://github.com/eliranwong/UniqueBible/files/9163905/main.zip) [uba.zip](https://github.com/eliranwong/UniqueBible/files/9163906/uba.zip)

After replacing uba.py and main.py this is what it prints;
uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
pip tool updated!
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
main:C
main:D
main:E

**Comment by otseng** [comment]
Getting closer.  Can you replace and rerun both scenarios again?
[main.zip](https://github.com/eliranwong/UniqueBible/files/9167549/main.zip)

Can you also run it as a telnet server:  `python3 uba.py telnet-server`

**Comment by Enockng** [comment]
> Getting closer. Can you replace and rerun both scenarios again? [main.zip](https://github.com/eliranwong/UniqueBible/files/9167549/main.zip)
> 
> Can you also run it as a telnet server: `python3 uba.py telnet-server`

Replacing main.py and running 'python uba.py telnet-server' here it prints;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
pip tool updated!
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
main:C
Running in remote CLI Mode on port 8888
Access by 'telnet 192.168.43.128 8888'
Press Ctrl-C to stop the server
C:\Users\xxxxx\UniqueBible\main.py:121: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**Comment by otseng** [comment]
telnet seems to be working.

Can you also try `python3 uba.py http-server` and `python3 uba.py`?

**Comment by Enockng** [comment]
> telnet seems to be working.
> 
> Can you also try `python3 uba.py http-server` and `python3 uba.py`?


python3 uba.py http-server;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
pip tool updated!
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
main:C
main:D
main:E


python uba.py;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
pip tool updated!
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
main:C
main:D
main:F
main:G
main:H
main:I
main:J
main:J1
main:J2
main:J3
INFO: Could not find files for the given pattern(s).
main:J4

**Comment by otseng** [comment]
Can you replace these files?

db/BiblesSqlite.py
[BiblesSqlite.zip](https://github.com/eliranwong/UniqueBible/files/9174122/BiblesSqlite.zip)

main.py
[main.zip](https://github.com/eliranwong/UniqueBible/files/9174125/main.zip)

Rerun commands:
python3 uba.py
python3 uba.py http-server

**Comment by Enockng** [comment]
> 

python3 uba.py:

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
pip tool updated!
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
main:C
main:D
main:F
main:G
main:H
main:I
main:J
main:J1
main:J2
main:J3
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
INFO: Could not find files for the given pattern(s).
main:J4
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:D
BiblesSqlite:E
BiblesSqlite:F
BiblesSqlite:G

And the program displays; 'Some of your files are old.  We are helping you to upgrade those files.  You will receive another message when the operation is done.'

On clicking OK it adds lines;

BiblesSqlite:H
BiblesSqlite:IOHGB

The program hangs in  'Not Respondig' 

For python3 uba.py http-server;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
pip tool updated!
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
main:C
main:D
main:E
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:D
BiblesSqlite:E
BiblesSqlite:F
BiblesSqlite:G
BiblesSqlite:H
BiblesSqlite:IOHGB

**Comment by Enockng** [comment]
> Can you replace these files?
> 
> db/BiblesSqlite.py [BiblesSqlite.zip](https://github.com/eliranwong/UniqueBible/files/9174122/BiblesSqlite.zip)
> 
> main.py [main.zip](https://github.com/eliranwong/UniqueBible/files/9174125/main.zip)
> 
> Rerun commands: python3 uba.py python3 uba.py http-server

python3 uba.py;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
chinese-english-lookup has been manually disabled
main:C
main:D
main:F
main:G
main:H
main:I
main:J
main:J1
main:J2
main:J3
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
INFO: Could not find files for the given pattern(s).
main:J4
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:D
BiblesSqlite:E
BiblesSqlite:F
BiblesSqlite:G

The program displays; 
![Untitled](https://user-images.githubusercontent.com/101056853/180645398-1c77d4f1-5cd2-4db1-9036-3ece8457a8c4.png)

On clicking 'OK ' it add lines;

BiblesSqlite:H
BiblesSqlite:ILXX

To final console;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
chinese-english-lookup has been manually disabled
main:C
main:D
main:F
main:G
main:H
main:I
main:J
main:J1
main:J2
main:J3
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
INFO: Could not find files for the given pattern(s).
main:J4
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:D
BiblesSqlite:E
BiblesSqlite:F
BiblesSqlite:G
BiblesSqlite:H
BiblesSqlite:ILXX

For python3 uba.py http-server;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
chinese-english-lookup has been manually disabled
main:C
main:D
main:E
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:D
BiblesSqlite:E
BiblesSqlite:F
BiblesSqlite:G
BiblesSqlite:H
BiblesSqlite:IOHGBi

**Comment by otseng** [comment]
Can you replace these files and rerun?

[main.zip](https://github.com/eliranwong/UniqueBible/files/9176390/main.zip)
[MainWindow.zip](https://github.com/eliranwong/UniqueBible/files/9176392/MainWindow.zip)
[BiblesSqlite.zip](https://github.com/eliranwong/UniqueBible/files/9176393/BiblesSqlite.zip)

**Comment by Enockng** [comment]
> Can you replace these files and rerun?
> 
> [main.zip](https://github.com/eliranwong/UniqueBible/files/9176390/main.zip) [MainWindow.zip](https://github.com/eliranwong/UniqueBible/files/9176392/MainWindow.zip) [BiblesSqlite.zip](https://github.com/eliranwong/UniqueBible/files/9176393/BiblesSqlite.zip)

Which folder do I place 'MainWindow.py' ?

**Comment by otseng** [comment]
In gui folder for MainWindow and in db folder for BiblesSqlite.

**Comment by onegladiator4u** [comment]
when I reinstalled UBA and copied Marveldata files i stored separately as a backup to new UBA Marveldata folder i had problems like these. So i deleted everything i downloaded using UBA from it and ran. then downloaded again. That worked . This could be something like that . i'm not sure though

**Comment by Enockng** [comment]
> In gui folder for MainWindow and in db folder for BiblesSqlite.

python3 uba.py;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
pip tool updated!
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
main:C
main:D
main:F
main:G
main:H
main:I
main:J
main:J1
main:J2
main:J3
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
INFO: Could not find files for the given pattern(s).
main:J4
main:HA
main:HB
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
main:HC
checkMigration:A
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:D
BiblesSqlite:E
BiblesSqlite:F
BiblesSqlite:G
checkMigration:B
BiblesSqlite:H
BiblesSqlite:I:OHGBi
BiblesSqlite:I1:OHGBi
BiblesSqlite:I2:OHGBi

python3 uba.py http-server;

uba:A
uba:B
uba:C
uba:D
uba:E:1
uba:E:2
main:A
main:B
pip tool updated!
Installing missing module 'chinese-english-lookup' ...
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
main:C
main:D
main:E
BiblesSqlite:A
BiblesSqlite:B
BiblesSqlite:C
BiblesSqlite:D
BiblesSqlite:E
BiblesSqlite:F
BiblesSqlite:G
BiblesSqlite:H
BiblesSqlite:I:OHGBi
BiblesSqlite:I1:OHGBi
BiblesSqlite:I2:OHGBi

**Comment by Enockng** [comment]
> when I reinstalled UBA and copied Marveldata files i stored separately as a backup to new UBA Marveldata folder i had problems like these. So i deleted everything i downloaded using UBA from it and ran. then downloaded again. That worked . This could be something like that . i'm not sure though

Big UP!!! 👍 It is TRUE!! The problem is within 'Marveldata' folder.

**Comment by otseng** [comment]
Oh wow.  I would've never guessed that solution.  Thanks @onegladiator4u !
