### ISSUE TITLE
Issue with Bible Tabs

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#1137]
I have 7 bible tabs, with the 7th set to LXX1i. I clear that tab via "Clear Main Tabs 7", then I click "UniqueBible/Quit". I reopen UBA and Bible tab 7 reopens to LXX1i. How can I have the tab stay clear?

**Comment by otseng** [comment]
What is "Clear Main Tabs 7"?  Is that a plugin?
Have you tried the bottom button on the left hand menubar?
For me, I clear populateTabsOnStartup config flag so it doesn't populate all the tabs.

**Comment by otseng** [comment]
Try adding this to your plugin:
`config.tabHistory["main"]['6'] = ''`

**Comment by darrelwright** [comment]
That works! Thank you!
