### ISSUE TITLE
Workspace question

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#1138]
I am confused on how to generate new workspace.
1. Do I have to create the workspace directory in advance? I manually created "The Lord of the Wind and the Waves".
2. Is there a limit to length of name?  The name I used is "The Lord of the Wind and the Waves". The book created is "The Lord of the Wind".
3. When I copy text to the clipboard, then when I click to copy clipboard to the workspace, how can I copy that text to a new workspace?

**Comment by otseng** [comment]
>     1. Do I have to create the workspace directory in advance? I manually created "The Lord of the Wind and the Waves".

No.  After you click "Save workspace in directory", in the save window, you can click on "new folder".

>     2. Is there a limit to length of name?  The name I used is "The Lord of the Wind and the Waves". The book created is "The Lord of the Wind".

There's no limit.  I was able to create "The Lord of the Wind and the Waves" as a book from the workspace.

>     3. When I copy text to the clipboard, then when I click to copy clipboard to the workspace, how can I copy that text to a new workspace?

What do you mean by "new workspace"?

**Comment by darrelwright** [comment]
I am reading a topic a topic from Rick Renner titled "Taking Authority Over the Wind and Waves in Your Life", and I want to include it n UBA. So I highlight the text and copy it to the clipboard.

Next I right-click the icon "B" and select "Add clipboard text to workspace", and I want to add it to a new workspace, but the only option is adding to an existing workspace.

Granted I can do that, then delete the existing content and save it in a new directory,but there is a lot of potential for error. I would like the ability to create a new directory and save the contents without the extra steps.

Next when I create a reference book from the workspace and name the book (in this example with the long name just mentioned) it creates the book nicely, but when you look at the book with a SQL editor the name of the book is chopped in half. This should not be. The name should be full length. I have to edit the book and make the name full length.

I love the workspace but would like just a couple of enhancements. Please tell me if I am overlooking something.

**Comment by otseng** [comment]
Right now, can only work on one workspace at a time.  

| but when you look at the book with a SQL editor 

What SQL editor are you using?

**Comment by darrelwright** [comment]
DB Browser for SQLite

**Comment by otseng** [comment]
Can you send a copy of your book?

**Comment by darrelwright** [comment]
Do you want a book that I have not edited and updated the name?

**Comment by darrelwright** [comment]
This is the result of the book creation following the steps given previously. Now I have to edit the book, browse data, modify the chapter, expand the name, remove the numbers at the beginning of the name, save the book and then I am good-go. I have done this process for 27 books.

[The Result of Pauls Preaching on Mars Hill.book.zip](https://github.com/eliranwong/UniqueBible/files/9192244/The.Result.of.Pauls.Preaching.on.Mars.Hill.book.zip)

**Comment by otseng** [comment]
Found the code.  Yes, it's limiting the filename length to 20 characters.  I'll create a config flag later to make it unlimited length.

**Comment by darrelwright** [comment]
I would sure like ability to create a new folder in workspace when creating a new entry. Right now when I add new content from the the clipboard it adds to the current workspace folder and IMMEDIATELY saves that folder. The only way around that is if I copy that folder, rename it to my new name, delete the contents, then copy the clipboard to the new folder.

**Comment by eliranwong** [comment]
use "Save Workspace in Directory", to save files in new directory
and use "new folder" from file dialog, e.g.
<img width="864" alt="Screenshot 2022-07-28 at 23 49 35" src="https://user-images.githubusercontent.com/25262722/181650390-69d0378f-8466-4f45-ab5a-c96c05e59a03.png">


<img width="816" alt="Screenshot 2022-07-28 at 23 50 20" src="https://user-images.githubusercontent.com/25262722/181650399-09fb56ce-79fa-4d89-9c44-d0144f668a85.png">

**Comment by otseng** [comment]
> Next when I create a reference book from the workspace and name the book (in this example with the long name just mentioned) it creates the book nicely, but when you look at the book with a SQL editor the name of the book is chopped in half. This should not be. The name should be full length. I have to edit the book and make the name full length.

I added the config flag limitWorkspaceFilenameLength.  Set it to false to have the name full length.

**Comment by darrelwright** [comment]
There is a continuing issue with a new workspace file.

I open a workspace file, then click "Save Workspace In Directory", then click on "workspace", then click on the "new directory" icon, give it a new name and then click "open". The workspace opens with the current file. I delete the current file, then add the clipboard text to workspace. Then I create reference book from workspace and get the following message:

![no valid file](https://user-images.githubusercontent.com/11500764/181872762-ecf324ff-6442-4ab2-8c8c-f1b50bf5e514.png)

And here is the workspace folder:

[Standing Together To Overcome the Darkness.zip](https://github.com/eliranwong/UniqueBible/files/9224801/Standing.Together.To.Overcome.the.Darkness.zip)

**Comment by otseng** [comment]
There is nothing in your zip file.

**Comment by otseng** [comment]
I see now why the title was limited to 20 chars.  If copying from clipboard, the title is the same as the entire clipboard text.  Perhaps the title should just be "clipboard" and then you have to edit the title later.

**Comment by darrelwright** [comment]
I don't really think that is the answer. When I add the clipboard to the 
workspace the next thing I do is change the title to what is supposed to 
be, but the file is corrupted at that point. If I set the name length to 
true and the repeat the same steps the file is good. I then have to edit 
the title, but the file is good.

**Comment by darrelwright** [comment]
Correct me if I am wrong, but I don't think the issue is multiple 
workspaces, just the ability to create a new folder under the workspace 
when adding new content?
