### ISSUE TITLE
Verse reference on hover only showing one verse 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1159]
Study window references in range works for notes when hover. not working for commentaries and title references .
![python_yjKGw2mX7G](https://user-images.githubusercontent.com/48617390/181473216-efa701b4-a3b5-44f1-ab9b-65aa48a741b2.gif)
![python_p7LVBIquMT](https://user-images.githubusercontent.com/48617390/181474383-58216910-e826-4705-b896-415cccc040fd.gif)

**Comment by eliranwong** [comment]
It looks like the commentary was converted before verse range is support.  This issue is down to individual commentaries files.  It depends on when they were created.  UBA previously did not support verse range for conversion, that's why files created long time ago does not support verse range.

**Comment by onegladiator4u** [comment]
> It looks like the commentary was converted before verse range is support. This issue is down to individual commentaries files. It depends on when they were created. UBA previously did not support verse range for conversion, that's why files created long time ago does not support verse range.

what about the title references in bible @eliranwong ? i was working , now it's not

**Comment by onegladiator4u** [comment]
Bro, it's working on Bible commentary plug in. Also I deleted the commentary and downloaded again. Still same problem. Are you sure there's no problem with it?

**Comment by eliranwong** [comment]
> > It looks like the commentary was converted before verse range is support. This issue is down to individual commentaries files. It depends on when they were created. UBA previously did not support verse range for conversion, that's why files created long time ago does not support verse range.
> 
> what about the title references in bible @eliranwong ? it was working , now it's not

What is "title references in bible"?

**Comment by eliranwong** [comment]
> Bro, it's working on Bible commentary plug in. Also I deleted the commentary and downloaded again. Still same problem. Are you sure there's no problem with it?

do you mean same file work on commentary plugin but not on Study Window?

**Comment by onegladiator4u** [comment]
> > > It looks like the commentary was converted before verse range is support. This issue is down to individual commentaries files. It depends on when they were created. UBA previously did not support verse range for conversion, that's why files created long time ago does not support verse range.
> > 
> > 
> > what about the title references in bible @eliranwong ? it was working , now it's not
> 
> What is "title references in bible"?

![fu8XSUKhJW](https://user-images.githubusercontent.com/48617390/181688431-d5587a22-3ef2-4639-9afb-c574105187a1.png)

I meant this one. 😀 Didn't know what to call it

**Comment by onegladiator4u** [comment]
> do you mean same file work on commentary plugin but not on Study Window?

Yes, see for eg: Barnes commentary 

https://user-images.githubusercontent.com/48617390/181688920-7da6b6e0-d52c-4e65-a311-fed47706bedb.mp4

**Comment by eliranwong** [comment]
> > do you mean same file work on commentary plugin but not on Study Window?
> 
> Yes, see for eg: Barnes commentary

I can see the difference now.  I will take a look into it.

**Comment by onegladiator4u** [comment]
There's two onmouseover for study window and bible window references 
Bible Window references below Titles- 
<ref onclick="bcv(38,13,7)" onmouseover="imv(38,13,7)" onmouseover="imv(38,13,7,13,9)">Zech 13:7-9</ref> 
<ref onclick="bcv(40,26,31)" onmouseover="imv(40,26,31)" onmouseover="imv(40,26,31,26,35)">Matt 26:31-35</ref> 
<ref onclick="bcv(42,22,31)" onmouseover="imv(42,22,31)" onmouseover="imv(42,22,31,22,38)">Luke 22:31-38</ref> 
<ref onclick="bcv(43,13,36)" onmouseover="imv(43,13,36)" onmouseover="imv(43,13,36,13,38)">John 13:36-38</ref>



Study Window Commentary -
<ref onclick="bcv(40,26,17)" onmouseover="imv(40,26,17)" onmouseover="imv(40,26,17,26,19)">Mat 26:17-19</ref>


Plugin Commentary -
<ref onclick="bcv(40,26,17)" onmouseover="imv(40,26,17,26,19)">Mat 26:17-19</ref>

**Comment by onegladiator4u** [comment]
> There's two onmouseover for study window and bible window references 
Bible Window references below Titles- 
<ref onclick="bcv(38,13,7)" onmouseover="imv(38,13,7)" onmouseover="imv(38,13,7,13,9)">Zech 13:7-9</ref> 
<ref onclick="bcv(40,26,31)" onmouseover="imv(40,26,31)" onmouseover="imv(40,26,31,26,35)">Matt 26:31-35</ref> 
<ref onclick="bcv(42,22,31)" onmouseover="imv(42,22,31)" onmouseover="imv(42,22,31,22,38)">Luke 22:31-38</ref> 
<ref onclick="bcv(43,13,36)" onmouseover="imv(43,13,36)" onmouseover="imv(43,13,36,13,38)">John 13:36-38</ref>



Study Window Commentary -
<ref onclick="bcv(40,26,17)" onmouseover="imv(40,26,17)" onmouseover="imv(40,26,17,26,19)">Mat 26:17-19</ref>


Plugin Commentary -
<ref onclick="bcv(40,26,17)" onmouseover="imv(40,26,17,26,19)">Mat 26:17-19</ref>

**Comment by onegladiator4u** [comment]
There's two onmouseover for study window and bible window references 
Bible Window references below Titles- 
```
<ref onclick="bcv(38,13,7)" onmouseover="imv(38,13,7)" onmouseover="imv(38,13,7,13,9)">Zech 13:7-9</ref> 
<ref onclick="bcv(40,26,31)" onmouseover="imv(40,26,31)" onmouseover="imv(40,26,31,26,35)">Matt 26:31-35</ref> 
<ref onclick="bcv(42,22,31)" onmouseover="imv(42,22,31)" onmouseover="imv(42,22,31,22,38)">Luke 22:31-38</ref> 
<ref onclick="bcv(43,13,36)" onmouseover="imv(43,13,36)" onmouseover="imv(43,13,36,13,38)">John 13:36-38</ref>
```



Study Window Commentary -
`<ref onclick="bcv(40,26,17)" onmouseover="imv(40,26,17)" onmouseover="imv(40,26,17,26,19)">Mat 26:17-19</ref>`


Plugin Commentary -
`<ref onclick="bcv(40,26,17)" onmouseover="imv(40,26,17,26,19)">Mat 26:17-19</ref>`

**Comment by eliranwong** [comment]
fixed in latest codes https://github.com/eliranwong/UniqueBible/commit/a42cc0e4daa5389191c36ad0ef63ba74b6ea14c9

**Comment by onegladiator4u** [comment]
Working now brother. Thank you
