### ISSUE TITLE
one book in Bible Promises not opening 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1161]
precious bible promises I not opening

**Comment by eliranwong** [comment]
thanks for report.  I can reproduce the issue.  I will fix it.

same issue as in Bible Parallel first module.

**Comment by eliranwong** [comment]
Fixed in latest codes

**Comment by onegladiator4u** [comment]
@eliranwong hey bro,  just checked parallel module. It's not opening. Console shows error as
Failed to run 'Bible Parallels. Py'!

**Comment by eliranwong** [comment]
Bible Parallels run as expected on my side.  I don't know how to reproduce the issue

**Comment by eliranwong** [comment]
> @eliranwong hey bro, just checked parallel module. It's not opening. Console shows error as
> Failed to run 'Bible Parallels. Py'!

can you try:

1) close UBA first
2) set "developer = True" in the third line of file "config.py"
3) run uba again and launch Bible Parallels

and see if any errors printed on console and let me know.

thank you.

**Comment by otseng** [comment]
I was able to duplicate it.  
@onegladiator4u open the Bible Parallels.py file and delete all the lines with Chinese characters in it starting on line 55.  Line 55 should then only have a ")" in it.

**Comment by onegladiator4u** [comment]
> I was able to duplicate it. @onegladiator4u open the Bible Parallels.py file and delete all the lines with Chinese characters in it starting on line 55. Line 55 should then only have a ")" in it.

It worked bro 👍🏼

**Comment by onegladiator4u** [comment]
@otseng can duplicate this issue also where buttons show like this ?
![image](https://user-images.githubusercontent.com/48617390/181876329-0a0e7d78-4d34-435e-82be-1e1051776bf2.png)

**Comment by eliranwong** [comment]
@onegladiator4u please update to the latest codes ver 31.59 and see if it works.  Thanks.
