### ISSUE TITLE
Create Windows executable version of UBA

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#1167]
Create a standalone version of UBA for Windows.  There's no need to install Python or any libraries and all need to do is unzip a file and double-click on the executable.

**Comment by otseng** [comment]
https://github.com/eliranwong/UniqueBible/discussions/1168

**Comment by otseng** [comment]
To run it:
- download the zip file
- unzip it
- double-click on UBA.exe

Note, this is an experimental alpha release, so there are many functionalities that do not work yet.

**Comment by onegladiator4u** [comment]
It's working good. Don't know which all the features are now available . So couldn't comment on each one

**Comment by otseng** [comment]
Great, thanks!  I'll have more experiments that I'll post here after I upload them.

**Comment by onegladiator4u** [comment]
> Great, thanks! I'll have more experiments that I'll post here after I upload them.

pk. cool

**Comment by otseng** [comment]
Released Windows binary 31.62 - alpha:
https://github.com/otseng/UniqueBible/releases/tag/windows_31.62_alpha1

This one should fix the virus check issue and saving the config.

**Comment by onegladiator4u** [comment]
Yes, virus warning is no more. good job bro. Config working too.

**Comment by otseng** [comment]
First official binary release for Windows.  😄 
https://github.com/eliranwong/UniqueBible/releases/tag/windows_31.62.1

**Comment by onegladiator4u** [comment]
Great!. Bro how does update work in this ? Should we unzip and replace old directory ?

**Comment by otseng** [comment]
Can you unzip and try just replacing UBA.exe in your old directory?

**Comment by onegladiator4u** [comment]
> Can you unzip and try just replacing UBA.exe in your old directory?

i haven't started using it normally yet bro, So i'm good with replacing all now. I just wanted to know before i use it often.

**Comment by onegladiator4u** [comment]
@otseng hey bro,
last week onwards it started to show it as virus again. Probably after bitdefender update. 

The file D:\UBA\UBA.exe is infected with Trojan.Python.Stealer.F. Bitdefender blocked this item, your device is safe.

**Comment by otseng** [comment]
> @otseng hey bro, last week onwards it started to show it as virus again. Probably after bitdefender update.
> 
> The file D:\UBA\UBA.exe is infected with Trojan.Python.Stealer.F. Bitdefender blocked this item, your device is safe.

Looks like I'll have to make a request for Bitdefender to whitelist the binary.  Unfortunately, this might mean every time I release a binary I have to make a request.

**Comment by onegladiator4u** [comment]
I checked whether its only in Bitdefender. But it's not.

[See here](https://www.virustotal.com/gui/file/e0c5cfb41dc7963358c4f4a8881086e75f041f03e65f9acd940250f3d0ae9796?nocache=1)
