### ISSUE TITLE
Apocrypha/Deutrocanical Books

### ISSUE THREAD

**Issue by Enockng** [eliranwong/UniqueBible#1169]
I have imported MyBible Modules with Apocrypha, but can't see Additions to Esther, Addition to Psalms and Prayer of Azariah in the app.
On using sqlite tools I can find the books data inside imported modules.
What can I do the app to display these books or is there something missing?

**Comment by otseng** [comment]
Support for Deuterocanonical books are hit and miss.  Can you provide link to the module you are trying to import?

**Comment by Enockng** [comment]
> 



> Support for Deuterocanonical books are hit and miss. Can you provide link to the module you are trying to import?

https://www.ph4.org/_dl.php?back=bbl&a=RSV&b=mybible&c

**Comment by eliranwong** [comment]
I remember converting apocrypha is supported for MyBible modules.

Some MyBible modules do not follow standard scheme MyBible team suggest.

Let me check on this one when I have time.

**Comment by otseng** [comment]
Give it a try now.  One thing is the MyBible RSV has "Greek Esther", which I mapped to "Additions to Esther".
