### ISSUE TITLE
UBA Is Not Displaying Modules

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#1174]
I just upgraded from Linux Mint 20.3 to version 21. When I start UBA it is not displaying modules as shown in this screenshot:

![display](https://user-images.githubusercontent.com/11500764/183552504-a8e91e1e-b0ca-4407-8a7c-7c9e95994eeb.png)

How can I recover? In this case I just opened BSB in both Mzin and Study windows. Also this is version 31.62. It was working until I did the OS upgrade. The webtop version displays perfectly.

**Comment by otseng** [comment]
Any output from console?

**Comment by darrelwright** [comment]
No. UBA, from the command, starts normal. Here is a screen showing the 
command line and how UBA starts.

**Comment by darrelwright** [comment]
Oh, just a little more info. I have removed and reinstalled python3, 
renamed UniqueBible directory and reinstalled from github with no change.

**Comment by otseng** [comment]
Can you try running in http-server mode?
`python3 uba.py http-server`

**Comment by darrelwright** [comment]
If you the webtop version it runs perfectly.

**Comment by otseng** [comment]
What about http-server mode?

**Comment by darrelwright** [comment]
If http-server as different from webtop I'm not sure how to do that.😅

**Comment by otseng** [comment]
In console in UBA directory, run `python3 uba.py http-server`

**Comment by darrelwright** [comment]
It appears to display:

**Comment by otseng** [comment]
So the database files are fine then. 

Way past time for me to sleep. Will think of some more ideas tomorrow.

**Comment by otseng** [comment]
Can you set the config flag `forceGenerateHtml` to true.  Then look in the folder htmlResources and open the file `main.html` with your browser.

**Comment by darrelwright** [comment]
It shows this:

**Comment by darrelwright** [comment]
Aye, it is 4:30am, I gotta sleep for a bit!😁

**Comment by onegladiator4u** [comment]
Did you download bible modules again or copied older files to it?

**Comment by darrelwright** [comment]
I copied older module files.I did reinstall UBA fresh from git clone.

**Comment by darrelwright** [comment]
Okay I installed from git clone, then installed some formatted bibles, 
and still have nothing displayed.

**Comment by otseng** [comment]
In your config.py, try setting:
qtLibrary = 'pyside2'

**Comment by otseng** [comment]
BTW, your screenshots are not showing up for me, except for the first one.

**Comment by darrelwright** [comment]
It already is.

**Comment by darrelwright** [comment]
hmmm. I better start posting them on github, huh?

**Comment by darrelwright** [comment]
I am debating whether I need to reinstall LM 21 from scratch. I am 
hesitant because I may end up losing a bunch of stuff. Thoughts?

**Comment by otseng** [comment]
Can you try... qtLibrary = 'pyside6'

**Comment by otseng** [comment]
Can you paste screenshot again for...

> Can you set the config flag `forceGenerateHtml` to true. Then look in the folder htmlResources and open the file `main.html` with your browser.

**Comment by darrelwright** [comment]
That appears to have fixed the issue! I have all my bibles showing, 
study window is functioning, audio is working...

Now is there anything else I might need change? It appears to be related 
to latest library used in Mint 21.

**Comment by darrelwright** [comment]
Here is the html screenshot:

![html](https://user-images.githubusercontent.com/11500764/183806375-ec859ddc-31cf-4bb2-955f-255ebe14aa70.png)

**Comment by darrelwright** [comment]
I posted it on github.

**Comment by otseng** [comment]
> That appears to have fixed the issue! I have all my bibles showing, study window is functioning, audio is working... Now is there anything else I might need change? It appears to be related to latest library used in Mint 21.

Great.  Looks like some incompatibility problem with Mint 21 and pyside2.  Closing the issue.

**Comment by darrelwright** [comment]
Thanks Oliver! I appreciate your help.

**Comment by darrelwright** [comment]
I don't know if I posted the html snapshot, so here it is!

![html](https://user-images.githubusercontent.com/11500764/183854416-1559f9a2-1143-4324-921c-cf0b01929cc5.png)

**Comment by darrelwright** [comment]
Need to add shift on done for clearing all checked bibles

**Comment by otseng** [comment]
> Need to add shift on done for clearing all checked bibles

Can you show a screenshot of your request?
