### ISSUE TITLE
Changing menu layout color issue

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1175]
Hi brothers, 
Changing menu layout from material layout to aleph or others changes color of material layout when changing back to it.
If color profile is not saved through Appearance > customize color it'll be a problem .

**Comment by eliranwong** [comment]
it is a good practice to save a file for customised colours.

menu layout other than material menu layout uses basic colours only.

**Comment by onegladiator4u** [comment]
ok got it.I thought material layout remembering the settings that used earlier would be a nice option when changing back to from other layout.
