### ISSUE TITLE
The file TheText.ico

### ISSUE THREAD

**Issue by jpgotopo** [eliranwong/UniqueBible#1178]
The file TheText.ico is not found in htmlResources folder.

**Comment by otseng** [comment]
How to replicate this issue?

**Comment by eliranwong** [comment]
TheText.ico?  I don't find "TheText.ico" in current codes.

**Comment by jpgotopo** [comment]
I refer this:
![Screenshot_20220817-150627_Chrome](https://user-images.githubusercontent.com/27728874/185233108-cc0899f9-fa3a-4193-92c0-57a14cff9681.jpg)

**Comment by eliranwong** [comment]
I got it now, can you try to use "UniqueBibleApp.png"?

**Comment by jpgotopo** [comment]
>

**Comment by eliranwong** [comment]
Thanks for correction.  I just added a .ico file in the latest code.  closing this issue now.
