### ISSUE TITLE
Add passage presentation mode to macros

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#118]
Add ability to present a Bible passage in full screen presentation mode using macros.  This would be helpful during sermons or just displaying a verse on a computer screen.  

It should be able to display multiple verses on the screen.  

Once get this working, will have a 2.0 version that can display verses on a separate monitor.

**Comment by otseng** [comment]
Add this as a command plugin by creating "plugins/command" directory.  Files in this directory will extend the TextCommandParser functionality.

**Comment by eliranwong** [comment]
sounds good

**Comment by eliranwong** [comment]
@otseng 

I think it may not be necessary to add "command" plugins.  I had just made a minor adjustment in text command parser, users can simply add command or functionality by adding entries to "interpreters".  I think startup plugin may be enough to do the work

please take a look at: https://github.com/eliranwong/UniqueBible/commit/dfacfdfcfa5598948f8afe4e63ba14d255f89d00

if something can be done with startup plugin, I don't want to add extra category of plugins unless it is necessary.

**Comment by eliranwong** [comment]
@otseng 

You can simply add a startup plugin with lines, e.g.

def newFunction():
    pass

config.mainWindow.textCommandParser.interpreters["mynewcommand"] = (newFunction, "documentation")

**Comment by otseng** [comment]
ok, will do.

**Comment by otseng** [comment]
To test, create a macro named "Presentation.ubam" with contents:

```
# Example presentation

. hideAllToolBar
. hideLeftToolBar
. hideRightToolBar
. setInstantSize 0

PRESENT:::NET:::Rom 5:12:::font-size:1.5em;margin-left:50px;margin-right:50px;color:red

. setParallelSize 0
. pause

PRESENT:::NET:::John 3:16-17:::font-size:1.5em;margin-left:50px;margin-right:50px;color:magenta

. setParallelSize 0
. pause

John 3:16

. showAllToolBar
. setParallelSize 2
. setInstantSize 1
```
