### ISSUE TITLE
Active Verse Color

### ISSUE THREAD

**Issue by Enockng** [eliranwong/UniqueBible#1183]
I want to set Active Verse Color in 'custom.css' file. Please help with the code!

**Comment by otseng** [comment]
It's not possible to set it in custom.css that I know of.  But you can manually edit the config.py file and change the following:
```
lightThemeActiveVerseColor = '#483D8B'
darkThemeActiveVerseColor = '#aaff7f'
```
However, this setting probably gets overwritten if you ever change to another theme.

**Comment by Enockng** [comment]
> It's not possible to set it in custom.css that I know of. But you can manually edit the config.py file and change the following:
> 
> ```
> lightThemeActiveVerseColor = '#483D8B'
> darkThemeActiveVerseColor = '#aaff7f'
> ```
> 
> However, this setting probably gets overwritten if you ever change to another theme.



> It's not possible to set it in custom.css that I know of. But you can manually edit the config.py file and change the following:
> 
> ```
> lightThemeActiveVerseColor = '#483D8B'
> darkThemeActiveVerseColor = '#aaff7f'
> ```
> 
> However, this setting probably gets overwritten if you ever change to another theme.

Also can set it from 'Customerise Color' item, again it gets altered on theme change. That is why I requested for it in custom.css!

**Comment by otseng** [comment]
I'll add ability to support colors customization for specific layout/theme:  https://github.com/eliranwong/UniqueBible/issues/1184
