### ISSUE TITLE
Add API or other possibilities to interact with UniqueBible

### ISSUE THREAD

**Issue by jajpater** [eliranwong/UniqueBible#119]
This is basically a request for enormous enhancements. I'm interested in mouseless navigation primarily. So it would be great if UniqueBible was navigatable in a way like the Surfingkeys plugin does for browsers. I guess that is very hard to implement. Another possibilitie would be to have a kind of API so that I can consult UniqueBible from emacs or from vi or at least import some of the information from UniqueBible into a emacs or vi buffer. I will not use the editor enclosed with UniqueBible since it has nog vi keybindings. Well of course I entirely understand it if you would reject these proposals. But I just humbly wanted to ask if something in this direction is possible?

**Comment by eliranwong** [comment]
@jajpater thanks for your message.  your suggestion is welcome.

Currently, we have a small project that can read / search / compare bibles versions via terminal / console:

https://github.com/eliranwong/bible

Personally, I like your idea.  I think UBA desktop version has potential to do it, as it is a command-based application behind the gui skin.  I would like to access UBA materials through terminal too.  I hope I may have time to do it in the future.  I also welcome to contribute codes and develop the app together.

may be @otseng can give us some inputs?  is the macro features you are developing going toward a similar direction as @jajpater suggested above?

**Comment by otseng** [comment]
Interesting idea of being able to remotely issue commands into UBA.  It's definitely worth looking into.

How about something like can access UBA through telnet/ssh and be able to run UBA commands?

**Comment by jajpater** [comment]
@otseng That would be very nice. For instance choose translation or commentary or verse references etc ... so that the asked for information becomes visible in UBA. Another second step would be to get the bibletext and/or commentary or notes back as either plain text or any other format into the editor or terminal from which the command was send.

**Comment by jajpater** [comment]
@eliranwong Does the dartbible you mention use the same marvelData as UBA does?

**Comment by eliranwong** [comment]
> @eliranwong Does the dartbible you mention use the same marvelData as UBA does?

no.  the only connection is that I use UBA convertor to convert bible texts into json for use in the dartbible.

in addition, don't expect too much from the small project I mentioned above.  this is an exercise when I first learnt dart.  it was later developed into a mobile app project.  so the terminal app only has very basic features.  simply read, search bible or do simple comparison.

**Comment by eliranwong** [comment]
@jajpater bty, the following dart/flutter project is going to use same resources as UBA desktop version:

https://github.com/eliranwong/UniqueBibleAppHybrid

**Comment by otseng** [comment]
This is how I'm thinking of designing it:

Start up UBA in remote CLI mode by:

`python main.py cli 8888`

This will cause UBA to act as a telnet server on port 8888.  The UI will not be started.  

Then in another window, run:

`telnet localhost 8888`

You'll then be able to run commands, such as:

`BIBLE:::KJV:::John 3:16`

The code will have to be modified to handle this differently than normal since using CLI, you only want one verse to be returned.

**Comment by otseng** [comment]
Documentation on Remote CLI:

https://github.com/eliranwong/UniqueBible/wiki/Remote-CLI

**Comment by eliranwong** [comment]
@jajpater  CLI without running server: https://github.com/eliranwong/UniqueBible/wiki/Command-Line-Interface

**Comment by jajpater** [comment]
This is really great!
