### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Enockng** [eliranwong/UniqueBible#1193]

**Comment by eliranwong** [comment]
I haven't tried.  Where did you see the tutorial?

**Comment by Enockng** [comment]
This issue was solved at
https://github.com/eliranwong/UniqueBible/commit/59ee63104023bfe74c04dad08c9244146fdfea85

Just copy the whole UniqueBibleApp folder from online computer and install the global python packages on offline computer downloaded by 'pip download -r path\requirements.txt -d path\offlinepackages'
