### ISSUE TITLE
need to check / fix sharing resource folder on Windows

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#12]
multple copies of UniqueBible.app can share a single resource folder on a single device.  It works well on Linux and macOS.  It looks like it is not working on Windows.  need to check or fix ...

**Comment by onegladiator4u** [comment]
Forgive me to ask on this issue. Brother how should I name the bible verse in **Note** so that it's verse shows up in bottom window on hover over it? Is there code for it. I tried many combo, nothing worked.

**Comment by eliranwong** [comment]
You are always welcome to report issues or make suggestion.  Bible verses in display mode are automatically linked.  Let me check if something broken.

**Comment by onegladiator4u** [comment]
Ok. Thank you

**Comment by eliranwong** [comment]
Shared folder works on Windows, just need to escape the backslash character, e.g.

> marvelData = 'C:\\Users\\username\\UniqueBible\\marvelData'
