### ISSUE TITLE
adding bibles and datasets are not working

### ISSUE THREAD

**Issue by Gennesse** [eliranwong/UniqueBible#1233]
Hi,
This is the first time I work with UAB, look s nice and useull!
But the unpacking of the zipfile took a very long time with 7zip, and with windows unzip was not possible.
When I want to add Bibles and commentaries etc it fails most of the time. I could download some , but most are failing in download so I wanted te hereby report it.
gr Richard Gennesse

**Comment by otseng** [comment]
Could you screenshots of the errors?

**Comment by Gennesse** [comment]
Hi
Thanks for your reply. It says that the download was failed. I found that
there was also a command box saying Icould also try to download a Dropbox
link in the browser an when I do that I see a warning that Chrome kan not
check the file for viruses but I can download it. So the automatic download
within UBA does not work for all files. I also see that the UBA on my
computer is slower then the web application? Normally this should be faster?
Gr Richard

Op do 13 okt. 2022 13:38 schreef Oliver Tseng ***@***.***>:

**Comment by otseng** [comment]
I'm not able to view your screenshot.  

Also, how did you download the file and running UBA?  Did you download the source code and run using python?  Or did you download the installer and run the UBA binary executable?

**Comment by Gennesse** [comment]
Hi I did run the executable binary


Op do 13 okt. 2022 22:06 schreef Oliver Tseng ***@***.***>:

**Comment by otseng** [comment]
> Hi I did run the executable binary 

It's in an experimental stage right now, so there are many things that needs to be worked out with the exe binary version.

The exe binary version is not able to update the code.

What Bibles and commentaries are you trying to download that cannot be downloaded?

**Comment by eliranwong** [comment]
closing, as we received no further information.
