### ISSUE TITLE
Error while updating from 32.21 to latest

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1244]
![python_H3QCyIij82](https://user-images.githubusercontent.com/48617390/196791590-d112593e-8df2-4b99-ab0a-e6e14e9a542f.png)
![python_wnx1fVZHsg](https://user-images.githubusercontent.com/48617390/196791601-9ca3f2d0-d4b5-45fc-aa1f-b186c13870fc.png)
![python_em4wO15xNF](https://user-images.githubusercontent.com/48617390/196791605-d555b1ed-71da-4846-82ce-3e3c8064cba5.png)

more errors like these

APP WORKS THOUGH

**Comment by otseng** [comment]
Could you manually create the directory `plugins/terminal` and retry?

**Comment by eliranwong** [comment]
fixed in the latest update.
