### ISSUE TITLE
Qt Graphical Interface Library' is not installed

### ISSUE THREAD

**Issue by mooru** [eliranwong/UniqueBible#1246]
I have been having this error for the past few days. What can I do to fix it?

Installing missing module 'PySide6' ...
'Qt Graphical Interface Library' is not installed!
To run UBA with graphical interface, install 'PySide6', 'PySide2' or 'PyQt5' first!

**Comment by eliranwong** [comment]
I guess you are running UBA on macOS?

try steps below:

1. make sure UBA is not running
2. edit the file "config.py"
3. locate 'usePySide6onMacOS = True'
4. change it to 'usePySide6onMacOS = False'

please let me know if it works for you.  thank you.

**Comment by mooru** [comment]
It used PyQt5, encountered an error and stopped all installation 

Installing missing module 'PySide2' ...
PySide2 is not found!  Trying to install 'PyQt5' instead ...
Installing missing module 'PyQt5' ...
Installing missing module 'PyQtWebEngine' ...
Installed!
Installed!
Installing missing module 'qtpy' ...
/Users/mac/UniqueBible/venv_macOS_x86_64_3.10.8/lib/python3.10/site-packages/qtpy/__init__.py:267: RuntimeWarning: Selected binding "pyside2" could not be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '
Installed!
Installing missing module 'html-text' ...
Installed!
Installing missing module 'html5lib' ...
Installed!
Installing missing module 'mammoth' ...
Installed!
Installing missing module 'htmldocx' ...
Installed!
Installing missing module 'diff_match_patch' ...
Installed!
Installing missing module 'langdetect' ...
Installed!
Installing missing module 'pygithub' ...
Installed!
Installing missing module 'qt-material' ...
Installed!
Installing missing module 'telnetlib3' ...
Installed!
Installing missing module 'ibm-watson' ...
Installed!
Installing missing module 'translate' ...
Installed!
Installing missing module 'qrcode' ...
Installed!
Installing missing module 'pillow' ...
Installed!
Installing missing module 'python-vlc' ...
Installed!
Installing missing module 'yt-dlp' ...
Installed!
Installing missing module 'gTTS' ...
Installed!
Installing missing module 'markdownify' ...
Installed!
Installing missing module 'markdown' ...
Installed!
Installing missing module 'nltk' ...
Installed!
Installing missing module 'word-forms' ...
Installed!
Installing missing module 'lemmagen3' ...
Installed!
Installing missing module 'chinese-english-lookup' ...
Installed!
Installing missing module 'textract' ...
Installed!
Installing missing module 'tabulate' ...
Installed!
Installing missing module 'pyluach' ...
Installed!
Installing missing module 'gmplot' ...
Installed!
Installing missing module 'haversine' ...
Installed!
Installing missing module 'prompt_toolkit' ...
Installed!
Installing missing module 'colorama' ...
Installed!
Installing missing module 'pyperclip' ...
Installed!
Installing missing module 'numpy' ...
Installed!
Installing missing module 'matplotlib' ...
Installed!
Installing missing module 'pickley' ...
Installed!
Installing missing module 'AudioConverter' ...
Installed!
Traceback (most recent call last):
  File "/Users/mac/UniqueBible/main.py", line 683, in <module>
    config.mainWindow = MainWindow()
  File "/Users/mac/UniqueBible/gui/MainWindow.py", line 145, in __init__
    self.setupMenuLayout(config.menuLayout)
  File "/Users/mac/UniqueBible/gui/MainWindow.py", line 265, in setupMenuLayout
    getattr(windowClass, 'setupToolBarStandardIconSize')(self)
  File "/Users/mac/UniqueBible/gui/MaterialMainWindow.py", line 750, in setupToolBarStandardIconSize
    self.addMaterialIconButton("cp0", icon, self.mainTextMenu, self.firstToolBar)
  File "/Users/mac/UniqueBible/gui/MainWindow.py", line 4986, in addMaterialIconButton
    button.setFixedSize(config.iconButtonSize * 4/3, config.iconButtonSize * 4/3)
TypeError: arguments did not match any overloaded call:
  setFixedSize(self, QSize): argument 1 has unexpected type 'float'
  setFixedSize(self, int, int): argument 1 has unexpected type 'float'

**Comment by mooru** [comment]
It worked. Thanks your for the great work

**Comment by eliranwong** [comment]
thanks you.
