### ISSUE TITLE
2 errors on update from 32.71

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1248]
![image](https://user-images.githubusercontent.com/48617390/197415684-e413f57f-55c0-4017-a68f-fd7f57b07d14.png)

**Comment by eliranwong** [comment]
Thanks for report, will fix it

**Comment by onegladiator4u** [comment]
> Thanks for report, will fix it

Anytime brother

**Comment by eliranwong** [comment]
fixed https://github.com/eliranwong/UniqueBible/commit/2547b1318e7c4948e69b50e09f9941603645e464
