### ISSUE TITLE
Does the downloader require Google Cloud?

### ISSUE THREAD

**Issue by JeremyBickel** [eliranwong/UniqueBible#1257]
/UniqueBible/gui/MainWindow.py", line 751, in downloadFile
    fileItems, cloudID, *_ = databaseInfo
ValueError: not enough values to unpack (expected at least 2, got 1)

I get this error when I try to download plugins. I'm using the GUI from a python installation in Linux, and I was able to download a couple of things before this error started (I think it was Bible characters, commentaries and data), but when I got to Bible Dictionaries, it started to blow up. Have you seen this before? I don't have Google Cloud set up.

**Comment by eliranwong** [comment]
@JeremyBickel you don't need to setup Google Cloud.  the app should download files from UBA shared google drive directly.

Thanks for reporting the errors.  We will take a look into it.

**Comment by JeremyBickel** [comment]
This looks the same as issue #1259. 

I should have given you the whole error message, so here it is:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/jeremy/Backups/Bible Study Materials/UniqueBible/main.py", line 874, in global_excepthook
    print(traceback.format_exc())
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "/home/jeremy/Backups/Bible Study Materials/UniqueBible/gui/Downloader.py", line 84, in startDownloadFile
    self.downloadFile(True)
  File "/home/jeremy/Backups/Bible Study Materials/UniqueBible/gui/Downloader.py", line 88, in downloadFile
    self.parent.downloadFile(self.databaseInfo, notification)
  File "/home/jeremy/Backups/Bible Study Materials/UniqueBible/gui/MainWindow.py", line 751, in downloadFile
    fileItems, cloudID, *_ = databaseInfo
ValueError: not enough values to unpack (expected at least 2, got 1)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
