### ISSUE TITLE
Error on installation 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1258]
I ws trying to install a fresh copy of UBA using this https://github.com/eliranwong/UniqueBible/wiki/Install-on-Windows
After this `python uba.py` command got this error 

![powershell_YnjrswN2Dd](https://user-images.githubusercontent.com/48617390/200504221-bc7f6208-ea9d-43ba-a74c-52412032e000.png)

I used zip package https://github.com/eliranwong/UniqueBible/archive/main.zip

and python version is Python311

**Comment by eliranwong** [comment]
@onegladiator4u in your config.py file, what is the value of 'iconButtonSize' ?

**Comment by onegladiator4u** [comment]
> 'iconButtonSize'

its 16.



> I will fix it in the latest update.

What should I do to get latest update after your fix?
Should I download zip package https://github.com/eliranwong/UniqueBible/archive/main.zip and install again ?

**Comment by eliranwong** [comment]
Uploaded, you may redownload. Let me know if it works. Thanks

**Comment by onegladiator4u** [comment]
It worked. Thank You
