### ISSUE TITLE
Upcoming Features

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#126]
Here is a list of upcoming featuers, @otseng free feel to add more.  Welcome everyone to suggest more.

* add a new tab 'Miscellenous' to 'Master Control' panel with new feature access via Master Control
* refresh history records when Master Control tab is opened
* set the search field in focus when Master Control Search tab is opened
* rename 'Remote Control' to 'mini Control'
* add an address bar to built*in YouTube downloader window.
    - The window will then become practically a simple web browser.
    - Two buttons will be added next to the address bar: Download mp3, Download mp4
* increase the number of verse highlight collections from two to ten
* add quick access to verse highlight feature via Master Control
* add ability to customise verse highlight collection name and colours
* add ability to customise kyeboard shortcuts (already done by @otseng; pending for merging)
* add ability to customise verse number single-click action
* add ability to customise verse number double-click action
* add ability to customise toolbar layouts on startup
* add ability to customise default text-to-speech voice via menu
* add ability to customise javascript for interacting with html content.  This may be useful for module creator.

**Comment by otseng** [comment]
I've created a discussion thread to solicit ideas from the public:

https://github.com/eliranwong/UniqueBible/discussions/128
