### ISSUE TITLE
Exiting closes external VLC

### ISSUE THREAD

**Issue by JeremyBickel** [eliranwong/UniqueBible#1261]
When VLC is being used externally to UniqueBible, exiting also closes VLC.

**Comment by eliranwong** [comment]
I can add an option not to close audio on exiting UBA

**Comment by eliranwong** [comment]
I just realised that there is already a config flag to do it,

steps:

1) open from menu "Set Config Flags"

2) search 'doNotStop3rdPartyMediaPlayerOnExit'

3) check it

4) restart UBA
