### ISSUE TITLE
wordNT.data not downloading 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1275]
When we click on the hebrew/ greek words on bottom window , it should open that on study window . But that module is not downloading 
![python_jDHQETH6gA](https://user-images.githubusercontent.com/48617390/207310330-383d6dfa-7f5f-4273-87d7-af9412ffbd30.png)
![python_9UQ3GzNzBm](https://user-images.githubusercontent.com/48617390/207310348-abd47349-c96b-4266-97db-c0eb8ed43234.png)

**Comment by otseng** [comment]
Can you see if the file size of marvelData/data/wordNT.data is 0?  If so, delete it and then try redownloading.

**Comment by onegladiator4u** [comment]
> Can you see if the file size of marvelData/data/wordNT.data is 0? If so, delete it and then try redownloading.

Hi @otseng There's no file in that name in the folder you mentioned .

**Comment by otseng** [comment]
Something is wrong with the remote permissions on Google.

@onegladiator4u can you try downloading it directly and unzipping and putting the file into marvelData/data:
https://drive.google.com/uc?id=11pmVhecYEtklcB4fLjNP52eL9pkytFdS

@eliranwong something seems wrong with the Google file permissions.  you can replicate it by deleting the the wordNT and wordOT data files and then running a `word:::1:::2` command.

It's giving error:
```
Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 
```

**Comment by onegladiator4u** [comment]
> @onegladiator4u can you try downloading it directly and unzipping and putting the file into marvelData/data:
> https://drive.google.com/uc?id=11pmVhecYEtklcB4fLjNP52eL9pkytFdS

yes. It works now bro. Thanks
