### ISSUE TITLE
Compare all versions on Study Window 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1284]
Is there an option an option to open Compare all versions on study window ?
Now it open by replacing current main window. If there is no option for that, would you like that option ? Like this
![Edited](https://user-images.githubusercontent.com/48617390/210867044-6ea763d6-41e1-4fb6-9035-f370a62b892d.png)

**Comment by eliranwong** [comment]
no, you can open the comparison in a new window.

alternately, you may have a single bible opened on study window and comparison on main window.

**Comment by onegladiator4u** [comment]
Oh ok. I thought it would make a good feature..

**Comment by onegladiator4u** [comment]
@eliranwong Only if you like the idea and easy to add, then do it. I can use it the way you described. I thought it's just easier this way when i saw like this in netbible.org. That's why i suggested it. Thanks for looking into it.

**Comment by eliranwong** [comment]
It is easy to add, so I did this:

Changes in 33.37:
* Added a config flag 'compareOnStudyWindow', configurable via Config Flag Window.
    Turn it on to display bible comparison on Study Window instead on Main Window.

@onegladiator4u please check if it works for you.

**Comment by onegladiator4u** [comment]
Yes it works bro. Thank you. It's great .
