### ISSUE TITLE
Interlinear and flat Modules creation Guide

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [eliranwong/UniqueBible#1298]
Hello,
is there any way to get a Guide on how to create my own Interlinear Bible and flat text Modules for Unique Bible.
I am independent Russian/Ukrainian Bible translator and would like to introduce my translations and Interlinears into your Bible app.

Thanks in advance.

**Comment by otseng** [comment]
You can start here:
https://github.com/eliranwong/UniqueBible/wiki#create-your-own-data

If you need more info, can add more info to the wiki pages.
