### ISSUE TITLE
Some components are not installing

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1305]
They are Translations, Discourse Analysis , Individual words, TDW Combo, 
![image](https://user-images.githubusercontent.com/48617390/216763071-5ff88813-b095-4504-a6a1-ead3088ac9a4.png)

It shows error like this 
![image](https://user-images.githubusercontent.com/48617390/216763034-53147e69-1bee-4f83-a70b-699974f74a90.png)

**Comment by eliranwong** [comment]
unfortunately, I cannot repeat the issue on my side.  The features are opened as expected on my devices.

@onegladiator4u when did this issue start?  can you use the features in the past?

can you check if data files are well installed?

marvelData/data/clauseNT.data

marvelData/data/clauseOT.data

marvelData/data/wordNT.data

marvelData/data/wordOT.data

marvelData/data/wordsNT.data

marvelData/data/wordsOT.data

marvelData/data/discourseNT.data

marvelData/data/discourseOT.data

please check if all of these files are not of 0 byte.  thank you.

**Comment by onegladiator4u** [comment]
@eliranwong I only noticed this after today's update. I haven't clicked these options for more than 2 months. I tried to click on all the sync options from the new update , that's when i got the errors.
This could have happened at the time of this https://github.com/eliranwong/UniqueBible/issues/1275#issue-1494080399
i have these files in data 

![image](https://user-images.githubusercontent.com/48617390/216775189-bfcc60ab-ed42-4a73-90a8-24218d78638f.png)

couldn't see 
marvelData/data/wordsNT.data
marvelData/data/wordsOT.data
marvelData/data/discourseNT.data
marvelData/data/discourseOT.data
no 0 byte files. 

You missed one file i think. `translationNT.data` because i got this error, probably `translationOT.data` too.

![image](https://user-images.githubusercontent.com/48617390/216775495-abd37a79-985e-4b80-af24-c6c408033b9c.png)

**Comment by eliranwong** [comment]
you may need to download some of these data.  please try go to Resources > Add > Marvel.bible Datasets and download the required data.

<img width="161" alt="Screenshot 2023-02-04 at 18 17 02" src="https://user-images.githubusercontent.com/25262722/216783113-0d3066f5-6b9a-435f-b954-329195ecf26d.png">

**Comment by onegladiator4u** [comment]
@eliranwong  Same error comes up

**Comment by onegladiator4u** [comment]
Got this in powershell. looks like i can get using the link

![image](https://user-images.githubusercontent.com/48617390/216786371-c4c743fc-f44b-41a0-9e22-5dea1faf841f.png)

**Comment by eliranwong** [comment]
can you try copy the drive.google.com/uc... links manually and enter it in a browser to download the file?

**Comment by onegladiator4u** [comment]
Yes. working now . closing this now
