### ISSUE TITLE
syncing study window doesn't work 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1308]
- [ ] study window won't sync with anything if we assign single click action to something like commentary. You may need to assign sync setting to single click action too. Or to [no action].
![image](https://user-images.githubusercontent.com/48617390/218027821-64fada30-4f3a-425d-a7f7-a7c9806cf6f3.png)

SAMPLE FOR TRANSLATION 

![python_ZPCv5SFiTq](https://user-images.githubusercontent.com/48617390/218025358-f9564495-5ecd-48ef-a1fd-e9e697053816.gif)

SAMPLE FOR COMPARE
![2XiJnH8JMd](https://user-images.githubusercontent.com/48617390/218026065-74fb7a94-2889-4c80-8e91-8cabfb7cceb1.gif)

- [ ] When we click on compare all version from left toolbar, study window title will not change to compare. But it changes to what the sync setting is assigned to. This is a minor bug i think. Below is an example where compare shows as translation 
![image](https://user-images.githubusercontent.com/48617390/218029107-d12b2206-9f35-4e4a-9aa1-c7c27e870462.png)

**Comment by eliranwong** [comment]
the last thing you mentioned happens only because you use Study Window to do comparison.  For the rest, I do not fully understand, but I will try.

**Comment by onegladiator4u** [comment]
Okay brother.

How does sync option work?
If we select Translation in Sync options and click on a verse, Translation of that verse comes to Study window right?

**Comment by eliranwong** [comment]
I think it is fixed in v 33.67:

Changes in 33.67:
* fixed displaying both sync action and single click action into different tabs.

you may try, thanks.

**Comment by onegladiator4u** [comment]
Couldn't see update , i'm still in 33.54

**Comment by eliranwong** [comment]
latest is 33.66

**Comment by onegladiator4u** [comment]
Updated. It seems it didn't work for me. What happens for you now when you click on a verse? While single click set to Commentary and sync to Translation.

**Comment by eliranwong** [comment]
> Updated. It seems it didn't work for me. What happens for you now when you click on a verse? While single click set to Commentary and sync to Translation.

commentary and translation content are displayed into two different tabs

**Comment by onegladiator4u** [comment]
Figured it out. We have to make OpenstudyWindowcontentnnextTab flag to true to make it work.

**Comment by eliranwong** [comment]
you are right, it is impossible to put two different content into the same tab.  closing this issue now.
