### ISSUE TITLE
File update 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1320]
Can you update the file in Plugins /language/ml.biblebooks
[ml.zip](https://github.com/eliranwong/UniqueBible/files/10735934/ml.zip)

**Comment by eliranwong** [comment]
added in version 33.78

Changes in 33.78:
* Added context plugin "Louw-Nida Lexicon Gloss"
* Added language plugin "ml"

**Comment by onegladiator4u** [comment]
Thank You @eliranwong
