### ISSUE TITLE
Config flag update dependencies bug

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1324]
Hey brothers,
When trying to check option to change `updateDependenciesOnStartup` this message box comes with two options. But if we click on either of them it restart . Only `Now` option should be working for restart. After the restart it doesn't change the flag to true also
![image](https://user-images.githubusercontent.com/48617390/220266062-e69456bc-59c8-4de9-a166-747e76c5b236.png)

**Comment by eliranwong** [comment]
What version are you using?  The latest one?  I cannot repeat the issue on my macOS, Ubuntu, ChromeOS.  I haven't tried Windows yet.

**Comment by onegladiator4u** [comment]
My version is 33.88

**Comment by eliranwong** [comment]
33.88 should be good enough, though not the latest.  I will try on Windows when I can borrow a Windows computer.

**Comment by eliranwong** [comment]
I checked a few things on Windows and fixed:

https://github.com/eliranwong/UniqueBible/commit/33a6fb63ff0676c10f5430c5395333bfb953991f

Changes in 33.96:
* Multiple fixes for Windows users:
    - fixed opening menu plugins that use simple browsers
    - fixed opening youtube browser
    - fixed handling restart
    - fixed playing gtts audio

**Comment by onegladiator4u** [comment]
Hey bro, the buttons of message box works now , but updateDependenciesOnStartup is not turning to true .
