### ISSUE TITLE
Update error 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1327]
plugins/menu/ToDo folder not created already so error pops up

**Comment by eliranwong** [comment]
what is the error?  did it happen just once?

**Comment by eliranwong** [comment]
@onegladiator4u please try the latest version and see if still an error message.  thanks.

bty, are you using Windows?  If so, I suggest you to upgrade the python version to the latest one and switch to PySide6.

you can choose PySide 6 from menu UniqueBible > Other Preferences > Qt Library

some latest features may only work on PySide6, as I mainly use PySide6

Changes in 33.98:
* added menu options to switch between Qt Library
* added config.openLinuxDirectory to specify the command / file manager to open a directory on Linux
* fixed launching UBA with PyQt5
* fixed opening video widget
* fixed an error message when media player is closed on Windows
* tested on Windows with Python 3.11.2 and PySide6
    We recommend Windows users to use PySide6 to get access to all UBA available features.

**Comment by onegladiator4u** [comment]
> please try the latest version and see if still an error message. thanks.

i created the folder manually when I saw the error. Raised the issue for others only. 🙂
Yes i'm using windows. How should I upgrade python since it's working on venv?

> you can choose PySide 6 from menu UniqueBible > Other Preferences > Qt Library

does this work only on new python version ?

**Comment by eliranwong** [comment]
you can try to use the menu to switch to PySide6 first.  no harm to try.  If PySide6 is not available to your current python version, you will just see "Not Available!".

to upgrade python version on Windows, you may read:

https://github.com/eliranwong/UniqueBible/wiki/Upgrade-Python-Version-in-Windows

I am closing this issue now.  thanks.

**Comment by eliranwong** [comment]
@onegladiator4u if you try, upgrade to the latest UBA version 34.00 first, as there was a bug in v33.99

**Comment by eliranwong** [comment]
> i can access pyside6 without updating python . So i don't need to update right ?

yes, you don't need to upgrade if your current python version supports it.  Just curious, may I ask what python version you are using?
