### ISSUE TITLE
Enhancements for icon

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1329]
Hey guys, 
it would be nice if you can add an icon for app in taskbar.
Now we can see the icon in tray, but in taskbar it still shows as python icon.
![image](https://user-images.githubusercontent.com/48617390/221360912-5f15b1a2-366e-4aec-9219-677cfa0fa370.png)

**Comment by eliranwong** [comment]
done. 

Changes in 34.09, 34.10:
* added Windows icon

**Comment by onegladiator4u** [comment]
Thanks bro. Looks good.
