### ISSUE TITLE
Ver 34.11 had startup problem after update 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1331]
App didn't start after the last update. Error said `pydub` module was missing.
Had to install manually. Now app starts but an error shows up.

D:\App\UniqueBible\venv_Windows_3.9.0\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

tried installing ffmpeg using 'pip install python-ffmpeg'. But error shows up. Just letting you know that APP IS WORKING though.

**Comment by eliranwong** [comment]
please update to the latest code and help check if it is fixed.  thanks @onegladiator4u

**Comment by onegladiator4u** [comment]
Still getting this error 

D:\App\UniqueBible\venv_Windows_3.9.0\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by eliranwong** [comment]
![Screenshot_20230302-120950](https://user-images.githubusercontent.com/25262722/222424967-a6c0fc2c-04f4-4e30-a380-099b6ce237e6.png)

**Comment by onegladiator4u** [comment]
@eliranwong Thank you bro. It worked. next time i'll try ChatGPT first .😀
