### ISSUE TITLE
Bible conversion problem 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1336]
I tried to install ISV Bible module from ph4.org. 
my import settings are
![image](https://user-images.githubusercontent.com/48617390/222963034-76fa3003-25ba-4c24-a488-708564482f4a.png)

1. Importing was very slow. Took more than 45 minutes 
2. Bible notes are visible in Bible itself. 
![image](https://user-images.githubusercontent.com/48617390/222963165-5b9a93ee-96f1-4da5-ab50-508078b308bb.png)

When I checked online its like this 
![image](https://user-images.githubusercontent.com/48617390/222963223-6ee4fb4f-9174-4dfb-ab18-5a6bff0f3e5e.png)

Is this the problem of Bible or parsing ?

[ISV.zip](https://github.com/eliranwong/UniqueBible/files/10891908/ISV.zip)

**Comment by otseng** [comment]
Yes, the zip file you are importing contains these additional notes.  So the generated Bible will also contain it.

**Comment by onegladiator4u** [comment]
> Yes, the zip file you are importing contains these additional notes. So the generated Bible will also contain it.

Oh ok. Thanks for looking into it.
