### ISSUE TITLE
Vlc player enhancements 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1338]
- [x] Can you make the player to remember the volume level too. It keeps going full after restart.
- [x] An option to hide player GUI from toolbar if there is not. I couldn't find it.. You could add it on Bible -> Toggle features or under a new menu like View.  
- [ ] If we open two Bibles versions , one on main window and another on Study window. Only Main window Bible version audio will play for both when clicking on the audio icon.
Hope you consider these suggestions.

**Comment by eliranwong** [comment]
> * [ ]  Can you make the player to remember the volume level too. It keeps going full after restart.

can do

> * [ ]  An option to hide player GUI from toolbar if there is not. I couldn't find it.. You could add it on Bible -> Toggle features or under a new menu like View.

Already done.

Master control > Media Player > Audio

You can also move to the second toolbar, which can save space

> * [ ]  If we open two Bibles versions , one on main window and another on Study window. Only Main window Bible version audio will play for both when clicking on the audio icon.

I don't understand this

**Comment by onegladiator4u** [comment]
@eliranwong 
![image](https://user-images.githubusercontent.com/48617390/223541711-e093aafc-3c03-4b15-91f7-b0884a4905e0.png)

**Comment by eliranwong** [comment]
> @eliranwong
> ![image](https://user-images.githubusercontent.com/48617390/223541711-e093aafc-3c03-4b15-91f7-b0884a4905e0.png)

did you install NKJV audio?  I don't think we provide that due to copyright issues.

I mainly work on verse-by-verse audio.  @otseng may know more about chapter audio.

**Comment by eliranwong** [comment]
bty, I added saving audio volume feature in the latest code https://github.com/eliranwong/UniqueBible/commit/9f87fd40d3fc25b5a735163da8c9aba338c35348

**Comment by eliranwong** [comment]
I think your third point is irrelevant.  UBA cannot play audio that have not been installed.

**Comment by otseng** [comment]
It's designed to only play the audio of the main Bible, not the study Bible.  @onegladiator4u what do you think if I just delete the icon from the study window to avoid confusion?

**Comment by onegladiator4u** [comment]
> > @eliranwong
> > ![image](https://user-images.githubusercontent.com/48617390/223541711-e093aafc-3c03-4b15-91f7-b0884a4905e0.png)
> 
> did you install NKJV audio? I don't think we provide that due to copyright issues.
> 
> I mainly work on verse-by-verse audio. @otseng may know more about chapter audio.

@eliranwong Yes, I have NKJV audio.

**Comment by onegladiator4u** [comment]
> It's designed to only play the audio of the main Bible, not the study Bible. @onegladiator4u what do you think if I just delete the icon from the study window to avoid confusion?

@otseng Yes, that's a good solution . Hiding it from Study does the job.

**Comment by eliranwong** [comment]
> > > @eliranwong
> > > ![image](https://user-images.githubusercontent.com/48617390/223541711-e093aafc-3c03-4b15-91f7-b0884a4905e0.png)
> > 
> > 
> > did you install NKJV audio? I don't think we provide that due to copyright issues.
> > I mainly work on verse-by-verse audio. @otseng may know more about chapter audio.
> 
> @eliranwong Yes, I have NKJV audio.

may I ask where did you get it?  just curious

**Comment by onegladiator4u** [comment]
> > > > @eliranwong
> > > > ![image](https://user-images.githubusercontent.com/48617390/223541711-e093aafc-3c03-4b15-91f7-b0884a4905e0.png)
> > > 
> > > 
> > > did you install NKJV audio? I don't think we provide that due to copyright issues.
> > > I mainly work on verse-by-verse audio. @otseng may know more about chapter audio.
> > 
> > 
> > @eliranwong Yes, I have NKJV audio.
> 
> may I ask where did you get it? just curious

@eliranwong I got it from this app. https://play.google.com/store/apps/details?id=com.futuresoft.wordofpromise.free
I had a new testament version subscribed. So copied it to UBA and arranged it.

**Comment by eliranwong** [comment]
@otseng do you want to do something about it, regarding chapter audio?  If no plan, I may close this issue?

**Comment by otseng** [comment]
> @otseng do you want to do something about it, regarding chapter audio? If no plan, I may close this issue?

OK, I'll modify the code.
