### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by AlainWill** [eliranwong/UniqueBible#1346]
Hi 
need some help eveything was ok...but after updating to v34.44  UniqueBible  not showing up anymore... i get this in powershell: 
> python D:\Users\UniqueBible\uba.py
Traceback (most recent call last):
  File "D:\Users\UniqueBible\uba.py", line 87, in <module>
    with open(shortcutBat, "w") as fileObj:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\Desktop\\UniqueBibleApp.bat'

**Comment by eliranwong** [comment]
thanks for report

I will check soon

**Comment by eliranwong** [comment]
checked, nothing wrong on my side.

I guess your desktop path has an issue.  anyway, I modified the file, the startup should be fine.

please unzip this zip file here and replace the uba.py file
[uba.zip](https://github.com/eliranwong/UniqueBible/files/10985128/uba.zip)

**Comment by AlainWill** [comment]
Thank's for the help working correctly.

**Comment by eliranwong** [comment]
I am glad that it is working now.
