### ISSUE TITLE
Verse audio icons

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1347]
Hey brothers,
There are 3 types of audio icons in a page when it has verse mp3s. 
1. All Verses Play Audio Icon
2. Chapter audio icon
3. Verse Audio Icon
In Bible >Toggle features there's an option to show and hide 'Display Verse Audio Icons'. 
This hides audio icons including 'Chapter audio icon' too. Is this intentional ? But the toggle name says Verse icons. 

![python_fBFL0uP06f](https://user-images.githubusercontent.com/48617390/225855705-4c15d438-931c-436c-959c-d7e3b7886c2e.png)
But it **didn't hide** `All Verse Play Audio Icon` as in **second** screenshot
![image](https://user-images.githubusercontent.com/48617390/225851636-7a1ac0fd-ec98-4463-994f-7fc6aa9744f8.png)

In my opinion, that toggle should hide/show All Verses Play Icon and Verse Audio Icon **OR** 
hide/show All audio icons by renaming it like Hide Verse Icons **OR** 
hide/show Verse Audio icons only.
Hope this doesn't confuse you.

**Comment by eliranwong** [comment]
"Verse Audio Icons" mean audio icon for a single verse audio.

I saw your screenshot have two icons next to chapter title, I think one of the icons is to trigger chapter audio, which I do not use myself.  the toggle hide/show feature currently affects only icons for single verse audio.  It does not affect chapter audio or word audio icons.

This toggle feature mainly helps me when I copy verses, when I don't want to include the icons in my copied content.

**Comment by onegladiator4u** [comment]
> "Verse Audio Icons" mean audio icon for a single verse audio.
> 
> I saw your screenshot have two icons next to chapter title, I think one of the icons is to trigger chapter audio, which I do not use myself. the toggle hide/show feature currently affects only icons for single verse audio. It does not affect chapter audio or word audio icons.
> 
> This toggle feature mainly helps me when I copy verses, when I don't want to include the icons in my copied content.

Ok. But chapter audio icon was affecting for me. That's why created the issue .
Chapters audio is still missing after the update.

**Comment by otseng** [comment]
> Chapters audio is still missing after the update.

The latest update should hide the chapter audio if the hide verse audio icons is disabled.  Is the chapter audio icon not toggling for you?

**Comment by onegladiator4u** [comment]
@otseng Hey bro, Are you saying that if we toggle the `hide verse audio icons` all icon including verse and chapter icons will be hidden/shown?

**Comment by otseng** [comment]
> @otseng Hey bro, Are you saying that if we toggle the `hide verse audio icons` all icon including verse and chapter icons will be hidden/shown?

Yes

**Comment by onegladiator4u** [comment]
> 

Oh ok. 
Then the toggle should be named `Hide Chapter and Verse Audio Icons` than `Hide verse audio icons` right ?
That's what confused me.
