### ISSUE TITLE
shortcuts problem

### ISSUE THREAD

**Issue by AlainWill** [eliranwong/UniqueBible#1348]
hi need help plz
since i updated to the last version 34.38 /34.39 i can no longer start uniquebible with shortcut bat anymore ...the problem is i must open powershell directly and paste ( python D:\Users\UniqueBible\uba.py ) for uniquebible to open other wise i cant start it with shortcut anymore.

**Comment by onegladiator4u** [comment]
If you open bat file in Note editor what's in it?
when I had problem like this i changed the content of bat file to just `python uba.py` and saved it, then it worked. 
If you change it like mine do make a backup of the bat file somewhere else before editing. If it doesn't work you can replace it then.

**Comment by AlainWill** [comment]
When i open the (bat file) the content is:  powershell.exe -NoExit -Command "python 'D:\Users\UniqueBible\uba.py'"

**Comment by eliranwong** [comment]
Does it work if you change the content of uba file to 'python D:\Users\UniqueBible\uba.py', edit and save with a text editor, e.g. notepad?

**Comment by AlainWill** [comment]
in which section of the uba file content should i change it ?

**Comment by onegladiator4u** [comment]
> in which section of the uba file content should i change it ?

bat file i guess

**Comment by AlainWill** [comment]
i try changes in the bat file but sadly nothing works (shortcut).

**Comment by onegladiator4u** [comment]
Did you edit the file in the root folder named 'UniqueBibleApp.bat'?
It'll be in D:\Users\UniqueBible\. I don't think we can edit the shortcut.

**Comment by AlainWill** [comment]
yes i did all that.

**Comment by eliranwong** [comment]
If you can use command line to launch UBA with powershell, you should be able to launch UBA via a *.bat file.

Just enter the same command you enter in powershell in the *.bat file.  I think it should be straightforward to get it work.

In your case, the desktop shortcut does not work.  I guess it may be something to be with where the UBA is installed.  I saw the path D:\Users\UniqueBible  .  Is "UniqueBible" one of your users name or the name of UniqueBible folder?

**Comment by AlainWill** [comment]
It launch UBA normaly
In Powershell:
> python D:\Users\UniqueBible\uba.py
> D:\Users\UniqueBible\venv_Windows_3.11.2\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

If i try with (UniqueBibleApp.bat) in the folder UBA....Dir....(D:\Users\UniqueBible\uba.py)
Nothing happens
In .Bat file:
powershell.exe -NoExit -Command "python 'D:\Users\UniqueBible\uba.py'"

Nothing either on my desktop:
 no shortcuts

But if i delete the (UniqueBibleApp.bat) in the folder UBA...By launch UBA with powershell it recreate the UniqueBibleApp.bat with the same content: powershell.exe -NoExit -Command "python 'D:\Users\UniqueBible\uba.py'"

Now to answer the question above it's the users name not the name of UniqueBible folder

**Comment by AlainWill** [comment]
finaly i got it working.thank for helping
