### ISSUE TITLE
Release APK on Github

### ISSUE THREAD

**Issue by meichthys** [eliranwong/UniqueBible#1356]

**Comment by eliranwong** [comment]
Please kindly give description.  Thanks.

**Comment by otseng** [comment]
I agree it would be best if UBA was packaged into an easy way to install it.  I've tried to do this, but unfortunately virus checkers flag it with issues so it's not possible to install them.  If you want use the app on your phone, I've created a simple UBA viewer at:
https://simple.uniquebibleapp.com/
