### ISSUE TITLE
Need to import additional Books/Sermons/Dictionaries to Read/View #906

### ISSUE THREAD

**Issue by passionate2023** [eliranwong/UniqueBible#1359]
Can you please provide import options to import for additional books/sermons/dictionaries to read/view along with the bible?

a. sample file format (.txt, .json)
b. import file option to import

**Comment by otseng** [comment]
Not sure what you mean.  The import data is available under Resources -> Import.  You can then import 3rd party files with 3rd Party Module.  Then select file types to see what types of files you can import.  

Is there a specific type of dataset you want ability to also import that is not currently available?

**Comment by passionate2023** [comment]
How to create a module so that will import in uniquebible? I am having text file and can create supported formats of uniquebible so that able to import them and do the search. Please let me know in detail

**Comment by otseng** [comment]
Under the menu, select Resources/Create and there's option to create a module from different types of files: image, HTML, note, PDF.  It's easiest to create the module by notes.   Create a note in UBA under menu/UniqueBible/Note Editor.  Each note will be end up being a chapter.
