### ISSUE TITLE
Windows version to download is missing

### ISSUE THREAD

**Issue by passionate2023** [eliranwong/UniqueBible#1360]
I'm unable to find any setup.exe or installation file for windows under the following links

https://github.com/eliranwong/UniqueBible/tags
https://github.com/eliranwong/UniqueBible/releases
https://github.com/eliranwong/UniqueBible/wiki/Install-UBA-on-Windows

pls help with the exact links to download. also the links are not very clear...if possible put it in the 1st readme description for easy access

**Comment by otseng** [comment]
Unfortunately, I've had to abandon binary releases.  Announced it here:
https://github.com/eliranwong/UniqueBible/discussions/1176#discussioncomment-3959014

I've now updated the wiki page as well.
