### ISSUE TITLE
Artix Linux it comes with an error

### ISSUE THREAD

**Issue by doonoo** [eliranwong/UniqueBible#1368]
When I do python3 UniqueBible/uba.py
this shows 

`This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland, minimalegl, eglfs, xcb, minimal, wayland-egl, offscreen, vnc, linuxfb, vkkhrdisplay.
`

**Comment by eliranwong** [comment]
What is your os?

**Comment by doonoo** [comment]
> What is your os?

Arch Linux, more specifically artix Linux

**Comment by eliranwong** [comment]
If you use wayland instead of xcb, you may try:

> export QT_QPA_PLATFORM=wayland;xcb<br>

> QT_QPA_PLATFORMTHEME=qt5ct<br>

**Comment by eliranwong** [comment]
For Arch Linux, you may also install the qt packages as in file:

https://github.com/eliranwong/uniquebibleapp-webtop/blob/main/Dockerfile

**Comment by doonoo** [comment]
I've installed arch linux, works as expected.
