### ISSUE TITLE
Couldn't find ffmpeg or avconv

### ISSUE THREAD

**Issue by jesse0515** [eliranwong/UniqueBible#1371]
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

MAC OS 13.4 M1

**Comment by eliranwong** [comment]
You need to install ffmpeg on macOS:

The quickest way to me is:

1. Launch macOS "Terminal" application

2. Install brew tools (https://brew.sh/), by running:

> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

3. Install ffmpeg:

> brew install ffmpeg

>
