### ISSUE TITLE
Provide a `FUNDING.yml` file

### ISSUE THREAD

**Issue by Panquesito7** [eliranwong/UniqueBible#1382]
### Description

By providing a [funding file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository), you can easily promote more your donation links and platforms, in this case, PayPal.
I recommend adding a funding file to the repository. If you like the idea, I'd like to work on this. 🙂

Thank you.

**Comment by eliranwong** [comment]
Yes, that would be lovely.  I appreciate it.

**Comment by Panquesito7** [comment]
Thanks! 🙂
