### ISSUE TITLE
Create a GitHub Actions workflow to compile the program on all the OSes

### ISSUE THREAD

**Issue by Panquesito7** [eliranwong/UniqueBible#1394]
### Description

I believe this would be a great addition. It would also make sure the program is able to properly compile and run on Linux, macOS, and Windows. If you need any help with this, count me in, I'd love to help with this. 🙂

**Comment by eliranwong** [comment]
That would be great! We tried a few things before, but haven't managed to find a satisfactory solution.

**Comment by Panquesito7** [comment]
> That would be great! We tried a few things before, but haven't managed to find a satisfactory solution.

Let's discuss about this and try to create one. Where can I find the full installation steps for macOS, Windows, and Linux?

**Comment by eliranwong** [comment]
> > That would be great! We tried a few things before, but haven't managed to find a satisfactory solution.
> 
> Let's discuss about this and try to create one. Where can I find the full installation steps for macOS, Windows, and Linux?

https://github.com/eliranwong/UniqueBible/wiki#installation

**Comment by eliranwong** [comment]
will someone consider to build a Windows installer with scoop?

**Comment by Panquesito7** [comment]
> > > That would be great! We tried a few things before, but haven't managed to find a satisfactory solution.
> > 
> > 
> > Let's discuss about this and try to create one. Where can I find the full installation steps for macOS, Windows, and Linux?
> 
> https://github.com/eliranwong/UniqueBible/wiki#installation

Thanks!

**Comment by eliranwong** [comment]
closed due to inactivity of this post
