### ISSUE TITLE
'Download UBA modules from Google drive' Error

### ISSUE THREAD

**Issue by OluseyiT** [eliranwong/UniqueBible#1411]
I followed all the instructions to the best of my knowledge. I thought I was done until I got this error
<img width="1280" alt="Screen Shot 2024-01-16 at 12 35 29 AM" src="https://github.com/eliranwong/UniqueBible/assets/124433335/e231c7ab-d469-47f8-b042-ad2d061bed0f">

Could it be because of my mac version
<img width="584" alt="Screen Shot 2024-01-16 at 1 35 59 AM" src="https://github.com/eliranwong/UniqueBible/assets/124433335/eda8ec0e-7b8c-48f8-b662-54f88fc5fbbb">

**Comment by otseng** [comment]
Yeah, unfortunately 11.7 is now obsolete.
