### ISSUE TITLE
add support reading online materials directly on study window

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#142]
I am thinking to add support opening website directly on Study Window.  doing this will allow users to slect word from websit and use the right-click menu to do search or dictionary lookup directly.  i.e. using UBA tools directly on 3-rd party website

I am thinking if users don't want to install some module or some copyrighted modules are not available to them, they may open website, e.g. bible gateway, on bible study window and use UBA tools from right click menu

or useful when reading biblical articles online

so integrating UBA tools with popular online resources

**Comment by eliranwong** [comment]
available from version 21.41

**Comment by darrelwright** [comment]
How do I enter a web address and have it show in study window? Either I have missed something or I am just overlooking the proper command.

**Comment by otseng** [comment]
online:::https://uniquebible.app

Also make sure the useWebbrowser config flag is off.

**Comment by darrelwright** [comment]
Thanks. That works nicely. I had useWebbrowser config flag turned on.
