### ISSUE TITLE
Stops on installation

### ISSUE THREAD

**Issue by artkarimov** [eliranwong/UniqueBible#1446]
My installation stops with this:
Installing 'chinese-english-lookup' ...
Module 'chinese-english-lookup' is installed!
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
Installing 'textract' ...
b"WARNING: Ignoring version 1.6.5 of textract since it has invalid metadata:\r\nRequested textract from https://files.pythonhosted.org/packages/6b/3e/ac16b6bf28edf78296aea7d0cb416b49ed30282ac8c711662541015ee6f3/textract-1.6.5-py3-none-any.whl has invalid metadata: .* suffix can only be used with `==` or `!=` operators\r\n    extract-msg (<=0.29.*)\r\n                 ~~~~~~~^\r\nPlease use pip<24.1 if you need to use this version.\r\n  error: subprocess-exited-with-error\r\n  \r\n  Getting requirements to build wheel did not run successfully.\r\n  exit code: 1\r\n  \r\n  [3 lines of output]\r\n  error in textract setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; .* suffix can only be used with `==` or `!=` operators\r\n      extract-msg<=0.29.*\r\n                 ~~~~~~~^\r\n  [end of output]\r\n  \r\n  note: This error originates from a subprocess, and is likely not a problem with pip.\r\nerror: subprocess-exited-with-error\r\n\r\nGetting requirements to build wheel did not run successfully.\r\nexit code: 1\r\n\r\nSee above for output.\r\n\r\nnote: This error originates from a subprocess, and is likely not a problem with pip.\r\n"
Optional feature 'Extract text from document' is not enabled.
Run 'pip3 install textract' to install it first.
C:\Users\Artur\UniqueBible\venv_Windows_3.12.4\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Installing 'llama-index' ...
Module 'llama-index' is installed!
Optional feature 'Lama Index (GPT Index)' is not enabled.
Run 'pip3 install llama-index' to install it first.
Installing 'duckduckgo-search' ...
Module 'duckduckgo-search' is installed!
Optional feature 'DuckDuckGo.com search' is not enabled.
Run 'pip3 install duckduckgo-search' to install it first.
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Artur\UniqueBible\startup\share.py", line 63, in global_excepthook
    print(traceback.format_exc())
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "C:\Users\Artur\UniqueBible\main.py", line 147, in <module>
    from startup.guiQt import *
  File "C:\Users\Artur\UniqueBible\startup\guiQt.py", line 16, in <module>
    from gui.MainWindow import MainWindow
  File "C:\Users\Artur\UniqueBible\gui\MainWindow.py", line 3, in <module>
    from distutils import util
ModuleNotFoundError: No module named 'distutils'

**Comment by otseng** [comment]
I use Python 3.8.10, so it might be something with your Python version.

See this if it helps you:
https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed

**Comment by eliranwong** [comment]
> My installation stops with this: Installing 'chinese-english-lookup' ... Module 'chinese-english-lookup' is installed! Optional feature 'Chinese-to-English word definition' is not enabled. Run 'pip3 install chinese-english-lookup' to install it first. Installing 'textract' ... b"WARNING: Ignoring version 1.6.5 of textract since it has invalid metadata:\r\nRequested textract from https://files.pythonhosted.org/packages/6b/3e/ac16b6bf28edf78296aea7d0cb416b49ed30282ac8c711662541015ee6f3/textract-1.6.5-py3-none-any.whl has invalid metadata: .* suffix can only be used with `==` or `!=` operators\r\n extract-msg (<=0.29._)\r\n ~~~~~~~^\r\nPlease use pip<24.1 if you need to use this version.\r\n error: subprocess-exited-with-error\r\n \r\n Getting requirements to build wheel did not run successfully.\r\n exit code: 1\r\n \r\n [3 lines of output]\r\n error in textract setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; ._ suffix can only be used with `==` or `!=` operators\r\n extract-msg<=0.29.*\r\n ~~~~~~~^\r\n [end of output]\r\n \r\n note: This error originates from a subprocess, and is likely not a problem with pip.\r\nerror: subprocess-exited-with-error\r\n\r\nGetting requirements to build wheel did not run successfully.\r\nexit code: 1\r\n\r\nSee above for output.\r\n\r\nnote: This error originates from a subprocess, and is likely not a problem with pip.\r\n" Optional feature 'Extract text from document' is not enabled. Run 'pip3 install textract' to install it first. C:\Users\Artur\UniqueBible\venv_Windows_3.12.4\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning) Installing 'llama-index' ... Module 'llama-index' is installed! Optional feature 'Lama Index (GPT Index)' is not enabled. Run 'pip3 install llama-index' to install it first. Installing 'duckduckgo-search' ... Module 'duckduckgo-search' is installed! Optional feature 'DuckDuckGo.com search' is not enabled. Run 'pip3 install duckduckgo-search' to install it first. Error in sys.excepthook: Traceback (most recent call last): File "C:\Users\Artur\UniqueBible\startup\share.py", line 63, in global_excepthook print(traceback.format_exc()) ^^^^^^^^^^^^^^^^^^^^ AttributeError: 'traceback' object has no attribute 'format_exc'
> 
> Original exception was: Traceback (most recent call last): File "C:\Users\Artur\UniqueBible\main.py", line 147, in from startup.guiQt import * File "C:\Users\Artur\UniqueBible\startup\guiQt.py", line 16, in from gui.MainWindow import MainWindow File "C:\Users\Artur\UniqueBible\gui\MainWindow.py", line 3, in from distutils import util ModuleNotFoundError: No module named 'distutils'

For installation on Windows, please follow the following links:

[Windows](https://github.com/eliranwong/UniqueBible/wiki/Install-on-Windows)

[WSL on Windows](https://github.com/eliranwong/UniqueBible/wiki/Install-UBA-on-Windows-via-WSL2-Ubuntu)

Support python versions: 3.8-3.12
