### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by broodingbabji** [eliranwong/UniqueBible#1468]
ModuleNotFoundError: No module named 'uniquebible'
PS C:\Users\michael> C:\Users\michael\UniqueBible\uniquebible\uba.py
Traceback (most recent call last):
  File "C:\Users\michael\UniqueBible\uniquebible\uba.py", line 5, in <module>
    from uniquebible.install.module import *
ModuleNotFoundError: No module named 'uniquebible'
PS C:\Users\michael> python C:\Users\michael\UniqueBible\uniquebible\uba.py
Traceback (most recent call last):
  File "C:\Users\michael\UniqueBible\uniquebible\uba.py", line 5, in <module>
    from uniquebible.install.module import *
ModuleNotFoundError: No module named 'uniquebible'
PS C:\Users\michael> C:\Users\michael\UniqueBible\uniquebible\__init__.py
Traceback (most recent call last):
  File "C:\Users\michael\UniqueBible\uniquebible\__init__.py", line 1, in <module>
    import os, requests, pkg_resources, re, socket
ModuleNotFoundError: No module named 'requests'
PS C:\Users\michael> python C:\Users\michael\UniqueBible\uniquebible\__init__.py
Traceback (most recent call last):
  File "C:\Users\michael\UniqueBible\uniquebible\__init__.py", line 1, in <module>
    import os, requests, pkg_resources, re, socket
ModuleNotFoundError: No module named 'requests'
PS C:\Users\michael> python C:\Users\michael\UniqueBible\setup.py
Traceback (most recent call last):
  File "C:\Users\michael\UniqueBible\setup.py", line 1, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

**Comment by otseng** [comment]
Can you try:

cd C:\Users\michael\UniqueBible

python -m uniquebible.main

**Comment by eliranwong** [comment]
> ModuleNotFoundError: No module named 'uniquebible' PS C:\Users\michael> C:\Users\michael\UniqueBible\uniquebible\uba.py Traceback (most recent call last): File "C:\Users\michael\UniqueBible\uniquebible\uba.py", line 5, in from uniquebible.install.module import * ModuleNotFoundError: No module named 'uniquebible' PS C:\Users\michael> python C:\Users\michael\UniqueBible\uniquebible\uba.py Traceback (most recent call last): File "C:\Users\michael\UniqueBible\uniquebible\uba.py", line 5, in from uniquebible.install.module import * ModuleNotFoundError: No module named 'uniquebible' PS C:\Users\michael> C:\Users\michael\UniqueBible\uniquebible__init__.py Traceback (most recent call last): File "C:\Users\michael\UniqueBible\uniquebible__init__.py", line 1, in import os, requests, pkg_resources, re, socket ModuleNotFoundError: No module named 'requests' PS C:\Users\michael> python C:\Users\michael\UniqueBible\uniquebible__init__.py Traceback (most recent call last): File "C:\Users\michael\UniqueBible\uniquebible__init__.py", line 1, in import os, requests, pkg_resources, re, socket ModuleNotFoundError: No module named 'requests' PS C:\Users\michael> python C:\Users\michael\UniqueBible\setup.py Traceback (most recent call last): File "C:\Users\michael\UniqueBible\setup.py", line 1, in from setuptools import setup ModuleNotFoundError: No module named 'setuptools'

how do you install the app?

**Comment by eliranwong** [comment]
I suggest installing the app via `pip`

pip install --upgrade uniquebible 

It would be easier to manage for future upgrading
