### ISSUE TITLE
New window named python 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#148]
I noticed a new window from update 21.35. Is this a bug?
![image](https://user-images.githubusercontent.com/48617390/108256211-3fcd3680-7183-11eb-81e3-ffb7c4f3c16f.png)

**Comment by eliranwong** [comment]
I don't think that is a bug.  I think that may relate to how you use python to run UBA.  I just turned on my Windows computer (yours is Windows, right) and updated to version 21.36.  I don't see any additional window.  Do you use special theme software for your windows?  I note that your desktop is a bit different from usual.

**Comment by eliranwong** [comment]
you can see that there is only one UBA window on my Windows laptop.

<img width="791" alt="Screenshot 2021-02-17 193717" src="https://user-images.githubusercontent.com/25262722/108258116-9e7cbb00-7157-11eb-90e7-d0baf75367fc.png">

**Comment by eliranwong** [comment]
do u use the example shortcut file to launch the app?

**Comment by onegladiator4u** [comment]
> 
> 
> do u use the example shortcut file to launch the app?

Yeah. I'm using a shortcut file. It's added in start menu.
I do use theme for windows. But i don't think it'll affect UBA like this.

**Comment by eliranwong** [comment]
Does everything else function as expected?  If so, my suggestion is to ignore the extra window for now.

regarding the extra window you mentioned, I am not able to check further as I cannot duplicate the issue on my side.

**Comment by onegladiator4u** [comment]
Ok. 
Can I mention one more issue here? It's a different one

**Comment by eliranwong** [comment]
> Ok.
> Can I mention one more issue here? It's a different one

please feel free to report issues.  if it is a different one, we prefer a separate post.

**Comment by eliranwong** [comment]
@onegladiator4u I can confirm your observation.  This issue was fixed in version 21.67.

**Comment by onegladiator4u** [comment]
Thank you. And good work as always.
