### ISSUE TITLE
Verse number double click and bibe version not changing in dropdown issues

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#161]
Hi brother,
I tried highlights it's really good. As you suggested I set double click to miscellaneous. 
I noticed that if master control is already opened and its in the background, double clicking verse number won't work. Because master control in the background already running. 
It would be nice to make master control come to foreground if we double click the verse number and change the tab to miscellaneous too.

I also noticed that if we click the MOB,MIB,MTB etc.. Bibles in left toolbar, the drop down box not changing the version. It's a minor thing. If I wanted to change the version NASB again as in the screenshot I'll have to change the different bible version then to NASB again.
![image](https://user-images.githubusercontent.com/48617390/108487628-790dbf80-72c5-11eb-8378-95e2c3ce76c4.png)

**Comment by eliranwong** [comment]
@onegladiator4u   thanks for reporting the issues here.

The first issue, bringing control panel, had been sorted out by @otseng yesterday.  It is expected to work on next version

I will try to fix the second issue.  thanks.

**Comment by eliranwong** [comment]
@onegladiator4u  for the first issue you mentioned, please try the fix in version 21.45 and let me know if it works on Windows.  thanks.

**Comment by onegladiator4u** [comment]
> 
> 
> @onegladiator4u for the first issue you mentioned, please try the fix in version 21.45 and let me know if it works on Windows. thanks.

Yes, it's solved. Thanks

**Comment by eliranwong** [comment]
The second issue is also address, please try version 21.47 and kindly let me know if it works for you.  thanks.

**Comment by onegladiator4u** [comment]
@eliranwong Yes it is solved too.
I just noticed a thing. If we set double click verse number to compare all Bible versions, after we double click all bible versions comes but the command box doesn't change to COMPARE...

**Comment by eliranwong** [comment]
> @eliranwong Yes it is solved too.
> I just noticed a thing. If we set double click verse number to compare all Bible versions, after we double click all bible versions comes but the command box doesn't change to COMPARE...

thanks for new finding, I will take a look into it.

**Comment by eliranwong** [comment]
> @eliranwong Yes it is solved too.
> I just noticed a thing. If we set double click verse number to compare all Bible versions, after we double click all bible versions comes but the command box doesn't change to COMPARE...

I checked the issue.  I made an adjustment about this in version 21.66.  Single-click / double-click action doesn't print command in command line field, but they are recorded in history so you can repeat the actions from history.  or you can double click the history item to edit the command and launch from history tab on Master Control.

**Comment by onegladiator4u** [comment]
The issue I wanted to point was really about the COMPARE command.
When we set double click to compare all Bible version
![image](https://user-images.githubusercontent.com/48617390/109118572-81547780-7769-11eb-8e58-2cfe01108e76.png)
The action happening behind is this right?
![image](https://user-images.githubusercontent.com/48617390/109119307-8239d900-776a-11eb-9656-2b29b0fa4b1a.png)

The command line field should have been `COMPARE:::John 8:27`. But it is `BIBLE:::MOV:::John 8:27` now. History tab also didn't change the command to `COMPARE:::John 8:27`. 
![image](https://user-images.githubusercontent.com/48617390/109121794-bcf14080-776d-11eb-9323-5e1de80d85b6.png)
The advantage I thought if it printed this command is that if we want to compare another verse like John 8:36 we just need to change 36 in command line. But it's different command `BIBLE:::MOV:::John 8:27` in command line and history not the COMPARE.
What do you think?

**Comment by eliranwong** [comment]
> The issue I wanted to point was really about the COMPARE command.
> When we set double click to compare all Bible version
> ![image](https://user-images.githubusercontent.com/48617390/109118572-81547780-7769-11eb-8e58-2cfe01108e76.png)
> The action happening behind is this right?
> ![image](https://user-images.githubusercontent.com/48617390/109119307-8239d900-776a-11eb-9656-2b29b0fa4b1a.png)
> 
> The command line field should have been `COMPARE:::John 8:27`. But it is `BIBLE:::MOV:::John 8:27` now. History tab also didn't change the command to `COMPARE:::John 8:27`.
> ![image](https://user-images.githubusercontent.com/48617390/109121794-bcf14080-776d-11eb-9323-5e1de80d85b6.png)
> The advantage I thought if it printed this command is that if we want to compare another verse like John 8:36 we just need to change 36 in command line. But it's different command `BIBLE:::MOV:::John 8:27` in command line and history not the COMPARE.
> What do you think?

Yes, I can see the advantage.  The command was misplaced in another column.  It is now fixed in version 21.69.  The COMPARE::: command should now be displayed on main window history.  If you double-click it, you can modify the reference, enter to finish the editing and select 'OPEN' button.  You may check the screenshot below (version 21.69):

![Screenshot_20210225_102650](https://user-images.githubusercontent.com/25262722/109140085-25332880-7754-11eb-8724-c6a28d8f3f94.png)

**Comment by onegladiator4u** [comment]
Thanks you for fixing that.
