### ISSUE TITLE
After manual backup restore of marvelData , Bible and commentaries won't download.

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#163]
One day ago I had to install UBA as fresh because of some errors. So I backed up my marvelData folder completely to different folder so that I don't have to download most of the resources again. It's more than 4 GB.
After fresh install I copied all data to marvelData folder from backup. From the next restart onwards I'm getting Bible modules needs to be updated messages for many versions even though it's updated (backed up versions are already updated ones). So I turned off module check on startup. So I wanted to check whether the message will go away if I delete a bible and update again. So I deleted MAB.bible. And tried to download it again. But this time Bible is not downloading.
After this problem I couldn't download any other Bible or commentaries. 
I think normally when downloading a module a temp file will be created in the corresponding folder right? I can't see anything now. Only this window stays up. I have to force close if I start a download.
![image](https://user-images.githubusercontent.com/48617390/108501751-c135dd80-72d7-11eb-8c61-68c930c3a4cc.png)
Do I have to replace any files related to this function?

**Comment by eliranwong** [comment]
this is an interesting finding.  @otseng will users not able to download resources if they set config.disableModulesUpdateCheck to True

**Comment by onegladiator4u** [comment]
Actually it won't download in any case. Sorry if I gave a wrong idea.

**Comment by onegladiator4u** [comment]
This happened after I replaced the marvelData folder mainly. If modules check is enabled it'll show messages that modules needed to update even though they are updated from my backed up files. It won't download any updated bibles even if it shows it needs to be updated.

**Comment by eliranwong** [comment]
when you click to download a file, does it come with any error message?

**Comment by eliranwong** [comment]
@onegladiator4u can u try,

1) close the app first
2) rename config.py to config_old.py
3) start the app again, and try to download a file

**Comment by onegladiator4u** [comment]
> 
> 
> when you click to download a file, does it come with any error message?

No. It doesn't show any error message. Only not responding.
I'll try to rename config.py

**Comment by onegladiator4u** [comment]
@eliranwong It didn't work.

**Comment by eliranwong** [comment]
@onegladiator4u what resource you are you trying to download?

**Comment by onegladiator4u** [comment]
Marvel annotated bible and spurgeons expositions on the bibe commentary

**Comment by eliranwong** [comment]
no worry, I can send you email links for downloading them while we keep looking into this issue.

**Comment by onegladiator4u** [comment]
It's not a problem brother. I just didn't want anyone else have this problem in future or anytime. That's why I just mentioned. 
I have MAB backup and I have enough commentaries now.😊. Thanks.
Close the issue if you couldn't recreate the issue. May be it's just for me.

**Comment by eliranwong** [comment]
okay, I close for now.  If we can duplicate the issue, we let you konw.
