### ISSUE TITLE
search MOB, MIB, MTB, MPB, MAB for selective morphology combined with particular translated word

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#165]
right now, double clicking a word in MOB, MIB, MTB, MPB, MAB allows searching selective morphology search.

I will add ability to further refine the scope of search with translation options.

**Comment by eliranwong** [comment]
@otseng @darrelwright what do you think?  below is my little idea:

allows users to search with selected morphology in combination with selection translations:

![Screenshot 2021-02-20 at 6 55 46 PM](https://user-images.githubusercontent.com/25262722/108605648-6969a600-73ad-11eb-853f-50e54b318269.png)

**Comment by eliranwong** [comment]
@otseng @darrelwright  The gui above will be added next upgrade, I think.

meanwhile, you can actually do such as a search with MORPHOLOGY::: keyword, e.g.

> MORPHOLOGY:::LexicalEntry LIKE '%G746,%' AND Morphology LIKE '%Singular%' AND (Interlinear LIKE '%rule%' OR Interlinear LIKE '%rulers%')

If you simply want to search a Strong's number together with a particular translation without selecting morphology, e.g. 

> MORPHOLOGY:::LexicalEntry LIKE '%G746,%' AND (Interlinear LIKE '%rule%' OR Interlinear LIKE '%rulers%')

I may / may not add an option in gui dialog to allow users also choose a bible translation so to list verses from a chosen translation.  That's mean, the search is based on Hebrew / Greek database, displayed verses could be an English or other translations.  I haven't seen a bible software do that yet.  what do you think?

**Comment by eliranwong** [comment]
okay, done in version 21.53.  wiki page: https://github.com/eliranwong/UniqueBible/wiki/Search-morphology

**Comment by darrelwright** [comment]
this is good! I like where it is heading!
