### ISSUE TITLE
Parallel and/or Comparison view

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#177]
It would be really good if either the Parallel or Comparison view could show connections. What I mean is when I have two bibles selected and I click a word in the left-hand bible that the corresponding word in the right-hand bible would also highlight, and linkage would be either the Strong's number or the lemma. Is this possible?

**Comment by eliranwong** [comment]
@darrelwright I will do this in next version.

This feature is useful, I think.

I will name this feature as "Instant highlight".  FYI, it is not a new thing.  I already implemented this in the hybrid version: https://github.com/eliranwong/UniqueBibleAppHybrid

**Comment by eliranwong** [comment]
done! @darrelwright  read this wiki page for instructions: https://github.com/eliranwong/UniqueBible/wiki/Instant-Highlight
