### ISSUE TITLE
Reference Book Enhancement Request

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#179]
I would love to have an option to click a button to select all my reference books. I like being able to select a subset, but I have over 300 books and sometimes I want to search all of them. That says I'd also like a button to clear all selected books.

**Comment by eliranwong** [comment]
I think you are talking about Control Panel.

currently, you can search all books with command, e.g.

> SEARCHBOOK:::ALL:::faith

to search your favourite book collection, e.g.

> SEARCHBOOK:::FAV:::faith

re Control panel gui, I will consider adding a "All Books" button, right next to "Favourite Books" button on control panel 'Search' tab

**Comment by eliranwong** [comment]
Added a button for searching all books in version 21.58

![Screenshot_20210223_155431](https://user-images.githubusercontent.com/25262722/108869830-7bd32200-75ef-11eb-8aea-2216eec395c4.png)
