### ISSUE TITLE
BDB Lexicon [not found]

### ISSUE THREAD

**Issue by hebrewmatthew** [eliranwong/UniqueBible#18]
When trying to do a word study on a Biblical Hebrew word in Windows install.

**Comment by eliranwong** [comment]
Hello, thanks for your message.  can you tell me more how to reproduce the same issue?  The BDB lexicon entries are in Strong's number format.  Did you check a Strong number?

**Comment by hebrewmatthew** [comment]
From the Lexicon tab/pane (after clicking Analytic Lexicon button from Word pane), the drop down menu "More Lexicons HERE" does not pull up BDB or Strong's Concordance, but says [not found].  This also happens when clicking Strong's numbers from anywhere in Windows App (version 17.9).

**Comment by eliranwong** [comment]
which word you did the lookup?

**Comment by hebrewmatthew** [comment]
I've tried to look up many. Just tried to look up every word in the first verse of Genesis, and no go. I thought perhaps I could download the BentoBiblePlus Lexicons, but I don't where to download those.

**Comment by eliranwong** [comment]
is it possible you give an example.  which bible version do you use in the app.  which verse and word you launch a lookup from?

the BDB lexicon works with Hebrew Strong's number embedded in Hebrew bibles, like MOB, MAB, MIB, MTB, MPB, OHSB, OSHBi.  you should be able to lookup Hebrew words from this bible modules with BDB lexicon.

**Comment by hebrewmatthew** [comment]
BIBLE:::OHGBi:::Exod 12:1 (word AMAR). See screen shots:

![unique] (https://user-images.githubusercontent.com/46854918/79079062-4ae94780-7cd2-11ea-91b0-4bd31380ba1d.PNG)
![unique2](https://user-images.githubusercontent.com/46854918/79079069-5472af80-7cd2-11ea-8832-6efec9bf9a62.PNG)

**Comment by eliranwong** [comment]
I think this issue was fixed sometimes ago.  Thanks.
