### ISSUE TITLE
Windows installation. 

### ISSUE THREAD

**Issue by psuedochoco** [eliranwong/UniqueBible#183]
Please can you tell where do I post this. After successfully installing UBA on my pc it fails to download anything and just crashes. I would prefer to post this on a forum but can't find one.  Has anyone got this to work on a pc?

**Comment by onegladiator4u** [comment]
Is UBA app opening?
Can you mention What are you trying to download too.

**Comment by psuedochoco** [comment]
Hi onegladiator4u. Thanks. Immediately on opening UBA a pop up window appears asking me to download sqlite.images but nothing happens.

**Comment by onegladiator4u** [comment]
Is it not responding after you click download and install?

@eliranwong I believe this resembles my issue with downloading bible and commentaries. not sure. Seems like it.

**Comment by otseng** [comment]
> I would prefer to post this on a forum but can't find one.

Forum discussion is here:

https://github.com/eliranwong/UniqueBible/discussions

**Comment by otseng** [comment]
> Has anyone got this to work on a pc?

@eliranwong uses Windows.  I'm on Mac and Ubuntu.

**Comment by onegladiator4u** [comment]
I'm using pc too. I too have similar download problem. But I can use the app. Can you able to use the app or is it crashing before opening?

**Comment by eliranwong** [comment]
@psuedochoco @onegladiator4u I will check on Windows next few days.  I will try a fresh installation.  Thamks for reporting the issue.

**Comment by eliranwong** [comment]
I am trying a fresh installation on Windows.  It appears to me that it is a general issue.  @otseng can you also try a fresh installation on mac and see if downloading work?

**Comment by eliranwong** [comment]
I can see a zero empty file bibles.sqlite created in marveData but the screen but the screen get stuck with the following dialog after I click download.  @psuedochoco @onegladiator4u is that same to you?

<img width="203" alt="Screenshot 2021-02-24 155226" src="https://user-images.githubusercontent.com/25262722/109027066-51996700-76b8-11eb-9601-4fd347d8f07c.png">

**Comment by eliranwong** [comment]
@otseng I think this could be the same issue as https://github.com/eliranwong/UniqueBible/issues/141

This might be a general issue rather than platform-specific.

**Comment by psuedochoco** [comment]
> @psuedochoco @onegladiator4u I will check on Windows next few days. I will try a fresh installation. Thamks for reporting the issue.

Thank you Eliran. I need to use this software on Windows otherwise I would only to gladly go back to Linux.

**Comment by psuedochoco** [comment]
I 

> > I would prefer to post this on a forum but can't find one.
> 
> Forum discussion is here:
> 
> https://github.com/eliranwong/UniqueBible/discussions

Thanks.

**Comment by psuedochoco** [comment]
> I can see a zero empty file bibles.sqlite created in marveData but the screen but the screen get stuck with the following dialog after I click download. @psuedochoco @onegladiator4u is that same to you?
> 
> <img alt="Screenshot 2021-02-24 155226" width="203" src="https://user-images.githubusercontent.com/25262722/109027066-51996700-76b8-11eb-9601-4fd347d8f07c.png">

Yes this is exactly what happens.

**Comment by onegladiator4u** [comment]
@eliranwong actually I replaced my marveldata folder. So I didn't have problem with images.sqlite. But I have the same download issue with all modules

**Comment by eliranwong** [comment]
@psuedochoco @onegladiator4u thanks for reply.  no worry, I am working on it.  Should be fixed in 30 min.

**Comment by eliranwong** [comment]
@psuedochoco @onegladiator4u please help check if version 21.63 correct the issue

After you click "Download", you should see "Installing ... please wait"

When file is installed, you should see "done".

Please kindly let me know if that fix.  many thanks in advance.

**Comment by onegladiator4u** [comment]
It solved for me.

**Comment by psuedochoco** [comment]
> @psuedochoco @onegladiator4u please help check if version 21.63 correct the issue
> 
> After you click "Download", you should see "Installing ... please wait"
> 
> When file is installed, you should see "done".
> 
> Please kindly let me know if that fix. many thanks in advance.

Great. Works. Thanks.

**Comment by psuedochoco** [comment]
> @psuedochoco @onegladiator4u please help check if version 21.63 correct the issue
> 
> After you click "Download", you should see "Installing ... please wait"
> 
> When file is installed, you should see "done".
> 
> Please kindly let me know if that fix. many thanks in advance.

I look forward to supporting your work.

**Comment by eliranwong** [comment]
> I look forward to supporting your work.

Welcome and appreciate your support

It looks like this issue is solved.  I am closing this issue.
