### ISSUE TITLE
Two translate to English options

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#193]
In right click menu there's two translate to English options.
![image](https://user-images.githubusercontent.com/48617390/109175233-9baf4500-77ab-11eb-81ab-b6492b09832e.png)

**Comment by eliranwong** [comment]
@onegladiator4u 

Select your language with Focus menu layout

UniqueBible > UBA Preferences > General > Select Language for Translation

**Comment by eliranwong** [comment]
After you select your language, the second one will change to the language you select.

I will hide the second one if user does not select their own language next version.

**Comment by onegladiator4u** [comment]
Ok got it. Thanks

**Comment by eliranwong** [comment]
> I will hide the second one if user does not select their own language next version.

done in this commit: https://github.com/eliranwong/UniqueBible/commit/c2934d51b07677bba19ed76b3dd6cb22098b894f

**Comment by eliranwong** [comment]
from ver 21.72

**Comment by onegladiator4u** [comment]
I already set it up bro. Thanks for the information.
