### ISSUE TITLE
Instant highlight issue

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#196]
The instant highlight works great, but I found if I do not clear the highlight before building a book the highlighted word (in this case it was faith) is included in the book and I do not appear to have any way to clear that highlight in the new book.

**Comment by eliranwong** [comment]
> The instant highlight works great, but I found if I do not clear the highlight before building a book the highlighted word (in this case it was faith) is included in the book and I do not appear to have any way to clear that highlight in the new book.

Instant Highlight is NOTHING to do with book highlights.  Instant highlight works only on Main Window.  Book content is displayed on Study Window or New Window.  There is no way Instant Hightlight gets into book content.

From what you described, I guess you did a book search for the word "faith".  The highlights on books are result of searching books.  To remove higlights of results after searching books, right-click and select "Remove Book Highlight".  I believe the issue you mentioned is nothing to do with instant highlights

**Comment by darrelwright** [comment]
That is correct. It had nothing to do with instant highlights. Problem solved and thanks!
