### ISSUE TITLE
Simple/formatted toggle does not work correctly when OHGB bible is displayed

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#199]
I have KJV Bible in main window and OHGB bible in study window.  Pressing the simple/formatted button does not work correctly.

**Comment by eliranwong** [comment]
@otseng   I tried to do the same setup, but haven't managed to reproduce the issue.  Did I miss something.

> BIBLE:::KJV:::Gen 1

> STUDY:::OHGB:::Gen 1

Pressing the simple/formatted button works.

**Comment by eliranwong** [comment]
I finally found that the issue happens only on Aleph and Classic menu layout.  I was using Focus menu layout so didn't notice that.  It is now fixed in this commit https://github.com/eliranwong/UniqueBible/commit/00dca30744046c1db3ae5145b7a5713f807efb91

**Comment by eliranwong** [comment]
updated in TextCommandParser.py line 868 in https://github.com/eliranwong/UniqueBible/commit/17a48f5e11b37f5cde6db08cad8a8a280894867d:

elif text in formattedBibles and text not in ("OHGB", "OHGBi", "LXX") and config.readFormattedBibles:
