### ISSUE TITLE
Error on latest update - Missing gui.InfoDialog

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#200]
When restarting latest update I get error "No module named 'gui.InfoDialog'". Restarted OS and still get same message

**Comment by eliranwong** [comment]
sorry, I think you uodate in-between the time I merged a PR and updated the patch file.  patch is now updated to ver 21.74

**Comment by darrelwright** [comment]
As I posted to Eliran, I was able to pull an old copy from my backup, ran it and downloaded the latest build and am now playing. It would be cool to be able to download missing file(s), but not a bigger.
