### ISSUE TITLE
Search Highlight Issue

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#210]
I had previously done a search for "faith" in all my books and it returned results. Today I created a new book and, as the screen shot shows, the search word was still highlighted in my new book. The chapter on the right does not show "faith" highlighted, only the completed book.
![faith2](https://user-images.githubusercontent.com/11500764/109404366-42b1ef00-791a-11eb-9849-8b7e6e8890ba.png)

**Comment by eliranwong** [comment]
I already replied you at https://github.com/eliranwong/UniqueBible/issues/196

You cannalso set config flag removeHighlightsOnExit

**Comment by darrelwright** [comment]
Thanks - issue resolved!
