### ISSUE TITLE
Add Malayalam language to UBA

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#215]
@onegladiator4u What do you think of adding Malayalam as a supported language to the GUI?

**Comment by onegladiator4u** [comment]
You mean for interface? What can I do to help ?

**Comment by otseng** [comment]
Yes.  When this code is merged, the Malayalam language will be added to the interface.  

In config.py, set `developer = True`.  When you startup UBA, you'll see "Edit language file" in Developer.  Select "ml".  This will show you list of Watson translated items for Malayalam.  Double-click a row to edit it.  Click "OK" to save it.

After you've corrected the translation file, create another issue and attach the language_ml.py file and I'll replace it in the code.

**Comment by onegladiator4u** [comment]
Ok brother.

**Comment by eliranwong** [comment]
@otseng thanks for the new PR.  I'm outdoor now, will merge it when home.
