### ISSUE TITLE
Back up

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#22]
Hello sir,
Thank you for the Unique bible in the name of Jesus. And Merry Christmas.
I'm new to this, and I'd love to know how to backup the files. Like notes of verses. I have no idea where are those files.
And it would be nice to see a back up option inside the app or syncing.
I would like to know if there is a bookmark option. Or did I miss it? Is there any tutorial videos of this app in YouTube ?
Thanks in advance

**Comment by eliranwong** [comment]
Hello onegladiator4u,

  Merry Christmas.  Thanks for your message.

  With regards to notes backup, are you talking about desktop version or mobile version?

  For desktop version, chapter and verse notes are store on file, "UniqueBible\marvelData\note.sqlite".  Topical notes are stored where you save your note files.

  For mobile version, you may read instructions at https://www.uniquebible.app/mobile/user-notes/back-up

  You can add favourites verses in mobile version.

  For your information, I am currently working on integrating the desktop and mobile version into a single cross-platform application at: https://github.com/eliranwong/UniqueBibleAppExpanded  I am try to bringing best features of both versions into this new one.  New feature suggestion is welcome.

**Comment by onegladiator4u** [comment]
I was talking about pc version. Thanks for the info. Now I can back up. 😊
For features I would recommend bookmarks. 
For interface: You could separate Bible Book names as separate. It's difficult to find the book names. Or you give colors to OT books one color and NT different one. Or It would be nice if you give different colors to books by it's category like
![Screenshot 2020-12-25 213359](https://user-images.githubusercontent.com/48617390/103138466-f7e8e080-46f8-11eb-8e03-c72cfd8a66c1.png)
I'm just suggesting colors only not names. Haha.
Changing Bible books is not easy. Is there any plan to add it as list view on the left? Like pinning and collapsing if someone don't want.
Is there a way to apply specific font to a Bible version? When I change font for my language everything uses that font. 
And one issue with pc is that after closing the app the books in bible windows are closed. Is there way to remember those Bible version and reopen it after the restart. Or you can add Bible versions as tabs.
I'm really sorry for making it longer . Hope you don't mind. I just really love this app. Thank you for that. 
May God bless you guys.

**Comment by eliranwong** [comment]
appreciate your suggestions.  thank you.  After I make significant progress in the new project, I will see if these additions are possible.  thanks once again.

**Comment by onegladiator4u** [comment]
Thanks brother .

**Comment by onegladiator4u** [comment]
Can I suggest one more thing?

**Comment by eliranwong** [comment]
> Can I suggest one more thing?

Sure.  You are welcome to make suggestions.  Thanks.

**Comment by onegladiator4u** [comment]
When we hover over verses in commentary or somewhere it's only showing one verse in bottom window. When hover over verses in range like John 1:2-5. It'll only show john 1:2. Can you make it that it'll show as full verses. Or to show in tooltip.
I thought the settings in **select more...** Named **showversenumbersinrange** will solve that.

**Comment by eliranwong** [comment]
I think this issue had been addressed sone times ago.  The current parser is able to parse verse references even in ranges.  Just some old module files converted in the past may needed to be converted again to update the bible reference links.

**Comment by onegladiator4u** [comment]
Ok thanks brother
