### ISSUE TITLE
Issue with internal hyperlinks

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#228]
The issue with external hyperlinks appears to be the same as with internal hyperlinks, where I want to link from one chapter in a book to another.
[Test.zip](https://github.com/eliranwong/UniqueBible/files/6074809/Test.zip)
[Test.book.zip](https://github.com/eliranwong/UniqueBible/files/6074812/Test.book.zip)

**Comment by eliranwong** [comment]
duplicate issue of https://github.com/eliranwong/UniqueBible/issues/207
