### ISSUE TITLE
Possible Spelling mistakes 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#233]
Noticed that in note editor tooltips for superscript and subscript shows `sytle` instead of style.
Not sure about the second one . In **set config flag** window tooltip for `ttsChineseAlwaysCantonese` should be `option to use Cantonese voice`. But it's showing `option to use Chinese voice`

**Comment by eliranwong** [comment]
corrected in this commit https://github.com/eliranwong/UniqueBible/commit/3bcb30bba36ebfe6f283bd821acd878efddda291

thanks again for reporting the issue.

**Comment by onegladiator4u** [comment]
@eliranwong bro still sytle in tooltip
![image](https://user-images.githubusercontent.com/48617390/110077354-f5b39a00-7dab-11eb-8f71-943cc85dcfce.png)

**Comment by eliranwong** [comment]
oh, I missed that.  I will fix it too.

**Comment by eliranwong** [comment]
fixed in https://github.com/eliranwong/UniqueBible/commit/18db66df0058a3cbd4c62142d8e55ab68faa9126
