### ISSUE TITLE
PopulateTabsOnStartup

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#238]
Is there any way openBibleWindowContentOnNextTab and openStudyWindowContentOnNextTab values can remember their values on next startup when PopulateTabsOnStartup is true?  
openBibleWindowContentOnNextTab keep turns on as the tooltip says at restart. Which makes whatever Command we give to open in next tab, that changes that tabs previous record. This happens even if we change bible version through dropdown box. Unless we turn turn of these options manually at every restart.
PopulateTabsOnStartup is a best feature, it would be better if there is a way to overcome this thing.

**Comment by eliranwong** [comment]
I will try.

**Comment by onegladiator4u** [comment]
Thank you

**Comment by eliranwong** [comment]
@onegladiator4u implemented in https://github.com/eliranwong/UniqueBible/commit/18db66df0058a3cbd4c62142d8e55ab68faa9126 (version 22.23)
