### ISSUE TITLE
Lexicon import 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#244]
I tried to import 2 lexicons from sqlite3 format. It's not adding to lexicon directories
One named BDAG 2000(BDAG3.dictionary.SQLite3) and  Danker.dictionary.SQLite3.
Got it from https://www.ph4.org/b4_index.php?k=dictionary&q=mybible

**Comment by otseng** [comment]
Does anything show up in the thirdparty/dictionaries folder?

**Comment by onegladiator4u** [comment]
Oh. I was looking at marveldata folder. I found it.
How can I access it via app? I couldn't find it here
![image](https://user-images.githubusercontent.com/48617390/110216611-0f510080-7ed6-11eb-8e8e-33ac4bba2fc0.png)

**Comment by otseng** [comment]
Can access in master control or command line or third party dictionaries in menu.

SEARCHTHIRDDICTIONARY:::Danker:::ὑποταγῇ

<img width="1367" alt="Screen Shot 2021-03-06 at 1 25 38 PM" src="https://user-images.githubusercontent.com/806056/110216973-93c46480-7e7f-11eb-95ef-c9f0efed7b91.png">

**Comment by otseng** [comment]
One thing I cannot find how to do is search all the third party dictionaries.  @eliranwong ?

**Comment by onegladiator4u** [comment]
@otseng Thanks bro.

**Comment by onegladiator4u** [comment]
@eliranwong I saw other lexicon files in marveldata folder like BDAGx in screenshot somewhere, where can we find it available?
That's why I thought these files go to marveldata folder.

**Comment by otseng** [comment]
In master control, in search, hebrew/greek lexicon.
In mini control, under lexicons.

**Comment by eliranwong** [comment]
> One thing I cannot find how to do is search all the third party dictionaries. @eliranwong ?

do you mean search all in one-go.  not available yet according to my memory

**Comment by eliranwong** [comment]
> @eliranwong I saw other lexicon files in marveldata folder like BDAGx in screenshot somewhere, where can we find it available?
> That's why I thought these files go to marveldata folder.

Third-party dictionaries / lexicons are use with plug and play, no conversion is done, so they are placed in a separate folder "thirdParty".  Users can simply download a dictionary and place in this folder for use with UBA, no conversion or installation is needed.

If you formatted a lexicon in the same format as other marvel data, you can put in marvelData folder.

**Comment by onegladiator4u** [comment]
> If you formatted a lexicon in the same format as other marvel data, you can put in marvelData folder.

How to format the lexicon to put in marvel data folder?

**Comment by eliranwong** [comment]
it requires knowledge on formats of both source and target files.  currently, third party file content is converted in runt time so plug and play works

**Comment by onegladiator4u** [comment]
Ok
