### ISSUE TITLE
Add action to single click

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#246]
Can you add an action to single click that would show the corresponding verse in the study window using the study Bible?

**Comment by eliranwong** [comment]
This function is already available with the button to sync Study Window bible with the main

on Focus:

![Screenshot_20210307_090720](https://user-images.githubusercontent.com/25262722/110234906-fae82480-7f24-11eb-8081-6c2788c5e02f.png)

on Aleph / Classic, it looks:

![Screenshot_20210307_090758](https://user-images.githubusercontent.com/25262722/110234894-ef94f900-7f24-11eb-93a7-c869b1cd9af5.png)

you can also specify which version to sync.

**Comment by otseng** [comment]
Ah, figured it out.  I have to select "Single-click action" to empty.  I had set it to "Bible".
