### ISSUE TITLE
Add configurable ability to go directly to the item in the toolbar items

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#247]
Right now, if I click on a toolbar item, it would open up the master control.  

Add a config flag to allow it instead to directly open the corresponding item.

So, if I click on the "KJV+:::1Tim 3:1" button, it would open up the verse in the main window.
Clicking "OHGBi:::1Tim 3:1" button would open up the verse in the study window.
Clicking "ICCNT:::1Tim 3:1" button would open ICCNT commentary.
Clicking "Hymn Lyrics" would open the Hymn Lyrics book.

<img width="717" alt="Screen Shot 2021-03-07 at 12 56 28 AM" src="https://user-images.githubusercontent.com/806056/110230627-3f9d9c80-7ee0-11eb-9522-3b22a8f95668.png">

**Comment by onegladiator4u** [comment]
Maybe double click action for that?
Single click to open as you said. And master control when double click.

**Comment by otseng** [comment]
Yes, that would be good.

**Comment by otseng** [comment]
Looking at the qt library, doesn't appear to be an easy way to distinguish between single click and double click.

**Comment by otseng** [comment]
I'm going to design it so it's configurable like verse number action.

Can select from opening master control, opening mini control, or go directly to reference.

**Comment by eliranwong** [comment]
noted, thanks.

**Comment by onegladiator4u** [comment]
@otseng bro, did you implement this ability ? How to set it up?

**Comment by eliranwong** [comment]
@onegladiator4u 

accessible from menu, see screenshot below

![Screenshot 2021-03-12 11 44 46 AM](https://user-images.githubusercontent.com/25262722/110936296-9401ab80-8328-11eb-9cbb-bf3e1f34821b.png)

**Comment by onegladiator4u** [comment]
@eliranwong thank you. I was searching everywhere except that place.😊 shouldn't this be with 'verse number action' in Bible menu?

**Comment by eliranwong** [comment]
@onegladiator4u 

I moved there, because it is not only affect bible button, but also some other buttons on the menu toolbars

**Comment by onegladiator4u** [comment]
Oh ok.
