### ISSUE TITLE
Edit working translations suggestion

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#249]
If we translate through 'Edit Working translation' the file doesn't get updated until next restart. If we translate some words and click OK on 'Edit GUI Language ' window and open again and try to edit remaining words ,previous translations won't show up. If we accidentally click OK all the translations that did moments ago will be lost. This happens only if we don't restart. Is it possible to reload language file when clicking on 'Edit Working translation' ? So that we don't need to restart app every time we edit some translation.

**Comment by otseng** [comment]
Yes, I'll add this.

**Comment by onegladiator4u** [comment]
Thank you.
