### ISSUE TITLE
Red letters

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#25]
Brother can you guide me how to add red letters to Jesus words to my language Bible version. Is it possible for me?
May be I Can add it to other versions too.
I found this app to edit wrong wordings and spaces from my Sqllite3 bible book. **DB Browser for SQLlite**. 
I don't know how to give color.
When I edited .bible files there was no change. So I edited Sqllite3 file then will import again.

**Comment by eliranwong** [comment]
Hello, I think it would be straightforward.  Just surrounds the text with <red>...</red>.

for example, <red>The text here is red.</red>

**Comment by onegladiator4u** [comment]
I couldn't see red brother.
Did you really mean to add the dots....

**Comment by eliranwong** [comment]
Oh, sorry.  I just realized that the online editor hide my tags.  I edited to make the tags readable.  Please let me know if it works for you.

**Comment by onegladiator4u** [comment]
Thank you so much. It's working.

**Comment by onegladiator4u** [comment]
May I know which are the colors allowed in the app?
Red is working. I tried crimson , it didn't. Can I add colors somewhere ?
Thanks

**Comment by eliranwong** [comment]
You can add any colors or fonts via css files, located in folder "htmlResources/css".  I think this app needs to add support for a user custom css file, so that future updates won't overwrite users' customized css style.

**Comment by onegladiator4u** [comment]
Oh ok ok. 
Then I have to change css when an update occurs right?
Thank you.
