### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#254]
Credentials spelling mistakes
![image](https://user-images.githubusercontent.com/48617390/110288960-c2bd1080-800e-11eb-9b63-1a1724fc72ab.png)

**Comment by eliranwong** [comment]
@onegladiator4u got your message, I will fix the spelling.  I deleted one of your screenshots above, so to hide your own credentials from the public.

**Comment by onegladiator4u** [comment]
Oh I forgot about that. Thank you.

**Comment by eliranwong** [comment]
fixed https://github.com/eliranwong/UniqueBible/commit/9406a68b13f58cbd9543540f5d37dc05a432c863
