### ISSUE TITLE
Compare view suggestion 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#270]
If we compare a verse and a Bible version didn't have that verse it'll normally look like this.
![image](https://user-images.githubusercontent.com/48617390/111026020-0b5d3b00-840e-11eb-8a7c-892069300392.png)
if someone don't want to view the Bible version if it didn't have verse corresponding to the verse number then an option to hide those version titles from the compare view would be nice in my opinion.
What do you guys think?

**Comment by otseng** [comment]
Added hideBlankVerseCompare config flag
