### ISSUE TITLE
Book building issue

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#280]
The attached book directory contains 4 chapters. I am not sure if I am doing something wrong in this module, but after 8 hours the UBA is still trying to create the module. I have created quite a few books and this is the only one that has had any issues. Am I missing something?

[Bible Study.zip](https://github.com/eliranwong/UniqueBible/files/6137615/Bible.Study.zip)

**Comment by otseng** [comment]
Something is strange.  I'm not even able to open them up as a note.

@eliranwong It's getting stuck on line 191 in BibleVerseParser.py
`text = RegexSearch.replace(text, searchReplace)`

**Comment by eliranwong** [comment]
> Something is strange. I'm not even able to open them up as a note.
> 
> @eliranwong It's getting stuck on line 191 in BibleVerseParser.py
> `text = RegexSearch.replace(text, searchReplace)`

@otseng   thanks.  will take a look.

which chapter could not be opened?

**Comment by eliranwong** [comment]
I have no idea, I think it takes too long to be loaded.  I randomly deleted a few long lines and it could be displayed but after waiting for minutes.

To improve performance for display, I suggest to cut a very long chapter into different sections.

regarding conversion into book module, I have no idea what is the problem.  @darrelwright you may try to make the chapter shorter and try again.

what is the original source of this book?  It may be already available in some other formats.

**Comment by darrelwright** [comment]
I think I have narrowed the issue down. It appears to be related to images in the uba file. The attached file is a subset of the first chapter and includes 3 jpeg files. The images cause a big slowdown inn creating the book. Is there a way the book building code could process images better?

[01.1 Introduction to bible Study.uba.zip]

**Comment by eliranwong** [comment]
The image can be stored externally in htmlResources/ .  I got your email and know that you solved the issue.  I am happy that you found a solution.  If no further question, I am closing this issue.  Thanks.
