### ISSUE TITLE
Duplicate presentation buttons

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#285]
With the latest release the go to Presentation and Go to Presentation Text Only buttons in the right-click context menu were duplicated. Can we remove one of each, leaving one Go to Presentation and Go to Presentation Text Only buttons-

**Comment by eliranwong** [comment]
That's easy to do.  They are plugins, you can add or remove at any time.

Open the folder "UniqueBible/plugins/context/ and delete the two that you do not want.

You probably want to delete the two, which does not have shortcut keys specified, i.e. Go to Presentation.py and Go to Presentation TEXT ONLY.py
