### ISSUE TITLE
New Wiki Pages tabs being opened repeatedly when mouse over bible frame

### ISSUE THREAD

**Issue by jdecent** [eliranwong/UniqueBible#288]
This happens after selecting Wiki Pages from the menu or via shortcut CTRL+H

==============================================================
Debugging Information
==============================================================
2021-03-17 15:59:36.010672

# Platform
Python=['3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]']
Could not get uname
platform=Windows-10-10.0.18362-SP0
platform=nt
platform=10

# Locale
timezone=Central Daylight Time-0500
defaultlocale=('en_US', 'cp1252')
Could not get locale

# Version
UBA Version: 22.82

# Config
config.theme=default
config.userLanguage=English
config.userLanguageInterface=False
config.menuLayout=focus
config.theme=default
config.menuShortcuts=micron
config.marvelData=marvelData
config.qtMaterial=False
config.qtMaterialTheme=
config.useFastVerseParsing=False
config.menuShortcuts=micron
config.startupMacro=
config.enableMacros=False
config.useFastVerseParsing=False
config.disableModulesUpdateCheck=True

# Marvel data
Bibles: 10
Books: 19
Data: 13
Commentaries: 1
Lexicons: 15

**Comment by eliranwong** [comment]
@jdecent thanks for report.

I tried on a Windows 10 laptop, but unfortunately cannot duplicate the issue.

There should be no connection between mouse hovering and opening wiki page, as I know.

Does the issue happen on your computer even after UBA startup for a while?

Check you check three things?

Select Menu > UniqueBible > Set Config Flags

'useWebbrowser' and 'populateTabsOnStartup'

are the above values checked or unchecked?

Select Menu > Master Control > History

can you take a screenshot of the history records (especially, history records of study window)?

**Comment by jdecent** [comment]
I currently have KJV and OHGBi in comparison mode. I've determined it repeats opening the Wiki Pages tab only when hovering over Greek text. If you cannot replicate I will record my screen to show the affect.

**Comment by eliranwong** [comment]
> I currently have KJV and OHGBi in comparison mode. I've determined it repeats opening the Wiki Pages tab only when hovering over Greek text. If you cannot replicate I will record my screen to show the affect.

@jdecent I can duplicate with the same setup.  Thanks very much.  This is definitely a bug.  I will try to fix it.

**Comment by eliranwong** [comment]
@jdecent fixed in version 22.87 https://github.com/eliranwong/UniqueBible/commit/999754603b05d94d4cbcce90976defcc01004f02

you may update through menu or git clone.

thanks again for reporting the issue

**Comment by eliranwong** [comment]
@jdecent does it work for you now?

**Comment by jdecent** [comment]
@eliranwong it seems to have been resolved. My version is now 22.95
