### ISSUE TITLE
popup window change request

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#294]
I use popup windows heavily. When I have a window open, then click to open the next chapter I would really like option to close the first open window. As it is now I end up with multiple open popup windows minimized.

**Comment by otseng** [comment]
Is this still an issue?  
How can it be reproduced?

**Comment by darrelwright** [comment]
Yes it is still an issue. Just take the last zip file I sent you, unzip 
it in uba, create the book and watch it fail!

Now, I have a question for you. I have rebuilt everything as html files 
(I have two left to do) and they are working beautifully. Do we want to 
consider switching from uba to html, or is the best answer to still fix 
the issue with uba?

**Comment by darrelwright** [comment]
I had trouble getting the file to upload so here is my latest response 
and now am off to bed. Talk later:

As I mentioned in the email the problem still exists with links in uba 
files. Now check out this book. It's the files but as html - and the 
entire book works! I still think we need to fix the issue with uba, but 
html does play!

The file is apparently too big to paste here, so here is a link to my cloud:
https://u.pcloud.link/publink/show?code=kZyPPCXZlGmCji9rbWuFwhTTNF9y3kPROSU7

**Comment by otseng** [comment]
Here's what I'm seeing.  If you click on the links in the study window, it'll open into the same popup window, no new windows will be created.  But, if you click on the "Rumsey - html" link at the top of the popup window, then the next time click in the study window, a new popup will be created.   Is that what you see?

**Comment by darrelwright** [comment]
I am seeing that also. That should not happen should it?

Also the uba links are now working!

**Comment by otseng** [comment]
> I am seeing that also. That should not happen should it? 

I'll need to fix that.

> Also the uba links are now working!

Great!

**Comment by darrelwright** [comment]
We're making progress, huh? You did see my message on git regarding rtl 
importing apparently not working from theWord Hebrew bibles? If you have 
an ONT bible will it import OT as rtl and NT as ltr?
