### ISSUE TITLE
Duplicate options 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#298]
![image](https://user-images.githubusercontent.com/48617390/111953649-eb640080-8b0c-11eb-8564-c0d8d4a3c637.png)
Found two drive plugins. Which plug-in should I keep ? 
![image](https://user-images.githubusercontent.com/48617390/111953846-31b95f80-8b0d-11eb-9eee-878178c9792e.png)
Do I need this folder now since there is another folder named 'plugins'?
![image](https://user-images.githubusercontent.com/48617390/111954017-7d6c0900-8b0d-11eb-862d-bc76c6fc27f4.png)

**Comment by eliranwong** [comment]
To get rid of duplicated items, you can either run 'git pull' or manually delete:

folder 'plugins_context'

files 'Notes from Google Drive.py' and 'Notes to Google Drive.py'

**Comment by onegladiator4u** [comment]
Ok. Thank you
