### ISSUE TITLE
Video music still plays when Youtube downloader window is closed

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#302]
To duplicate:

- Highlight text
- Select Context/Plugins/Youtube Downloader
- Play a video
- Close the window 

The window will close, but the video audio is still running.  

Duplicated on Mac and Ubuntu.

**Comment by eliranwong** [comment]
I noted the issue too, but haven't managed to find a complete solution.

A temporary solution is to stop the music before closing the window.

**Comment by eliranwong** [comment]
I think of a solution, will test and let you know.

**Comment by eliranwong** [comment]
@otseng I think it is now fixed, but please help check if it works on your side too.  thanks.

https://github.com/eliranwong/UniqueBible/commit/9bd732f5c1e348dd041f63934c18c993c1cfe3ea

**Comment by otseng** [comment]
yes, it works now!
