### ISSUE TITLE
Compare displays RTL for Old Testament after OHGB

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#308]
I've never seen this before,  but when doing `COMPARE:::Prov 4:23`, the verses are all displaying right to left after the OHGB.

<img width="1440" alt="Screen Shot 2021-03-27 at 10 17 49 AM" src="https://user-images.githubusercontent.com/806056/112723638-00160f00-8ee6-11eb-9c60-b12faa399400.png">

**Comment by eliranwong** [comment]
@otseng I think the issue was introduced recently.  The display was perfect some times ago.

**Comment by eliranwong** [comment]
@otseng I fixed, uploading soon.

**Comment by eliranwong** [comment]
error was introduced in merging this PR: https://github.com/eliranwong/UniqueBible/pull/287/files

it is now fixed in this commit: https://github.com/eliranwong/UniqueBible/commit/f372957229f3bdfb2f6ea386bb750cc29a6b6e02

**Comment by otseng** [comment]
Thanks
