### ISSUE TITLE
After update app not opening 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#31]
Bible updated to version 18.7. After the restart its not opening app. What to do?

**Comment by eliranwong** [comment]
@otseng Do you have any ideas?  in version 18.7, I merged your work on tts.

**Comment by eliranwong** [comment]
@onegladiator4u can you try downloading the file "main.py" at https://github.com/eliranwong/UniqueBible/blob/master/main.py

then go to your UniqueBibleApp folder to replace the old main.py with this new one?

please kindly let me know if it works after you try.  thank you very much.

**Comment by onegladiator4u** [comment]
I replaced it. Not working brother. Should I reinstall whole app?

**Comment by onegladiator4u** [comment]
I reinstalled it. I think it's because I didn't install plugin correctly. BTW is plugin working? I couldn't notice change.
Thanks

**Comment by eliranwong** [comment]
can you launch the app now?  It seems the new "detect language " feature works on mac but not on Windows.

**Comment by onegladiator4u** [comment]
Yeah I can launch it. 
Ok OK.
Thanks again for the replies.

**Comment by otseng** [comment]
Have you ran this before running?

pip install langdetect

**Comment by onegladiator4u** [comment]
No. After it didn't launch, I read the changes. Then installed pip install langdetect. 
Didn't work. Then I just reinstalled everything. Then ran `python .\main.py` through PowerShell. Then I saw error that plugin is missing. Then installed plugin. Ran again, it worked.
Now it's working.
