### ISSUE TITLE
Interface language doesn't show correctly

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#311]
Yesterday when i changed interface to Malayalam the menu words was unreadable.
![image](https://user-images.githubusercontent.com/48617390/112742917-7b43f780-8fb0-11eb-9161-bda926a3b916.png)
For example : The words should look like this.
![Untitled](https://user-images.githubusercontent.com/48617390/112743110-0a054400-8fb2-11eb-836d-e9d81e002b3b.png)

**Comment by onegladiator4u** [comment]
Hindi language too had the same problem.

![image](https://user-images.githubusercontent.com/48617390/112744272-29a16a00-8fbc-11eb-972f-ee1c28a76ec5.png)

I noticed that right click context menu didn't change language until the next restart too.

![image](https://user-images.githubusercontent.com/48617390/112744295-81d86c00-8fbc-11eb-8599-0f723eebcf68.png)

**Comment by otseng** [comment]
It looks like it's inserting another character for you?

On my Mac, it seems to be correct:

<img width="891" alt="Screen Shot 2021-03-28 at 10 07 25 AM" src="https://user-images.githubusercontent.com/806056/112755268-f48e1b00-8fad-11eb-99da-ba1331f24e06.png">
<img width="891" alt="Screen Shot 2021-03-28 at 10 10 13 AM" src="https://user-images.githubusercontent.com/806056/112755270-f526b180-8fad-11eb-81bd-4e3f24541fd3.png">

**Comment by onegladiator4u** [comment]
> It looks like it's inserting another character for you?

It's not inserting a character, it's separating a character and a vowel sign. I don't know how to explain. But I'll try.
For example: This one letter consist of two characters. `വി` = വ + ി. App is separating like that.
![image](https://user-images.githubusercontent.com/48617390/112755834-19ab7980-9000-11eb-8e5f-7756c3ec1efa.png)
![image](https://user-images.githubusercontent.com/48617390/112755891-54151680-9000-11eb-9899-eabb0c0e758e.png)
![image](https://user-images.githubusercontent.com/48617390/112755907-6abb6d80-9000-11eb-90f0-7498eaff8011.png)

**Comment by otseng** [comment]
On Ubuntu, it has the problem.

![Screenshot from 2021-03-28 12-06-12](https://user-images.githubusercontent.com/806056/112759079-61f67780-8fbf-11eb-9d58-92fc371d25fc.png)

**Comment by onegladiator4u** [comment]
Oh i see. Earlier this wasn't a problem. 
Do you guys have old versions of the app and see it looks like this? May be you guy's can figure out by comparing.

**Comment by otseng** [comment]
That's the strange thing, I went back to March 1 when the language file was added, and it also has the same problem.

git checkout a4d341501346c9a9c507d72ce8715e4e082af6ce

**Comment by onegladiator4u** [comment]
That's strange. Have you checked Hindi language ?

**Comment by otseng** [comment]
I don't think it's an issue with the language files.  I believe It's when Qt is trying to underline the first character of the menu item.  Mac doesn't underline, so there's no issue.  I tried to see if there's a setting to disable underlining, but haven't found one yet.

**Comment by otseng** [comment]
I'll add a config flag to disable underlining.

**Comment by otseng** [comment]
In the config, set enableMenuUnderline to False.

**Comment by onegladiator4u** [comment]
Ok. I'll try it.

**Comment by onegladiator4u** [comment]
@eliranwong it's ok now. Thanks

**Comment by eliranwong** [comment]
thanks @otseng for adding this option.
