### ISSUE TITLE
Ancient Hebrew Lexicon of the Bible (AHLB)

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#321]
I use the AHLB quite a bit in another program. I have ported it to UBA, but UBA does not recognize the fonts. I have ncluded the fonts and the current AHLB dictionary. Can you help UBA to recognize these fonts?

[fonts.zip](https://github.com/eliranwong/UniqueBible/files/6240383/fonts.zip)
[AHLB.dct.mybible.zip](https://github.com/eliranwong/UniqueBible/files/6240385/AHLB.dct.mybible.zip)

**Comment by otseng** [comment]
Got it to work on my Mac as follows:

1. Unzip the fonts in the htmlResources/fonts directory.

<img width="294" alt="Screen Shot 2021-03-31 at 10 49 01 PM" src="https://user-images.githubusercontent.com/806056/113236685-5a5ef900-9273-11eb-91c8-04b826e4fe37.png">

2. Edit the htmlResources/css/custom.css file and add:

```
@font-face {
  font-family: 'Semitic-Early';
  src: url('../fonts/semear.ttf')
}
@font-face {
  font-family: 'Semitic-Middle';
  src: url('../fonts/semmid.ttf')
}
@font-face {
  font-family: 'Semitic-Modern';
  src: url('../fonts/semmod.ttf')
}
@font-face {
  font-family: 'Semitic-Late';
  src: url('../fonts/semlate.ttf')
}
.semear {font-family:'Semitic-Early'}
.semlate {font-family:'Semitic-Late'}
.semmid {font-family:'Semitic-Middle'}
.semmod {font-family:'Semitic-Modern'}
```

Can now see the fonts:

<img width="863" alt="Screen Shot 2021-03-31 at 10 50 48 PM" src="https://user-images.githubusercontent.com/806056/113236802-a01bc180-9273-11eb-8bb9-f43ca7e10d50.png">

**Comment by eliranwong** [comment]
The above answer is a wonderful demonstration on use of UBA custom css feature.  Thank you @otseng

**Comment by eliranwong** [comment]
@darrelwright I assume it works for you.  I am closing this issue.  thanks.

**Comment by darrelwright** [comment]
I still have an issue with fonts. I have made the changes mentioned 
here, and the Hebrew Alphabet Chart displays the hebrew scripts 
perfectly. But when I open select and right-click a Strong's number in a 
Bible (i.e., H2962), then go to Bible Resources followed by Third Party 
Dictionaries, then AHLB. Now clicking on H2962 I do not get the ancient 
Hebrew scripts displayed.

When I do the same in theWord I get the 2nd screenshot, so something is 
not being picked up. Is there something missing?

Darrel

**Comment by darrelwright** [comment]
Also the Hebrew scripts display properly when nothing is added to the 
css file. So something is missing.

**Comment by darrelwright** [comment]
I'm sorry, but this is still not working in the AHLB dictionary. The 
Hebrew alphabet chart works fine, but the AHLB dictionary does not. I 
have attached the AHLB dictionary and included a snapshot of the results.

**Comment by otseng** [comment]
Here's what I see for H430...

<img width="684" alt="Screen Shot 2021-06-20 at 12 26 50 PM" src="https://user-images.githubusercontent.com/806056/122681574-e6255900-d1c2-11eb-932f-1037f33b519a.png">

**Comment by otseng** [comment]
Here's what I see for H2962...

<img width="671" alt="Screen Shot 2021-06-20 at 12 31 42 PM" src="https://user-images.githubusercontent.com/806056/122681675-8da28b80-d1c3-11eb-8651-900fee7d03ac.png">

**Comment by darrelwright** [comment]
Thanks for sharing. I really don't understand. I have the fonts in the 
fonts directory. I have the proper entries added to the css file. I have 
even re-downloaded ahlb, and yet when I right-click and select AHLB from 
third-party resources. I am running Linux Mint 20.1. Do you have any 
thoughts?

**Comment by otseng** [comment]
Can you right click on the page and select Copy/HTML Code.  Then paste the contents into a file called study.txt.  Then attach that file here?

<img width="1440" alt="Screen Shot 2021-06-21 at 8 37 35 PM" src="https://user-images.githubusercontent.com/806056/122844980-bcf2ee80-d2d0-11eb-82e8-44da8259e3a8.png">

**Comment by darrelwright** [comment]
Yes

[study.txt.tar.gz](https://github.com/eliranwong/UniqueBible/files/6690732/study.txt.tar.gz)

**Comment by otseng** [comment]
I took your file and created a test.html and put it in the htmlResources folder and see this.  So, it's generating the file correctly.  

<img width="1037" alt="Screen Shot 2021-06-22 at 8 07 16 AM" src="https://user-images.githubusercontent.com/806056/122921944-1c80e680-d331-11eb-9822-a4d58d7ddf51.png">

**Comment by darrelwright** [comment]
I just made a test.html file, opened it and I do not get the correct display. I get the same thing I sent you.

**Comment by darrelwright** [comment]
Is there possibly a py file or something that did not get installed from my last build?

**Comment by darrelwright** [comment]
Well I rebuilt UBA and have the results, so I don't think I am missing a file. But still cannot AHLB properly.

**Comment by darrelwright** [comment]
But still failing on my end. I even rebuilt UBA and nothing changed.

**Comment by otseng** [comment]
Can you post a screenshot here?

**Comment by darrelwright** [comment]
It's the same as I have been posting

![error2](https://user-images.githubusercontent.com/11500764/123177279-cc417b80-d439-11eb-9be6-6c42ab7d0f8a.png)

**Comment by otseng** [comment]
Make sure the fonts are under the htmlResources/fonts folder like this:

<img width="324" alt="Screen Shot 2021-06-23 at 7 10 58 PM" src="https://user-images.githubusercontent.com/806056/123179192-d9209800-d456-11eb-8e10-760c71a8c27b.png">

**Comment by darrelwright** [comment]
they are and have been since the first message and and css is set since the first message:

![fonts](https://user-images.githubusercontent.com/11500764/123179678-c00bed00-d43e-11eb-9272-26d82343de55.png)

![css](https://user-images.githubusercontent.com/11500764/123179690-c306dd80-d43e-11eb-9b52-7ad88dce3baf.png)

**Comment by otseng** [comment]
I think I might've found the problem.  Fix will be in the PR.

**Comment by darrelwright** [comment]
Cool! I look forward to checking it out. Thanks Oliver!
