### ISSUE TITLE
Problem with latest update

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#323]
When I open a Bible, MIB, I get a wrong screen. Check the snapshop.
![latest update](https://user-images.githubusercontent.com/11500764/113278479-d28ae600-9296-11eb-878a-bc08c593e95e.png)

**Comment by eliranwong** [comment]
fixed in ver 23.34; https://github.com/eliranwong/UniqueBible/commit/132c99112a50cb6b9487d219b550c1639f8476e9
