### ISSUE TITLE
bible reading plan

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#324]
will explore if possible to add bible reading plan to UBA.

**Comment by eliranwong** [comment]
what do you think?  welcome any comments before it is finalised.

![Screenshot 2021-04-03 11 57 56 AM](https://user-images.githubusercontent.com/25262722/113476571-26065b00-9474-11eb-86ae-f6c6478494b2.png)

**Comment by otseng** [comment]
Looks good.

What does "Uncheck all items" and "Save reading progress" buttons do?

Is it possible to also define other Bible reading plans?  Like one for reading the Bible in 2 years?  Or only reading from one book per day?

**Comment by eliranwong** [comment]
> Looks good.
> 
> What does "Uncheck all items" and "Save reading progress" buttons do?
> 

"Uncheck all items" is like a reset button to start another cycle of reading.

"Save reading progress" - when I read a portion, I check the item.  clicking "Save reading progress" button to save my progress.  the "checks" will appear next time the window is opened again.

> Is it possible to also define other Bible reading plans? Like one for reading the Bible in 2 years? Or only reading from one book per day?

for version 1, I am using https://www.biblica.com/resources/reading-plans/

as the whole list is displayed, users can read faster or slower rather than a fixed year.

ideally, I want something like https://github.com/mskelton/bible-plan-generator, which can generate a plan by specifying a start and a end day.

**Comment by eliranwong** [comment]
I will rename the "Uncheck all items" button to "Reset all items"

**Comment by eliranwong** [comment]
Uploaded in https://github.com/eliranwong/UniqueBible/commit/36df9ce221bbc6f5152d045f23eed737e90d8b89

@otseng  feel free to further improve it.

**Comment by eliranwong** [comment]
made available to users from version 23.39

A wiki page is written about this plugin https://github.com/eliranwong/UniqueBible/wiki/Bible-Reading-Plan
