### ISSUE TITLE
import usfm format

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#329]
I hope UBA will support importing usfm format one day.

https://ubsicap.github.io/usfm/

**Comment by otseng** [comment]
Looking at that format, it's quite complicated.  It might be easier to use a tool that can convert a USFM file into OSIS, such as:
https://github.com/chrislit/usfm2osis

**Comment by otseng** [comment]
Or add support for USFX and convert the USFM to USFX.

https://ebible.org/usfx/
https://ebible.org/WordSend/

**Comment by eliranwong** [comment]
I think the workaround mentioned above is good enough.  Thanks.
