### ISSUE TITLE
Research ability to directly download and install modules from Github repo

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#332]
After repo is created of [public domain Bibles](https://github.com/eliranwong/UniqueBible/issues/331), research if there's a way to access the files directly from UBA.  This will also be useful for books and commentaries in other Github repos.

**Comment by otseng** [comment]
For this to work, need to generate a personal access token here:
https://github.com/settings/tokens

Click generate token.
Enter "UBA" for note.
Check the public_repo Access public repositories

Copy the token value into the githubAccessToken in config.py

**Comment by otseng** [comment]
https://github.com/eliranwong/UniqueBible/wiki/Github-access-token

**Comment by otseng** [comment]
Created new branch to work further on this:

https://github.com/eliranwong/UniqueBible/tree/github-downloader

**Comment by otseng** [comment]
> bty, I see you added code to install PyGithub in checkup.py, current code in checkup.py already install pygithub automatically for users, as it is required by gist.

Since gist is optional, is it possible it won't be installed?

> I may probably work further from your codes, as I prefer not to ask users to register a token if possible.

I originally generated a token and made it a default value, but Github detected it in the code and automatically disabled the token.  Let me see if I can stop that.

**Comment by otseng** [comment]
Added code to stop the auto token detection.

**Comment by eliranwong** [comment]
> Since gist is optional, is it possible it won't be installed?

with regards to gist, I suggest you may consider placing it in plugin instead.  so that package will only be installed when users run the plugin.  for example, I moved this one to plugin, https://github.com/eliranwong/UniqueBible/blob/master/plugins/context/Chinese%20PinYin.py

**Comment by eliranwong** [comment]
> Created new branch to work further on this:
> 
> https://github.com/eliranwong/UniqueBible/tree/github-downloader

Great! I will take a look into it.

**Comment by eliranwong** [comment]
> Added a default token and also added code to try to stop the auto token detection.

does it mean users do not need to generate a token themselves?

**Comment by otseng** [comment]
> > Added a default token and also added code to try to stop the auto token detection.
> 
> does it mean users do not need to generate a token themselves?

Correct.
