### ISSUE TITLE
Hovering on bible references in bible notes does not work

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#34]
An issue reported by a user and confirmed:

Hovering on bible references in bible notes does not work.

Clarification: Currently, only clicking on those links changes the main window, but hovering over them does nothing.  It would be nice if hovering on those links shows bible text on instant window at the bottom.

<img width="960" alt="bible_notes_display_mode_hovering_not_working" src="https://user-images.githubusercontent.com/25262722/103438432-fa809400-4c2a-11eb-8ad7-1a0b5e0d52da.png">

**Comment by onegladiator4u** [comment]
Hi brother,
Noticed that the title reference In Bible (Paragraph heading) also don't show full verse.
![image](https://user-images.githubusercontent.com/48617390/104090661-41f7c780-529e-11eb-87bf-3004dde0b024.png)

**Comment by eliranwong** [comment]
Noted with thanks.

**Comment by eliranwong** [comment]
@onegladiator4u  I took a look at the issue.  This was due to some materials were parsed by an old parser.  We already updated the parser some times ago to correct the problem.  I think I will update the subheading database.  For other resources, unless materials are parsed once or they remains the same. 

I created a simple plugin as a workaround though,

Extract the zip file here and place in folder "plugins_context", select references and right-click, choose "Extract references to Bottom Window"

[Extract Verses to Bottom Window.zip](https://github.com/eliranwong/UniqueBible/files/6097282/Extract.Verses.to.Bottom.Window.zip)

**Comment by onegladiator4u** [comment]
@eliranwong got this after clicking on 

> "Extract references to Bottom Window"

![image](https://user-images.githubusercontent.com/48617390/110244681-df613600-7f85-11eb-8bc6-c817ea8b3aa3.png)

**Comment by eliranwong** [comment]
this issue was fixed already, please use the latest version to apply the fix.

**Comment by eliranwong** [comment]
@onegladiator4u  the latest version is 22.39, if you also see "Speak Hebrew" and "Speak Greek" on the context menu, then you should be about to run the file I attached above.

**Comment by onegladiator4u** [comment]
> this issue was fixed already, please use the latest version to apply the fix.

Oh ok. Thanks

**Comment by eliranwong** [comment]
@onegladiator4u I added two startup plugins in version 22.45.  All issues mentioned in this post should be fixed.

Please update to version 22.45 and help check if it works for you.  Thanks.

**Comment by onegladiator4u** [comment]
Yes it's working bro.
Thank you.
