### ISSUE TITLE
Clearing tabs

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#341]
Would it be possible to have either a right-click or a button allowing bible and study tabs to be cleared? This would be handy so when doing a study the tabs would be populated with bibles and/or study modules relating to the study, currently I don't see a way to do that. Thanks!

**Comment by eliranwong** [comment]
To be "cleared" and to be "populated" appears to be opposite.  Therefore, I may not fully understand your request.

**Comment by darrelwright** [comment]
Oh sorry - I like the tabs being populated as they are now, but would 
like the ability to clear them before starting a study so the tabs then 
refill with the contents of my current study. Make sense?

**Comment by eliranwong** [comment]
I am afraid I still not understand.

You can simply disable populate feature

or every new command will overwrite current content, it is not necessary to clear

**Comment by eliranwong** [comment]
can you give an example?

**Comment by otseng** [comment]
I think I understand.  I'll work on this.

**Comment by eliranwong** [comment]
thanks @otseng I leave it to you.

**Comment by darrelwright** [comment]
Hey I just want to say to all of you - I really like where UBA is going! 
It's like everything I have thought about or requested you have done! 
Even including the Bible reading plan! UBA is my go-to Bible app. Thank you!

Darrel

**Comment by darrelwright** [comment]
My intent with this request is to have all tabs focused on my current 
study and not have mixed tabs. So if I am studying a clean heart  want 
to be able to jump around the tabs and have everything focused on the 
current study. Does that make sense?

Darrel

**Comment by darrelwright** [comment]
That is what I wanted! Thanks so much

**Comment by darrelwright** [comment]
I tried posting this in the discussion area, but couldn't figure how to 
post a question so here it is. I thought we had a wiki page discussing 
regex. I like the UBA commands, but I want more information on using 
regex, in particular the functions that work in UBA. Thanks

Darrel

**Comment by otseng** [comment]
> I tried posting this in the discussion area, but couldn't figure how to post a question so here it is. I thought we had a wiki page discussing regex. I like the UBA commands, but I want more information on using regex, in particular the functions that work in UBA. Thanks Darrel

https://github.com/eliranwong/UniqueBible/discussions/351
