### ISSUE TITLE
Issue with Interlinear data plugin

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#348]
The plugin requires openpyxl to be installed via pip3. I did that, restarted UBA, ran the plugin again and it still says that openpyxl is required. Am I missing something?

**Comment by eliranwong** [comment]
@darrelwright   please try run in your terminal and let me know if any error messages on your side:

[this first line depends on where you install UBA]

> cd UniqueBible

> source venv/bin/activate

> pip3 install openpyxl

**Comment by eliranwong** [comment]
fixed in https://github.com/eliranwong/UniqueBible/commit/db6c6b0036366f44917f8163ecc54409e890ff14

**Comment by darrelwright** [comment]
Results of installing openpyxl followed by trying to open uba. It is missing gui.EnableIndividualPlugins

![venv](https://user-images.githubusercontent.com/11500764/113765843-a4136d80-96d1-11eb-8068-1857a38862bc.png)
![runing](https://user-images.githubusercontent.com/11500764/113765881-ad9cd580-96d1-11eb-98d2-c04ce1b19bb0.png)

**Comment by darrelwright** [comment]
I am on python 3.8.5

**Comment by darrelwright** [comment]
Please check my response. I am now dead in the water with missing 
gui.EnableIndividualPlugins

**Comment by darrelwright** [comment]
I rebuilt UBA from an earlier version, applied the updates to 23.53 and am now working again. Not sure why the first update crashed things but all is good now.

**Comment by eliranwong** [comment]
> I rebuilt UBA from an earlier version, applied the updates to 23.53 and am now working again. Not sure why the first update crashed things but all is good now.

sorry for the trouble, the crash was due to my mistake in updating the patch file in version 23.51-52.  It is fixed in version 23.53

**Comment by darrelwright** [comment]
I like the features you are adding

**Comment by darrelwright** [comment]
The only problem I still have - I select Acts 17:28, then right-click, 
select plugin and select Interlinear data. Now at this point it should 
open to Acts 17:28 (if I understand correctly) but it opens with John 
3:16, forcing to have to reenter Acts 17:28 in the reference window.

**Comment by eliranwong** [comment]
if u encounter issue with parsing, please read standard parsing instead of fast verse parsing.

read https://github.com/eliranwong/UniqueBible/wiki/Verse-parsing#remarks

**Comment by darrelwright** [comment]
I use standard now for greater versatility 😊

________________________________
