### ISSUE TITLE
Toolbar icons size

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#349]
Standard toolbar size looked small.

![image](https://user-images.githubusercontent.com/48617390/113739818-c8953700-971d-11eb-91ef-4748458f16a3.png)
When tried Full size it's too big. Most icons not visible on both sides.

![image](https://user-images.githubusercontent.com/48617390/113739584-908df400-971d-11eb-91b3-47f3b82745a7.png)
Is there a way to correct it's size? I couldn't find it's css functions.
My desktop resolution is 1366x768.

**Comment by eliranwong** [comment]
@onegladiator4u 

It is easier and more consistent to control the icon size in Focus menu layout.

try the following, if this works for you, I can make the settings configurable in next update:

1) Open gui/FocusMainWindow.py with a text editor

Find at the end of the file:

        if config.qtMaterial and config.qtMaterialTheme:
            for toolbar in (self.firstToolBar, self.studyBibleToolBar, self.secondToolBar):
                toolbar.setIconSize(QSize(config.iconButtonWidth / 1.33, config.iconButtonWidth / 1.33))
                toolbar.setFixedHeight(config.iconButtonWidth + 4)
            for toolbar in (self.leftToolBar, self.rightToolBar):
                toolbar.setIconSize(QSize(config.iconButtonWidth * 0.6, config.iconButtonWidth * 0.6))

change the value of 1.33 and 0.6 and restart UBA and see, try to find the right size you like most.

**Comment by eliranwong** [comment]
@onegladiator4u 

Please try update to ver 23.55

Edit the values of toolbarIconSizeFactor and sidebarIconSizeFactor in config.py

Remarks: close UBA first when you edit the file config.py

Major changes in version 23.55:
* Added two config values in config.py, with which users can adjust the icon size when Qt-material theme is enabled.
    1 is original full size; the smaller the values the smaller the icon sizes.
    toolbarIconSizeFactor [default: 0.75], sidebarIconSizeFactor [default: 0.6]

**Comment by onegladiator4u** [comment]
Bro this changed icon size but that didn't affect layout. It has margins or something.
![Untitled](https://user-images.githubusercontent.com/48617390/113824418-63812600-979d-11eb-87d1-d10c03947c85.png)

**Comment by eliranwong** [comment]
I don't know how to change individual margin without affecting other elements.

**Comment by onegladiator4u** [comment]
Oh, it's OK then. Thanks for trying.

**Comment by eliranwong** [comment]
I use standard icon size option when I use Qt-material theme.  Full size icons with Qt-material theme are too big for me too.

**Comment by onegladiator4u** [comment]
I'm going to use the standard size option too then.
