### ISSUE TITLE
Problem with English word form search

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#356]
I have the BSB as my current Bible on Psa 51:10. I right-click on "heart", select Plugins and "Search all English forms". I get error message. I close UBA, run "pip3 install -U word_forms, restart UBA and get the same message.

![english forms](https://user-images.githubusercontent.com/11500764/114118677-0de07280-989e-11eb-8b1b-986f75237eb9.png)

**Comment by darrelwright** [comment]
Any movement yet?

**Comment by eliranwong** [comment]
@darrelwright 

try:

1) close UBA

2) open terminal and run:

> cd UniqueBible [depends where you install UBA]

> source venv/bin/activate

> pip3 install -U word_forms

and check if any errors.  thanks.

**Comment by darrelwright** [comment]
Nope. Here's the screen shots:

![venu](https://user-images.githubusercontent.com/11500764/114138085-f61ae580-98c1-11eb-971b-0f66e954a46a.png)
![venu2](https://user-images.githubusercontent.com/11500764/114138105-fc10c680-98c1-11eb-98fc-e50c80172296.png)

**Comment by darrelwright** [comment]
when running UBA from command prompt it throws a comment, "Instralling '-U word_forms' ... followed by the last screen shot about the plugin not being enabled.

**Comment by eliranwong** [comment]
How do you start UBA?

also try from terminal:

> cd UniqueBible [depends where you install UBA]

> source venv/bin/activate

> python3

> from word_forms.word_forms import get_word_forms

> print(get_word_forms("test"))

**Comment by darrelwright** [comment]
![venu3](https://user-images.githubusercontent.com/11500764/114140922-bfdf6500-98c5-11eb-849b-b33a3a2a03a1.png)

**Comment by eliranwong** [comment]
how do you start UBA?  can you use other plugins, e.g. Interlinear Data, exporting data to spreadsheet?

please also try from terminal:

> cd UniqueBible [depends where you install UBA]

> python3 uba.py

run the same plugin again.  please check if errors appear on terminal.

thanks.

**Comment by darrelwright** [comment]
those were the last screen shots I sent you. I can run Interlinear Data and export to a spreadsheet perfectly. When running from command prompt I get the last screenshot where it is trying to install -U word_forms...

**Comment by eliranwong** [comment]
> those were the last screen shots I sent you. I can run Interlinear Data and export to a spreadsheet perfectly. When running from command prompt I get the last screenshot where it is trying to install -U word_forms...

does any error message comes up on "terminal" (not UBA) when you see the message dialog "Your plugin not enabled ..."

**Comment by eliranwong** [comment]
please also try to use a simple text editor to open this file below:

plugins/context/Search ALL English Forms.py

try deleting lines from line 15 to line 19, save the file, restart UBA and try again the plugin

![Screenshot 2021-04-09 8 05 53 AM](https://user-images.githubusercontent.com/25262722/114142144-72d1b200-990a-11eb-8350-2b1c109b700a.png)

**Comment by darrelwright** [comment]
same message
![venu4](https://user-images.githubusercontent.com/11500764/114142785-34b39e80-98c8-11eb-825d-fd6c15b9c22d.png)

**Comment by eliranwong** [comment]
does any error message comes up on "terminal" (not UBA) when you see the message dialog "Your plugin not enabled ..."???

**Comment by darrelwright** [comment]
only the "installing '-U word_forms' ..." and nothing else. And as I have been saying this is from the terminal and not UBA

**Comment by eliranwong** [comment]
if you have "developer" set to True in config.py  <<<  can you set this option first, and restart UBA?

there may be some error messages displayed on your terminal.

**Comment by darrelwright** [comment]
This only started the last couple of releases. I have successfully used the search previously. Okay with developer set on here is the error:

![venu6](https://user-images.githubusercontent.com/11500764/114143442-04b8cb00-98c9-11eb-95bf-c9eeb27a47ab.png)

**Comment by eliranwong** [comment]
it is a bit strange that other plugins work for you (e
g. exporting interlinear data uses third-party package in the same way as this plugin), but not this one.  I haven't figured out why yet.

**Comment by darrelwright** [comment]
Here is exporting interlinear data: 

![venu7](https://user-images.githubusercontent.com/11500764/114144348-16e73900-98ca-11eb-8026-c0b78a0b6cb7.png)

**Comment by eliranwong** [comment]
how do you run UBA?  python3 uba.py?

can you run plugin "webster"?

**Comment by darrelwright** [comment]
it required me to run "pip3 install lemmagen3". I did that, then restarted UBA, and got the message "This plugin is not enabled

![venu8](https://user-images.githubusercontent.com/11500764/114150568-0edec780-98d1-11eb-9b1b-897ec8311653.png)

**Comment by darrelwright** [comment]
![venu9](https://user-images.githubusercontent.com/11500764/114150710-346bd100-98d1-11eb-9680-85220e4ccae3.png)

**Comment by darrelwright** [comment]
Is there anything else I can do?

**Comment by eliranwong** [comment]
it appears that the import statement was not run successfully.  The package had been installed, but it was not imported.  I don't know why this happens on your device.  I tested on various devices, without having an issue.

**Comment by darrelwright** [comment]
So what can I do to fix that?

**Comment by darrelwright** [comment]
Do I need to reinstall fresh?

**Comment by eliranwong** [comment]
please try below

**Comment by darrelwright** [comment]
Not sure what you mean?

**Comment by darrelwright** [comment]
When you said "please try below", what did you mean?

**Comment by eliranwong** [comment]
> When you said "please try below", what did you mean?

changed the line 3213 and 3218 in gui/MainWindow.py as below:

![Screenshot 2021-04-09 9 42 04 AM](https://user-images.githubusercontent.com/25262722/114154079-ed54fe80-9917-11eb-98cc-92fe7928ba9b.png)

**Comment by darrelwright** [comment]
well this is frustrating. I made both those changes, then first ran English forms, then webster

![venu11](https://user-images.githubusercontent.com/11500764/114155317-33896e00-98d6-11eb-9272-d67372d1565d.png)

**Comment by eliranwong** [comment]
reason not know yet.  you may try run:

python3 main.py to start UBA and see if any difference

**Comment by darrelwright** [comment]
That had even more issues. What I did that worked was to reinstall UBA completely, then ran both 'Search All English forms' and 'Webster' and both ran successfully. So it looks like when I previously did a rebuild (and not reinstall) that something got corrupted! I've got to move a few folders from the old install to the new one and I should be good-to-go. Interesting learning curve stuff huh? Thanks for working with me!

**Comment by eliranwong** [comment]
okay.  I am glad that you sorted out the issue.

**Comment by darrelwright** [comment]
Yes, this is good. I do not know what happened before (I chalk it up to our experimenting...), but I have everything copied across and everything appears to work. Yea!

**Comment by eliranwong** [comment]
plugin is a powerful feature in UBA.  you can actually do a lot of things, at least practically you can set keyboard shortcut to frequently used features.

another example, you can change website one to lookup dictionary in multiple modules.  can discuss more in discussion area
