### ISSUE TITLE
PySide2 in anaconda not detected; opened for @Franstv99

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#357]
@Franstv99  we may discuss the issue you encountered here.

**Comment by Franstv99** [comment]
I delete my UniqueBible directory and restart a new installation (I did it three times with same error)

With Powershell (non admin):

cd \religion\bibles
git clone https://github.com/eliranwong/UniqueBible
python .\UniqueBible\uba.py

uba.py starts and displays : 

PS J:\religion\bibles> UniqueBible\uba.py
PS J:\religion\bibles> Installing missing module 'PySide2' ...
PySide2 is not found!  Trying to install 'PyQt5' instead ...
Installing missing module 'PyQt5' ...
Required feature 'Qt Graphical Interface Library' is not enabled.
Install either 'PySide2' or 'PyQt5' first!

here a blinking cursor but nothing happens

**Comment by eliranwong** [comment]
May I ask how did you install python?  Did you follow our instructions about installation of python or other means.  I remember you mentioned anaconda in another post.  Can you let us know more about the setup?

**Comment by otseng** [comment]
UBA has not been tested with anaconda.  UBA is developed and tested only with python.

**Comment by otseng** [comment]
Updated FAQ to say UBA does not support anaconda.

https://github.com/eliranwong/UniqueBible/wiki/FAQ#does-uba-run-in-anaconda

**Comment by eliranwong** [comment]
@otseng  I think it is not totally right to say that UBA does not support Anaconda.  I used anaconda to run UBA in my previous devices.  We had notes about installing python packages with conda command but I removed them sometimes ago.  We just to put back those notes for anaconda users.
