### ISSUE TITLE
Backup file suggestion 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#358]
Guys, will you consider adding files like custom CSS and title files that linked to a bible to backup list with notes ?

**Comment by eliranwong** [comment]
Hi @onegladiator4u I may not fully understand.  What especially mean "...to backup list with notes "?

**Comment by onegladiator4u** [comment]
Oh sorry. We now have option to backup notes to gdrive. I was thinking maybe adding custom CSS and custom titles if you have like `bibles_ml.sqlite` in that.

**Comment by eliranwong** [comment]
I see.  I will take a look into it.

**Comment by onegladiator4u** [comment]
Ok. Thanks

**Comment by otseng** [comment]
I'll work on this.  Besides css and sqlite files, anything else you want to backup?

**Comment by onegladiator4u** [comment]
Thanks for the the option bro. Can i delete other plugins named 
Google Drive Notes Backup
Google Drive Notes Backup_Ctrl+Shift+K
Google Drive Notes Restore
Google Drive Notes Restore_Ctrl+Shift+R
Backup Notes to G-Drive(in plugins folder)
Restore Notes fr G-Drive(in plugins folder) ?

**Comment by otseng** [comment]
Yes, you can delete the old one.  I'll delete it from the code also.
