### ISSUE TITLE
Load PDF files

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#361]
I am trying to open a PDF in Notes and it does not appear to load. Am I doing something wrong? I open Notes, set it for pdf, it acts like it loads but nothing is displayed.

[Gods_plan_for_the_ages.pdf](https://github.com/eliranwong/UniqueBible/files/6291059/Gods_plan_for_the_ages.pdf)

**Comment by otseng** [comment]
I think notes can only display the text in pdf files.  Your pdf file has no text in it.

**Comment by darrelwright** [comment]
Thanks Oliver, but is there any way to display and/or open PDF files?

**Comment by otseng** [comment]
@eliranwong what are your thoughts on adding full pdf support, instead of just loading the text?

**Comment by darrelwright** [comment]
anything happening yet? Just curious

**Comment by otseng** [comment]
I'll see if I can add full pdf support.

**Comment by otseng** [comment]
I was originally thinking of writing this as a plugin, but now I'm thinking of making it a feature of UBA.  The ability to read pdf files opens the door to build a collection of pdf docs, just like we have for books and commentaries.  This collection of pdf files would be in the pdf directory.   Would create a Github repo of pdf files and ability to download them.  Another tab would be added to the master control to be able to read the pdf files in the pdf directory.

**Comment by darrelwright** [comment]
Oliver, that would be awesome. It provides what I feel is a necessary 
enhancement!

**Comment by eliranwong** [comment]
> I was originally thinking of writing this as a plugin, but now I'm thinking of making it a feature of UBA. The ability to read pdf files opens the door to build a collection of pdf docs, just like we have for books and commentaries. This collection of pdf files would be in the pdf directory. Would create a Github repo of pdf files and ability to download them. Another tab would be added to the master control to be able to read the pdf files in the pdf directory.

Thanks for working on it.  That would be perfect if pdf is searchable in UBA.

**Comment by darrelwright** [comment]
Oh! I'm gonna start salivating!!!

**Comment by darrelwright** [comment]
And prayerfully that there is not a size limit on the PDF?

**Comment by otseng** [comment]
@eliranwong I created a branch for you to test out before merging:
https://github.com/eliranwong/UniqueBible/tree/pdf-merge

I used the pdf.js library to view pdf files:
http://mozilla.github.io/pdf.js/

It works quite well and has several nice features.  It's also fast and from what I can tell there is no limit to the size of the file it can open.  I tested with it with a PDF that has 1080 pages and it works.

But, the only drawback to it is it doesn't have dark mode support.  I added a request here:
https://github.com/mozilla/pdf.js/issues/2071#issuecomment-821938295

I commented out line 47 in CentralWidget.py.  Not sure what that line does, but if it's there, it opens an extra tab when viewing a pdf file.

You can download pdf files from the menu (Github PDF) which will pull it from:
https://github.com/otseng/UniqueBible_PDF

**Comment by eliranwong** [comment]
> line 47 in CentralWidget.py

thanks.  I will test.  btw, line 47 in CentralWidget is useful ... I will check.

**Comment by eliranwong** [comment]
the pdf feature is awesome, more than I expected.  thanks very much for adding this ...

does mozilla has something for epub like the pdf ?

**Comment by otseng** [comment]
I'll also try adding epub support.

**Comment by darrelwright** [comment]
You guys are awesome! I look forward to working with this feature!

**Comment by darrelwright** [comment]
I really like what you have done with pdf files. And yes, it appears to work very well with large files.  I would like the ability to open the pdf file in a separate window like I can do with book modules. Can that be added?

**Comment by eliranwong** [comment]
opening in separate window doesn't have the same right-click context menu as with Study Window

**Comment by darrelwright** [comment]
Just thought I'd do an update on this post. I have 77 pdf files and 485 
book files. When I search all of them (for example "exegesis") the 
search is extremely fast! Some of those pdf files are very large, over 
1,000 pages; some it appears to pass over since the contents are an 
image. But it's like "wow!" I am impressed.

Darrel
