### ISSUE TITLE
TypeError "NoneType" object is not utterable

### ISSUE THREAD

**Issue by fillgun** [eliranwong/UniqueBible#362]
I don't know why I am getting this error all of a sudden. ㅠ.ㅠ

<img width="582" alt="KakaoTalk_Photo_2021-04-12-15-53-30" src="https://user-images.githubusercontent.com/7662970/114353053-8c435a00-9ba7-11eb-82a7-72bd0c3a8651.png">
<img width="684" alt="KakaoTalk_Photo_2021-04-12-15-53-34" src="https://user-images.githubusercontent.com/7662970/114353096-97968580-9ba7-11eb-9577-b298d947367f.png">

**Comment by otseng** [comment]
Did you delete a Bible from the marvelData/bibles folder?

**Comment by fillgun** [comment]
No. I haven't deleted marvelData/bibles folder.

**Comment by otseng** [comment]
Can try renaming config.py to config.py.bak, then restart UBA.

**Comment by fillgun** [comment]
Thank you ^^
UBA working now 

let me know what was the problem?

**Comment by otseng** [comment]
My guess is you had deleted/moved a Bible file.  UBA was trying to load it on startup.  Since it was no longer there, it caused the error.
