### ISSUE TITLE
How to hook into Louw-Nida Lexicon

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#366]
The LN has a website at that allows searching for a gloss i.e., http://www.laparola.net/greco/louwnida.php?LNGloss=faith where I am searching for "faith". It would be really cool to have a search link in Master Control allowing a word to be entered and then opening that website to search.

**Comment by eliranwong** [comment]
this would be easy to do with a plugin.  no need to do with master control

I also don't know if this website has permission from copyright holder of LN dict

**Comment by darrelwright** [comment]
how can we check the permission? The website does really good at 
providing LN information.

**Comment by eliranwong** [comment]
the website owner and the copyright holder should know.

**Comment by darrelwright** [comment]
I have tried, but everything is in Spanish.

**Comment by frank4532** [comment]
You can view the site in English http://www.laparola.net/english.html and you can write in English to Richard Wilson (he is Australian and Italian) http://www.laparola.net/richard/ .
you can write to him in English at this email address E-mail: info @ lаparola . net

**Comment by darrelwright** [comment]
Hey thanks Eliran,

I will do that. By the way I have built a plugin that hooks into the 
website and works pretty well. I don't advertise it since I want to 
honor and respect your stand on (potentially) copyright issues.

Darrel

**Comment by otseng** [comment]
```
-------- Forwarded Message --------
Subject:	R: Website question
Date:	Mon, 21 Jun 2021 10:06:43 +0200
From:	Richard Wilson <richard@laparola.net>
Reply-To:	richard@laparola.net

Yes, you can use my site in the app, or in any other way you like.

Richard Wilson
richard@laparola.net
```

**Comment by otseng** [comment]
Thanks @darrelwright for the code!
