### ISSUE TITLE
Feature Suggestions 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#37]
Hello brother,
Do you have plan to add a feature to highlight verses with different colors and underlining?
It would be nice.

- [ ] highlighting / underline
- [ ] bookmark

**Comment by eliranwong** [comment]
These are possible.  but I am currently working on another version of UniqueBible.app at:
https://github.com/eliranwong/UniqueBibleAppHybrid
I may do it after the hybrid version take shape, but no guarantee.

I also welcome others to add highlighting / book feature to this project.  In case someone can do it, please kindly send me a PR.  I will surely merge it.  Thanks.

**Comment by onegladiator4u** [comment]
Hybrid looks great. When can we expect this?

**Comment by eliranwong** [comment]
> Hybrid looks great. When can we expect this?

I am still playing search feature.  I think the final product will be a little bit better than the current desktop version in terns of searching bible.

I may create some testing files for current UBA users to test.

![Screenshot_20210104-075318](https://user-images.githubusercontent.com/25262722/103543370-4edb7c00-4e96-11eb-9571-bfe753dfd208.png)

![Screenshot_20210104-083403](https://user-images.githubusercontent.com/25262722/103543511-8c400980-4e96-11eb-8019-be38c95e697f.png)

**Comment by onegladiator4u** [comment]
Awesome. Love to try when available.

**Comment by eliranwong** [comment]
> Awesome. Love to try when available.

Please read https://github.com/eliranwong/UniqueBibleAppHybrid/issues/1
