### ISSUE TITLE
update UniqueBibleApp_FeatureList.docx

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#373]
@darrelwright I remember you wrote the following file some times ago.  can you update this file?

https://github.com/eliranwong/UniqueBible/blob/master/UniqueBibleApp_FeatureList.docx

**Comment by darrelwright** [comment]
Okay, I'm working on it now. It will take a couple of days. I need to 
list a whole lot of new and/or updated features, but it is coming 😁

**Comment by eliranwong** [comment]
thanks, please don't miss plugins.  how plugins work changes UBA significantly.

you may simple direct users to this link about plugin https://github.com/eliranwong/UniqueBible/wiki/UBA-Plugins

**Comment by otseng** [comment]
@darrelwright It might be too slow to keep updating the Word doc since UBA is practically changing everyday.  Would you be willing to help keep the wiki up-to-date instead?

**Comment by otseng** [comment]
I spoke with Darrel.  He agreed to delete this file.
