### ISSUE TITLE
Search display

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#380]
You had mentioned about adding a search results chart in the hybrid version. I really like that concept! Any chance of this coming into UBA?

**Comment by eliranwong** [comment]
I think it us not difficult to do, but not urgent.

When I have spare time, I will probably add it as a plugin. 

A bar chart / pie chart displays distribution of bible references in different books.

This feature is not limited to search result.

What I am thinking is a context plugin.
When users select texts having bible references, a chart will be generated based on selection.
If users trigger the plugin without text slection, a chart will be generated based on all bible references displayed in the whole page.

Therefore, I should work with serach result as welle as other features, e.g. topical dictionary entry, cross-references, etc.

I haven't seen any other bible softwares doing this.  so, it is another unique feature.

also, I haven't come up with a good name to describe this feature.

**Comment by eliranwong** [comment]
this screenshot is an example, a pie chart generated from cross-references of Genesis 1:1

![Screenshot 2021-04-21 5 46 45 PM](https://user-images.githubusercontent.com/25262722/115591163-b85a8b80-a2c9-11eb-9c95-7e955fb2e30a.png)

**Comment by eliranwong** [comment]
Here is an example, These are minimum effort to generate a pie chart and a bar chart from cross-references of Genesis 1:1

![Screenshot 2021-04-21 6 07 19 PM](https://user-images.githubusercontent.com/25262722/115593636-a7f7e000-a2cc-11eb-9153-98992d82f3e3.png)

**Comment by eliranwong** [comment]
a wiki page: https://github.com/eliranwong/UniqueBible/wiki/Charts

**Comment by eliranwong** [comment]
ver 23.78; https://github.com/eliranwong/UniqueBible/commit/5f417b585d428ed664d3e4cf2f837f86c881b6b4

**Comment by darrelwright** [comment]
I really appreciate what you have done with charts. I kind of hate 
asking, but I'd like to see two enhancements.

1. The ability to select either pie, bar or both charts

2. The ability to click on a segment and have those verses displayed on 
the bible window. That would really be awesome!

**Comment by eliranwong** [comment]
> I really appreciate what you have done with charts. I kind of hate asking, but I'd like to see two enhancements. 1. The ability to select either pie, bar or both charts 2. The ability to click on a segment and have those verses displayed on the bible window. That would really be awesome!

regarding your 1st request, you can easily do it yourself, follow these steps:

1) in folder plugins/context/, make 2 more copies of "Charts.py", e.g. "Pie Chart.py" & "Bar Chart.py" (choose filenames whatever you like)

2) Open the files with a text editor and locate the following lines.

![Screenshot 2021-04-22 7 54 24 AM](https://user-images.githubusercontent.com/25262722/115669749-85071380-a340-11eb-8b84-d8f389b786fc.png)

3) In "Pie Chart.py", delete lines 16-22 and save.

4) In "Bar Chart.py", delete lines 23-29 and save.

With these steps, you will have 3 plugins, one to generate both charts, one to generate pie chart only and one to generate bar chart only.

regarding your 1st request, the charts are generated with a script provided by Google, which I don't want to edit it.  However, I can write a separate context plugin to list references sorted by books, so you can click and open selected verses.  What do you think?

**Comment by darrelwright** [comment]
I did the modifications on first request and that works perfectly!

**Comment by eliranwong** [comment]
added a table to the plugin https://github.com/eliranwong/UniqueBible/commit/7becd4222c0c71faff931c438b257f6cbfbba202
