### ISSUE TITLE
improving speed of loading books / notes containing images

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#387]
@darrelwright I remember you mentioned loading issues of book / note when they contain images, right?

I think I may figure out why.  if you have an example, we may try to fix and test it.

**Comment by eliranwong** [comment]
added a single line, but the speed has a huge difference.

https://github.com/eliranwong/UniqueBible/commit/bd0f211703e3c7cf3cfdd49937dbfcc76882ee0e

**Comment by darrelwright** [comment]
Is there a need/difference for the multiple word document plugins?
