### ISSUE TITLE
Compare view issue

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#39]
Hey brother,
I don't know whether it's a bug. When I click on verse number in compare view it's going to normal one Bible version view. Did you mean to make it that way?
Problem is when I want a commentary on one verse, I would click the verse. That's when the compare view disappears.
![image](https://user-images.githubusercontent.com/48617390/103859761-9b19fc80-50e0-11eb-83bc-7637c3515cf4.png)
If I click **verse 12** the view will be
![image](https://user-images.githubusercontent.com/48617390/103859889-d4526c80-50e0-11eb-968c-b2a3fa39a68b.png)

**Comment by eliranwong** [comment]
It is not a bug, but needs improvement.

When you click a link, the apps runs "Bible:::" command instead of "COMPARE:::".

I think I will add something, so that the app will keep the COMPARE::: one for convenience.

**Comment by onegladiator4u** [comment]
Oh ok. Thanks.

**Comment by eliranwong** [comment]
This issue was closed by the original author.  I re-open this issue to remind myself to do something about it in the future.

**Comment by eliranwong** [comment]
@onegladiator4u version 21.02 addressed on of issues you mentioned.  You may read the changes.

Next update will address this issue.  I will try to keep compare / parallel view if users last command is compare or parallel.

**Comment by eliranwong** [comment]
You may read the changes at https://github.com/eliranwong/UniqueBible/commit/b6b44ee6a8def543f734daca50d992bbd1d99e45

I will close this issue soon.
