### ISSUE TITLE
Fix display of second Strongs

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#390]
In the simple view, if there are two Strongs numbers together, the second one is not displaying correctly.  

<img width="663" alt="Screen Shot 2021-04-23 at 4 45 29 AM" src="https://user-images.githubusercontent.com/806056/115845522-f1405080-a3ee-11eb-99e6-f216d949876d.png">

**Comment by eliranwong** [comment]
thanks for the fix @otseng
