### ISSUE TITLE
crash on 23.90

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#392]

**Comment by darrelwright** [comment]
I upgraded to 23.90, restarted and crashed. Have not been able to recover. Need help ASAP

![Error](https://user-images.githubusercontent.com/11500764/115859615-49725500-a3e5-11eb-8575-7c0c14c4a3e4.png)

**Comment by eliranwong** [comment]
strange, it looks like not related to the update.  @otseng do you have an issue with the latest code?

**Comment by darrelwright** [comment]
I rebuilt from a fresh download and the update went okay. When the 
problem occurred all I did was an update and it crashed.

**Comment by eliranwong** [comment]
I tried two different devices for update and found no issue.  I am glad that it finally works for you.  If you want you may use git pull to update instead, which is much easier.  You may ask @otseng about it.

**Comment by darrelwright** [comment]
That's what I am doing when it crashes. I then update all marvel data 
with mine and it usually brings me back. My concern is primarily for 
non-tech folks. I'm going back to bed. This flu stuff is really kicking 
my tail. Love ya my friend. Oh by the way I have made good progress on 
the write-up

**Comment by otseng** [comment]
I'd recommend using git to be able to go back to any version of the code.  It requires a little bit of setup, but once you have it setup, if broken code is checked in, you'll be able to go back to a working version.

More info at:
https://github.com/eliranwong/UniqueBible/wiki/Using-Git

**Comment by darrelwright** [comment]
Is there any way this can "automated" within UBA, so if a crash occurs 
and on trying to restart UBA it will automatically load the previous 
version?
