### ISSUE TITLE
Interlinear Data Request

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#396]
The Interlinear Data plugin works very will, but I'd like the menu version to open based on the current verse and not John 3:16. The context works great.

**Comment by eliranwong** [comment]
You can simply change the reference to a reference you like, for example Rm 5:8, in the search field and press ENTER

I don't see a need to create another plugin.  can you elaborate what effect you want to achieve?

**Comment by darrelwright** [comment]
Hi Eliran,

It was just a convenience and less keystrokes, not a big thing. I am 
curious why Interlinear Data exists in both menu plugins and context 
plugins? Unless I am missing something it seems redundant?

**Comment by eliranwong** [comment]
in my opinion, tying a single reference is much faster than scrolling through book / chapter / verse dropdown menu selection three times.

you can hide a plugin anytime with "Enable Individual Plugins" window
