### ISSUE TITLE
feature enhancement: regular expression

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#40]
Regular expression is now supported in mobile and hybrid version for searching bibles, but not in desktop version.

I think I will add support of regular expression to desktop version, in addition to AND combination, OR combination and custom SQL.

This may make searching words in order easier even custom SQL can do it as an alternative for now.

This issue is created to remind myself for doing that later.

**Comment by onegladiator4u** [comment]
Hey bro,
Wanted to share a suggestion. Don't know whether it's possible.
Is there a way to point bible a verse or range of verse to the app from other software like PowerPoint?
Like hyperlink. If you click a hyperlink on PowerPoint so that it takes it to UniqueBible app. May be we can generate that hyperlink  by right clicking a portion or particular verses and paste as hyperlink. Is it possible to add this to hybrid or this version?

**Comment by eliranwong** [comment]
hybrid version can do it.  It is already in the plan.  Selectable bible references from any places like, browers, office apps, can launch UBA Hybrid with specific passage.  I am thinking to do it in two ways:
1) select, share, and launch UBS Hybrid
2) via bubble overlay

**Comment by onegladiator4u** [comment]
That's great. All the best .

**Comment by onegladiator4u** [comment]
Hi brother,
Just wanted to share a suggestion.
When opening multiple commentaries the tab won't display the name of author. Like this
![image](https://user-images.githubusercontent.com/48617390/104898724-fdf07b00-599f-11eb-923a-4626130a1b52.png)
can you add names as tab names. Like Com:Barnes or Com:Gill.
I added Com: With it to make know us it's a commentary. If you can add different color or icons to tabs that would be nice too. Like one color for book and another for commentary.
What do you think ?

**Comment by eliranwong** [comment]
can you create a separate issue for things other than regular expression described in this issue?  thanks.

**Comment by onegladiator4u** [comment]
Oh sorry. Sure

**Comment by eliranwong** [comment]
available from version 21.36
