### ISSUE TITLE
Add ability to find a word on the current displayed page

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#420]
Implement:

https://doc-snapshots.qt.io/qtforpython-5.15/PySide2/QtWebEngineWidgets/QWebEnginePage.html#PySide2.QtWebEngineWidgets.PySide2.QtWebEngineWidgets.QWebEnginePage.findText

**Comment by eliranwong** [comment]
I play a bit: https://github.com/eliranwong/UniqueBible/commit/3b22dc3f678f5719bff95edf0af9e5e174742156

feel free to advance further or making something new.

**Comment by eliranwong** [comment]
improved a bit: https://github.com/eliranwong/UniqueBible/commit/3a7f13f2b601136f1ac9ff275ecba9e78917506d
