### ISSUE TITLE
suggestion: should we add scroll bar to remote control?

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#43]
should we add scroll bar to remote control?  If too many modules are installed.  Those at the bottom are not displayed like this screenshot.

<img width="574" alt="Screenshot 2021-01-11 015943" src="https://user-images.githubusercontent.com/25262722/104141942-1fa29e80-53b1-11eb-9721-18a79cb4cd80.png">

**Comment by otseng** [comment]
You have a lot of Bibles and commentaries!  

Yes, I'll add it.

**Comment by otseng** [comment]
I added tabs instead:
https://github.com/eliranwong/UniqueBible/pull/44

**Comment by onegladiator4u** [comment]
@otseng How about numbers 0 to 9 and : And - plus enter button?

**Comment by eliranwong** [comment]
> I added tabs instead:
> #44

Great! much appreciated.  will merge soon.

**Comment by eliranwong** [comment]
The new tabs looks very nice.  I can now see my lexicons on remote control.  Thank you.

**Comment by eliranwong** [comment]
> @otseng How about numbers 0 to 9 and : And - plus enter button?

I'm curious why do you need a enter button?  after you type, simply press enter can do.  press enter key after typing a command is faster than typing a command and then use mouse to press an enter button.

**Comment by otseng** [comment]
> @otseng How about numbers 0 to 9 and : And - plus enter button?

Added number buttons and also dictionaries tab:
https://github.com/eliranwong/UniqueBible/pull/45

**Comment by onegladiator4u** [comment]
@eliranwong Sorry for that. Don't take that as a suggestion. ✌I didn't think like a normal person would. I can't use keyboard. I use mouse for all. Even typing. That's why I thought like that.

**Comment by eliranwong** [comment]
> @eliranwong Sorry for that. Don't take that as a suggestion. ✌I didn't think like a normal person would. I can't use keyboard. I use mouse for all. Even typing. That's why I thought like that.

no problem at all.  I appreciate different ways to use the app.

**Comment by onegladiator4u** [comment]
Thank you.

**Comment by eliranwong** [comment]
I think this issue can be closed now.  Thanks to Oliver for new additions.
