### ISSUE TITLE
POR FAVOR AYUDA NO ME INICIA UniqueBible

### ISSUE THREAD

**Issue by Elvis75Cristiano** [eliranwong/UniqueBible#445]
Hola muy bunos dias DIOS LES BENDIGA MUCHO. Soy un hermano que aprecia mucho su trabajo estoy apasionado por la Biblia y me gusta mucho UniqueBible  pero la actualize a la version 24.32 y  no quiere iniciar. Instale de nuevo versiones anteriores pero siempre me pasa lo mismo cuando actualizo.  Este es el mensaje que me pone:         
                                                                                                                               
 C:\Users\PC>cd C:\Users\PC\Downloads\NO TOCAR UniqueBible\UniqueBible
C:\Users\PC\Downloads\NO TOCAR UniqueBible\UniqueBible>python .\main.py
Traceback (most recent call last):
  File "C:\Users\PC\Downloads\NO TOCAR UniqueBible\UniqueBible\main.py", line 26, in <module>
    ConfigUtil.setup()
  File "C:\Users\PC\Downloads\NO TOCAR UniqueBible\UniqueBible\util\ConfigUtil.py", line 38, in setup
    config.qtLibrary = os.environ["QT_API"]
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'QT_API'

**Comment by eliranwong** [comment]
Hello, thanks for your message, please run uba.py instead of main.py

C:\Users\PC\Downloads\NO TOCAR UniqueBible\UniqueBible>python .\uba.py

**Comment by Elvis75Cristiano** [comment]
Es un privilegio para mi tener la gracia y la bendicion de poder disfrutar de los materiales que usted esta preparando biblias, diccionarios, la uniquebible plus para android y especialmente UNIQUEBIBLE para escritorio. Esta haciendo un GRAN TRABAJO QUE DIOS LE BENDIGA MUCHO.  Oro por usted y su equipo para que Dios os bendiga con vida larga con salud y prosperidad a ustedes y a sus queridos. MUCHAS GRACIAS .

**Comment by eliranwong** [comment]
Thank you very much.  Let us know if any further issues.  I assume this issue is solved, so I closed this one now.  Thanks.

**Comment by Elvis75Cristiano** [comment]
DIOS LES BENDIGA. SI SEÑOR ESTA RESUELTO EL PROBLEMA. MUCHAS GRACIAS.
