### ISSUE TITLE
Add http-server mode

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#447]
Run UBA as a http-server by running:
```
python main.py http-server
```

**Comment by eliranwong** [comment]
@otseng 
errrors by running python uba.py http-server:
  File "uba.py", line 71
    *_, stderr = updatePip.communicate()
    ^
SyntaxError: invalid syntax

error by running python main.py http-server
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from util.FileUtil import FileUtil
ImportError: No module named util.FileUtil

**Comment by eliranwong** [comment]
finally running after using venv, getting excited!  but another issue is about encoding, can you make it to use "utf-8"

the following page is the result of viewing a Chinese chapter
![Screenshot 2021-05-16 8 59 30 AM](https://user-images.githubusercontent.com/25262722/118390108-515c9800-b625-11eb-9920-9354ceb166c9.png)

**Comment by eliranwong** [comment]
in addition, I changed the port to 8080, so I can run on Android and Chromebook.  below is a screenshot on Android, the command field is very small visibly
![Screenshot_20210516-092543](https://user-images.githubusercontent.com/25262722/118390810-080e4780-b629-11eb-8fb8-5d47d0395744.png)

**Comment by eliranwong** [comment]
one more issue: html content does not read the javascript

e.g. run MIB
