### ISSUE TITLE
.restart command for http-server?

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#468]
@otseng is it possible to add a .restart command to restart http-server?

I am thinking to add a .update command and restart the server to apply the update.

**Comment by otseng** [comment]
Since nothing is listening once it's stopped, I do not think it's possible.

**Comment by eliranwong** [comment]
okay, thanks.

**Comment by eliranwong** [comment]
I added a .restart command in https://github.com/eliranwong/UniqueBible/commit/51cb680c3f43429724f8bb122f1a1e20410b833a
