### ISSUE TITLE
 leixcons names squeezed on remote control

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#47]
On remote control's lexicon tab, there are two leixcons names appear to be squeezed / overflow beyond button width.

it is minor, practically does not matter.

<img width="383" alt="Screenshot 2021-01-11 164957" src="https://user-images.githubusercontent.com/25262722/104212516-37b80380-542d-11eb-94f6-b2702aec6221.png">

**Comment by otseng** [comment]
It assumes the abbreviated names.  You can manually resize the window to be larger to see it.

**Comment by eliranwong** [comment]
You are right, it is not a problem.
