### ISSUE TITLE
Add ability for congregants to view same Bible verse presented by teacher 

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#473]
During a sermon, the teacher is teaching on a verse.  He opens the verse on his device.   People open their browser with the server URL and sees the exact verse on their phone.

**Comment by otseng** [comment]
First person who connects to the http-server will be the presenter and has full access.  Everyone else who connects after that can only view the contents.

**Comment by otseng** [comment]
After playing around with this, this would be really useful while singing hymns.

**Comment by eliranwong** [comment]
> First person who connects to the http-server will be the presenter and has full access. Everyone else who connects after that can only view the contents.

is there an option that everyone has full access of the app?

**Comment by eliranwong** [comment]
I added an option config.webPresentationMode.

This feature will be turned on when config.webPresentationMode is set to True

So, in general use, multiple users can use UBA as they want.
