### ISSUE TITLE
search Hebrew bible linguistic annotations

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#48]
This issue is created as a reminder to add search ability to desktop version for searching linguistic annotations of Hebrew Bible.

**Comment by darrelwright** [comment]
Is there any movement on this issue yet?

**Comment by eliranwong** [comment]
this is not an urgent one. 

recently, I am playing desktop UBA on Android tweaking it for mobile screen
![Screenshot_20210524-111122](https://user-images.githubusercontent.com/25262722/119332808-04aa3a00-bc81-11eb-8e2a-fd426a27a329.png)

**Comment by eliranwong** [comment]
not a urgent one.
