### ISSUE TITLE
Display output of "cmd" command

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#483]
Display result of "cmd" command.

Example:
```
> cmd:::ls Bible*
BibleBooks.py
BibleVerseParser.py
BiblesSqlite.py
```

**Comment by eliranwong** [comment]
To do it, you may change line 991 in file TextCommandParser.py

from:

> subprocess.Popen(command, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

to, e.g.:

> runCmd = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

> display, *_ = runCmd.communicate()

with this, you can put content of "display" to where you like.

just a suggestion.

**Comment by eliranwong** [comment]
I added in this commit https://github.com/eliranwong/UniqueBible/commit/b93a5b728e9c7d626b72e4420e12a85122ad7bd3

please check if this is what you want.  thanks.

**Comment by otseng** [comment]
Yes, that's what I was looking for.  Thanks.
