### ISSUE TITLE
pillow cannot be installed on Termux, qrcode not working

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#490]
pillow cannot be installed on Termux, qrcode not working

**Comment by eliranwong** [comment]
@otseng 

I found at: https://pypi.org/project/qrcode/ that can use image_factory=PymagingImage instead of pillow

I tried a bit in https://github.com/eliranwong/UniqueBible/commit/7b8d7bb190ec3395d5fba24d6be3378d5579887c

but it seems  image_factory=PymagingImage produces an error.  can you take a look at this issue?  I want to use qrcode feature with Android if possible.

thanks.

**Comment by otseng** [comment]
QR code fixed on Android and iOS.

**Comment by eliranwong** [comment]
thank you very much.
