### ISSUE TITLE
Comparison window font suggestion 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#492]
Guys would you consider making the compare view also to affect the individual font applied to bibles.

**Comment by otseng** [comment]
It's theoretically possible, but it would require a lot of work.

**Comment by onegladiator4u** [comment]
ok brother . if you  have time, please consider it. thank you .

**Comment by onegladiator4u** [comment]
how can i set this up brother @otseng

**Comment by onegladiator4u** [comment]
@otseng bro, it's working on comparison window . not on compare window . by the the way , thank you so much for your work .
