### ISSUE TITLE
Search request

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#495]
Is it possible to search all books and all PDF files in the Books and PDF folder at the same time?

**Comment by darrelwright** [comment]
I'd sure like to see some movement on being able to search books and PDF files together?

**Comment by otseng** [comment]
Going to first add the ability to search through PDF files:
https://github.com/eliranwong/UniqueBible/issues/572

Then add a button to search through both books and PDF files in one shot.

**Comment by darrelwright** [comment]
Awesome! I know I have said it before, but I appreciate what both you 
and Eliran are doing for UBA. One of many features I continue playing 
with is the search function and getting more comfortable with the RegEx 
functions.

Darrel

**Comment by darrelwright** [comment]
It appears that if a search is returning a number of hits in a pdf that the search takes you to the first page of the pdf. If there are a limited number of hits then you can cycle through the found words. Can this be addressed?

**Comment by otseng** [comment]
> It appears that if a search is returning a number of hits in a pdf that the search takes you to the first page of the pdf. If there are a limited number of hits then you can cycle through the found words. Can this be addressed?

Yes, I'll add that.

**Comment by darrelwright** [comment]
Thanks. I appreciate being able to search all pdf files

**Comment by darrelwright** [comment]
I really appreciate what you are doing with searching pdf files. Is 
there a possibility, when you finish with pdf, to expand this search 
into epub files?

**Comment by otseng** [comment]
>  Is there a possibility, when you finish with pdf, to expand this search into epub files?

Unfortunately, the epub library does not support directly opening a file, so this would not be possible.

**Comment by darrelwright** [comment]
The search for both books and pdf files works nicely! Thank you. And it 
looks like you also fixed the returning of a large number of search 
hits, right? It appears to be returning a lot more.

**Comment by darrelwright** [comment]
One other small change, When there are a number of books/pdfs that do 
not return any hits the current search just displays them as horizontal 
lines. It would be nice if the name of the file with no hits was 
displayed rather than horizontal lines?

**Comment by darrelwright** [comment]
Okay, one more question. Can you do the same with Kindle files (.azw 
extension) as you did with epub files?
