### ISSUE TITLE
Secondary toolbar issue

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#5]
left side of secondary toolbar not being hidden when hiding that bar.
![UB secondary toolbar](https://user-images.githubusercontent.com/11500764/72562747-fe23db00-3860-11ea-8c76-d419e165c9a5.png)

**Comment by eliranwong** [comment]
there is a bug to fixed.  thanks for reporting this.

**Comment by eliranwong** [comment]
fixed in this commit: https://github.com/eliranwong/UniqueBible/commit/935a57612560f1f1ea97228772b209823eff18d1
