### ISSUE TITLE
Verse alignment in parallel view

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#503]
I would really like verses to be aligned in parallel view. The picture shows parallel view with ALXX and KJVx. Verse Jer 19:2 should be aligned, rather than one being lower than the other. If I replace KJVx with MIB things really get skewed!

![Parallel](https://user-images.githubusercontent.com/11500764/119472139-d1a68b80-bcfe-11eb-9b4a-0c83349646df.png)

**Comment by eliranwong** [comment]
to achieve what you want, open ALXX on on Bible Window and KJVx on Study Window.  Use Sync Bible with Study Window feature.  I guess you forget this feature

**Comment by darrelwright** [comment]
Hah! I've been down for quite awhile and am having to "relearn" so much. Yes, I did forget that! I am thoroughly amazed at all of you folks have added to UBA. The PDF stuff alone is worth its weight in gold. Thanks Eliran and team!

Darrel
