### ISSUE TITLE
Issue with Search Morphology help page

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#508]
The screen shot at the bottom (in Search from Master Control panel) only shows as a little box rather than a screen shot.

**Comment by otseng** [comment]
Can you put the screen shot here?

**Comment by darrelwright** [comment]
Yes, this issue is more of just correcting the documentation. If you look at where an image should be displayed all you see is the small rectangular box

![search](https://user-images.githubusercontent.com/11500764/123735414-05bc2180-d854-11eb-9aa4-c159ac8e2b61.png)

**Comment by otseng** [comment]
Fixed
