### ISSUE TITLE
Add ability to search Bible by highlighting

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#51]
Add ability to search Bible by highlighting.

For example: show all verses that have yellow highlighting.

**Comment by eliranwong** [comment]
I think this feature is useful and practical when number of highlights are not too many.
When users build up many highlightings.  This feature may be useful if the search scope could be limited, e.g.

SEARCHHIGHLIGHT:::yellow:::Gen or SEARCHHIGHLIGHT:::yellow:::Gen 2-5

**Comment by otseng** [comment]
Yes.  good point.  I'll add limiting the search also.

**Comment by onegladiator4u** [comment]
Looks good bro. Is it possible to highlight part of Bible verse? Not as whole.

**Comment by eliranwong** [comment]
@onegladiator4u everything is possible, but we consider how things may be maintained.  Bible modules or texts may be updated from times to times.  To me, it is better to have highlighting applied to all bible versions.

To allow highlighting for individual words, I think a possible way to do it is to have a database to keep records of "words" being highlighted for particular verses.  However, to make it easier to be maintained, all occurrences of the same word within a single verse will be highlighted too.  This makes the highlight database independent of bible modules themselves.

For example, take a look at this screenshot: https://github.com/eliranwong/UniqueBibleAppHybrid/wiki/instant_highlighting

In Gen 1:5, "called" occur twice.  If users highlight the word "called", the database should record Gen 1:5 having the word "called" highlighted.  No matter which bible versions are loaded, all words "called" in Gen 1:5 are highlighted.  Therefore, even users highlight one word "called", if Gen 1:5 like the text in the screenshot have two "called", both of them are highlighted.  Do you think it will work for you?

**Comment by eliranwong** [comment]
@otseng I think I will add verse highlighting to upcoming hybrid version too.  I hope to use the same database for highlighting so that the highlighting could be sync across devices.  Currently, you provide two predefined colors, h1 & h2.

In hybrid versions, I prefer to allow users to pick any kinds of colors they want, I will probably use color picker something like this one: https://pub.dev/packages/flutter_colorpicker

I am thinking how to make the highlighting database file to work in both versions.  In hybrid version, I am planning to store actual color codes instead of predefined ones, so users can select any colors.  To make the database to work for both versions, I may add some codes to the desktop version, when the desktop version read color codes other than h1 or h2, they are all shown as h1 automatically on desktop version.  What do you think?

**Comment by otseng** [comment]
> Is it possible to highlight part of Bible verse? Not as whole.

For highlighting for a single Bible in just formatted view, it's not too hard.  But, then to make it also viewable in verse/simple view would be harder.  And it make it highlight for all Bibles, it would be impossible since words are all different.

I like the ability of seeing highlights in all Bibles, so I think it's best to have it verse only.

Also, some other software, like YouVersion, only has verse highlighting.

>  think I will add verse highlighting to upcoming hybrid version too. I hope to use the same database for highlighting so that the highlighting could be sync across devices. Currently, you provide two predefined colors, h1 & h2.

One disadvantage of freeform custom colors is making it difficult to be able to search by highlighting.  Perhaps allow for user to define colors of the hl1, hl2, etc tags?

> when the desktop version read color codes other than h1 or h2, they are all shown as h1 automatically on desktop version. What do you think?

I can check if it's a registered code (hl1, hl2, ul1, etc).  If it's not registered, it'll default to hl1.

**Comment by eliranwong** [comment]
> Perhaps allow for user to define colors of the hl1, hl2, etc tags?

Yes, great idea.  I think this will work better.  Also, more tags may be better, for hl1 - hl10?

**Comment by onegladiator4u** [comment]
> I like the ability of seeing highlights in all Bibles, so I think it's best to have it verse only.

Yeah I got it.


> In Gen 1:5, "called" occur twice. If users highlight the word "called", the database should record Gen 1:5 having the word "called" highlighted. No matter which bible versions are loaded, all words "called" in Gen 1:5 are highlighted. Therefore, even users highlight one word "called", if Gen 1:5 like the text in the screenshot have two "called", both of them are highlighted. Do you think it will work for you?

I'm ok with anything. 
Is it possible to create a table in database from the app? I was thinking if you can create it then we can create a table for each Bible version. And adding verse details with how many words in that verse and positions of words that are highlighted.

**Comment by otseng** [comment]
Create PR to add highlight search.

            # Usage - SEARCHHIGHLIGHT:::[COLOR]:::[BIBLE_REFERENCE]
            # To search entire Bible for all highlight
            # e.g. SEARCHHIGHLIGHT:::all
            # To search entire Bible for yellow highlight
            # e.g. SEARCHHIGHLIGHT:::yellow:::all
            # e.g. SEARCHHIGHLIGHT:::yellow
            # To search New Testament for blue highlight
            # e.g. SEARCHHIGHLIGHT:::blue:::nt
            # To search Old Testament for blue highlight
            # e.g. SEARCHHIGHLIGHT:::blue:::ot
            # To search Matthew for blue highlight
            # e.g. SEARCHHIGHLIGHT:::blue:::Matthew
            # To search James for underline highlight
            # e.g. SEARCHHIGHLIGHT:::underline:::James

**Comment by eliranwong** [comment]
@otseng appreciate your contributions.  Thank you very much.  I will merge the PR this afternoon.
