### ISSUE TITLE
Logos factbook

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#510]
Logos has a really cool feature. It's call the Factbook. Essentially it gathers facts about a given subject and keeps that information, allowing you to use however you desire. It essentially gathers data from different sources so you only need to search for that data one time! I'd love to see UBA implement something similar to this. Here's a link that discusses Factbook - https://www.kevinpurcell.org/logos-9-factbook-how-to-get-the-most-out-of-the-new-features-in-logos-9/

Darrel

**Comment by otseng** [comment]
This is an interesting idea.  From first sight, it seems it would require a lot of work to also do this in UBA.  But, it might be worth investigating sometime later.

**Comment by darrelwright** [comment]
Yes, the concept of the fact book is very intriguing and I think would 
add a lot of value to bible studies but it would entail a fair amount of 
work. Thanks for considering it. You two have already added a LOT of 
value to UBA and I appreciate it!

Darrel

**Comment by darrelwright** [comment]
BibleAnalyzer has the multiwin that does similar to Logos Factbook. Perhaps this might be easier to implement than Factbook. Just a thought.

![multiwin](https://user-images.githubusercontent.com/11500764/125876642-b1688c71-4074-4ff1-8df5-8f0b84bc834a.png)

**Comment by otseng** [comment]
I'm thinking of an easy way to do this.  Add an option to save the Bible or Study window as an HTML file.  Then use the convert reference book from HTML files.  Then can view all your saved info as a reference book.

**Comment by otseng** [comment]
Master control now has ability to support directories in books.

**Comment by darrelwright** [comment]
So how does that work? I upgraded to 25.85, but I do not see any ability 
to work with directories in control. Is it not added yet?

**Comment by darrelwright** [comment]
Well I don't understand why but after restarting a few times directories 
are showing in  master control. That's cool!

**Comment by darrelwright** [comment]
When I put book files in a folder UBA does not see them. I put Maps_ABS 
in a folder titled "Map files". When I clicked the format button on a 
bible, it is prompting me to download and install that file.
