### ISSUE TITLE
Add execute-macro command line parameter

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#521]
Add ability to execute macros from command line:

python3 uba.py execute-macro set-config-values.ubam

```
config.webDecreaseBibleDivWidth = "100px"
config.webPaddingLeft = "50px"
config.webCollapseFooterHeight = True
config.favouriteBible3 = "TRLIT"

. displayMessage Config values set for old TV

```

**Comment by eliranwong** [comment]
I just had a quick check.

at least pprint was mistakenly removed from RemoteHttpHandler.py 

I think it may be better to have a new branch created for testing as so many files changed.  better test to make sure they are ok.   can you create a new branch of it?  thanks.

**Comment by otseng** [comment]
Create test-changes branch
