### ISSUE TITLE
Master control issue

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#525]
I may be missing something. When I open a book module via the control panel, then close UBA. When I start UBA again the previously opened book always opens at startup. How do I turn that off?

**Comment by eliranwong** [comment]
can add an options, not loading history at all.  will not do only for book

**Comment by darrelwright** [comment]
Would it be possible to add this to the populate tabs config setting?

**Comment by eliranwong** [comment]
populate tabs already have an option to enable or disable it

**Comment by darrelwright** [comment]
Well I was talking about not displaying the last opened book when populate tabs is not enabled. Make sense? Currently neither populating or not populating tabs has no affect on displaying the last opened book.

**Comment by darrelwright** [comment]
I seem to remember you had asked for a uba file with an image that takes 
a long time to build. This file has one embedded png file, and it takes 
a long time to build the reference module. If I remove the png file it 
builds very fast.

**Comment by otseng** [comment]
Created issue - Add config flag to turn on/off loading files automatically on startup

https://github.com/eliranwong/UniqueBible/issues/598

Closing this.
