### ISSUE TITLE
Bible Selection

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#538]
Currently when you click in the Bible selection drop-down you have to scroll either up or down to locate the Bible you want to use. When you have a lot of Bibles this selection slows things down (currently I have 44 Bibles). I would like either a scroll bar allowing me to rapidly move up/down my list of Bibles, or some other method to move through my list.

**Comment by eliranwong** [comment]
use "Classic html menu" for verse number single-click action.  all bibles are displayed in one go

**Comment by darrelwright** [comment]
I must be missing something. Even in classic menu I do not see the ability to easily scroll through all Bibles to find the one I want. Am I missing something?

**Comment by eliranwong** [comment]
This screenshot below shows a classic html menu.  All bible versions are displayed:

To take a look, you may try: https://bible.gospelchurch.uk , open a bible passage and click a verse number.

![Screenshot 2021-06-03 9 04 20 AM](https://user-images.githubusercontent.com/25262722/120610139-c82dc980-c44a-11eb-8182-45382af319fd.png)

**Comment by darrelwright** [comment]
Got it! What I had forgot was clicking on the chapter header, which 
allows me to see all bibles, verses etc. Thanks for working with me!

**Comment by darrelwright** [comment]
I'm going to close this issue since it now works for me. Thanks!

**Comment by otseng** [comment]
If I want to rapidly change between Bibles to see what different translations say, I use mini control.  I also have a lot of translations, over 50.

**Comment by darrelwright** [comment]
Oliver, thanks! I had not even thought of looking at the mini tabs. That 
is superb!
