### ISSUE TITLE
add developer resources to web version

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#540]
add developer resources to web version so that developers can access resources that are not open to the public.

@otseng what do you think?

**Comment by eliranwong** [comment]
Major changes in version 25.28:
* Added support of access to private data on web version.
* Added options config.marvelDataPublic, config.marvelDataPrivate and config.webPrivateHomePage for developers to access private data.
    e.g. with the following settings, developers can access data in directory 'myPrivateData' via http://<ip>/private.html
    config.marvelDataPublic = 'marvelData'
    config.marvelDataPrivate = 'myPrivateData'
    config.webPrivateHomePage = 'private'

added in https://github.com/eliranwong/UniqueBible/commit/700de8b0ff4ebc0627e0109a516a315dd1c39ed5

**Comment by otseng** [comment]
I'll add additional security to it:  
https://github.com/eliranwong/UniqueBible/issues/541

**Comment by eliranwong** [comment]
added
