### ISSUE TITLE
Commentary tab names

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#55]
Hi brother,
Just wanted to share a suggestion.
When opening multiple commentaries the tab won't display the name of author. Like this
![image](https://user-images.githubusercontent.com/48617390/104949214-97418080-59e4-11eb-8450-8f979d7bac96.png)
can you add names as tab names. Like Com:Barnes or Com:Gill.
I added Com: With it to make know us it's a commentary. If you can add different color or icons to tabs that would be nice too. Like one color for book and another for commentary.
What do you think ?

**Comment by eliranwong** [comment]
thanks for suggestion.  will consider.

**Comment by onegladiator4u** [comment]
Should I close this issue ?

**Comment by eliranwong** [comment]
please keep it, thanks.
