### ISSUE TITLE
PDF Context Issue

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#554]
I open a PDF file and try saving a page in the history or working with word studies, and I have no context selections for saving a page in history or for doing a word study. I can select text with verses and display the verses in a bible window nicely, but I have no options for saving a page in history or doing a word study until I open the PDF content in the study window. Is that the way it is supposed to operate? Is there any way to have these functions work within the PDF?

**Comment by otseng** [comment]
Not sure what you mean.  Can your provide screenshots?

**Comment by darrelwright** [comment]
I think it was more a misunderstanding on my part. I was think that when 
I open a multi-page pdf file, and the page count is showing in the upper 
left corner that I could right-click the page (i.e., 10 of 197) and have 
that page reference saved in the history file. Make sense?

**Comment by otseng** [comment]
Yes, there's a button to save your current PDF page into history.  It's in the middle of the second row of the toolbar.  

<img width="771" alt="Screen Shot 2021-06-29 at 11 27 53 PM" src="https://user-images.githubusercontent.com/806056/123897783-09be7100-d932-11eb-923f-1777aed556de.png">

**Comment by darrelwright** [comment]
Thanks! I totally missed that one!
