### ISSUE TITLE
Problem building module from note files

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#563]
I am building a book module, currently with only two chapters, and the one chapter  has external links to two .jpg files. Not only does the module take a long time to build, but the jpg files are not linked into the module as images. All you see is a bunch of gibberish for each image.

[Thomas.tar.gz](https://github.com/eliranwong/UniqueBible/files/6613037/Thomas.tar.gz)
[Thomas - Porn Addiction.tar.gz](https://github.com/eliranwong/UniqueBible/files/6613039/Thomas.-.Porn.Addiction.tar.gz)

**Comment by darrelwright** [comment]
Here is the current book module showing the junk for jpg files

[Thomas - Porn Addiction.book.tar.gz](https://github.com/eliranwong/UniqueBible/files/6613092/Thomas.-.Porn.Addiction.book.tar.gz)

**Comment by otseng** [comment]
I added a config flag parseTextConvertNotesToBook to bypass text parsing when converting notes to a book for creating a custom song book.  Set that to false and give it a try after the PR is merged.

**Comment by otseng** [comment]
I tried it out and I see the images, but there's some code that I need to add to parse the website links.

**Comment by darrelwright** [comment]
This fix works very well as long as  a uba file has an image, but if you 
have a beginning file that is text and table of contents the book will 
not build, and in the process of building it takes FOREVER to build. 
Turn the flag off, import the folder I attached, and try to build a 
book. When that fails, rename the first file, turn the flag on and watch 
the book build very fast!
