### ISSUE TITLE
Fix concurrent bible browsing in web mode

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#564]
If two people are using web mode simultaneously, they can overwrite each other's current bible text, chapter, and verse.

Can simulate this by having two browsers open.

In browser A, go to a different book and chapter.

In browser B, enter .bible command.  It will display what browser A last selected instead of what browser B last selected.

**Comment by eliranwong** [comment]
Fixed .bible in https://github.com/eliranwong/UniqueBible/commit/c904fa49082f19afb414479db7a74a1162671713

still need to fix some other shortcut commands

**Comment by eliranwong** [comment]
further fix on .bible command https://github.com/eliranwong/UniqueBible/commit/b42dfc251840b32d41b852dc006cb2f01a68e409

**Comment by eliranwong** [comment]
from ver 25.50
