### ISSUE TITLE
update error on png's

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#566]
i was updating UBA from 24.77 and i'm getting many png errors like this
![image](https://user-images.githubusercontent.com/48617390/121395475-19204f00-c970-11eb-90f6-005dad1a733f.png)
![image](https://user-images.githubusercontent.com/48617390/121395559-2fc6a600-c970-11eb-9bec-75d5c9f41991.png)
app updated by the way.

**Comment by otseng** [comment]
Are you still having this error?

**Comment by otseng** [comment]
Closing this.
