### ISSUE TITLE
Need advice on chapter title 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#57]
Hi,
In the book of Psalms i want to add the title in my own language. So I created a table named title added the values just like titles in bibles.sqlite. I wanted to add because the title comes in with the verse like in the bottom image.
![image](https://user-images.githubusercontent.com/48617390/105173190-ae987f00-5b46-11eb-805b-4d9e29862ac3.png)
But its not showing up in the app. 
![image](https://user-images.githubusercontent.com/48617390/105173371-ed2e3980-5b46-11eb-81d4-cfe019c6cf75.png)
I tried to distinguish it with Bold. It doesn't look good.
Is it overwriting by the default title? Or is it because the value title not  calling from the app?
If I added the titles in bibles.sqlite that's going to come in all Bible version. Is there a way to view in only one version? 
I don't want you to change anything in the app for this. I wanted to know whether I can do anything to fix this. It's ok even if there is no way. Thanks.

**Comment by eliranwong** [comment]
@onegladiator4u There are two reading modes, formatted and simple.  May I ask which mode you are using for the screenshot above?

**Comment by eliranwong** [comment]
Depending on how you format the bible, you can indeed have subheadings in your own languagge, like this one below:

<img width="315" alt="screenshot_subheading" src="https://user-images.githubusercontent.com/25262722/105389960-6ba2de00-5c10-11eb-958f-2af5b332d0b6.png">

I will come back to this issue later or add documentation on how to format the bible.  Meanwhile, you may take CUV.bible as a reference.  You may open the file with a sqlite software and check the formatting of subheadings.

**Comment by eliranwong** [comment]
When I have time, I will also check the code on 3rd  party module converter and see if some changes are needed.

**Comment by onegladiator4u** [comment]
Oh ok. Thank you.
I'm using this format for reading.
![image](https://user-images.githubusercontent.com/48617390/105402593-9a8b7500-5c4d-11eb-8b9f-267ca0cecbc0.png)
don't know whether this is formatted or simple😑


>  Meanwhile, you may take CUV.bible as a reference.

Ok. Thanks

**Comment by onegladiator4u** [comment]
I think it works on formatted mode only.

**Comment by onegladiator4u** [comment]
How can I add title for simple mode? Is it possible?
I tried add title as a verse by adding one record . But it's showing above everything or bottom with verse number part.

**Comment by eliranwong** [comment]
@onegladiator4u you can overwrite the "title" table of "bibles.sqlite"

**Comment by onegladiator4u** [comment]
@eliranwong that'll change the title of other Bible version too right?

**Comment by otseng** [comment]
I'll work on this.  This is how it'll work:

The Modify Database will have a language field to set a language for the Bible version.
Set  Bible to the "ml" language.
Copy bibles.sqlite to bibles_ml.sqlite.
Edit the title table with the data you want in the titles to display for Bibles set to the "ml" language.

If this works for you, then will create a tool to use Watson to translate the titles.

**Comment by onegladiator4u** [comment]
This works for me. I just needed to add title for some chapters in Psalms only. You can add Watson translator tool if someone else asks for it or you like it.
Thanks for working on it.😊

**Comment by onegladiator4u** [comment]
@otseng hey bro, thanks for the PR. It's working. Can you add how someone can do this in wiki page too, like copying bibles.sqlite to bibles_ml.sqlite. etc..? 
Otherwise they won't know how to do it. Thanks.

**Comment by otseng** [comment]
Great!

Created wiki:
https://github.com/eliranwong/UniqueBible/wiki/Chapter-Title-Subheadings

At this point, is there anything else in UBA that does not fully support your language?

**Comment by onegladiator4u** [comment]
I just noticed that the words in the menu bar doesn't show correctly. Earlier it showed correctly, when I was working on the language file.
![image](https://user-images.githubusercontent.com/48617390/112732618-02697f00-8f61-11eb-9a53-d81e2d88642d.png)
Did the first letter underline exist previously ? Is it because of that ?

**Comment by otseng** [comment]
Are you using the Classic menu layout?  Can you try Focus or Aleph?

**Comment by eliranwong** [comment]
> I just noticed that the words in the menu bar doesn't show correctly. Earlier it showed correctly, when I was working on the language file.
> ![image](https://user-images.githubusercontent.com/48617390/112732618-02697f00-8f61-11eb-9a53-d81e2d88642d.png)
> Did the first letter underline exist previously ? Is it because of that ?

The underlining of the first letter is normal.  It is the same in English menu.

**Comment by onegladiator4u** [comment]
> Are you using the Classic menu layout

@otseng No, I'm using Focus. I tried other layout too. It didn't change.


> The underlining of the first letter is normal. It is the same in English menu.

@eliranwong ok. I thought that was new. Didn't notice earlier.
