### ISSUE TITLE
installation error Linux

### ISSUE THREAD

**Issue by frank4532** [eliranwong/UniqueBible#573]
I tried to install UB on Linux Mint. I had this error message:
 File "/home//UniqueBible/main.py", line 25, in <module>
    ConfigUtil.setup()
  File "/home//UniqueBible/util/ConfigUtil.py", line 172, in setup
    config.verseNoSingleClickAction = "_menu" if config.enableHttpServer else "INDEX"
AttributeError: module 'config' has no attribute 'enableHttpServer'

**Comment by eliranwong** [comment]
@frank4532 please check check if it works for you now.  thanks.
