### ISSUE TITLE
Error set-up android termux

### ISSUE THREAD

**Issue by frank4532** [eliranwong/UniqueBible#575]
This is the screenshot with error message
![Screenshot_20210612-174036](https://user-images.githubusercontent.com/85790869/121781625-f9726c00-cba5-11eb-9254-89e8eec12660.png)

**Comment by eliranwong** [comment]
@frank4532  thanks for reporting this issue.  this error was caused by one of our recent updates about refactoring.  we will fix this soon.

**Comment by eliranwong** [comment]
latest codes now contain the fix

@frank4532 please update by running

> cd UniqueBible

> git pull

then try to run uba again.

please kindly let us know if it works or not.  thanks.

**Comment by frank4532** [comment]
Now it works well. Thanks a lot.
