### ISSUE TITLE
Add ability to search Hebrew/Greek without letter variations

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#580]
Would like to be able to search Hebrew/Greek that is insensitive to accent marks, vowel marks, cantillation marks, and letter final forms.

More details at:
https://debatingchristianity.com/forum/viewtopic.php?p=1041918#p1041918

**Comment by Zoomerhimmer** [comment]
I've made an amateurish python script that normalizes Greek accent marks. Here it is for all it's worth: https://github.com/Zoomerhimmer/NT-Textual-Toolkit/blob/main/normalize.py

**Comment by otseng** [comment]
> I've made an amateurish python script that normalizes Greek accent marks. Here it is for all it's worth: https://github.com/Zoomerhimmer/NT-Textual-Toolkit/blob/main/normalize.py

Thanks!  That'll give me a head start.

**Comment by eliranwong** [comment]
I suggest also consider Tauber's one, which is used in many open-spurce academic work:

https://pypi.org/project/greek-normalisation/

**Comment by eliranwong** [comment]
actually, searching Hebrew / Greek without accents or Hebrew vowels is supported

**Comment by eliranwong** [comment]
I don't fully understand why need an extra.

**Comment by eliranwong** [comment]
try:

> SEARCHALL:::MOB:::εκ της

> SEARCHALL:::MOB:::בראשית ברא

**Comment by Difflugia** [comment]
Thanks. I was using the OHGB and didn't realize that MOB supported searches without accents.

That's the main functionality I was looking for. It looks, though, like REGEXSEARCH doesn't work with the MOB. "REGEXSEARCH:::MOB:::בני [ה]*אלהים" filters out the brackets and asterisk.

**Comment by eliranwong** [comment]
> Thanks. I was using the OHGB and didn't realize that MOB supported searches without accents.
> 
> That's the main functionality I was looking for. It looks, though, like REGEXSEARCH doesn't work with the MOB. "REGEXSEARCH:::MOB:::בני [ה]*אלהים" filters out the brackets and asterisk.

The text of OHGB = the text of MOB
The text of OHGBi = the text of MIB

OHGB or OHGBi is created for verse comparison display but not for searches.

I think we can fix the regex search

**Comment by otseng** [comment]
Created new issue and closing this.

https://github.com/eliranwong/UniqueBible/issues/583
