### ISSUE TITLE
Mini Control tab enhancement

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#587]
Currently when I click on the verse reference (i.e., Mark 4:35) it opens the mini Control with the Bible books selected. When I click on the commentary reference (i.e., NICNT:::Mark 4:35) it opens the mini Control with the Commentaries selected. This is great! I find I really like the mini Control!

But when I click on the Bible reference (i.e., MIB) it does not open the mini Control. Instead it opens the LONG vertical list of installed Bibles! Could you tie this click into the mini Control, or supply a config setting allowing that? Thanks for considering!

Darrel

**Comment by otseng** [comment]
Do you mean Master Control?  It might be good though to also add support for clicking on a verse to go to miniControl.

Click on the chapter reference does only open the HTML menu.  Adding support to configure that to open different things would be good to add.

**Comment by darrelwright** [comment]
Yes I mean mini control. When I click on chapter reference it opens mini 
control, same with commentary. Bible is only that does not. I've reached 
a point I REALLY like the mini control!😂

**Comment by darrelwright** [comment]
As a followup,

When I click on Acts 17:28 it opens the mini control. Same, when I click 
on CBSC it opens mini control. I would love the same to happen when I 
click on MIB. Currently it opens that LONG list of my bibles. Make sense?

**Comment by otseng** [comment]
Ah, I thought you were referring to the verse links in the Bible window.  I see what you mean now with the buttons for Bible and Commentary.  Just to be clear about the "MIB" button, do you mean the top right button in the Focus menu layout?

**Comment by darrelwright** [comment]
No, the MIB text with the down arrow, reflecting the currently selected 
Bible. If you click that Bible, UBA currently displays a LONG list of 
Bibles you can select from. I would like to be able to click the current 
Bible and have UBA display the mini Control with the focus on Translation.

**Comment by otseng** [comment]
Got it. I'll work on that.

**Comment by darrelwright** [comment]
This issue (mini Control) works very nice.
