### ISSUE TITLE
Question on hovering on a verse in MIB

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#588]
When I have Gen 1:1 open in the MIB and I hover over any Hebrew word why does every word in the verse highlight? Is it finding something common in every word?

**Comment by eliranwong** [comment]
All words on the same clause, not verse, are highlighted.  Some verses have multiple clauses.

**Comment by darrelwright** [comment]
Okay, thanks my friend. I'll go ahead and close this.
