### ISSUE TITLE
Continuing issue with AHLB

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#591]
If I understand correctly, you're saying the AHLB was fixed? It is not. I am seeing same issue. Am I missing something?

![ahlb](https://user-images.githubusercontent.com/11500764/123404463-dbb9e500-d55d-11eb-8409-e1e70d28e0df.png)

**Comment by otseng** [comment]
It's working on my Ubuntu computer.  What version of Linux are you using?

**Comment by darrelwright** [comment]
Are you starting UBA from a command prompt? That's the only way that 
error occurs. If you start UBA normally there is no error

**Comment by darrelwright** [comment]
Linked to wrong issue. The issue is no displaying AHLB characters.

**Comment by otseng** [comment]
I booted up with Linux Mint and can see it.  I started it with "python3 main.py".

![Screenshot from 2021-06-25 11-24-54](https://user-images.githubusercontent.com/806056/123418222-514aa300-d5a8-11eb-99c8-4e56359fb4aa.png)

**Comment by darrelwright** [comment]
Okay, starting from "python3 main.py" I get these errors. So it looks like an issue in java?

![main](https://user-images.githubusercontent.com/11500764/123483140-2453bb80-d5bb-11eb-88e8-b8be801a4399.png)

**Comment by otseng** [comment]
https://github.com/eliranwong/UniqueBible/issues/321

**Comment by otseng** [comment]
Looks like it has issues with ttf fonts.

https://stackoverflow.com/questions/52088484/chrome-failed-to-decode-downloaded-font-ots-parsing-error-post-failed-to-parse

I've converted it to woff fonts.  Unzip the below into folders in htmlResources folder.

[htmlResources.zip](https://github.com/eliranwong/UniqueBible/files/6719136/htmlResources.zip)

**Comment by darrelwright** [comment]
Oh my friend! Thank you for your diligence and persistence!! That 
worked, not only worked but worked perfectly! I can now display ancient 
pictographs. Whoop!! If you were in my neck of the woods I'd buy you 
coffee. Thank you.

**Comment by otseng** [comment]
One day I'd like to take you up on that offer.  :)
