### ISSUE TITLE
Help converting a new AHLB Module

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#594]
I'm gonna throw this out in the hope that one of you can help me. In theWord I modified the AHLB module, added all adopted root codes, hyperlinked them to the original spots - and the modified module plays beautifully in theWord. But I am having a real problem converting it to use in UBA. I have tried converting to MySword but it won't convert. The developers tell me the problem is MySword does not support fonts embedded in theWord modules. I have tried Simple Bible Reader, but it won't convert either. So I am stuck! The modifications I've made appear correct, I have permission to do the modifications, and it's the only module I know of that contains the adopted roots that match Mr. Benner's book. Can either of you help me? I know it's a long shot, but I figure nothing ventured nothing gained. Thanks for listening. Here is the compressed module:

[AHLB.dct.twm.zip](https://github.com/eliranwong/UniqueBible/files/6721048/AHLB.dct.twm.zip)

**Comment by otseng** [comment]
Sorry, it's encoded in a format I'm not familiar with.

**Comment by darrelwright** [comment]
I was afraid of that. theWord format is not html, but the old style (I 
don't remember its name) and it is not easy to work with. You were kind 
of my last hope. I can do a little bit with html (used to be very good, 
....) but theWord module format I am not there.

**Comment by otseng** [comment]
I'm glad Eliran chose to use html, it makes UBA much more flexible.

Closing this.
