### ISSUE TITLE
Change in text-to-speech from espeak to playing mp3 file

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#597]
Is there anyway the speak function could be rewritten or a plugin written so that rather than running espeak it would play an mp3 file for the selected chapter or verse. I'm including a compressed KJV Ephesians 6 mp3 file to illustrate the difference between what espeak produces and what an mp3 file sounds like.

[Ephesians 06.mp3.zip](https://github.com/eliranwong/UniqueBible/files/6739902/Ephesians.06.mp3.zip)

**Comment by otseng** [comment]
This could be quite complicated to get it fully functional.  But, can try to build up towards it.  Here's first step: https://github.com/eliranwong/UniqueBible/issues/600

**Comment by darrelwright** [comment]
I'd better let you know - I have it started also and should finish in a 
week. Will be out of town next 4 days.:)

**Comment by otseng** [comment]
Add READBIBLE to play Bible mp3 file 
https://github.com/eliranwong/UniqueBible/issues/605

**Comment by otseng** [comment]
Added download KJV mp3 files from GitHub

https://github.com/eliranwong/UniqueBible/pull/614

**Comment by otseng** [comment]
Functionality has now been implemented:

https://github.com/eliranwong/UniqueBible/wiki/MP3-MP4-files,-VLC,-and-reading-Bibles

**Comment by darrelwright** [comment]
Hi guys,

We're back from our anniversary.

When I update and try to run UBA I get "ModuleNotFoundError: No module 
named 'gui.MediaLauncher'". How do I install that module?

Darrel

**Comment by otseng** [comment]
Added code to fix missing gui.MediaLauncher in 25.71
