### ISSUE TITLE
Qt Graphical Interphace library missing

### ISSUE THREAD

**Issue by Franstv99** [eliranwong/UniqueBible#601]
When I updated to v.25.64 I got a lot of errors, 
I tried to reinstall from new UniqueBible v.25.64 but each time I get the same lines :

Installing missing module 'PySide2' ...
PySide2 is not found!  Trying to install 'PyQt5' instead ...
Installing missing module 'PyQt5' ...
Installing missing module 'PyQtWebEngine' ...
Required feature 'Qt Graphical Interface Library' is not enabled.
Install either 'PySide2' or 'PyQt5' first!

And all stop at this message.
How can I install the "Qt Graphical Interphace library" ?
Thanks for your help

**Comment by otseng** [comment]
What OS are you using?  

If you're on Linux, see this:
https://github.com/eliranwong/UniqueBible/wiki/Install-on-Linux#debian-troubleshooting-tips
