### ISSUE TITLE
Add READBIBLE to play Bible mp3 file

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#605]
Add READBIBLE command to play Bible mp3 file recording of a chapter

**Comment by otseng** [comment]
Download and unzip this file into audio/bibles: 

https://www.dropbox.com/s/c54b82ipbes156u/KJV.zip?dl=0

**Comment by otseng** [comment]
Select KJV and a NT book.  Click on the speaker button next to the chapter:

<img width="433" alt="Screen Shot 2021-07-03 at 1 21 08 AM" src="https://user-images.githubusercontent.com/806056/124343894-0f6bbf00-db9d-11eb-9ba9-57d2bdc73af4.png">

**Comment by mooru** [comment]
Can't see audio icon after installation of KJV file

**Comment by otseng** [comment]
> Can't see audio icon after installation of KJV file

Code can not been merged yet.  When it's merged, this issue will close automatically.  You should then be able to see the icon after the update.
