### ISSUE TITLE
Update to recent version throw vlc error

### ISSUE THREAD

**Issue by mooru** [eliranwong/UniqueBible#607]
I just tried to update to the recent version and it gives me this error when i launch uba from terminal

`File "/Users/mac/UniqueBible/main.py", line 378, in <module>
    config.mainWindow = MainWindow()`
 ` File "/Users/mac/UniqueBible/gui/MainWindow.py", line 120, in __init__
    self.setupMenuLayout(config.menuLayout)`
  `File "/Users/mac/UniqueBible/gui/MainWindow.py", line 220, in setupMenuLayout
    getattr(windowClass, 'create_menu')(self)`
  `File "/Users/mac/UniqueBible/gui/FocusMainWindow.py", line 257, in create_menu
    sc.openControlPanelTab6)):`
`AttributeError: module 'shortcut' has no attribute 'openControlPanelTab6'`

**Comment by mooru** [comment]
Fixed. I had to delete 'openControlPanelTab6' from the file and that restored the app

**Comment by otseng** [comment]
Can try deleting the shortcutpy file.  It will then regenerate the shortcut.py file when UBA starts up and it should have that shortcut.
