### ISSUE TITLE
Resources folder not opening 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#609]
i don't know whether  it's for me only . opening folder through menu not working .
![image](https://user-images.githubusercontent.com/48617390/124348904-44fac180-dc0a-11eb-912c-d278039c5f5b.png)

**Comment by otseng** [comment]
It's working for me.  Do you see any error messages?

**Comment by onegladiator4u** [comment]
no. nothing happening .

**Comment by onegladiator4u** [comment]
==============================================================
Debugging Information
==============================================================
2021-07-04 17:37:12.938043

# Platform
Python=['3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]']
Could not get uname
platform=Windows-10-10.0.19041-SP0
platform=nt
platform=10

# Locale
timezone=India Standard Time+0530
defaultlocale=('en_IN', 'cp1252')
Could not get locale

# Version
UBA Version: 25.65

# Config
config.theme=dark
config.userLanguage=Malayalam
config.userLanguageInterface=False
config.menuLayout=focus
config.theme=dark
config.menuShortcuts=micron
config.marvelData=marvelData
config.qtMaterial=True
config.qtMaterialTheme=dark_lightgreen.xml
config.useLiteVerseParsing=False
config.menuShortcuts=micron
config.startupMacro=
config.enableMacros=False
config.useLiteVerseParsing=False
config.disableModulesUpdateCheck=False

# Marvel data
Bibles: 25
Books: 26
Data: 13
Commentaries: 11
Lexicons: 15

**Comment by otseng** [comment]
In your config.py, set this:
```
enableCmd = True
```

**Comment by onegladiator4u** [comment]
i'll let you know if it works

**Comment by otseng** [comment]
This should now be fixed with the latest update.

**Comment by onegladiator4u** [comment]
it's opening now. but folder opens twice. 2 windows for same location

**Comment by otseng** [comment]
I've added displayCmdOutput to the config.  Set that to false.

**Comment by onegladiator4u** [comment]
It is false. Still opening twice.
![image](https://user-images.githubusercontent.com/48617390/124643316-96c37600-deae-11eb-891e-b0c548c51c78.png)

**Comment by otseng** [comment]
See if this is better:  https://github.com/eliranwong/UniqueBible/pull/628
