### ISSUE TITLE
Something goes wrong with new parser update

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#61]
@otseng I merged your new PR #60 

The new codes no longer give proper results for displaying multiple verses.
Could you help check what is the problem?
The following examples work in previous version, you may use them to check.  Thanks.

Jn 3:16, Rm 5:8
BIBLE:::KJV:::Jn 3:16, Rm 5:8
randometext abc Jn 3:16, randometext abc  Rm 5:8 randometext abc 
BIBLE:::KJV:::randometext abc Jn 3:16, randometext abc  Rm 5:8 randometext abc 

All the examples above previously gives display of John 3:16 and Romans 5:8

**Comment by otseng** [comment]
I was only checking for ";" like:
john 1:1; john 10:10; mark 2:4; mark 6:7-8

I'll add "," for splitting and also look at the others.

**Comment by eliranwong** [comment]
@otseng I am afraid that the issue is more than a ",".

With current codes, 
the following example works,
john 1:1; john 10:10; mark 2:4; mark 6:7-8
HOWEVER, the following example does not work:
john 1:1; random text john 10:10; random text mark 2:4; random text mark 6:7-8

**Comment by eliranwong** [comment]
The idea to enable random text inbetween references is that

users can copy part of text from an article or website, and paste directly into the command field
the app then automatically parse all available references.

also, please note that I require the capital letter for each book for a purpose:
i.e. to minimize errors when a block of text is parsed.

**Comment by eliranwong** [comment]
Another issue I found:

In previous versions, the following example works:
John 3:16, 18-20, 22; Rm 5:8

however, with current changed code, both of the examples below do not work:
John 3:16, 18-20, 22; Rm 5:8
John 3:16; 18-20; 22; Rm 5:8

It appears to me the current parser has less features than before.

**Comment by otseng** [comment]
I think what I'll do for the time being is if in classic menu mode, it'll use the original parsing.  If in the aleph menu mode, it'll use faster parsing.  For me, it's more important to be fast.

**Comment by eliranwong** [comment]
> I think what I'll do is if in classic menu mode, it'll use the original parsing. If in the aleph menu mode, it'll use faster parsing. For me, it's more important to be fast. Also, I'll modify so only aleph mode can search by lowercase Bible abbreviations. Classic mode will revert back to requiring capitalizing first letter.

I think it is a good idea.  I appreciate options for users to choose.  Thanks a lot.

**Comment by otseng** [comment]
By default, verse parsing will use standard parsing. Fast parsing option can be enabled in config flags.
Also, reverted back to title case for book names for standard parsing.

**Comment by eliranwong** [comment]
Thank you very much @otseng .  I will merge the PR this afternoon.  I think it is good for users to choose.  Some users did ask me some times ago that they want to use small letters for entering references.
