### ISSUE TITLE
AYUDA¡¡¡ CAMBIE IDIOMA DE INTERFAZ A ESPAÑOL Y YA NO ME INICIA UBA

### ISSUE THREAD

**Issue by Elvis75Cristiano** [eliranwong/UniqueBible#610]
HOLA MUY BUENOS QUE DIOS LES BENDIGA MUCHO. DECIRLES QUE DISFRUTO MUCHO LA APLICACION UNIQUEBIBLE LES AGRADESCO MUCHO POR SU TRABAJO. RESULTA QUE AYER INTENTE CAMBIAR EL LENGUAGE DEL PROGRAMA DE INGLES A ESPAÑOL Y NO ME QUISO INICIAR MAS. ME PONE ESTE MENSAJE:
PS C:\Users\PC> cd C:\Users\PC\UniqueBible
PS C:\Users\PC\UniqueBible> python uba.py
PS C:\Users\PC\UniqueBible> Traceback (most recent call last):
File "C:\Users\PC\UniqueBible\main.py", line 378, in
config.mainWindow = MainWindow()
File "C:\Users\PC\UniqueBible\gui\MainWindow.py", line 118, in init
self.setupMenuLayout(config.menuLayout)
File "C:\Users\PC\UniqueBible\gui\MainWindow.py", line 216, in setupMenuLayout
getattr(windowClass, 'create_menu')(self)
File "C:\Users\PC\UniqueBible\gui\FocusMainWindow.py", line 42, in create_menu
addMenuItem(subMenu, feature, self, action)
File "C:\Users\PC\UniqueBible\gui\MenuItems.py", line 25, in addMenuItem
return menu.addAction(QAction(config.thisTranslation[feature] if translation else feature, object, triggered=action, shortcut=shortcut))
KeyError: 'bibleCollections'

  TAMBIEN QUISIERA AÑADIR ESTE MODULO DE BIBLIA EN FORMATO BBLX Y NO ME RECONOCE BIEN LA FUENTE. MUCHAS GRACIAS.
[iRV1960+ Reina Valera Interlineal Inversa.zip](https://github.com/eliranwong/UniqueBible/files/6758162/iRV1960%2B.Reina.Valera.Interlineal.Inversa.zip)

AYUDA POR FAVOR¡¡¡ DIOS LES BENDIGA.

**Comment by otseng** [comment]
> KeyError: 'bibleCollections'

Replace your lang/language_es.py with:

https://github.com/eliranwong/UniqueBible/blob/master/lang/language_es.py

> [iRV1960+ Reina Valera Interlineal Inversa.zip]

I could not convert it either.

**Comment by Elvis75Cristiano** [comment]
Hola muy buenas. Dios les bendiga mucho. Muchas gracias por la ayuda. Le pondre los detalles que me envio

**Comment by Elvis75Cristiano** [comment]
Muy buenos dias Dios les bendiga mucho. Muchas gracias hermanos. Por la gracia de Dios y vuestro trabjo si me funciona. Me quedaria el tema de la BIBLIA REINA VALERA INTERLINEAL INVERSO decirles tambien que en una oportunidad me reconocio este archivo en la version 25.43 creo o por alli. Tuve que instalar UniqueBible de nuevo porque no me funcionaba las Tablas Graficas y luego ya no me lo reconocio bien. Esto es lo que me pone:     

Gen 1
1 PB H7225:NCcSFC H1254:VqAsSM3 H430:NPDSMN H853:PA XD H8064:NCcDMNH CC H853:PA XD H776:NCcSFPH {\cf2 tierra.}
2 CC XD H776:NCcSFPH H1961:VqAsSF3 H8414:NCcSMN CC H922:NCcSMN CC H2822:NCcSMN H5921:Pu H6440:NCcPMC H8415:NCcSCN CC H7307:NCcSFC H430:NPDSMN H7363:VpAvSF-N H5921:Pu H6440:NCcPMC XD H4325:NCcDMPH {\cf2 aguas.}
3 Cc H559:VqAmSM3 H430:NPDSMN H1961:VqAJSM3 H216:NCcSMN Cc H1961:VqAmSM3 H216:NCcSMN {\cf2 luz.}        
Muchas gracias. Dios les  bendiga mucho.

**Comment by otseng** [comment]
It's encoded in RTF format.  I added some support for it here:  https://github.com/eliranwong/UniqueBible/pull/628

Give it a try now.  I know there's still some issues with it, but it's better than before.

**Comment by Elvis75Cristiano** [comment]
Muchisimas gracias hermanos. Vuestro trabajo bendice mucho nuestras vidas y provoca en nosotros muchos agradecimientos hacia Dios.
