### ISSUE TITLE
wrong verses are hightlighted in formatted style reading

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#62]
Hello @otseng , I noted an issue for current highlighting feature.

In simple style mode, I highlighted John 3:16 and John 3:17, but in formatted style mode, John 3:1 and John 3:2 are highlighted instead of  John 3:16 and John 3:17.

Please see the screenshot below, thanks:

<img width="960" alt="bug_highlight" src="https://user-images.githubusercontent.com/25262722/105389710-123aaf00-5c10-11eb-8588-439bfc757f4f.png">

**Comment by eliranwong** [comment]
@otseng I fixed this issue in https://github.com/eliranwong/UniqueBible/commit/9115f3470e82220ec4c90808e706db9bbaac5c65

**Comment by otseng** [comment]
Thanks
