### ISSUE TITLE
Add ability to read multiple chapters 

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#631]
https://github.com/eliranwong/UniqueBible/issues/627#issuecomment-875256231

**Comment by darrelwright** [comment]
Version 25.74 says I can read multiple books and chapters, but there appears to be a problem. Plus I cannot make selections on the GUI. When I enter "READBIBLE:::KJV:::Matt 1-5" as an example on the command line it does not play that selection but pulls up screen for me to select chapters to be read. On the Media Player window the "Play" button acts like the "Open" button and wants me to select the chapter to be read. Make sense?

**Comment by otseng** [comment]
Does "READBIBLE:::KJV:::Matt 1" work?

**Comment by darrelwright** [comment]
No, it brings up the media player and when you hit "Play" it opens the 
folder so you can select a selection to play.

**Comment by otseng** [comment]
Is the KJV mp3 files installed?
Do you see the speaker icon for KJV bible?
Does that button work?

**Comment by darrelwright** [comment]
Yes they are all installed.I rebuilt UBA last night. Currently I have 
speaker icons showing for all NT books, but none for OT.

If I open Act 17:1 and press the speaker icon UBA plays Acts 17. if I go 
to Master Control and enter "READBIBLE:::KJV:::Matt 1" it plays Acts 17!

If I open Gen 1, then go to control and enter "READBIBLE:::KJV:::Matt 1" 
it plays Acts 17.

When I click the speaker icon on any NT book it plays that chapter 
beautifully! When I go to OT, say Gen 1:1, then go to Master Control and 
enter "READBIBLE:::KJV:::Gen 1" it plays the LAST played NT book. Does 
that help?

**Comment by otseng** [comment]
I think it's an issue with the command when there's two ":::" in it...

Can you also try opening KJV and running: 
READBIBLE:::Matt 1
READBIBLE:::KJV:::1 Cor 13, Rev 1:::default

**Comment by darrelwright** [comment]
Same thing:

READBIBLE:::Matt 1 wants to open selection window to select a chapter to 
play

READBIBLE:::KJV:::1 Cor 13, Rev 1:::default does same as above
