### ISSUE TITLE
RTF support question

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#633]
Since you're adding support for RTF, is there any change of adding support for importing files from theWord, which is RTF formatted? I would like to be able to import bibles, dictionaries and commentaries.

**Comment by otseng** [comment]
The import I added was a very naive approach.  Basically it was just stripping out the text and did not include any formatting.  But, we can try it out importing bibles first.  Can you attach a bible here?

**Comment by darrelwright** [comment]
Sure, I'll give you a couple:

[ant.nt.zip](https://github.com/eliranwong/UniqueBible/files/6786432/ant.nt.zip)
[AFV+.ont.zip](https://github.com/eliranwong/UniqueBible/files/6786433/AFV%2B.ont.zip)

**Comment by otseng** [comment]
> [ant.nt.zip](https://github.com/eliranwong/UniqueBible/files/6786432/ant.nt.zip)

https://github.com/eliranwong/UniqueBible/issues/640

**Comment by darrelwright** [comment]
That worked really nice on the ant.nt bible. It imported beautifully!

**Comment by darrelwright** [comment]
That plays very well for importing NT bibles. Can it be opened up for OT 
also?

**Comment by otseng** [comment]
> That plays very well for importing NT bibles. Can it be opened up for OT also?

https://github.com/eliranwong/UniqueBible/issues/642

**Comment by otseng** [comment]
It's now able to import theWord OT bibles as well.

It looks like theWord dictionaries and commentaries are in RTF format, which will require much more effort to import.  Create another issue if needed.

Closing this issue.

**Comment by darrelwright** [comment]
When I pull import for theWord bibles, I see import NT and import Complete, but I do not see ability to import OT bibles. Am I missing something?

**Comment by otseng** [comment]
Can you post here an OT file and I'll add the ability to import it.

**Comment by darrelwright** [comment]
Here is 2:

[lxxmorph.ot.zip](https://github.com/eliranwong/UniqueBible/files/6837006/lxxmorph.ot.zip)
[BSB Interlinear OT-Heb.ot.zip](https://github.com/eliranwong/UniqueBible/files/6837007/BSB.Interlinear.OT-Heb.ot.zip)

**Comment by darrelwright** [comment]
Done. I put 2 up there.

**Comment by otseng** [comment]
Code added to import .ot files.  However, it strips out all morphology information.  If that needs to be added, will take additional work to figure that out.  Create another issue if that's needed.
