### ISSUE TITLE
Issue with GIT

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#643]
I am having trouble using GIT to install and/or update UBA. I have UBA installed with a lot of modules in third Party and Marvel Data.

How can I set up and use GIT to do updates on an existing UBA installation? I have tried renaming the UBA directory, doing "git clone" which creates the UBA directory, copying all my modules into the new cloned installation - but that wipes out whatever GIT had produced. So when I then try "git pull" I get the following error:

"fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)."

So what do I do?

**Comment by otseng** [comment]
The only thing that git needs is the .git folder in the UBA folder.  Somehow that .git folder is being deleted when you copy things over.

**Comment by darrelwright** [comment]
Thanks. I copied the .git files and folders over and now it's working.
