### ISSUE TITLE
READBIBLE:::Matthew 1 not working

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#644]
If the soft-music rendition is installed and the default rendition is not installed, it should play the soft-music rendition instead of not playing anything.

**Comment by darrelwright** [comment]
Actually it would be nice to have a config entry allowing the default rendition to be specified. I have 6 renditions installed. I can select any of them via the media player, but not any other way.

**Comment by otseng** [comment]
Added defaultMP3BibleFolder to config
