### ISSUE TITLE
Moving UBA to a folder name with a space will not open app

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#646]
i moved the bible app to a folder `Bible Study`, it's not working through shortcut bat file named UniqueBibleApp.bat. 
if we run `python uba.py` in powershell it works
when i try to run bat file in poweshell it gave

```
Suggestion [3,General]: The command uniquebibleapp.bat was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\uniquebibleapp.bat". See "get-help about_Command_Precedence" for more details.
PS F:\BIBLE STUDY\App\UniqueBible> .\uniquebibleapp.bat

F:\BIBLE STUDY\App\UniqueBible>python F:\BIBLE STUDY\App\UniqueBible\uba.py
python: can't open file 'F:\BIBLE': [Errno 2] No such file or directory
PS F:\BIBLE STUDY\App\UniqueBible>
```
if i gave double quotes to path inside UniqueBibleApp.bat. then running ` .\uniquebibleapp.bat` opens the app but
it rewrites path inside UniqueBibleApp.bat without quotes.

My darktheme didn't work well after the location change . 
To run the app now i have to use powershell with `python uba.py`
Shortcut won't work

**Comment by otseng** [comment]
Can you give a screenshot of dark theme issue?

**Comment by onegladiator4u** [comment]
this is after moving.
![image](https://user-images.githubusercontent.com/48617390/125168981-caabdd80-e1c5-11eb-9304-63a388030158.png)
this is the one i posted earlier on discussions 
![image](https://user-images.githubusercontent.com/48617390/125169028-ff1f9980-e1c5-11eb-968b-4b519c9a2100.png)

i used custom css and edited qmaterial themefile named `dark_lightgreen` to get the second look. i think it's not linking to qtmaterial theme `dark_lightgreen`.

**Comment by otseng** [comment]
Can you replace uba.py and see if that fixes the shortcut?

[uba.py.zip](https://github.com/eliranwong/UniqueBible/files/6795747/uba.py.zip)

**Comment by onegladiator4u** [comment]
no it didn't . it just created a shortcut in the directory i believe

**Comment by onegladiator4u** [comment]
the icons for verse highlights seems to have gone missing too. don't know whether it's the same problem .
![image](https://user-images.githubusercontent.com/48617390/125174885-fa6add80-e1e5-11eb-9a10-280f3ef62550.png)

**Comment by otseng** [comment]
To open a parent folder in Windows, use this:

```***[CMD:::start ..@Open parent directory on PC]```

**Comment by otseng** [comment]
> no it didn't . it just created a shortcut in the directory i believe

What happens when you start with the generated shortcut?

**Comment by onegladiator4u** [comment]
> > no it didn't . it just created a shortcut in the directory i believe
> 
> What happens when you start with the generated shortcut?

Nothing happened. Didn't open the app

**Comment by onegladiator4u** [comment]
> 
> 
> > no it didn't . it just created a shortcut in the directory i believe
> 
> What happens when you start with the generated shortcut?

Its working . don't know why it didn't work yesterday with the new shortcut. i tried again now.

**Comment by onegladiator4u** [comment]
> To open a parent folder in Windows, use this:
> 
> `***[CMD:::start ..@Open parent directory on PC]`

I want to go one more UP directory. And open a folder inside it too.

**Comment by onegladiator4u** [comment]
Theme still not working. I tried changing the qtthemes it didn't change. Later I deleted the theme folder and restarted the app. The old theme is still there and I could change it to another theme without the qt theme files. Is qtthemes files stored and using it from somewhere else? Or is it cached? I couldn't find out why it's not working.

**Comment by onegladiator4u** [comment]
Just found out that qt materials are used from python lib folder. Not from Unique Bible lib folder. When I changed the theme file in C python directory it worked.. Do you have any idea why it used from there than from Unique Bible directory?

**Comment by otseng** [comment]
> I want to go one more UP directory. 

`***[CMD:::start ../..@Open directory on PC]`

> And open a folder inside it too.

`***[CMD:::start ../../mydirectory@Open directory on PC]`

> Do you have any idea why it used from there than from Unique Bible directory?

qtthemes is native python support, it's not something we wrote.  The built-in themes (dark, light, night) we wrote.

**Comment by onegladiator4u** [comment]
> ***[CMD:::start ../..@Open directory on PC]

it didn't work . i tried different combos.
![image](https://user-images.githubusercontent.com/48617390/125203741-6c4f2f80-e297-11eb-8834-aff912eb9a24.png)

>qtthemes is native python support, it's not something we wrote. The built-in themes (dark, light, night) we wrote.

i mean earlier App used `F:\BIBLE STUDY\App\UniqueBible\venv\Lib\site-packages\qt_material\themes` this .
now its using `C:\Python39\Lib\site-packages\qt_material\themes`.



> I'll add that uba.py file into the next release.

ok thank you .

There is one more issue .
no icons for color and underline highlights 
![image](https://user-images.githubusercontent.com/48617390/125203892-45ddc400-e298-11eb-8f7c-34eabf94f085.png)

**Comment by otseng** [comment]
> > ***[CMD:::start ../..@OPEN directory on PC]

Sorry, try for Windows:

`***[CMD:::start ..\..@OPEN directory on PC]`

> i mean earlier App used `F:\BIBLE STUDY\App\UniqueBible\venv\Lib\site-packages\qt_material\themes` this .
> now its using `C:\Python39\Lib\site-packages\qt_material\themes`.

Can you try delete the F:\BIBLE STUDY\App\UniqueBible\venv folder and restart to regenerate the venv?

> no icons for color and underline highlights

I'll have to research about that one...

**Comment by onegladiator4u** [comment]
> ***[CMD:::start ..\..@OPEN directory on PC]

i tried those too. it didn't work . its opens upto one level only. if we use ` ..\..` or ` ..\..\..` it opens unique bible directory .


> Can you try delete the F:\BIBLE STUDY\App\UniqueBible\venv folder and restart to regenerate the venv?

is this the code to download it again ?`python -m venv venv`

**Comment by otseng** [comment]
> i tried those too. it didn't work . its opens upto one level only. if we use ` ..\..` or ` ..\..\..` it opens unique bible directory .

Can you try:

`**[CMD:::start ..\\..@OPEN directory on PC]`

> is this the code to download it again ?`python -m venv venv`

Yes, you can do that.  Or when you start up with "python uba.py" it should regenerate it.

> no icons for color and underline highlights

Do you have it toggled on?

<img width="633" alt="Screen Shot 2021-07-11 at 3 42 37 PM" src="https://user-images.githubusercontent.com/806056/125208235-5887d700-e25f-11eb-808b-fccaf4442947.png">

**Comment by onegladiator4u** [comment]
> **[CMD:::start ..\\..@OPEN directory on PC]
That worked . with an extra *. 

> Yes, you can do that. Or when you start up with "python uba.py" it should regenerate it.

its downloaded again . still not using qt materials in UBA.




> Do you have it toggled on?

sorry for that . that was off actually . i thought enableversehighlighting in config is the one.

` ***[CMD:::start ..\\..@OPEN directory on PC]` if there is a single  quote in one directory how to put that character inside this code? if we use '`` then code won't work . is there is an escape option for these characters ?

**Comment by otseng** [comment]
> is there is an escape option for these characters ?

Try backslash \'

> still not using qt materials in UBA.

Will need Eliran to help debug this since I don't have Windows.

**Comment by onegladiator4u** [comment]
> Will need Eliran to help debug this since I don't have Windows.

ok. May I know why he's not active ?

**Comment by otseng** [comment]
He's been very busy with his church.
