### ISSUE TITLE
reference book from html not showing images 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#653]
i tried to create a reference book from html files . But its not showing images of html in book. 
images works in web browser if we open html file .

**Comment by otseng** [comment]
Can you post the reference book here?

**Comment by onegladiator4u** [comment]
[Study Book.zip](https://github.com/eliranwong/UniqueBible/files/6813913/Study.Book.zip)

**Comment by otseng** [comment]
I wrote up instructions here on how to embed an image into a book:

https://github.com/eliranwong/UniqueBible/wiki/How-to-embed-an-image-in-a-book

**Comment by onegladiator4u** [comment]
for html ?

**Comment by otseng** [comment]
> for html ? creating book from html. Above one is about notes right ?

For HTML, use the img tag

`<img src="/Users/otseng/dev/UniqueBible/htmlResources/icons/UniqueBibleApp.png" />`

**Comment by onegladiator4u** [comment]
> <img src="/Users/otseng/dev/UniqueBible/htmlResources/icons/UniqueBibleApp.png" />

i used the tag, but it doesn't work . 
After i noticed htmlResources in your link, i copied the images to /htmlResources directory . Now it works .
I thought images were embedded when converting. Is there any better way than this? we have to copy images with book. it'll be nice if html embedded those images when converting to book

**Comment by otseng** [comment]
There's a problem with embedding an image into HTML.  Created an issue for it:
https://github.com/eliranwong/UniqueBible/issues/656

**Comment by onegladiator4u** [comment]
This update didn't fix it i bro.

**Comment by otseng** [comment]
Can you try recreating a note, embed an image, and convert it to a book?  Make sure the parseTextConvertHTMLToBook config is false.

**Comment by onegladiator4u** [comment]
note created shows the code of embedded image i think.
![image](https://user-images.githubusercontent.com/48617390/125832207-4c740d7f-d945-4952-994c-507f2834caf9.png)

actually requested about the html images to be embedded, 
you can leave this issue if you want . i couldn't link some folder names to html. some folder opens and others not opening. also i don't know how to link a folder name with spaces too.
thanks for looking into these. i don't want to take your time anymore . even i wasted lot of time to open some folder without spaces too.

**Comment by otseng** [comment]
> actually requested about the html images to be embedded,

Sorry, I meant recreating an HTML file and embedding an image.  The fix involved disabling the parsing which was messing up the images.  

> even i wasted lot of time to open some folder without spaces too.

Who knows how many trillions of dollars in time and money has been wasted on Microsoft never fully addressing the issue of spaces in filenames?

**Comment by onegladiator4u** [comment]
i

> Sorry, I meant recreating an HTML file and embedding an image. The fix involved disabling the parsing which was messing up the images.

It Didn't work .i turned it off and tried .also tried with true . parseTextConvertHTMLToBook . didn't try with restarting app though. 



> Who knows how many trillions of dollars in time and money has been wasted on Microsoft never fully addressing the issue of spaces in filenames?

haha. They couldn't fix windows 10 bugs completely yet. After each update something new arises.
i just put underscore on the folders now.

**Comment by otseng** [comment]
Can you verify you're clearing parseTextConvertHTMLToBook and not parseTextConvertNotesToBook?

Can you try converting this HTML?

[embed image.html.zip](https://github.com/eliranwong/UniqueBible/files/6835484/embed.image.html.zip)

**Comment by onegladiator4u** [comment]
this is the current setting 

![image](https://user-images.githubusercontent.com/48617390/126060972-843136eb-e949-4239-86f6-aa64d2967340.png)


> Can you try converting this HTML?
> 
> [embed image.html.zip](https://github.com/eliranwong/UniqueBible/files/6835484/embed.image.html.zip)

This html works.

**Comment by otseng** [comment]
So the issue is creating the HTML file.   Can you create a new HTML file, insert an image into it, then paste it here for me to look at?

**Comment by onegladiator4u** [comment]
you want an html with just an image right ?

**Comment by onegladiator4u** [comment]
[Test.zip](https://github.com/eliranwong/UniqueBible/files/6836548/Test.zip)

**Comment by otseng** [comment]
Can you try embedding the image instead of linking the image?

<img width="1030" alt="Screen Shot 2021-07-18 at 12 06 48 PM" src="https://user-images.githubusercontent.com/806056/126074269-fb58a9ca-ece0-4bd8-9122-d40f0645cefb.png">

**Comment by onegladiator4u** [comment]
do i have to create html from uba editor? .
i'm using external editor to create html. then only i can use css classes and all.

**Comment by otseng** [comment]
There are some sites explaining how to embed an image.

https://www.thesitewizard.com/html-tutorial/embed-images-with-data-urls.shtml

Some HTML editors might also have this builtin.

**Comment by onegladiator4u** [comment]
ok brother . yeah i searched for it.
i'll make it work. Thanks for your helps ☺.
