### ISSUE TITLE
Add support for downloaded MP3 files from faithcomesbyhearing.com

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#654]
Add support for playing files downloaded from:
https://www.faithcomesbyhearing.com/audio-bible-resources/mp3-downloads

**Comment by otseng** [comment]
Place all mp3 files downloaded from faithcomesbyhearing.com for a particular Bible rendition in audio/bibles/[Bible Text]/[rendition]/

More info at:
https://github.com/eliranwong/UniqueBible/wiki/MP3-MP4-files,-VLC,-and-reading-Bibles

**Comment by darrelwright** [comment]
That works very well.
