### ISSUE TITLE
Cannot start http-server on Amazon Fire tablet

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#655]
Cannot start http-server on Amazon Fire tablet

**Comment by darrelwright** [comment]
I install all files on my tablet, then run "python uba.py http-server & disown" and it crashes with filenotfounterror where it is looking for "activate_this.py".

**Comment by otseng** [comment]
Can you check if the activate_this.py file exists?

If not there, run: `python3 download.py activate_this.py`
