### ISSUE TITLE
DIOS LES BENDIGA. DENUEVO SOLICITANDO SU AYUDA.

### ISSUE THREAD

**Issue by Elvis75Cristiano** [eliranwong/UniqueBible#658]
Muy buenas de nuevo. Dios les bendiga mucho hermanos. Tengo un problema con el menu de descarga de GitHub Bible MP3 File. Le doy a descargar todos los capitulos de la biblia MP3 y  descarga solo un capitulo y se queda conjelado. Si lo saco se saca UBA tambien. Tampoco RECONOCE el capitulo descargado. Luego queria pedirle ayuda tambien con la funcion FILTRO VIVO no me REALIZA LA BUSQUEDA o NO ENTENDI YO como se usa. AYUDA POR FAVOR. Muchas gracias. DIOS les bendiga mucisimo.

**Comment by otseng** [comment]
I've now added the Spanish Reina-Valera Bible support into UBA.  You can download the Bible from the menu under "Add/Github Bibles".  You can download the mp3 files from "Add/Github Bible mp3 files".

For how to use live filter, see:  
https://github.com/eliranwong/UniqueBible/wiki/Live-Filtering

**Comment by Elvis75Cristiano** [comment]
Muy buenas. Dios les bendiga mucho. Les agradesco mucho la solucion. He podido descargar la biblia mp3. Sobre el Filtro Vivo resulta que todavia no me da resultados. Me abre en la ventana de estudio solo dos filas con los numeros de los capitulos del genesis. No me abre el texto como le abre a usted en el ejemplo dado. Muchas gracias. Dios le bendiga mucho.

**Comment by otseng** [comment]
Can you post screen shots of doing a search and also using the live filter?

**Comment by Elvis75Cristiano** [comment]
Muy buenos dias. Dios les bendiga. aqui le pongo hermano unas capturas del Filtro Vivo:  
![20210717_145604(0)](https://user-images.githubusercontent.com/84225622/126038093-8a8465b5-eaff-4316-9cbd-91004f653666.jpg)
![20210717_145918](https://user-images.githubusercontent.com/84225622/126038128-96216350-e4fc-4767-88d6-3faa3f25723a.jpg)
![20210717_150821](https://user-images.githubusercontent.com/84225622/126038212-9374ac22-7b5b-4961-be36-cf85c4066063.jpg)

Lo unico que hace es mostrar dos filas de los numeros de los capitulos de los libros en la ventana de estudio. Muchas gracias. Dios les bendiga mucho.

**Comment by otseng** [comment]
I see the problem.  Because its displaying the verses in the formatted view, it's not filtering it correctly.  I'll force it to be in simple view when opening up the live filter.

**Comment by otseng** [comment]
Live filter now forces to be in simple view.

**Comment by Elvis75Cristiano** [comment]
Dios les bendiga mucho. Gracias por su trabajo. Bendice mucho nuestras vidas. Un abraso muy fuerte de España. Que Dios les pague abundantemente.
