### ISSUE TITLE
Enhancement to charts and tables

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#659]
Charts and table work great when searching for a single entry such as rhema (G4487) or logos (G3056). But if I am searching for either "word" (which can be either one of those) or if I am searching for G3056 or G4487 and it returns 748 hits in 378 verses I have no way of knowing which verses contain which instance. Now I know Matt contains 70 occurrences, but unless I go through all 70 verses I don't know which verses contain which occurrence of "word".

I would love to see a little deeper breakdown so I can see what the verses contain. In the chart I'd like to see (for example) Matt showing 60 verses for G3056 and 10 for G4487. On the charts I'd like to see the same thing in the legend: Matt (G3056 - 60, G4487 - 10). This would be immensely helpfull!

Can we do that?

**Comment by otseng** [comment]
Honestly, I have no idea.  But, all of it is powered by Google charts.  If you can design it Google charts with the required data, I can see if UBA can provide that data.

Here's Google charts:
https://developers.google.com/chart/interactive/docs/gallery

There might also be some other interesting ways to chart other data in UBA.

**Comment by darrelwright** [comment]
Well, actually I don't think it involves new charts, just a modification 
of the Charts and Tables.py code. In my search I used G3056|G4487, so it 
seems like (and here is my lack of understanding) somewhere in 
generateCharts you should be able to count verses and use a where clause 
with each element searched for. Thus it would return "Matt - G3056 - 60" 
and "Matt - G4487 - 10", then the charts would (in this case) just build 
a pie chart with 2 Matt slices rather than one slice "Matt 70". Now am I 
oversimplifying things or is that doable just from the data?

**Comment by otseng** [comment]
After the search results get displayed, the only thing it's doing is grabbing all the verse references.  So, it has no idea about any of the search terms.

The only way to do this would be to create a new chart function and generate data on both the references and the search words.   I can create a new feature "Power charts" that can produce more interesting charts based on data such as this.

**Comment by eliranwong** [comment]
@otseng any progress about it?

**Comment by eliranwong** [comment]
inactive for a while

**Comment by darrelwright** [comment]
Why are closingnthis without doing anything with it? Am I missing somthing?

**Comment by darrelwright** [comment]
Is anything happening on the power charts?
