### ISSUE TITLE
Hindi Bible and mp3 files

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#661]
I'm thinking about adding the ability to download Hindi Bible and mp3 files directly from UBA.

There are Hindi mp3 files here:
https://audiotreasure.com/mp3/Hindi/

I've found one Hindi Bible:
https://sourceforge.net/projects/zefania-sharp/files/Bibles/HIN/Hindi%20Indian%20Revised%20Version%20Bible/

@onegladiator4u
Can you confirm if these match with each other?

**Comment by onegladiator4u** [comment]
let me see

**Comment by onegladiator4u** [comment]
they don't match exactly with each other . some words differ or missing . but that doesn't seen to have changed the meaning .
i heard almost 2 chapters from matthew and john 1. i noticed around 6 or 8 words changes. we can look it like revised versions of same versions like ESV or NIV.
Hindi is not my mother tongue. i have learned to read and write it. so i can say that it's not exactly same . slight difference is there.

**Comment by otseng** [comment]
Do you think it's worth it to add those to UBA?  Or will people complain they are different?

**Comment by onegladiator4u** [comment]
you could add it to UBA if we can find a correct hindi version of it. you can add the link to the bible in latest changes .

can you able to download bibles from ph4.org? i saw some hindi bible versions but couldn't download to check it.
last week i tried for some commentaries too. but couldn't download from it .

**Comment by otseng** [comment]
> can you able to download bibles from ph4.org?

I'm not able to download the Hindi Bibles from there either.

**Comment by onegladiator4u** [comment]
> I'm not able to download the Hindi Bibles from there either.

i'll check for it to download it whenever i can. i'll let you know if i find a correct one for it.
UBA doesn't have default bible right? So you can wait until someone request . or let an option to manually get mp3s from any sites for each bible and putting in a folder inside UBA.

Btw is mp3 bible download working inside uba? is there an option to turn on. i'ts not downloading anything for me. It just says downloading.. please wait . Do I have to create a issue ?

> I'm not able to download the Hindi Bibles from there either.

**Comment by otseng** [comment]
> UBA doesn't have default bible right?

The only requirement for mp3 files is the Bible name must match the mp3 folder name.

> Btw is mp3 bible download working inside uba? is there an option to turn on. i'ts not downloading anything for me. It just says downloading.. please wait . Do I have to create a issue ?

There's no explicit flag to turn it on or off.  Really the only thing required is manually installing VLC.  UBA would automatically install the python-vlc pip module.  

If you get to the MP3 download window, then it should all work.  Are you able to download any of the Github Bibles, Books, PDF, etc?

**Comment by onegladiator4u** [comment]
> The only requirement for mp3 files is the Bible name must match the mp3 folder name.

that's nice.


> 
> 
> > UBA doesn't have default bible right?
> 
> The only requirement for mp3 files is the Bible name must match the mp3 folder name.
> 
> > Btw is mp3 bible download working inside uba? is there an option to turn on. i'ts not downloading anything for me. It just says downloading.. please wait . Do I have to create a issue ?
> 
> There's no explicit flag to turn it on or off. Really the only thing required is manually installing VLC. UBA would automatically install the python-vlc pip module.
> 
> If you get to the MP3 download window, then it should all work. Are you able to download any of the Github Bibles, Books, PDF, etc?

I just installed a book via that. its working . 
i get mp3 window . but nothing else happening . 
vlc i installed earlier . it's not my default player though.
should I check something else ?

**Comment by otseng** [comment]
VLC doesn't need to be default player.

Do you see the download screen like this?

<img width="484" alt="Screen Shot 2021-07-17 at 4 13 53 PM" src="https://user-images.githubusercontent.com/806056/126048401-ae5b5e45-4bb7-4594-93ae-84436879aaaa.png">

Can you just try to download a single chapter?  Downloading an entire Bible would take a long time.

Try downloading a single chapter for KJV (American) and verifying it created the directory: audio/bibles/KJV/default

**Comment by onegladiator4u** [comment]
> Can you just try to download a single chapter? Downloading an entire Bible would take a long time.

yes. that's what I did.
![image](https://user-images.githubusercontent.com/48617390/126060375-14cfbf15-c3c0-4b0c-a8fb-75011a587c59.png)

it just stay like this 
![image](https://user-images.githubusercontent.com/48617390/126060397-3b4d422b-f1d6-4c15-95e3-e5d79b1a823a.png)

I'm using a different KJV than provided inside the App i believe . Will that affect it?
My bible name is `KJV.bible` in directory .
I wanted to point out that there is no` audio` directory inside app directory .

**Comment by otseng** [comment]
> I wanted to point out that there is no` audio` directory inside app directory .

That's a problem then.  I'll modify that in the next release.  In the meantime, you can create the audio directory and if that fixes it.

**Comment by onegladiator4u** [comment]
yup. its ok now. Thanks brother . Have a blessed Sunday.

**Comment by onegladiator4u** [comment]
hi @otseng Just found the Hindi bible for this audio. Didn't check more chapters . only checked matthew 1 and half of John 1.
ph4 site is now ok to download .
go to `https://www.ph4.org/b4_index.php`. if it's in all languages then search `HHBR` using ctrl +f.

**Comment by otseng** [comment]
Added HHBD and MP3 files into Github for download from menu.
