### ISSUE TITLE
Difference of verse shows css codes

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#665]
Just noticed that when looking at a difference between verses `<woj>` css comes up. (words of Jesus)
![image](https://user-images.githubusercontent.com/48617390/126040622-2e61337f-69e2-42dd-a039-8d49e21808c2.png)

**Comment by otseng** [comment]
I can't duplicate that issue.  Where did you get the KJV Bible from?

**Comment by onegladiator4u** [comment]
from ph4.org.
they had `<j>` as tags. i changed it to `<woj>` when i saw that css in the app used `woj `as css style.
 i didn't know much css then. so replaced all `<j>` with `<woj>` and its closing tags. 
i used DB browser for sqlite to change

![image](https://user-images.githubusercontent.com/48617390/126072162-2ad557a8-4c53-4636-b40b-22e1ca929444.png)

**Comment by otseng** [comment]
Can you try using `<red> </red>` instead?

**Comment by onegladiator4u** [comment]
do i have to replace `<woj> </woj>` with `<red> </red>` in bible file?

**Comment by otseng** [comment]
Yes.  Probably easier to change the <j> in original file first and then reimport.

**Comment by onegladiator4u** [comment]
now <red> comes up
![image](https://user-images.githubusercontent.com/48617390/126079763-f048603e-a089-45d1-b0a6-d3ba104314fd.png)

**Comment by otseng** [comment]
OK, I'll need to write a fix for this then...
