### ISSUE TITLE
Problem building and using a book

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#668]
I have built a 5 chapter book with TOC. The appears to build okay, but the hyperlinks have an issue. If I open the book in the study window the hyperlinks work properly, but if I open the book in a window the hyperlinks do nothing.

The following shows the hyperlinks in the TOC. They follow the same pattern as all links. I havfe unchecked "parseTextConvertNotesToBook" and the book builds very quick. Am I missing something?

/home/darrel/UniqueBible/David Rumsey - Timeline Collection.zip
/home/darrel/UniqueBible/marvelData/books/David Rumsey - Timeline Collection.book.zip

**Comment by otseng** [comment]
You'll need to set parseTextConvertHTMLToBook to true to parse links.  But, it'll take longer to build.  And it could cause issues with embedded images.

**Comment by darrelwright** [comment]
I am uploading a very small test set that just does not build properly. I don't think I am doing anything wrong. If I turn on parsing it never seems to build. If I turn parsing off it builds very quick, but hyperlinks will not work outside of study window.

[Rumsey -test.zip](https://github.com/eliranwong/UniqueBible/files/6837132/Rumsey.-test.zip)

**Comment by darrelwright** [comment]
I'm a bit frustrated. Either I am doing something wrong or there is still a problem building books. I am working with the Rumsey - test which contains 2 files. I build the book, then open it in control. But I cannot get the link to the image to work unless I am in the study window.

**Comment by otseng** [comment]
Can you embed the image instead of linking it?  That way the book will be truly portable.

**Comment by darrelwright** [comment]
It does not matter if embedded or linked. Something that bothers me - I have the small test case I sent you one book module and one image, really quite small. I turn on parsing links. That thing has been building for almost 2 hours and is still going. Something is not right. If I turn off parsing it builds in less than a minute, but the links only work inside the study window and not in a popup window. I hate to consider turning it loose on a big book build. Can you look at your code and determine what is taking such a huge amount of time? Currently this feature is unusable by me. I can build books, commentaries and dictionaries in theWord extremely fast. Why so long here?

**Comment by otseng** [comment]
The fundamental problem is links not working in a popup window.  I'll have to research that...

**Comment by darrelwright** [comment]
Yes, that, but also why does it take so long to build a book when parse 
is turned on? I have been runing 2 hours on building a book with 1 
module and 1 image. Is it parsing the image?

**Comment by darrelwright** [comment]
I just did a test:

1. The huge amount of time appears to be parsing the image. I removed 
all reference to the image, ran the build and it finished in under a minute

2. Hyperlinks are still not working right. If I open the UBA modules in 
the study window, click a link to return to the TOC it works great. If I 
open the book in a popup window OR in the study window the hyperlinks DO 
NOT work.

So two issues: one concerning images and the other concerning hyperlinks 
in the completed book.

Also just so you - I have another instance of UBA running and the build 
process, including 1 module and 1 image has been running for 2 hours and 
still not done!

**Comment by otseng** [comment]
I created a folder with 3 HTML files.  Convert this to a book and see if you can click the links in a popover window.

[BookTest.zip](https://github.com/eliranwong/UniqueBible/files/6844962/BookTest.zip)

**Comment by darrelwright** [comment]
No the links do not do anything

**Comment by darrelwright** [comment]
Is that code in 25,88?

**Comment by otseng** [comment]
> Is that code in 25,88?

Yes

Can you try this book?

[BookTest.book.zip](https://github.com/eliranwong/UniqueBible/files/6844990/BookTest.book.zip)

**Comment by darrelwright** [comment]
I did another test on the booktest. It got further this time, but threw 
an error "Entered command is invalid! 'BOOK:::BOOKTEST:::Index'

**Comment by darrelwright** [comment]
Ah Ha!! You had typed BookTest as BOOKTEST, so I changed it to BookTest, 
recompiled and the link work now!

**Comment by darrelwright** [comment]
Is the hyperlink code in25.88 or will it be in 89? I just did a compile 
on my small book with no image and the links do not work.

**Comment by darrelwright** [comment]
Yea, there is definitely something different between the html and uba 
code. I copied a link from your html code and put it in one of my uba 
files, and get the same no work.

**Comment by darrelwright** [comment]
The code does appear to bypass parsing image and is fast. Now if we can 
get links to work we should be gold!

**Comment by otseng** [comment]
Oops...  Fixed BookTest files...

[BookTest.zip](https://github.com/eliranwong/UniqueBible/files/6845264/BookTest.zip)
[BookTest.book.zip](https://github.com/eliranwong/UniqueBible/files/6845266/BookTest.book.zip)

>  I copied a link from your html code and put it in one of my uba
files, and get the same no work.

When you use the link, make sure there is no formatting in it.  Highlight the link code and hit the clear formatting button.

<img width="867" alt="Screen Shot 2021-07-19 at 11 21 06 PM" src="https://user-images.githubusercontent.com/806056/126257116-a8b9e758-6db1-4dae-97a3-eb66a6619485.png">

**Comment by darrelwright** [comment]
I am not sure what to do. When I build BookTest the links play 
beautifully. When I build my test they do not play. It does not matter 
how I set the parse flag, the links in a uba file just don't work.

Also when I try to build a book containing an image it is taking a very 
long time with just 1 image!

from BookTest:

***[BOOK:::BookTest:::Chapter 1@Chapter 1]

from Rumsey - test:

***[BOOK:::Rumsey - test:::a - jpg@View Picture]

**Comment by darrelwright** [comment]
Here is as simple a test as I can get - toc and screen1. I built the book, but the links do not work. I tried with parse checked and unchecked.

[Rumsey - test2.zip](https://github.com/eliranwong/UniqueBible/files/6846723/Rumsey.-.test2.zip)
