### ISSUE TITLE
Control List window - need a search bar to find desired commentary and/or book

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#672]
Could you add search functionality on the master control library 1 and library 2 windows?

**Comment by otseng** [comment]
Can add additional search features in the fourth tab (search tab).  What would you like to add?

I'm thinking one useful feature is to add "Check all", "Check none" for the books.

**Comment by darrelwright** [comment]
I've got over 500 books, and I know I can search all books for a given 
text, such as finding all books that deal with "Darius" or "Paul". I'd 
like to search my book titles, so if I am looking for all my books that 
Morgan Campbell wrote about Paul or I want to see just the book titles 
dealing with revival. When you enabled directories in the control list 
that really helped me to group books by author. Now I'd like the ability 
to narrow that list down to just books dealing with a specific topic or 
set of topics. Is that possible?

**Comment by darrelwright** [comment]
I did  a pull, tried to start UBA and it won't start. Here is a snap of 
the pull and resultant error
