### ISSUE TITLE
Need ability to import morphology data in theWord RTF bibles

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#674]
It would be really good if we can import morphology data when importing RTF OT bibles

**Comment by otseng** [comment]
Select "Allow search for morphology codes" in the Import options.  

<img width="378" alt="Screen Shot 2021-07-19 at 11 27 34 PM" src="https://user-images.githubusercontent.com/806056/126257462-3e4061a2-2f0b-4301-afef-e045b29b1b74.png">

Then import the LXX file.  You'll then see this:

<img width="689" alt="Screen Shot 2021-07-19 at 11 26 15 PM" src="https://user-images.githubusercontent.com/806056/126257393-514df04f-45d6-41ac-9d51-a43d2b76153a.png">
