### ISSUE TITLE
input method breaks on Chrome OS, Debian 10, wayland

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#68]
It is found that input method fcitx breaks on Chrome OS, Debian 10, wayland.  The mainwindow closes and reopen unexpectedly.  This is probably due to a bug in the wayland compositor Chrome OS uses, as indicated by the error message poping up at launch:

> qt.qpa.wayland: Ignoring unexpected wl_surface.enter received for output with id: 7 screen name: "Screen5" screen model: "202B" This is most likely a bug in the compositor.

I will try to find a workaround for it.

**Comment by eliranwong** [comment]
In the upcoming fix, we use an invisible window to wrap the main window in order to get around the possible wayland compositor bug.

We have this notes in the code:

# BufferWindow() is an invisble window to wrap the main window.
# It looks like that it is redundant, but it is created to get around a bug that probably caused by a wayland compositor in Chrome OS's Linux container (version 87).
# The bug breaks input method fcitx.  With this BufferWindow in place, fcitx now works properly with Unique Bible App desktop version.
# It does not sort out all issues caused by the possible bug in the wayland compositor.  At launch the main window closes and reopen when users type in command field.
# A workaround to type command in Chrome OS is to use remote control, called by "ctrl + o" key combination.

**Comment by eliranwong** [comment]
We also added a workaround feature to address this issue.  You may read more at: https://github.com/eliranwong/UniqueBible/wiki/preferRemoteControlForCommandLineEntry

Chrome OS users who encountered this issue should have preferRemoteControlForCommandLineEntry option enabled.

**Comment by delong369** [comment]
I have this issue while opening altamaker Cura and it said deprecation warning that imp module is deprecated in favor of importlib and slated for removal in python 3.12; see the modules documentation for alternative uses GT.GPA Wayland ignoring unexpected WL surface enter received for output with ID 7 screen name screen 5 screen model unknown this is most likely a bug in the compositor are there any commands I can use to fix this? Thank you
