### ISSUE TITLE
SALUDOS Y AGRADECIMIENTOS DE ESPAÑA

### ISSUE THREAD

**Issue by Elvis75Cristiano** [eliranwong/UniqueBible#681]
Dios les bendiga mucho. Gracias por su trabajo. Bendice mucho nuestras vidas. Un abraso muy fuerte de España. Que Dios les pague abundantemente.

**Comment by otseng** [comment]
You're welcome.😇

Can you do something for us?  We did the language translations without knowing any of the foreign languages.  If you see things in the Spanish translation that needs to be modified, can you let us know?  The file is at:
<https://github.com/eliranwong/UniqueBible/blob/main/lang/language_es.py>

**Comment by Elvis75Cristiano** [comment]
Hola muy buenas. Dios les bendiga mucho. Claro que si hermano, con placer. Ademas podria ayudarles tambien con la traduccion al Rumano.

**Comment by otseng** [comment]
Thank you
