### ISSUE TITLE
theWord OT and ONT Hebrew bibles are not importing in RTL

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#684]
I have Old Testament Text Direction: Right-to-left checked. I import Hebrew Westminster LC, WLC and WLC+ and they are imported LTR. Am I missing something?Here's 2 bibles to play with:

[Hebrew Westminster LC.ot.zip](https://github.com/eliranwong/UniqueBible/files/6851307/Hebrew.Westminster.LC.ot.zip)

[WLC+.ont.zip](https://github.com/eliranwong/UniqueBible/files/6851302/WLC%2B.ont.zip)

**Comment by darrelwright** [comment]
When I look at the WLC it imported RTL perfectly (including the fonts!), but WLC+ (as an example) did not and it has font issues.

**Comment by otseng** [comment]
For RTL, all it's doing is modifying the config file to determine if it's displayed RTL.  Add your Bible to the rtlTexts in config.py

```
rtlTexts = ['original',
 'MOB',
 'MAB',
 'MIB',
 'HWLC',
]
```

For the font issue, will need to play around with it.

**Comment by darrelwright** [comment]
On RTL that worked perfect. Thanks!

**Comment by darrelwright** [comment]
the font issue is kinda interesting - there appears to be only 1 letter 
that has a problem (i.e., בְּרֵאשִׁ֖ית, and yet in BHS+(as an example) 
it displays properly (בְּרֵאשִׁית). In the bibles (such as BSB Interlinear 
OT and WLC+) it appears to be the accent on 4th letter from the right 
that causes the issue.
