### ISSUE TITLE
bottom window font request 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#688]
Will you consider making bottom window also to show the font the Bible uses on hover?
![image](https://user-images.githubusercontent.com/48617390/126659329-d3a36888-253e-472a-b8fe-fcf99dc6dd51.png)

**Comment by onegladiator4u** [comment]
brother , this worked on normal window . but in comparison mode it didn't work .
![image](https://user-images.githubusercontent.com/48617390/127129334-061d046b-b7ee-4cb4-b83b-c811298ced04.png)

![image](https://user-images.githubusercontent.com/48617390/127129570-a4be8cdd-5480-406b-b049-056f9807e90e.png)

**Comment by otseng** [comment]
How are you showing 2 translations in the bottom window?

**Comment by onegladiator4u** [comment]
> How are you showing 2 translations in the bottom window?

from the beginning it was like that .
Does it have to do it with selecting a favorite Bible? when i choose my favorite bible as `MOV` malayalam bible it shows 2 versions . when I choose different one , it'll show that version below malayalam verse. if i restart app then it'll show only that version . i really liked 2 versions .so i kept MOV as favorite bible . now it shows 2.
