### ISSUE TITLE
How to access/use 15 built-in dictionaries

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#694]
I don't see how to effectively use the built-in dictionaries that show on the Dictionaries tab on the mini Control and the search screen. I need some way of knowing what the modules contain so I know what to search for.

**Comment by otseng** [comment]
It's searching by English words.  For example, search for "river":

<img width="1440" alt="Screen Shot 2021-07-26 at 8 09 27 AM" src="https://user-images.githubusercontent.com/806056/126986462-ed44e9bb-b81d-46d5-986d-86b8872c82fe.png">

**Comment by otseng** [comment]
One thing I will change is how it searches. Right now, you have to press the button, then add the search term, then hit enter.  I'll make it so you enter the search term, then hit the button to search.
