### ISSUE TITLE
Issue between 3rd party dictionary and lexicon

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#695]
I have a dictionary that I converted to a lexicon (see attachments). I pull up Gen 1:1 in the MIB and click on "ברא". When the lexicons show I select LEM (the lexicon) and nothing displays. When I right-click on "ברא", walk down the list to Bible resources, then to 3rd party dictionaries, then select "LEM" I get the results shown in the png. From the lexicon list I get nothing. It appears that when I click an entry and select from the list of lexicons that UBA is pulling its search entry (in this case) as E70003 rather than "ברא". Can we rework how UBA goes after its lexicon data?

More precisely, when clicking on "ברא" or any lemma UBA pulls from another dictionary where it picks up (in this case) either E70003 or H1254 rather than "ברא", then when clicking on "More Lexicons Here" it uses (in this case) either E70003 or H1254 as its search criteria for other lexicons and returns potentially bad results. Again, can we rework this?

[LEM.lexicon.zip](https://github.com/eliranwong/UniqueBible/files/6875986/LEM.lexicon.zip)
[LEM.dct.mybible.zip](https://github.com/eliranwong/UniqueBible/files/6875991/LEM.dct.mybible.zip)
![lem](https://user-images.githubusercontent.com/11500764/126941277-a3750dd2-d707-4c82-a7d9-9b7dd9f75544.png)

**Comment by otseng** [comment]
Don't think it's possible to really alter the way MIB works since all the links are defined in the database.  For instance, in the database, it's:  
`<ref onclick="lex('E70003')" ondblclick="searchLexicalEntry('E70003')"><wlex><heb>ברא</heb></wlex></ref>`

**Comment by darrelwright** [comment]
Ouch! I have 44 lexicons that get affected by this. So you're saying 
that I must alter how I go after things by using some other bible since 
there are not many that I can just click on a word and have UBA jump to 
a dictionary.

So I have another question. Can we set up a database that links a 
default dictionary to a Bible. For example I have BSB Interlinear NT 
open to Acts 17:28. I would like to click on "αὐτός" and have it open 
MLSJ to that entry (which is essentially what happens with MIB except 
it's picking up the Strong's number and opening TBESG).

Make sense?

**Comment by otseng** [comment]
Another option is if can have some database that can link E70003 to ברא, then can use that to link to your dictionaries.

> Can we set up a database that links a default dictionary to a Bible.

That is possible also.

**Comment by darrelwright** [comment]
Either one of those is good. Now about that to-do list ....😂

**Comment by otseng** [comment]
Another option is to created a MIB enhanced (MIBE) version.  It would add another link to be able to search on the words.

**Comment by darrelwright** [comment]
Is anything happening on this?

**Comment by otseng** [comment]
I have an idea to experiment with this.  How about I convert the searchLexicalEntry to lexicon via a plugin?

**Comment by darrelwright** [comment]
This looks very good. Need to play with it, but I like what it opens up. 
Thank you!

**Comment by darrelwright** [comment]
Cool!
