### ISSUE TITLE
Links are not generated in dakes commentary 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#696]
Don't know whether it's only in dakes.
Verse links are not generated when Dakes commentary is imported through github commentary .
![image](https://user-images.githubusercontent.com/48617390/126988214-ffd74fba-e009-4460-912a-699cc4d3736c.png)

**Comment by otseng** [comment]
I uploaded a new Dakes commentary.  Can you delete  marvelData/commentaries/cDakes.commentary and redownload it?

If there's any other commentaries that need updating, feel free to create another issue.
