### ISSUE TITLE
owens hebrew commentary issues

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#698]
noticed that cOwenHebrews commentary from github commentary has some issues .
some words gets bigger and window looks larger with scrollbars. free spaces also

![image](https://user-images.githubusercontent.com/48617390/127038757-abb631f2-f373-49ce-b61f-b96467371b04.png)
![image](https://user-images.githubusercontent.com/48617390/127038877-d3a9f299-4037-465b-96a9-bb1a2aafa466.png)

**Comment by otseng** [comment]
There's too many issues with it, so I deleted it from Github.  I did however find it as a PDF so its available under Github PDF download.

**Comment by onegladiator4u** [comment]
> 
> 
> There's too many issues with it, so I deleted it from Github. I did however find it as a PDF so its available under Github PDF download.
oh ok

**Comment by onegladiator4u** [comment]
@otseng may i ask you which commentary you use?

**Comment by otseng** [comment]
> @otseng may i ask you which commentary you use?

Actually, I don't regularly use a commentary.  All of my studies now are focused on translating, so spending most of my time learning Greek and Hebrew.  That is when I'm not coding UBA.  :)

**Comment by onegladiator4u** [comment]
> 
> 
> > @otseng may i ask you which commentary you use?
> 
> Actually, I don't regularly use a commentary. All of my studies now are focused on translating, so spending most of my time learning Greek and Hebrew. That is when I'm not coding UBA. :)

Oh ok brother. Are you learning Greek and Hebrew by yourself ?

**Comment by otseng** [comment]
> Oh ok brother. Are you learning Greek and Hebrew by yourself ?

Pretty much just through UBA and Youtube.

**Comment by onegladiator4u** [comment]
> Pretty much just through UBA and Youtube.

Oh ok.
