### ISSUE TITLE
Issue with Deut books

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#702]
I open control bible panel, select Deut, select 1Enoch, chapter 1 and verse 1. I then click Bible window which should open 1Enoch in the Bible window, but it does not. The first screen shot (deut 1) shows the reference I entered. When I click Bible window UBA shows the 2nd screen shot. This just started with version 25.94

![deut 1](https://user-images.githubusercontent.com/11500764/127262431-68bd3ec0-28ea-4a65-ad4d-3503fddfa367.png)
![deut 2](https://user-images.githubusercontent.com/11500764/127262442-17692e34-b161-4c79-84d8-b7b953552787.png)

**Comment by otseng** [comment]
One thing strange is in your Bible dropdown, it's "Deut" instead of "DEUT".  What is the file called in marvelData/bibles?

**Comment by darrelwright** [comment]
I deleted it and redownloaded it from GitHub Bibles and have the same 
thing happening. I'm really not senile. Prior to 25.94 (and possibly 
25.93) I could use DEUT perfectly. Now I cannot.

**Comment by otseng** [comment]
I wonder if UBA is getting confused with the book of Deut.  I've uploaded file to Github called "DEUTC".  Can you try that?

**Comment by darrelwright** [comment]
What results should I see? When I ran DEUTC it's giving the same results 
I reported. Should I set as developer and try again?

**Comment by darrelwright** [comment]
When I click on DEUT I get the message that "'DEUTC' does not contain 
this chapter".

**Comment by otseng** [comment]
Don't click on DEUT.  Only click on DEUTC for the Bible.  Then click on 1Enoch for the book.

<img width="1440" alt="Screen Shot 2021-07-28 at 10 46 28 PM" src="https://user-images.githubusercontent.com/806056/127423697-86a9681c-820f-4fcc-a45f-f989bb5008ed.png">

**Comment by darrelwright** [comment]
That's what I did. I delete DEUT first, then imported DEUTC. What 
appears to happen when clicking on DEUTC it's trying to go after the 
last book and verse and does not recognize the deut book and chapter.

**Comment by otseng** [comment]
Go to the config.py file and rename all references of DEUT to DEUTC.

**Comment by darrelwright** [comment]
I did that and still get same results. It tries to do a search rather 
than opening DEUTC

**Comment by otseng** [comment]
OK, was able to duplicate it.  Something is wrong when the useLiteParsing is false.

**Comment by darrelwright** [comment]
Yeah!!!

**Comment by darrelwright** [comment]
Yes it does have to with lightParsing being false. If I enable it DEUT 
works perfectly.
