### ISSUE TITLE
Continuing issue with building module from e-sword book

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#703]
I am attaching the e-sword refi file, the book built from it with parse flag checked and the screen shot showing the bible links that do not work. When I click Heb 1:1-2 nothing happens. The bible window does not change to that verse. If I am missing something please tell me. Either there is something different between your system and mine or ... It just does not work!

[Stevenson - Studies in the Doctrines of the Bible.refi.zip](https://github.com/eliranwong/UniqueBible/files/6890393/Stevenson.-.Studies.in.the.Doctrines.of.the.Bible.refi.zip)
[Stevenson - Studies in the Doctrines of the Bible.book.zip](https://github.com/eliranwong/UniqueBible/files/6890396/Stevenson.-.Studies.in.the.Doctrines.of.the.Bible.book.zip)
![stevenson](https://user-images.githubusercontent.com/11500764/127265638-edcf9cea-4ee0-4ddc-82fa-3e053b626cec.png)

**Comment by otseng** [comment]
Now importing the refi books will parse verse references.  This will make it take longer to import it, but you can see the status of the import by turning on config.enableLogging.  Then look at the uba.log file.  It will log each chapter as it's being converted.

**Comment by darrelwright** [comment]
That worked, whatever you did! Stevenson converted I watched it build in 
uba.log, it finished and the bible links work! Now I have to go 
re-import some books. Thank you my friend!
