### ISSUE TITLE
Enhanced Morphology Search tool

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#710]
We have a pretty sophisticated morphology search in UBA, but it still requires a good grasp on using the command line. PC Study Bible has a really good GUI search screen that takes the hard part out of sophisticated morph searching. Is there any change of getting something similar to the attached screen shot in UBA?

![Greek Morphological Search](https://user-images.githubusercontent.com/11500764/127725976-050f4ad3-f375-4550-9191-838896c2036c.png)

**Comment by darrelwright** [comment]
I am looking for a way to do something like "MORPHOLOGY:::LexicalEntry LIKE '%G746,%' AND (INTERLINEAR LIKE '%rule%' OR INTERLINEAR LIKE '%ruler%')" or even "MORPHOLOGY:::LexicalEntry LIKE '%G746,%' AND Morphology LIKE '%Singular%' AND (Translation LIKE '%rule%' OR Translation LIKE '%ruler%')" from a GUI. That way I don't have to memorize how to build strings like these. Can we do that?

**Comment by darrelwright** [comment]
Actually this would be pretty easy to do I think. Just expand how morph works now when double-clicking a word, but tie the expanded window to a menu plugin so its morph elements are not dependent on a particular word. What do you think?

**Comment by otseng** [comment]
I'll add another tab to master control to do this.

**Comment by darrelwright** [comment]
I love having this tool, but I must not be understanding something. No matter what I enter I get 0 hits. I select N-ASM, NT, I put the word "account" in the search field and I get 0 hits. I leave the search field blank and nothing happens. I put a bible name with morphology in the search field and get 0 hits.

What am I missing?

**Comment by darrelwright** [comment]
Just so you know, I posted an issue with the enhanced morphology sear 
tool ....

**Comment by darrelwright** [comment]
Ah Ha! I figured out how to use it (I think)! This returned 1 result:

![morph](https://user-images.githubusercontent.com/11500764/127850951-529a3b4f-8eb2-445f-b7b0-c238bdee8cf9.png)

**Comment by otseng** [comment]
I've added instructions in the wiki:
https://github.com/eliranwong/UniqueBible/wiki/Search-morphology#morphology-search-tab

**Comment by darrelwright** [comment]
thanks Oliver, that helped. I just did a search for the gloss "God" 
specifying Pronoun and Dative and returned 322 hits. Cool!
