### ISSUE TITLE
Showing different Word translations across bibles

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#713]
This is a bad title, but the best I can do for now.
I want to several bibles open (either in parallel or one in the bible window and one in the study window), then when I hover (or possibly click/double click) on a word I want whatever word form in the 2nd translation to be highlighted. The following screen shot shows how Accordance does this. I know how to sync bibles, but I want to go one step further and be able to see how a word is translated in different bibles.

![highlight](https://user-images.githubusercontent.com/11500764/127753611-3f1674b3-872c-42cd-8022-06ae6c89f9d1.png)

**Comment by otseng** [comment]
I saw Mounce doing this while teaching a passage on Youtube and thought that was pretty neat.  The closest I've seen UBA with this is the TDW Combo - `COMBO:::Esther 8:9`

But to do this, it'll require every word to be keyed to an id.  Eliran did this for the TDW Combo.  I'm not sure how he did that.

**Comment by eliranwong** [comment]
MPT was created for this purpose.

**Comment by darrelwright** [comment]
Did you mean MPB? I am not sure what BPT is.

**Comment by darrelwright** [comment]
So how does one do this with the MPB to compare words in different translations?

**Comment by darrelwright** [comment]
How to use this version to show various word translations across multiple bibles?

**Comment by darrelwright** [comment]
You closed this but I do not see how to do this. Can you give example 
please?

**Comment by eliranwong** [comment]
okay, will give you some examples.

I will modify 2 lines in a plugin.

Marvel bibles already have this feature

this will work only in Strong's number module

**Comment by eliranwong** [comment]
added mutual highlights in version 30.97

remarks: How good it works depends on how good your Strong's number bible is tag.  do not complain about UBA if your own modules are not properly tagged.

please see the following example
<img width="1440" alt="mutual_highlights" src="https://user-images.githubusercontent.com/25262722/176723535-cef45dba-04d5-4ea8-a406-d16104e22428.png">

**Comment by eliranwong** [comment]
more examples below:
<img width="1440" alt="mutual_highlights3" src="https://user-images.githubusercontent.com/25262722/176746774-88587032-6176-473a-b732-7ca3c7fcef8a.png">
<img width="1440" alt="mutual_highlights2" src="https://user-images.githubusercontent.com/25262722/176746797-f4b41f85-3669-498c-a941-e94b92b14e5c.png">

I think enough examples.  I am closing this issue.

**Comment by darrelwright** [comment]
I thank you for what you did on #713. Maybe I am not understanding 
something. The attached image shows two bibles: AFVs and KJVx. I can 
hover on a strongs number, say G2424, and that number highlights in all 
open bibles.

If I click hideLexicalEntryInBible, then the strongs numbers are hidden, 
and now if I hover a word the corresponding word(s) in the other bibles 
are highlighted. Is that how it is supposed to work?

Is there a way to mark the highlighted word(s) for more study?

**Comment by darrelwright** [comment]
i guess I've been gone too long. What is MPT?
