### ISSUE TITLE
Official reverse interlinear

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#715]
I'd love to have a marvel.bible reverse interlinear, like a reworked MIB as a reverse interlinear!

**Comment by darrelwright** [comment]
Anything happening yet?

**Comment by otseng** [comment]
Sorry, I have little time now to work on UBA.  Would be great if others can also contribute to the project.

**Comment by eliranwong** [comment]
Sorry, I don't want a reverse interlinear.  I think the highlighting of MTB or MPB is better than using a reverse-interlinear.

**Comment by darrelwright** [comment]
I would prefer you to not close this request, for maybe someone will 
also see the need and do something with it!
