### ISSUE TITLE
Jewish Encyclopedia 1901-1906 has issue

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#718]
This is from hithub commentaries .
![image](https://user-images.githubusercontent.com/48617390/127780840-839742aa-0667-4ae2-accf-a747c27c00aa.png)
This commentary won't show up if we select a book. because it has chapters as `0`.
if we change the chapter to `0` in command then only  it'll show.
![image](https://user-images.githubusercontent.com/48617390/127780901-81f9808d-ab6f-4a10-a5fc-2ed1df36397a.png)

also found out that we can look for commentaries by clicking this button .
![image](https://user-images.githubusercontent.com/48617390/127781042-3bd2d6a7-1c80-490c-b459-24a0e43c70df.png)
it'll take us through available ones.
![image](https://user-images.githubusercontent.com/48617390/127781111-3b2886d8-c9be-4f41-8341-5904bb6cf803.png)
 it'll be a helpful info to add to wiki page if it didn't have this info.

**Comment by otseng** [comment]
Created issue for better support of commentary intros

https://github.com/eliranwong/UniqueBible/issues/720
