### ISSUE TITLE
Better support of commentary intros

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#720]
Add Better support of commentary intros

https://github.com/eliranwong/UniqueBible/issues/718

**Comment by onegladiator4u** [comment]
hey @otseng Do we have to type `COMMENTARY:::JE-TNK:::Genesis` like this to get the intro or is there any way else ?

**Comment by otseng** [comment]
> hey @otseng Do we have to type `COMMENTARY:::JE-TNK:::Genesis` like this to get the intro or is there any way else ?

Right now, it's the only way.  I'll be adding more ways in upcoming releases.

**Comment by onegladiator4u** [comment]
oh ok.

**Comment by otseng** [comment]
Now can pull up commentary book intros in miniControl and html chapter menu.

**Comment by onegladiator4u** [comment]
even though i don't know how to pull it up from html menu, it's working with mini control .that is great.
thanks
