### ISSUE TITLE
Showing different Bible version on hover

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#727]
These command opens the verse in main window now. 
`***[BIBLE:::LXXUK:::Amos 7:1@Amos 7:1]` for LXXUK or
`***[BIBLE:::ESV:::Amos 7:1@Amos 7:1]` for ESV
`***[BIBLE:::LXX1:::Amos 7:1@Amos 7:1]` for greek 
it would be a good addition if we have an option to change what Bible version to show on bottom window on hover Bible references through different CMD links like or similar to these. 
Now it shows KJV with favorite Bible in bottom .

![image](https://user-images.githubusercontent.com/48617390/128303727-278bbb3b-9682-47c8-8367-d6af8ee8f6f2.png)

**Comment by onegladiator4u** [comment]
hey @otseng , just noticed that when current bible version is different , hover won't show the font of that bible.
![image](https://user-images.githubusercontent.com/48617390/128515032-353e75d5-d20e-49da-807a-85bbc3bdf80a.png)

is it because of this enhancement ?

**Comment by otseng** [comment]
> is it because of this enhancement ?

Most likely.  This is such an edge case scenario that I'd say you're the only one in the world that would encounter this.  😸

**Comment by onegladiator4u** [comment]
> Most likely. This is such an edge case scenario that I'd say you're the only one in the world that would encounter this. 😸

Haha. Well, then it's ok. thanks for your works brother .
