### ISSUE TITLE
Expanded Search funtionality

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#736]
Need search expanded to search different repositories when looking for a specific word. If that module is not installed offer option to install it.

**Comment by darrelwright** [comment]
If I am understanding how this works, I enter a word ("hinder" which is in Dungan's book Hermeutics) in the search field and UBA (since I removed that book locally) should find it in Github Books, but it does not. Am I missing something?

**Comment by otseng** [comment]
The library catalog only searches the filename, not the contents.  

To search for a filename that exists in Github, select the Remote.  Then you can search for "Dungan".

**Comment by darrelwright** [comment]
Oh that's cool! I did not even see the remote. It works great!
