### ISSUE TITLE
Library book, introduction and timelines fail to find modules in subfolders

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#740]
I have used sub-folders to organize my books. When I click on Library book, introduction or timelines it fails to find the corresponding books when they are in sub-folders and not in books. UBA should be able to find them when the sub-folders are under books.

**Comment by otseng** [comment]
Can you put in screenshots for me to try to replicate this?

**Comment by darrelwright** [comment]
![timeline](https://user-images.githubusercontent.com/11500764/128613802-76598ae9-1c73-47ac-bb5e-819b320979e9.png)

**Comment by darrelwright** [comment]
That now works beautifully. Thanks!
