### ISSUE TITLE
"Bible Window Bible Reference" button no longer works after installing 25.77

### ISSUE THREAD

**Issue by jdecent** [eliranwong/UniqueBible#742]
I must use Bible option under Master Control menu or keyboard shortcut.

**Comment by otseng** [comment]
That is quite an old version.  Current version is 26.04.  Could you redownload the latest UBA version and see if you still have that issue?

**Comment by jdecent** [comment]
Before this issue I tried opening UBA and was alerted that an update was available so I started update process. After it finished the main app window would no longer open. So I deleted the installation folder and downloaded the master from https://github.com/eliranwong/UniqueBible/wiki/Installation . I assumed it would be the latest. Anyhow I successfully updated via Update in the menu. I still have the same problem. Could you link the latest download link?

**Comment by jdecent** [comment]
I am still having the same problem. If my memory is correct. Clicking that button used to do the same as CTRL+B. It currently seems that its only affect is to open selected bible tab to the address visible on the button.

**Comment by otseng** [comment]
Ah, I see one problem.  That wiki page has old info.  

I've now updated it.  It was referring to master.zip, but it should've been main.zip.  

Can you redownload with this:
https://github.com/eliranwong/UniqueBible/archive/main.zip

**Comment by jdecent** [comment]
Sorry for the delay. I used the link provided and I don't see any difference in how the button functions.

**Comment by otseng** [comment]
Can you see what the UBA Preferences/Select Menu Layout/Reference Button Action is set to?  It's at:

<img width="800" alt="Screen Shot 2021-08-14 at 2 51 45 PM" src="https://user-images.githubusercontent.com/806056/129457477-74b5a567-3ca7-4a8d-8675-e5dfcbb96e5b.png">

<img width="400" alt="Screen Shot 2021-08-14 at 2 52 10 PM" src="https://user-images.githubusercontent.com/806056/129457480-fd3e925a-3b71-424a-8f9b-08a9376f8c9b.png">

**Comment by jdecent** [comment]
It was set to Direct. I switched to Master Control. I now functions as I expected. Is it normal that the Direct option is the default for a fresh install?

**Comment by otseng** [comment]
> It was set to Direct. I switched to Master Control. I now functions as I expected. Is it normal that the Direct option is the default for a fresh install?

Yes, currently set to direct for a fresh install.

**Comment by otseng** [comment]
I'll change it to default to master in next release.
