### ISSUE TITLE
Add jump to anchor for books

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#755]
Add jump to anchor for books

https://github.com/eliranwong/UniqueBible/discussions/130#discussioncomment-1184196

**Comment by otseng** [comment]
https://github.com/eliranwong/UniqueBible/wiki/How-to-execute-a-command-in-a-book-generated-from-HTML#jumping-to-an-anchor-in-a-book

**Comment by onegladiator4u** [comment]
@otseng Hi brother ,
this feature is now not working i think. Can you check ?
i tried a link from note to an id in a book. it didn't work . tried changing id to name too..

**Comment by otseng** [comment]
Could attach the book you're using?

**Comment by onegladiator4u** [comment]
[Josephus.zip](https://github.com/eliranwong/UniqueBible/files/10323579/Josephus.zip)

I was pointing to Antiquities of the Jews Book 19 Chapter 8 Sec 2.
The anchors were working when i checked months ago. Now old ones are not working too.

**Comment by otseng** [comment]
Do you mean jumping to/from footnotes?  That's working for me...


https://user-images.githubusercontent.com/806056/210156593-66ed16ae-5cba-4823-9b92-09f105b04aa0.mp4

**Comment by onegladiator4u** [comment]
No, its not the one i had in mind .
I created an id for a section in Josephus using DB browser like this
![DB_Browser_for_SQLite_ivNtOSZtcK](https://user-images.githubusercontent.com/48617390/210162675-57498f1d-7793-4423-8f54-896b86d02312.png)
Then created a link to that in note like this 
 
![HwXu5zK7cj](https://user-images.githubusercontent.com/48617390/210162734-22d20b82-d150-4edb-b0ff-6f57fd43b471.png)
It should go to that section in book when we click on it. But it's not going to it anymore . it used to go there before . Now it only goes to the top.
![python_j5iOpnZLkC](https://user-images.githubusercontent.com/48617390/210162910-4bf16ecd-0791-440d-a45c-23abab21ccaa.gif)

You created this issue when we discussed about it. 
> Add jump to anchor for books
> 
> [#130 (reply in thread)](https://github.com/eliranwong/UniqueBible/discussions/130#discussioncomment-1184196)

Btw, Happy New Year brother .

**Comment by otseng** [comment]
Got it.  Made a fix.  See if it works now.
Happy New Year!

**Comment by onegladiator4u** [comment]
@otseng Yes, it's working now. Thanks bro

**Comment by onegladiator4u** [comment]
@otseng hey bro, did this mess up commentary anchor tags?

**Comment by otseng** [comment]
> @otseng hey bro, did this mess up commentary anchor tags?

Can you send video shot?

**Comment by onegladiator4u** [comment]
First I'm clicking on verses to go to its commentary. Study window not changing .
If we open that commentary on plugin, it opens it's corresponding commentary .
I checked on toggles whether it's syncing . It is.

https://user-images.githubusercontent.com/48617390/210258737-9f682e5c-a2aa-4f09-a0ea-b050f588ce4c.mp4

**Comment by otseng** [comment]
Commentaries don't have anchors to verses.  Does it work if you go to a different chapter?

**Comment by onegladiator4u** [comment]
> Commentaries don't have anchors to verses. Does it work if you go to a different chapter?

Oh my bad. Then it's a different problem . Yes, it changes on chapters , not on verses. This problem arise after the update , so i thought it might be because of it.
If i change verses on plugin commentary , it works . Not on study window .

**Comment by eliranwong** [comment]
> Commentaries don't have anchors to verses. Does it work if you go to a different chapter?

commentaries do have anchors, but now not working on Study Window?  Is it because of a recent change?

e.g. anchor with the following command works on commentary plugin, but not on Study window.

COMMENTARY:::CBSC:::Jn 3:16

**Comment by eliranwong** [comment]
anchors to commentary verses worked a few days ago

**Comment by eliranwong** [comment]
I found that this commit https://github.com/eliranwong/UniqueBible/commit/b233f9bdb00075a6478f5cb9703c44375dcfd79f causes the commentary issue:

![Screenshot 2023-01-02 6 55 04 PM](https://user-images.githubusercontent.com/25262722/210270106-59826935-7983-4679-a609-8e4947f96783.png)

I reversed the change in the latest code.  The commentary anchor works again.

**Comment by otseng** [comment]
I think now the book anchor doesn't work anymore
`book:::Josephus:::21 - Antiquities - Book19#chstwo`

**Comment by eliranwong** [comment]
> I think now the book anchor doesn't work anymore `book:::Josephus:::21 - Antiquities - Book19#chstwo`

how did book anchor work?  may modify the code for book anchor to make it work?

**Comment by otseng** [comment]
@onegladiator4u  posted how he made the changes manually to Josephus database in https://github.com/eliranwong/UniqueBible/issues/755#issuecomment-1368367324
After my change, it fixed that.  But obviously my fix also broke the commentary.  
I think it has to do with different places calling finishstudyviewloading incorrectly.

**Comment by eliranwong** [comment]
I can take a look into it

**Comment by eliranwong** [comment]
@onegladiator4u  @otseng with the latest code https://github.com/eliranwong/UniqueBible/commit/0ab6611bd969b31093376c990ad52ebb4d03508d both commentary and book anchors work.  thank you

**Comment by onegladiator4u** [comment]
@eliranwong @otseng Great .Thank you guys.

**Comment by eliranwong** [comment]
closing now ... thank you
