### ISSUE TITLE
Problem building a book

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#758]
When I am building a book and I enter a string like:

^(?:L(?<c1>)(?<c2>))+[^LM]+(?<-c1>M)+[^MR]+(?<-c2>R)+(?(c1)(?!))(?(c2)(?!))$

Then I delete formatting and the Note Editor changes the string to:

^(?:L(?)(?))+[^LM]+(?M)+[^MR]+(?R)+(?(c1)(?!))(?(c2)(?!))$

I have had other strings containing unique characters with the same result - the string gets modified.

I have to (currently) delete formatting in order to handle fonts in my book.

**Comment by otseng** [comment]
That is one complicated regex!
Can you just highlight the other text and delete that formatting instead?

**Comment by darrelwright** [comment]
Here's a simpler example. It comes from the attached book

(?<CAPS>[A-Z]+)

When I remove formatting on this line it changes to:

(?[A-Z]+)

So it seems the "<" and possibly ">" are not being handled? In the file this line is above the "How Capture Groups Get Numbered" section.

[09 - Capture & Back.uba.zip](https://github.com/eliranwong/UniqueBible/files/7024498/09.-.Capture.Back.uba.zip)

**Comment by otseng** [comment]
I'm thinking this is a special use case.  Most people will not be creating books with regex in it.  Instead of trying to handle regex expressions, I'm thinking of seeing if building books via PDF would solve the issue for you.  What do you think?

**Comment by darrelwright** [comment]
how do you see that working with this case? Would I be working with a 
PDF or a book, and could I search, copy, etc the contents?

You know, this is all your fault? You turned me on to RexEgg, which 
turned me on to RegexBuddy and now I am moving down a path to finally 
learn regex.😂😂

**Comment by darrelwright** [comment]
I only potential issue with treating it as a one-off is when someone wants to build a book that contains mathematical formulas. Since I think the problem involves the "<" and :>" symbols it could still affect others. So it seems that, rather than thinking along the line of regex, we should just deal with how "delete formatting" is handling those symbols. Check out this book (it's not quite done yet, but is looking pretty good!

[RexEgg.book.zip](https://github.com/eliranwong/UniqueBible/files/7026224/RexEgg.book.zip)

**Comment by otseng** [comment]
Here's what it's doing when clearing it:
```
                selectedText = re.sub("<[^\n<>]*?>", "", selectedText)
```

**Comment by darrelwright** [comment]
In the book I sent you I did not use the "Delete Formatting" and everything (regex code) came out good.

**Comment by otseng** [comment]
Looks good

**Comment by darrelwright** [comment]
I have finished it now (well, a little bit of cleanup to be done yet).

Also I just checked out converting PDF to book and I like it!
