### ISSUE TITLE
Book building problem

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#760]
My browser background is set to light, uba theme is set to light. I build a book with a weblink to an address. When I click the link in my book it opens the web address, but the background is dark and I cannot get it light. It should not be doing this.

![dark](https://user-images.githubusercontent.com/11500764/130298740-8009e8fc-65d5-4572-98b6-219c2fd46e71.png)

**Comment by otseng** [comment]
Can you attach the book here?

**Comment by darrelwright** [comment]
This is just one chapter with this very large book, but it demonstrates well the issue I am having. When you build this book, then drop down the the "regex uses" line, click on it and it opens in your browser. I have had the same results in Opera, Firefox and Chromium.

[28 - Regex Tools.uba.zip](https://github.com/eliranwong/UniqueBible/files/7024468/28.-.Regex.Tools.uba.zip)
