### ISSUE TITLE
Requesting Devotions be added

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#768]
I'd love to be able to work with devotions in UBA. I'd like ability to work with existing devotions and be able to add devotions from other sources

**Comment by otseng** [comment]
Could you break down the steps you'd like to do to create a devotional?

**Comment by darrelwright** [comment]
1. I'd like either a plugin or possibly another tab on Library 2 showing 
current loaded devotionals

2. Under Data/Convert I'd like the ability to import devotionals from 
our current sources, creating a devotional book type

3. The devotionals are linked to the current date.

**Comment by darrelwright** [comment]
Yes, each chapter would be a date. The date should be linked to the calendar similar to how the bible reading plugin works.

Here's an example from BibleAnalyzer:

[meyer.dev.zip](https://github.com/eliranwong/UniqueBible/files/7095071/meyer.dev.zip)

And here's one from theWord:

[Hoekstra's Day by Day by Grace.dev.twm.zip](https://github.com/eliranwong/UniqueBible/files/7095074/Hoekstra.s.Day.by.Day.by.Grace.dev.twm.zip)

**Comment by otseng** [comment]
I like this idea of having a devotional.  I'll work on this next.  However, I've got a large project at work that I'll be working on for the next several weeks.  But, I'll squeeze in some time to work on this.

**Comment by darrelwright** [comment]
Take care of yourself my friend!

**Comment by darrelwright** [comment]
Hey my friend,

I see the devotional entry, but am not sure what to do with it. When I 
go to resources/Add github devotionals there is nothing there. When I go 
to import/3rd party module I don't see a devotional entry. So am not 
sure just how to add devotionals. Can you help me?

**Comment by otseng** [comment]
Can you try changing UniqueBibleAppVersion.txt to 26.12?  And then rerun the update again?

**Comment by darrelwright** [comment]
I downgraded appversion, reran update and it updated uba to 26.13, but I 
still don't see anything I can with devotionals. Am I missing something? 
So nothing is pulled in from github, and nothing is shown on importing 
devotionals.

**Comment by otseng** [comment]
I believe the problem is a missing directory.  I was hoping the update would fix it.  
Can you manually create the directory "devotionals" under marvelData?

**Comment by darrelwright** [comment]
That worked! Are we going to have ability to create additional 
devotionals? Those 2 imported perfectly and I am now looking at 
devotional for 9/3. Thanks my friend!

**Comment by otseng** [comment]
I couldn't find any more HTML devotionals.  All the ones I could find are in RTF.  I'll probably work on doing a simple RTF to HTML converter.

**Comment by otseng** [comment]
I'll also work on the ability to create your own devotionals.

**Comment by darrelwright** [comment]
Cool. I can dig up some more html devotionals if you would like.

**Comment by otseng** [comment]
That would be great.

**Comment by darrelwright** [comment]
Here's 5 more. 😉

**Comment by otseng** [comment]
Info on creating a devotional:
https://github.com/eliranwong/UniqueBible/wiki/Devotionals

**Comment by darrelwright** [comment]
Import devx works nicely on e-sword devotionals!

**Comment by otseng** [comment]
> Import devx works nicely on e-sword devotionals!

There are some that have issues, in particular files that have complicated RTF codes in it.   There are also some that are exe downloads which I did not test.

**Comment by darrelwright** [comment]
Also the full name is not being imported. I imported Fortner -
