### ISSUE TITLE
Pinning map locations on a map

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#769]
I would like to pin more than one location on a map. Say I select Berea and it gives me that location on a map, but then I select Thessalonica I would that location pinned on the same map containing Berea. Can we do that?

**Comment by otseng** [comment]
I'm not familiar with the map feature.  How do you access it?

**Comment by darrelwright** [comment]
You mean the map feature in UBA or the one in BibleAnalyzer?

**Comment by otseng** [comment]
In UBA

**Comment by darrelwright** [comment]
You can click on the verse number (i.e., Acts 17:1), then in the study 
window you'll have Bible Locations showing Amphipolis, apollonia and 
thessalonica.

When you click, for example, Amphipolis it opens a map showing where it 
is located. I can send you a map from bibleanalyzer showing what it 
looks like if you want.

I'd like an option to keep the pinned locations and when I click another 
location to have it pinned on the same map

**Comment by eliranwong** [comment]
opening a map on a single place is already available

for multiple locations, follow https://github.com/eliranwong/UniqueBible/issues/1113

**Comment by darrelwright** [comment]
I HOPE we are not closing this issue in the state it is in. I want to 
use multiple pinned locations but have NO idea how to use these links to 
do that! I am HOPING either you or Oliver will take it to the next step 
so the tool is usable by the people who use UBA.

**Comment by eliranwong** [comment]
In my previous post, I already mentioned that you should follow the issue at https://github.com/eliranwong/UniqueBible/issues/1113 for multiple locations on a map.

**Comment by darrelwright** [comment]
Unless I am mistaken #1113 requires coding to implement those steps. I 
cannot do the coding!

**Comment by eliranwong** [comment]
follow issue there, not here

**Comment by darrelwright** [comment]
Not sure what you mean. If you folks don't want to do anything just say so. Sorry, I am a bit frustrated on this issue.

**Comment by eliranwong** [comment]
follow there https://github.com/eliranwong/UniqueBible/issues/1113 .  this issue is closed

you are totally mistaken, I think.

<img width="810" alt="Screenshot 2022-07-09 at 08 31 21" src="https://user-images.githubusercontent.com/25262722/178096422-d59f9c7a-d7fe-44e7-97b6-585854da8fc3.png">

**Comment by darrelwright** [comment]
Well, if I am mistaken then show me. I don't know how to use the Bible Locations screen show above. Can you show me?

**Comment by eliranwong** [comment]
I don't want to post on this issue anymore. I already said, use #1113

**Comment by darrelwright** [comment]
I have looked #1113 and I don't know what to do with it! So are we at an 
end, or is there something we can do? If you want to post on #1113 I 
don't have an issue with that. If we have reached an empasse I can deal 
with also.

**Comment by otseng** [comment]
@darrelwright 

The coding is not done yet.  It's being worked on in https://github.com/eliranwong/UniqueBible/issues/1113

**Comment by eliranwong** [comment]
@darrelwright you need to read the last post of https://github.com/eliranwong/UniqueBible/issues/1113

**Comment by darrelwright** [comment]
I can live with the coding not being completed yet. I wish someone would 
have mentioned that earlier rather than giving the impression that 
nothing was being done. Thank you!

**Comment by eliranwong** [comment]
@darrelwright You still do not understand.  Anyway, up to you.

**Comment by darrelwright** [comment]
Rather than telling someone they do not understand, as a developer it might be better to help us neophytes by showing and/or teaching us HOW to use UBA to accomplish our goals. That would go a lot further than implying we lack understanding. I really like the tool you are developing, but I do not like being told I don't understand and nothing being offered to help me learn.
