### ISSUE TITLE
LN-type lexicon not working

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#77]
A user emailed me to report that LN-type lexicon is not working, I will take a look into the issue.

**Comment by mooru** [comment]
Thanks for the great work. It will be great if this can be up fixed. LN is a great resource

**Comment by eliranwong** [comment]
can use context plugin https://github.com/eliranwong/UniqueBible_Plugins_Context/blob/main/Search%20LN.py.zip
