### ISSUE TITLE
Searching for Strongs number translated as a Greek/Hebrew word

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#770]
You had asked me to post an issue on this back in February, and I don't know if I ever did. Please let me know if this has been done. Thanks!

I am wanting to use UBA as my primary electronic bible. I come from having used theWord bible for over ten years. One of the main features I need a bible program to do is allow me to search for a Strongs number where is translated as a particular word. For example in theWord I enter the search phrase G746 TR αρχη and it returns 12 verses containing G746 translated as αρχη. How do I do that in UBA?

**Comment by otseng** [comment]
I added a plugin menu called "Search for word with Strongs".  Install that and open your TRx bible.  Enter "αρχη G746" in the search.

**Comment by darrelwright** [comment]
That works great as long as I don't use a bible that accents like "ἀρχῇ" 
from TRi or MIB. Using TRx and unaccented words it plays nicely.

Can I do similar search in OT?

**Comment by otseng** [comment]
Should be able to.  But I haven't tried it.

**Comment by darrelwright** [comment]
It appears to work with Greek bibles, such as ABP+, but am having 
trouble with Hebrew.

**Comment by darrelwright** [comment]
It does work but a bit of chore with getting the strong's number on 
correct side of Hebrew word. this did work: לאור.*H216 - well the string 
I entered actually is reversed with Hebrew showing on the right side.

**Comment by otseng** [comment]
I'll create another version so can enter the Greek/Hebrew word and the Strongs in two separate input fields.

**Comment by darrelwright** [comment]
Great! And thanks.

**Comment by otseng** [comment]
I've updated the plugin.  Delete the 'Search for word with Strongs.py` file.  Reinstall it, then restart UBA.

Or you can download it from here and unzip the file and replace it:
https://github.com/eliranwong/UniqueBible_Plugins_Menu/blob/main/Search%20for%20word%20with%20Strongs.zip

**Comment by darrelwright** [comment]
his plugin works great - not against MIB, but TRx for Greek and HSB for 
Hebrew. Not sure why the MIB does not work for Hebrew.

**Comment by otseng** [comment]
MIB actually does not contain Strongs number in the verses table.

**Comment by darrelwright** [comment]
Gotcha.

I do like the Strongs being separated from the word. Makes it much nicer 
to enter Hebrew data. Good plugin.

**Comment by darrelwright** [comment]
shortcut key?

**Comment by otseng** [comment]
Just rename the file and add whatever shortcut key you want.  So, for example, you can name it `Search for word with Strongs_Ctrl+Shift+1.py`

**Comment by darrelwright** [comment]
Okay, I can do that.

I am having an issue. I have the bible in one tab set to Interlinear-Gen 
6:4 and the next tab is MIB-Gen 6:4. The active tab is Interlinear, and 
when I pull the plugin and enter H5303 and  it returns 
REGEXSEARCH:::MIB:::\bהנפלים\b.*\bH5303\b, but it should be pulling from 
the Interlinear and not MIB. So either that needs fixing or we need a 
dropdown on the plugin to allowing selecting bible to search?

**Comment by otseng** [comment]
Can you create a separate issue to add a Bible dropdown to the search?
