### ISSUE TITLE
Update for AHLB

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#771]
You did an awesome job fixing fonts in the AHLB module. I have updated the AHLB and added all adopted roots (A2001 - A4020) to the end of the module. Could you fix the fonts in the adopted roots and modify the links in the text that point to these roots so they are hyperlinked? I'd sure appreciate it!

[AHLB.dct.mybible.zip](https://github.com/eliranwong/UniqueBible/files/7093792/AHLB.dct.mybible.zip)

**Comment by darrelwright** [comment]
Just checking if you can do this update on the AHLB?

**Comment by otseng** [comment]
Sure, I can take a look.

**Comment by otseng** [comment]
Not sure how I modify this.  For example, the content for A4001 is:
```
<p>  ( AG-RH ) Letter: (origin: Persian) [freq. 3] |kjv:
</p><p>letter| <a class='strong' href='#sH104'>H104</a></p>
```

I suppose the text at the beginning should have font association for it?

**Comment by darrelwright** [comment]
The only difference between what you had originally done to this file 
was I added all the adopted roots (those beginning with "A", so whatever 
you did to convert the original file should work with the add-on material?

**Comment by otseng** [comment]
I don't recall having to require to modify any of the data.

The data will need to have span tags in it like:
```
<span class='semear'>Erca%</span> (<span class='semmod'>Erca%</span> 
```

**Comment by darrelwright** [comment]
Can you do this?

**Comment by otseng** [comment]
> Can you do this?

It looks like it'll require manual changes every this is required.  So, I won't be able to do this.
