### ISSUE TITLE
Issue with Mini Control

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#772]
When I am opening another bible tab to another bible, I click the translation then click the bible reference. UBA opens another tab for each of those clicks. For example I have tab 1 set to MIB-Gen 1:1. I select TRx and UBA sets tab 2 to TRx-Gen 1. I click Bible and select Eph and UBA sets tab 3 to TRx-Eph 1:1. I then enter 6:10 and UBA sets the 4th tab to TRx-Eph 6:10.

I would prefer UBA only update the 2nd tab to TRx-Eph 6:10 when I press the Enter button. Is that possible? This is how the Master Control works.

**Comment by darrelwright** [comment]
I had both checked. When unchecking them the mini control opens a new 
bible and verse in one tab. When I recheck 
openBibleWindowContentOnNextTab it goes through several tabs.

**Comment by otseng** [comment]
> I had both checked. When unchecking them the mini control opens a new bible and verse in one tab. When I recheck openBibleWindowContentOnNextTab it goes through several tabs.

Yes, I believe this is how its designed to work.

**Comment by darrelwright** [comment]
But should only update the tab when pressing the Enter key after 
selecting Bible and reference, not after selecting each element. Correct?
