### ISSUE TITLE
UBA.py fails citing PySide2 missing yet pip list shows it installed

### ISSUE THREAD

**Issue by Denofalltrades** [eliranwong/UniqueBible#774]
# UBA.py fails "PySide2 missing", pip list shows installed

I downloaded the zip (primarily because I didn't feel like getting involved with github (too much like work!))

When it first failed I went to the link requirements link and *manually installed* every package, thinking maybe it can't do it itself.
* Install all dependencies required (listed at: https://github.com/eliranwong/UniqueBible/blob/main/requirements.txt)

------

**Windows 7 Professional SP1**
** python 3.8**
![My desktop environment](https://user-images.githubusercontent.com/66243905/131920836-6434ca16-eb5b-4e58-81f3-ff830ec04153.PNG)

------

# **uba.py fails, yet modules installed**  

## example 1  
Showing a standard "cmd" with uba.py failing and a "pip list" in Windows Powershell (Admin)

![Fails install-modules exist](https://user-images.githubusercontent.com/66243905/131920090-5963f4fa-6272-4dc1-87ac-af98a721e87f.PNG)

------

## example 2  
then, in case you think it was because of the cmd/powershell choices, here's it doing the same in the opposite windows
![Fails install-modules exist-reversed screens](https://user-images.githubusercontent.com/66243905/131920698-04ffed5e-27c7-4d11-a244-3c8cca8c102a.PNG)

**Comment by otseng** [comment]
Since you've manually installed the packages, can you try starting it with "python main.py"?   main.py does not use the virtual env, but uba.py does.
