### ISSUE TITLE
urllib3 version==1.25.8

### ISSUE THREAD

**Issue by WuQio** [eliranwong/UniqueBible#775]
In China, we cannot access Google Drive where UBA download assets(e.g. images.sqlite) so that we always use proxy. 
![uba download proxy](https://user-images.githubusercontent.com/17561985/131992973-01cf4501-e1b4-443e-9e32-b24933fd4985.png)

UBA use `gdown` and `gdown` use `urllib3` to access Google Drive. 
My version of `urllib3` is 1.26.6 and when I try to run  there is something wrong with it.

![urllib3 1 26 6](https://user-images.githubusercontent.com/17561985/131993201-c5111fa4-d15d-4b55-8522-f2726be602e8.png)
![uba failed UI](https://user-images.githubusercontent.com/17561985/131993271-a606e419-d7d5-4f6d-aba1-1ba98a82824b.png)

When I use  **urllib3(version == 1.25.8)**, It is OK.

![uba success](https://user-images.githubusercontent.com/17561985/131994138-849a9605-31af-4d5a-848d-4cc25ff36fd0.png)
![uba success UI](https://user-images.githubusercontent.com/17561985/131994154-bcd338c3-cca5-4253-a052-bbf02f89083e.png)

[https://blog.csdn.net/u010741112/article/details/115907497](url)
[https://github.com/urllib3/urllib3/issues/517](url)

**Comment by otseng** [comment]
Thanks for the info.  I'll research alternatives to using Google drive to store the data files.
