### ISSUE TITLE
Parallel view

### ISSUE THREAD

**Issue by derrikF** [eliranwong/UniqueBible#777]
Hello

In no program have I ever seen that in parallel mode verses are not parallel, this is only in UB. what causes this?

can you still make it readable? for example, this is in eSword

**Comment by otseng** [comment]
Not sure what you mean by parallel mode.  Do you mean the Bible window and the Study window are not synching?  

You can toggle the sync from the menu (Bible/Toggle Features/Sync Study Window Bible) or click the sync button on the top right.

<img width="800" alt="Screen Shot 2021-09-04 at 4 26 55 PM" src="https://user-images.githubusercontent.com/806056/132107293-f05e18db-c5f8-47a7-bebc-b8978e8a0b5a.png">

**Comment by derrikF** [comment]
But no one talked about synchronizing windows. We are talking about opening several Bibles in one window in the 'Parallel' mode (Master Control - the 'Parallel' button).

It seems logical to do as in TheWord - to make one mode (instead of Comparison and Parallel), so that the user himself chooses how to display the Bibles, columns or rows. And now Parallel is absolutely useless thing.

**Comment by darrelwright** [comment]
Yes, in theWord you can have several bibles (say BSB and TRx) open in parallel in the Bible window. Then you can view them as columns or rows. Does these pictures help?

And I think he may have missed that we have the Parallel view AND the Comparison view, which is the same as columns and rows he is referring to, right?

**Comment by derrikF** [comment]
![01](https://user-images.githubusercontent.com/4710022/132220781-8934fe31-e51e-475b-bfb1-21052f1b3cb0.png)
![02](https://user-images.githubusercontent.com/4710022/132220795-4858f357-3b52-4b74-b40b-6038005ddeac.png)

**Comment by otseng** [comment]
Yes, there are limitations of the parallel comparison - verses are not aligned and it only displays results as columns.

What if I add an option to only show the verse like this?

![Screenshot from 2021-09-06 09-35-17](https://user-images.githubusercontent.com/806056/132225598-8738aa12-2ebd-4f46-b086-4f061c6d79ad.png)

**Comment by derrikF** [comment]
![Безымянный](https://user-images.githubusercontent.com/4710022/132255421-267cbf2a-1077-4657-b68b-4c84d4b6552f.png)

**Comment by otseng** [comment]
Got it.  I'll see if I can make UBA align verses.  This will basically require a rewrite of the parallel code, so would take some time to implement.

**Comment by otseng** [comment]
Added the PARALLELVERSES command.  It is also in the master control.

![Screenshot from 2021-09-10 06-36-02](https://user-images.githubusercontent.com/806056/132841145-744abcd2-d182-4c2c-9f9b-779a676e760d.png)
