### ISSUE TITLE
how to parse verse links in a pdf

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#781]
I convert a pdf to book module, but the verses do not hyperlink. Am I missing something? Here's one that should hyperlink. On page 30 part way down is Psalm 19:1 that appears like it should hyperlink. Any ideas?

[Barnhouse - The Invisible War.pdf.zip](https://github.com/eliranwong/UniqueBible/files/7114715/Barnhouse.-.The.Invisible.War.pdf.zip)

**Comment by otseng** [comment]
This is currently not supported.  Not even sure if it's possible, but will require some research.
