### ISSUE TITLE
Syncing tabs in bible window

### ISSUE THREAD

**Issue by psuedochoco** [eliranwong/UniqueBible#785]
Am I posting in the right place? I can't seem to find a way to keep my bible tabs in sync. I want to be able to have more than one translation open in multiple bible tabs and be able to sync them all to the same verse. Am I missing something here?

**Comment by otseng** [comment]
Not sure what you mean by syncing the tabs.

**Comment by psuedochoco** [comment]
> Not sure what you mean by syncing the tabs.

I want to be able to have more than one translation open in multiple bible tabs and be able to sync them all to the same verse.

**Comment by otseng** [comment]
> I want to be able to have more than one translation open in multiple bible tabs and be able to sync them all to the same verse.

I see.  That's currently not possible.  The tabs are currently all independent.  

But that is an interesting idea and I'll consider adding that.

**Comment by psuedochoco** [comment]
Ok thanks. So basically when a verse in the active tab is highlighted there should be a means to toggle all tabs to sync to the same verse. Thank you again!

**Comment by eliranwong** [comment]
@psuedochoco 

I added a menu plugin named "Sync All Bible Window Tabs" to do what you mentioned above.

To install the plugin, go to "Resources > Add > GitHub Plugins Menu" and select "Sync All Bible Window Tabs" to install.

<img width="584" alt="add" src="https://user-images.githubusercontent.com/25262722/176236026-b14cff6e-4682-4b13-becc-9b299fcc890f.png">

To run it, go to "Plugins" and select "Sync All Bible Window Tabs" to run.

<img width="545" alt="Sync All Bible Window Tabs" src="https://user-images.githubusercontent.com/25262722/176236206-fea7610a-1d77-4b26-af9b-fa75483530ca.png">

Hope it help.

**Comment by eliranwong** [comment]
@psuedochoco 

I forgot to mention.  You need to update UBA to the latest version for the plugin to work.

Bty, you may want to try Material menu layout to get the most out of recent updates.
