### ISSUE TITLE
Need a change on formatted/simple

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#787]
When I click the formatted/simple style I would like 2 things:
1 - to have verses starting on new line
2 - to have verse highlight buttons showing on each row

I want verses on separate rows and the highlighting symbols as shown in 2nd screenshot.

I am assuming this screenshot is the formatted
![formatted-simple](https://user-images.githubusercontent.com/11500764/132944761-6d254d0d-d39d-42f2-93da-18d558f8afde.png)

and I am assuming this screenshot is the simple:
![formatted-simple 2](https://user-images.githubusercontent.com/11500764/132944865-94aa8afd-b2b4-4e57-bf10-61ba5be9df88.png)

**Comment by otseng** [comment]
To be clear, what you're asking for is to have highlight buttons on the formatted view?

**Comment by darrelwright** [comment]
Yes, and to be able to have verses on separate lines

**Comment by otseng** [comment]
I don't think this will be possible.  In effect, you want formatted to act just like simple.  However, the formatted is able to be formatted because each record is a chapter.  Whereas for the simple, each record is a verse.

**Comment by darrelwright** [comment]
mmm ... Okay, thanks. That makes sense
