### ISSUE TITLE
A reverse interlinear concept

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#788]
The attached image shows how the Step Bible does a reverse interlinear. In this case you hover over a word and the side panels show the additional information. Just a thought.

![reverse](https://user-images.githubusercontent.com/11500764/132966932-39855fbd-7f28-46da-897b-b815bc10709c.png)

**Comment by eliranwong** [comment]
I use MTB or MPB hoverning to relate translation to original words.

**Comment by darrelwright** [comment]
I need some help please. How are you using either MTB or MPB hovering to 
relate translation to original words. I am willing to modify how I work 
with things, but need help understanding what to do. Thanks!

**Comment by otseng** [comment]
Yeah, I don't see the MTB showing any info when hovering over the English words.  

The way I do reverse is to view Bibles with Strongs, then hover or click on the Strongs.
