### ISSUE TITLE
Problem displaying book chapters when checking "openBookInNewWindow"

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#791]
I attached the book "Larkin - Dispensational Truth". When I have checked "openBookInNewWindow" and do Ctl+L to show the book, then click chapter 6 it displays chapter 6 in a separate window. When I do Ctl_L and select it chapter 9 it will not display chapter 9 but rather chapter 6! If I close and restart UBA then open chapter 9 it displays a white screen, but if I turn off "openBookInNewWindow" and do the same thing chapter 9 opens fine in the study window. I do not understand what is happening!

[Larkin - Dispensational Truth.book.zip](https://github.com/eliranwong/UniqueBible/files/7169131/Larkin.-.Dispensational.Truth.book.zip)

**Comment by otseng** [comment]
Yes, something weird is going on, but not sure yet what's the problem.  It only seems to be a problem with this book.  All of my other books work fine.  It is also loading the data from the database correctly, so it's not a problem with fetching the chapter.  But, it's not able to display the chapter in the window, so it displays the previous chapter.  

I'm thinking it might be a data problem (too much data, invalid data).  Will continue to research when I have time.

**Comment by darrelwright** [comment]
This is puzzling. I broke the book down to several books: chapters 1-9, 
Chapter 9, Chapter 10, Chapter 11-19, chapters 20-34. The book 
containing chapters 20-34 plays beautiful. The book with chapters 11-19 
has issues with chapter 13. The book with chapter 10 has issues as does 
book with chapter 9. The book with chapters 1-8 plays beautifully.

If I uncheck "openBookInNewWindow" everything opens perfectly in the 
study window! So I don't see how it can be a problem with the book. When 
I check the full book, chapters 1-34, it plays beautifully in the study 
window!

**Comment by otseng** [comment]
It looks like it's a size issue.  If it's greater than 1565880 characters, then it won't load correctly from memory in the popup window.  I've dded code to load it from disk instead of memory if it's greater than 1 MB.

**Comment by darrelwright** [comment]
Thanks Oliver. It's a tad bit slower, but it works perfectly. I 
appreciate it!
