### ISSUE TITLE
KJV (American) audio bible name problem 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#792]
In this audio bible Philemon won't show the audio icon 
![image](https://user-images.githubusercontent.com/48617390/133598828-ee75a165-0a6a-46ed-8b73-66542f0b7079.png)

When i checked , it's mp3 file doesn't have `001` in its filename it should be `57_Philemon001.mp3` but it's `57_Philemon.mp3`

**Comment by otseng** [comment]
Thanks.  Updated the file.
