### ISSUE TITLE
No latency in curser hovering on link

### ISSUE THREAD

**Issue by psuedochoco** [eliranwong/UniqueBible#795]
Can you please tell me if their is a way to increase the latency of a hover action over a link? Problems with constantly activating the wrong link accidently due to no latency in curser hovering over a link. Is there a .config file I can tweak? Thanks.

**Comment by otseng** [comment]
There is currently no setting to change latency.  When you say activate link, to my knowledge, the only thing that happens is info about the hovered over item is displayed in the bottom window.  Do you want a delay for when this is displayed?

**Comment by psuedochoco** [comment]
Yes thank you. It would seem appropriate as the slightest accidental movement of a mouse-over will accidently change the contents of the window. It just seems a bit unforgiving! Just a thought.

**Comment by psuedochoco** [comment]
Hi again otseng. The problem more specifically is that the curser needs to 'hover' over the link in order to populate the lower window with the content. The problem is that this link is becomes active even if the curser doesn't hover, but happens to accidentally go over the link which is why you need to build in a few milliseconds of latency.

**Comment by otseng** [comment]
To change this will require significant changes since the hover over functionality is native javascript code.   Basically it's just doing what its supposed to be doing.

**Comment by psuedochoco** [comment]
Ok I can live with it.

**Comment by otseng** [comment]
Cool, closing issue.
