### ISSUE TITLE
Building a book duplicates information in the book

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#796]
I am having a serious problem. The first attachment is the folder containing the raw material of a book:
[How to do a Word Study - The Complete Guide.zip]

(https://github.com/eliranwong/UniqueBible/files/7206879/How.to.do.a.Word.Study.-.The.Complete.Guide.zip)

The second attachment is the book built from the first attachment.  As you can see the parts of the book is duplicated many times and I do not understand why. Can you help me?

[How to do a Word Study - The Complete Guide.book.zip](https://github.com/eliranwong/UniqueBible/files/7206886/How.to.do.a.Word.Study.-.The.Complete.Guide.book.zip)

**Comment by otseng** [comment]
Which parts are duplicated?

**Comment by darrelwright** [comment]
It starts with the section "Basis Word Study" down through "Word Study 
Prerequisites" - then repeats that section a number of times. Just look 
at the book I sent you then look at the raw material, and you will see 
it is duplicated a number of times inn the book.

**Comment by otseng** [comment]
I opened it in UBA and I don't see any repeats.  Also, I opened the data file with DB Browser and also don't see any repeats.  The file sizes of the raw uba and book files are also the same at 1.3 MB.

I wonder if it's some config setting in your UBA that is causing it.

**Comment by darrelwright** [comment]
Well, I removed config.py, rebuilt the book, and it still has duplicate 
sections as before. So I don't know what to do on that. Any ideas?

**Comment by otseng** [comment]
I think the problem is you have both a html and uba file in the folder when you build it.  Can you delete one of them and then rebuild?

**Comment by darrelwright** [comment]
The only thing in the folder that I can see is a uba file. When I open 
the zip that's all it shows. Where are you seeing an html file?

**Comment by otseng** [comment]
I was looking at the wrong folder.... ok, I think i've duplicated your issue.  Now just need to figure out what's the problem...

**Comment by darrelwright** [comment]
You know I appreciate you!

**Comment by otseng** [comment]
Give it a try now.

**Comment by darrelwright** [comment]
still duplicating data!

**Comment by darrelwright** [comment]
The same sections are repeated 3 times.

**Comment by otseng** [comment]
Here is file that I generated...
[How to do a Word Study - The Complete Guide.zip](https://github.com/eliranwong/UniqueBible/files/7228965/How.to.do.a.Word.Study.-.The.Complete.Guide.zip)

**Comment by darrelwright** [comment]
This file has the same duplicates that mine does!

**Comment by otseng** [comment]
Here's PDF of my output.  Not sure what is duplicated...

[word study.pdf](https://github.com/eliranwong/UniqueBible/files/7228983/word.study.pdf)

**Comment by darrelwright** [comment]
Well, in your PDF there is no duplicate text. Looking at your previous 
email with the zip file - it has duplicate text

**Comment by otseng** [comment]
Can you try opening this one?
[How to do a Word Study 2.zip](https://github.com/eliranwong/UniqueBible/files/7229108/How.to.do.a.Word.Study.2.zip)

**Comment by darrelwright** [comment]
That one looks good! What did you do?

**Comment by otseng** [comment]
All I did was rename my book.  

So, my fix is working correctly.  My guess is something is caching the old book content on your computer.  By renaming the book, it would not go to cache.  Or another guess is the update didn't work and you didn't get my code fix.

Do a `git log` and see if you see:
```
commit 391959909e0219f39bba79cc4807fda35b213eee (HEAD -> changes, origin/main, main)
Author: Oliver Tseng <otseng@yahoo.com>
Date:   Fri Sep 24 20:09:58 2021 -0400

    Ver 26.20; Fix repeating sections when building a book (#162)
    
    * Fix repeating sections when building a book
```

Can you also try renaming your source directory and rebuilding to generate a new book name?

**Comment by darrelwright** [comment]
That's fascinating. The git log returned same as yours. I renamed the 
folder, rebuilt the book and it came out beautifully. I will remember 
that on future books. Thanks!
