### ISSUE TITLE
vlc is not enabled 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#797]
Hi @otseng 
on my brother's system vlc app is installed and also installed using `pip3 install python-vlc` too.
but it's showing its not installed when running using `python main.py`
his system is Windows 8. And i just want to point out that his uniquebible folder is changed its location from `c:\` to `f:\App`.
is that the problem and how to fix it.
![image](https://user-images.githubusercontent.com/48617390/134325783-e8b92bbd-ac3d-42fa-b719-d9c8334f166e.png)

**Comment by otseng** [comment]
Don't have a windows computer to debug this, so will have to try out some things.

Can you try starting with "python uba.py"?
Can you make sure VLC is able to play a file natively?

**Comment by onegladiator4u** [comment]
> Can you try starting with "python uba.py"?

yeah i did earlier . Problem is not about starting unique bible app. App works . But mp3 don't work .
`Data-> Add->Github Bible Mp3 files` and `Library ->media player` didn't open also.


> Can you make sure VLC is able to play a file natively?

yes, we played an mp3 in vlc externally.

uba.py showed these. and opened the app
![image](https://user-images.githubusercontent.com/48617390/134385990-6c6286d2-54e6-4b9e-839b-92b3aadc5be2.png)

**Comment by otseng** [comment]
Can you try manually installing python-vlc?  

Activate venv, then run "pip3 install python-vlc"

**Comment by onegladiator4u** [comment]
yesterday i run these after deleting venv folder
```
python -m venv venv

.\venv\Scripts\activate

pip3 install gdown PySide2 PyPDF2 python-docx diff_match_patch googletrans

pip3 install -r requirements.txt
pip3 install python-vlc
python .\main.py
```
but didn't work .
i run it without admin of powershell . that's ok right ?
do i have to do try again ?
is `Activate venv` this the code to run first before `pip3 install python-vlc`

**Comment by otseng** [comment]
What you did looks correct.

Can you check for these issues?
https://stackoverflow.com/questions/42045887/python-vlc-install-problems
* Add libvlc.dll to path
* 32 vs 64 bit version of VLC

**Comment by onegladiator4u** [comment]
>     * 32 vs 64 bit version of VLC

This solved it brother. thank you . i installed 32 bit version in 64bit system .
