### ISSUE TITLE
Change in selecting items ...

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#799]
Is it possible to right-click an element and select a lexicon without having to highlight an item first. For example I have Eph 6:10 open in the MIB. I want to click on "κράτει", then click on indexes in the study window. Next I want to right-click on Eph 6:10 and select  Bible Resources, then select a lexicon. Currently I have to highlight Eph 6:10 before performing the remaining items. Can we change that?

**Comment by eliranwong** [comment]
No. text selection tells UBA what users look for
