### ISSUE TITLE
Search multiple book modules

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#8]
Need to search multiple book modules in same manner as multiple bibles.

**Comment by eliranwong** [comment]
search of multiple books is now supported through command line, will consider a gui later.

**Comment by eliranwong** [comment]
Thanks for suggestion.  I added a function search all book modules in this commit: https://github.com/eliranwong/UniqueBible/commit/1a6e656bc3f5c9ce3c04f7b8992ebb486cb515a1
