### ISSUE TITLE
Attempting to install http server on Android

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#800]
I am trying to install http server on Android, on my Amazon Fire tablet. It bombs with the error "ModuleNotFoundError: No module named 'github'". What should I do?

**Comment by otseng** [comment]
What version Python is it?

**Comment by darrelwright** [comment]
I finally got UBA to install and run via Termux on my laptop! This is 
pretty cool.

**Comment by darrelwright** [comment]
So how can copy my uba content to the web installation on my tablet?

**Comment by darrelwright** [comment]
I didn't read far enough! I have the transfer almost complete!

**Comment by otseng** [comment]
> I finally got UBA to install and run via Termux on my laptop! This is pretty cool.

What did you do to get it to work?

> So how can copy my uba content to the web installation on my tablet?

If you can transfer via SD card,  that would be easiest.

**Comment by darrelwright** [comment]
Well, I had installed everything again and it worked. Then I was following directions for copying my media (marvelData) to the tablet, it took over 30 Gb, tablet ran out of memory, so I deleted and reinstalled and now am stuck on no gitHub. Will try again today.
