### ISSUE TITLE
Tutorial video?

### ISSUE THREAD

**Issue by bartonhammond** [eliranwong/UniqueBible#802]
This is an amazing project, very impressive. I'm using the python desktop version.  I have the apps on the phone and they are straight forward but the desktop is a beast. I'm kind of lost trying to figure out how to use it properly.  Trying to wade through the documentation is  little cumbersome.   Is there a video available for tutorials?  I think that would be a great help.  I've been using e-sword but I think this is much more powerful but I haven't quite figured out things work.

**Comment by otseng** [comment]
No videos yet, but I think that'd be a great idea.  I'll start planning on creating some.

**Comment by otseng** [comment]
I've created a request for our users to submit videos:
https://github.com/eliranwong/UniqueBible/discussions/804

**Comment by otseng** [comment]
Video tutorials here:
https://github.com/eliranwong/UniqueBible/wiki/Video-Tutorials
