### ISSUE TITLE
Issue converting theWord ONT to UBA 

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#808]
The first file is the TW full bible:
[Greek+ OT Septuagint & NT Byzantine Textform 2005.ont.zip](https://github.com/eliranwong/UniqueBible/files/7233186/Greek%2B.OT.Septuagint.NT.Byzantine.Textform.2005.ont.zip)

This file is the converted UBA bible:

[Greek+ OT Septuagint & NT Byzantine Textform 2005.bible.zip](https://github.com/eliranwong/UniqueBible/files/7233201/Greek%2B.OT.Septuagint.NT.Byzantine.Textform.2005.bible.zip)

This image is the TW screenshot:
![TW](https://user-images.githubusercontent.com/11500764/134842343-3bf0e4a5-c946-45ae-b4bd-06e42feb68f6.png)

This image is the UBA screenshot:
![UBA](https://user-images.githubusercontent.com/11500764/134842377-45a5aeb8-756d-42aa-9075-25043da5b1c6.png)

I am not seeing the strong's or morphology data in the UBA conversion. Am I missing something?

**Comment by otseng** [comment]
Can you try selecting the import options: allow search for strongs, morphology codes, and interlinear bible?

Here's my screenshot:
![Screenshot from 2021-09-27 21-00-43](https://user-images.githubusercontent.com/806056/135005318-22216d86-f4ab-4ee4-b708-32007af8b330.png)

**Comment by darrelwright** [comment]
Fascinating! I had those selected previously, but somewhere they were 
unselected. I selected them, reimported the bible and it displays 
perfectly! Thank you. You can close that issue.
