### ISSUE TITLE
Word docx

### ISSUE THREAD

**Issue by psuedochoco** [eliranwong/UniqueBible#811]
I need to be able to somehow bookmark Word documents. I can bookmark an epub file but the scripture hyperlinks aren't parsed whereas they are in my Word documents. The Word document just opens at the beginning of the document making it extremely difficult to find where I left off.

**Comment by otseng** [comment]
I'm not sure this is possible.  Word docs are treated as one large file in UBA, whereas epub files have pages.

**Comment by psuedochoco** [comment]
Is there a way of parsing an epub file of my own? Have you a tool like eswords tool tip  utility to parse the Scripture. I'm not sure how it all works. Maybe highlighting a Word docx or something. I'm not a programmer.
