### ISSUE TITLE
Youtube downloader is not responding 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#831]
Hey bro,
i tried to download video using the downloader by clicking MP4
![image](https://user-images.githubusercontent.com/48617390/140478394-c45a9e5f-1dde-454f-8640-13382985b04b.png)

UBA is not responding . I checked the video directory . it's looks like a file is downloading and it's taking too much time . i have to end UBA to stop downloading . 
i also tried downloading via ths `+`
![image](https://user-images.githubusercontent.com/48617390/140478946-fe103c64-54c0-4c06-9bd6-79f9bc4775d6.png)

![image](https://user-images.githubusercontent.com/48617390/140479081-a41bc437-5be6-4386-bc5c-910c16285084.png)

Same problem

**Comment by otseng** [comment]
The library we are using has been abandoned.  
https://github.com/ytdl-org/youtube-dl

Looking into a replacement...

**Comment by otseng** [comment]
Replaced youtube-dl with yt-dlp.  Give that a try.  Only tested on Linux and Mac.

**Comment by onegladiator4u** [comment]
hi @otseng ,
i tried it . Now there's no option to download 
![image](https://user-images.githubusercontent.com/48617390/140692503-67eda7b6-eaab-42ef-9a49-766fe8eed696.png)

**Comment by otseng** [comment]
Can you try manually installing yt-dlp from:
https://github.com/ytdl-org/youtube-dl

**Comment by onegladiator4u** [comment]
> 
> 
> Can you try manually installing yt-dlp from: https://github.com/ytdl-org/youtube-dl

i'll try brother

**Comment by onegladiator4u** [comment]
i couldn't work it out brother @otseng 
i placed that exe file in python folder because it is already added in variables .
i also installed through pip3 install youtube-dl from unique bible . it was installed but didn't come up in UBA.

**Comment by otseng** [comment]
Try running the exe file to have it install the driver.

**Comment by otseng** [comment]
Ah OK.  

Are you able to manually run youtube-dl from the command prompt to download a video from Youtube?

**Comment by otseng** [comment]
Can you also try activating the venv and then running:
`pip install yt-dlp`

**Comment by onegladiator4u** [comment]
i first did `.\venv\Scripts\activate`
then `pip install yt-dlp`. is this the correct way ?
it showed that it was installed. but nothing changed in the toolbar yet.

**Comment by otseng** [comment]
Can you see if Python can load it?

Activate venv.
Start up python
type `import yt_dlp`

You should see something like this:
```
(venv) oliver@oliver-Aspire-VN7-791:~/dev/UniqueBible$ python3
Python 3.8.7 (default, Dec 21 2020, 21:23:03) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yt_dlp
>>> 
```

**Comment by onegladiator4u** [comment]
How should I do it ? is it using powershell?
i don't know python.
can you guide me? i have vscode.

**Comment by otseng** [comment]
Yes, use powershell.

Activate venv:
`.\venv\Scripts\activate`

Start python:
`python3`

You'll then see python interactive mode message.

```
Python 3.8.7 (default, Dec 21 2020, 21:23:03) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Type:
`import yt_dlp`

If you see this, then it's not able to find it:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'yt_dlp'
`

If you see nothing, then it was able to find it:

Type `Ctrl-D` to stop the interactive mode.

**Comment by onegladiator4u** [comment]
> Traceback (most recent call last): File "<stdin>", line 1, in <module> ModuleNotFoundError: No module named 'yt_dlp'

i got this message

**Comment by onegladiator4u** [comment]
bro something else happened after that . i updated python version 39 to python310.
i have a new folder for each version of python. i updated using Chocalatey GUI.
![image](https://user-images.githubusercontent.com/48617390/141614183-2c371944-79b7-4409-8c78-3cecca9b578f.png)

now i'm having errors 

![image](https://user-images.githubusercontent.com/48617390/141614195-c960ff7f-ea26-4b7b-825d-5c38bedb8bce.png)

**Comment by otseng** [comment]
> > Traceback (most recent call last): File "", line 1, in  ModuleNotFoundError: No module named 'yt_dlp'

OK.  So, something went wrong with the pip install yt-dlp

Can you try uninstalling it and installing it again and copy the results here?

Here's my results:
```
oliver@oliver-Aspire-VN7-791:~/dev/UniqueBible$ pip uninstall yt-dlp
Found existing installation: yt-dlp 2021.11.10.1
Uninstalling yt-dlp-2021.11.10.1:
  Would remove:
    /home/oliver/.local/bin/yt-dlp
    /home/oliver/.local/lib/python3.9/site-packages/yt_dlp-2021.11.10.1.dist-info/*
    /home/oliver/.local/lib/python3.9/site-packages/yt_dlp/*
    /home/oliver/.local/share/bash-completion/completions/yt-dlp
    /home/oliver/.local/share/doc/yt_dlp/README.txt
    /home/oliver/.local/share/fish/vendor_completions.d/yt-dlp.fish
    /home/oliver/.local/share/man/man1/yt-dlp.1
    /home/oliver/.local/share/zsh/site-functions/_yt-dlp
Proceed (y/n)? y
  Successfully uninstalled yt-dlp-2021.11.10.1
oliver@oliver-Aspire-VN7-791:~/dev/UniqueBible$ pip install yt-dlp
Collecting yt-dlp
  Using cached yt_dlp-2021.11.10.1-py2.py3-none-any.whl (2.4 MB)
Requirement already satisfied: websockets in /home/oliver/.local/lib/python3.9/site-packages (from yt-dlp) (10.0)
Requirement already satisfied: pycryptodomex in /home/oliver/.local/lib/python3.9/site-packages (from yt-dlp) (3.11.0)
Requirement already satisfied: mutagen in /home/oliver/.local/lib/python3.9/site-packages (from yt-dlp) (1.45.1)
Installing collected packages: yt-dlp
Successfully installed yt-dlp-2021.11.10.1
```

**Comment by otseng** [comment]
> bro something else happened after that . i updated python version 39 to python310. 

I haven't upgraded to python 3.10 yet, so it's not supported right now.

**Comment by onegladiator4u** [comment]
here's what I got . i got errors for both pip and pip3

```
PS F:\BIBLE STUDY\App\UniqueBible> pip uninstall yt-dlp
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'
PS F:\BIBLE STUDY\App\UniqueBible> pip3 uninstall yt-dlp
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pip3.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'
PS F:\BIBLE STUDY\App\UniqueBible>
```

**Comment by onegladiator4u** [comment]
> 
> 
> > bro something else happened after that . i updated python version 39 to python310.
> 
> I haven't upgraded to python 3.10 yet, so it's not supported right now.

ah ok. i uninstalled it. UBA working now

**Comment by otseng** [comment]
> here's what I got . i got errors for both pip and pip3

Looks pip is not installed.  Can you install pip and rerun?

**Comment by onegladiator4u** [comment]
Don't know whether it's installed correctly. i got
```
PS F:\BIBLE STUDY\App\UniqueBible> pip install yt-dlp
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
Collecting yt-dlp
  Using cached yt_dlp-2021.11.10.1-py2.py3-none-any.whl (2.4 MB)
Requirement already satisfied: websockets in c:\python39\lib\site-packages (from yt-dlp) (10.0)
Requirement already satisfied: mutagen in c:\python39\lib\site-packages (from yt-dlp) (1.45.1)
Requirement already satisfied: pycryptodomex in c:\python39\lib\site-packages (from yt-dlp) (3.11.0)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
Installing collected packages: yt-dlp
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Python39\\share'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
PS F:\BIBLE STUDY\App\UniqueBible>
```

But Youtube icon is showing . but didn't work .
when clicked on the plus icon it showed 
![image](https://user-images.githubusercontent.com/48617390/141694555-2c3b1352-5184-4ff4-9342-a2c7d4a07fc6.png)

mp3 and mp4 icons opened the respective folders

**Comment by otseng** [comment]
Did it actually download the video into your folder?

**Comment by onegladiator4u** [comment]
> 
> 
> Did it actually download the video into your video folder?

no, it didn't . it only opened the folder

**Comment by otseng** [comment]
Can you try to run these commands from command line?

```
yt-dlp -x --audio-format mp3 https://www.youtube.com/watch?v=NYhmWIOvebQ

yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 https://www.youtube.com/watch?v=NYhmWIOvebQ
```

**Comment by onegladiator4u** [comment]
i got this 
![image](https://user-images.githubusercontent.com/48617390/141929893-a2b24622-e239-4986-a4d8-41f814fa4416.png)

looks like something should be added on PATH
don't know what I should add

**Comment by otseng** [comment]
> 
> looks like something should be added on PATH don't know what I should add

Yes, it needs to be added to the path.  After you add it, then try rerunning the commands to manually download.

**Comment by onegladiator4u** [comment]
> 
> 
> > looks like something should be added on PATH don't know what I should add
> 
> Yes, it needs to be added to the path. After you add it, then try rerunning the commands to manually download.

which folder or file should I add? 
i added `F:\BIBLE STUDY\App\UniqueBible\venv\Lib\site-packages\yt_dlp` here. is that correct ?
![image](https://user-images.githubusercontent.com/48617390/142010616-7a8e5db9-1f3b-4561-854c-d03740d66f7d.png)
but didn't work .

**Comment by otseng** [comment]
Can you put the file yt-dlp.exe in the c:\python39 directory?  Then run from the command line:
`yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 https://www.youtube.com/watch?v=NYhmWIOvebQ`

**Comment by onegladiator4u** [comment]
exe file name is different . it is `youtube-dl.ex
I renamed it to yt-dlp.exe. now cmd line downloading. it's very slow in downloading 
UBA was still not responding. it may be because of slow downloading. it finished after a long time .
Thanks brother.

**Comment by otseng** [comment]
https://github.com/yt-dlp/yt-dlp

**Comment by onegladiator4u** [comment]
Should I update it?

**Comment by otseng** [comment]
Yes, please, I had posted the wrong url for the new library. It should be: https://github.com/yt-dlp/yt-dlp

The old one was using: https://github.com/ytdl-org/youtube-dl

**Comment by onegladiator4u** [comment]
Ok brother
