### ISSUE TITLE
Update to live filter

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#834]
I'd like an update to results of the live filter. I have 762 results returned by a search. When I apply a live filter the results are narrowed down to to 11 verses. I'd like to see an indicator showing the resultant verses for each applied filter.

**Comment by otseng** [comment]
What do you mean by "indicator showing the resultant verses for each applied filter"?

**Comment by darrelwright** [comment]
something showing many verses are left after applying a filter. Say 
after the search I had 734 verses; applying a filter reduces that to 122 
verses - I would like to see 122 verses showing after the734. Can you do 
that?

**Comment by darrelwright** [comment]
Awesome! Thank you my friend!
