### ISSUE TITLE
Whedon commentary images do not show

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#836]
The images in Whedon commentary only show as a little square box. You can see this in entry for Eph 6:11, but the same holds for all images. this is the official commentary downloaded from "Add|Bible Commentary"

**Comment by otseng** [comment]
You're right!  I don't see an image either.  Looks like the commentary was originally created incorrectly.  Only way to fix is to recreate the original.

**Comment by darrelwright** [comment]
Well, I pulled Whedon from BibleAnalyzer, where all images show 
correctly, converted it to MySword, imported into UBA, and the images do 
not show. hmmm

**Comment by otseng** [comment]
Give this one a try:
[cWhedon.commentary.zip](https://github.com/eliranwong/UniqueBible/files/7885155/cWhedon.commentary.zip)

**Comment by darrelwright** [comment]
That looks good! The images are showing nicely.
