### ISSUE TITLE
Opening Harmony parallels in bible window 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#837]
He bro,
i saw this in screenshot folder
<img width="960" alt="screenshot_book_chapter_features3" src="https://user-images.githubusercontent.com/48617390/142198116-01908f45-d527-47e7-ae72-b109c9ed0cf9.png">
how to open Harmony parallels in bible window  like this.
i can do it in study window only.
![image](https://user-images.githubusercontent.com/48617390/142198358-b588e37b-7b3d-430d-ad9c-0be74820c7f8.png)
is there a way to view two bible books in this view?

**Comment by otseng** [comment]
Right now, it can only be opened in study.  I'll add code to be able to select which one to open in.

**Comment by onegladiator4u** [comment]
Ok brother . Thank you @otseng

**Comment by otseng** [comment]
In Focus layout, toggle the "Open Bible References in Bible Window" button to switch between Bible and Study window.

![Screenshot from 2021-11-18 22-18-04](https://user-images.githubusercontent.com/806056/142559432-ea56eb52-fadd-4251-a5e5-71c1bf1da769.png)

**Comment by onegladiator4u** [comment]
got it brother . Thank You
