### ISSUE TITLE
UBA not maximized in windows

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#840]
I noticed that for a long time UBA is not starting up in maximized window. Earlier it was .
i tried to change it in shortcut file , but it didn't work . is it like that in mac and linux? or only in windows?

**Comment by otseng** [comment]
Can you try adding this in config.py?

`cli = False`

**Comment by onegladiator4u** [comment]
yes, it worked . it replaces the code on the next restart though
