### ISSUE TITLE
Overview in library using default titles 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#842]
Hey @otseng 
Do you remember adding an option for custom title for different bible versions like this?
![image](https://user-images.githubusercontent.com/48617390/142757363-d5b28ca2-99b4-49bc-84ca-c276ced65bb1.png)
this changes the titles in bible window 
![image](https://user-images.githubusercontent.com/48617390/142757396-1a70d013-b374-485d-84ec-3eed3227dc75.png)

But when opening library=>Overview in Aleph layout. titles are taken from `bibles.sqlite` not from `bibles_ml.sqlite`.
![image](https://user-images.githubusercontent.com/48617390/142757482-1fc789f5-902a-4a88-901f-af28fc43e4c8.png)

Also can you tell me where the Harmonies and Parallels are taken from ? is it from the Harmonies and Parallels book?

**Comment by otseng** [comment]
> titles are taken from bibles.sqlite not from bibles_ml.sqlite

This only applies to Bibles.

> is it from the Harmonies and Parallels book?

Yes.  All the titles are embedded in the Harmonies_and_Parallels.book file.

If you do want it changed, it would have to be modified in the Harmonies_and_Parallels.book file.

**Comment by onegladiator4u** [comment]
Ok brother. Thank you
