### ISSUE TITLE
Populate tab enhancement

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#848]
Hey Brother ,
Can you make improvements on populate tabs on startup?
Its currently taking History to populate. This is a problem. Because if we go through some verses inside a single tab, that's going to be in the history. Other tabs will be populated by these when restart occurs.
It would be nice to keep one record of verse for each tab in confg file or other files when that tab refreshes/change verse. Then you can populate tabs with that data. Hope you get the idea.

**Comment by otseng** [comment]
Makes sense.  I'll see if I can add that sometime.

**Comment by darrelwright** [comment]
There appears to a slight glitch. I open Rom 1:1 in BSB on tab 1, then Eph 6:10 in MIB on tab 2. I then close and reopen UBA. Tab 1 opens with MIB Rom 1:1 (not BSB), tab 2 opens with MIB Eph 6:10. So it appears that tab 1 does not open with correct bible.

**Comment by otseng** [comment]
Now, it's only storing what is actually ran as a command.  It doesn't store the additional information of what Bible is used.  So, if the Bible is not specified, it'll just open whatever happens to be the active Bible.

I'll see if it's possible to save the Bible being used also in the history.

**Comment by darrelwright** [comment]
Oliver, I appreciate you!

**Comment by otseng** [comment]
Now when there's a Bible or Study command, it'll add the Bible translation to the command in tabHistory

```
tabHistory = {'main': {'0': 'BIBLE:::OHGBi:::Exod 19:1',
          '1': 'BIBLE:::TRLIT:::Matt ',
          '2': 'BIBLE:::CUVs:::Matt 5:1',
          '3': 'BIBLE:::Greek+:::Exod 8:1',
          '4': 'BIBLE:::MOB:::psa'},
 'study': {'0': 'LEXICON:::H4007',
           '1': 'STUDY:::OHGBi:::Exod 19:1',
           '2': 'LEXICON:::H4422',
           '3': 'LEXICON:::H3427',
           '4': 'STUDY:::KJVx:::Exod 19:1'}}
```

**Comment by darrelwright** [comment]
Cool, that works great. Thanks!

**Comment by onegladiator4u** [comment]
Thanks brother . It's working great . Happy New year
