### ISSUE TITLE
Incorrect LSJ definition

### ISSUE THREAD

**Issue by Difflugia** [eliranwong/UniqueBible#854]
The LSJ definition for ἐπὶ (G1909) is wrong in a way that looks like a broken script was used to generate the data. The definition presented in UniqueBible is from ἐπαλείφω, but begins part way into the definition after the word ἐπὶ appears.

The definition of ἐπαλείφω in the source data begins with, "smear over, ἐπὶ δʼ οὔατʼ ἀλεῖψαι ἑταίρων Od. 12.47; ἐπʼ οὔατα πᾶσιν ἄλειψα ib. 177;"

The definition of ἐπὶ in UniqueBible.app begins with, "δ’ οὔατ’ ἀλεῖψαι ἑταίρων Od. 12.47; ἐπ’ οὔατα πᾶσιν ἄλειψα ib. 177;"

Other definitions that I spot-checked in UniqueBible.app look correct. The source data that I downloaded from https://github.com/Eumaeus/cite_lsj_cex/ appears to have a correct definition for ἐπὶ.

**Comment by eliranwong** [comment]
Thanks @Difflugia for report.  I will try to fix it.  Thanks.

**Comment by otseng** [comment]
I was looking into this and the LSJ.lexicon is what is in the [lsj_chicago.cex](https://github.com/Eumaeus/cite_lsj_cex/blob/master/lsj_chicago.cex) file.  

From lsj_chicago.cex file:

116543#urn:cite2:hmt:lsj.chicago_md:n37962#ἐπὶ1# ἐπὶ `A` δ' οὔατ' ἀλεῖψαι ἑταίρων Od. 12.47; ἐπ' οὔατα πᾶσιν ἄλειψα ib. 177; κηρὸν.. ὅν σφιν ἐπ' ὠσὶν ἄλειψ' ib. 200; ὁπόταν.. λεαίνῃ ἐπαλείφουσα τὰ τραχυνθέντα Pl. *Ti.* 66c; ἐ. χρόαν ἐτέραν ἐφ' ἑτέραν Arist. *Sens.* 440a9 : prov., τοὺς τοίχους τοὺς δύο ἐ. 'run with the hare and hunt with the hounds', Paus. 6.3.15 :— Pass., τὸ ἐπαλειφθέν Pl. *Ly.* 217c; ἐπαλήλιπται ὁ κύτταρος Arist. *HA* 555a6; χρυσὸς ἐπαληλιμμένος J. *AJ* 17.10.2. `A..2` metaph., from anointing athletes, **prepare for contest, stir up, irritate**, τινὰ ἐπί τινα Plb. 2.51.2; ἐ. τινάς τινι **set** them **upon** him, D.L. 2.38; μέθυσμα ἐ. θυμούς Ph. 1.680; so perh. in physical sense, **irritate**, Hp. *Mul.* 1.99, *Epid.* 5.20. 

From LSJ in UBA:

δ’ οὔατ’ ἀλεῖψαι ἑταίρων Od. 12.47; ἐπ’ οὔατα πᾶσιν ἄλειψα ib. 177; κηρὸν.. ὅν σφιν ἐπ’ ὠσὶν ἄλειψ’ ib. 200; ὁπόταν.. λεαίνῃ ἐπαλείφουσα τὰ τραχυνθέντα Pl. Ti. 66c; ἐ. χρόαν ἐτέραν ἐφ’ ἑτέραν Arist. Sens. 440a9: prov., τοὺς τοίχους τοὺς δύο ἐ. ’run with the hare and hunt with the hounds’, Paus. 6.3.15: -

1. Pass., τὸ ἐπαλειφθέν Pl. Ly. 217c; ἐπαλήλιπται ὁ κύτταρος Arist. HA 555a6; χρυσὸς ἐπαληλιμμένος J. AJ 17.10.2.

2. metaph., from anointing athletes, prepare for contest, stir up, irritate, τινὰ ἐπί τινα Plb. 2.51.2; ἐ. τινάς τινι set them upon him, D.L. 2.38; μέθυσμα ἐ. θυμούς Ph. 1.680; so perh. in physical sense, irritate, Hp. Mul. 1.99, Epid. 5.20.
