### ISSUE TITLE
Enhancement to Note Editor to create commentaries

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#857]
Currently I can build books using the Note Editor. I'd like the ability to create dictionaries and/or commentaries from within the Note Editor

**Comment by otseng** [comment]
Good idea.  Will see about working on this in the future.

**Comment by otseng** [comment]
Splitting this and making this only for commentaries and another for dictionaries

**Comment by otseng** [comment]
https://github.com/eliranwong/UniqueBible/wiki/Create-Commentary-from-Notes-files

**Comment by darrelwright** [comment]
There appears to be a problem between the writeup on creating a 
commentary and how to do it. The write-up says the individual chapters 
are "Gen_1", but the database has the book name as integer, so the name 
has to be "1_1". I'd prefer being able to enter "Gen_1". Can we change that?

**Comment by darrelwright** [comment]
Also it would nice to enter "Gen 6:4" and have the commentary open to 
that verse?

**Comment by otseng** [comment]
> There appears to be a problem between the writeup on creating a commentary and how to do it. The write-up says the individual chapters are "Gen_1", but the database has the book name as integer, so the name has to be "1_1". I'd prefer being able to enter "Gen_1". Can we change that?

Yes, you're supposed to do "Gen_1".  It converts it to a 1 automatically.
