### ISSUE TITLE
Enhancement to Search Morphology screen

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#868]
The SearchMorphology screen is really good, but could we expand it to include Bible collections allowing it to search morphologies in more than one bible? That would be awesome!

**Comment by otseng** [comment]
I assume you mean on master control.  It uses only a single source for that so there's no way to change it.  Eliran built the database for that so not sure what is the source text for it.

**Comment by darrelwright** [comment]
You assumed correctly..sigh...Thanks for responding. It would have been 
nice, but I understand.
