### ISSUE TITLE
Problem restarting UBA with multiple bible windows

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#871]
UBA1 shows uba open with 7 bible windows. UBA2 shows uba opening with those windows. The problem is where the Bible opens at. Notice MIB-Acts 17:27 tab. The Bible opens at Acts 17:1. this is the same for all tabs. Can we get tabs to open to the appropriate bible verse?
![uba1](https://user-images.githubusercontent.com/11500764/150443092-62ebe08c-4ff5-4274-a032-534b32450317.png)

![UBA2](https://user-images.githubusercontent.com/11500764/150443105-9cd1660b-2f11-4778-ad78-6503f9eec6f5.png)

**Comment by otseng** [comment]
I can reproduce this, but can't figure out how to fix this.  Will think about a possible solution.

**Comment by eliranwong** [comment]
I don't understand about this.  I can see the first screenshot go to the verse correctly.  What do you mean by UBA1 and UBA2, what different steps done to get different results?

**Comment by darrelwright** [comment]
This issue concerns having multiple Bible tabs. I delete the last tab, then I click the 4th tab which shows it being set to Mark 4:38. The tab opens to Mark 4:1. Mark 4:38 is highlighted, but I have to scroll down to the correct. The tabs when clicked should open with selected verse.

**Comment by darrelwright** [comment]
I have 7 tabs set up with various Bibles. I delete tab 7 so that tab is 
empty. I then click on tab 4 which is set to Mark 4:38. When tab 4 opens 
it should to verse Mark 4:38, but it opens to Mark 4:1 and I have to 
scroll down to verse 38.

Does that make sense?

**Comment by eliranwong** [comment]
I am trying to guess what do you mean "restart" issue in your title.

I guess you have "config.populateTabsOnStartup" set to True

Tabs are populated on startup.  When you activate a tab, the page is not scrolled to the active verse.

Am I right?

**Comment by darrelwright** [comment]
Sorry if I am a little frustrated. Here is the last email I sent:

"I have 7 tabs set up with various Bibles. I delete tab 7 so that tab is 
empty. I then click on tab 4 which is set to Mark 4:38. When tab 4 opens 
it should scroll to Mark 4:38, but it opens to Mark 4:1 and I have to 
scroll down to verse 38."

Yes I have populateTabsOnStartup set to true.And your last line is true 
- tabs auto-populate on startup, and when the tab is activated the page 
does not scroll to the active verse.

**Comment by eliranwong** [comment]
the issue title here is about restarting, so I will focus on it.

the restart issue with config.populateTabsOnStartup enabled is easy to be fixed.

Separate issues should be posted separately.

**Comment by eliranwong** [comment]
ver 30.94 should fix both issues you mentioned, I think:

https://github.com/eliranwong/UniqueBible/commit/efc4da62ec4b2c2b50ec344874cae0835589f8d2
