### ISSUE TITLE
Import theWord modules

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#9]
Could we have feature to import modules from theWord as we do with e-Sword and MySword.

**Comment by eliranwong** [comment]
would be nice addition, but not on my plan any soon.  UniqueBible can now import e-Sword, MyBible, MySword, marvel.bible modules.  I think it is more than enough.  you can convert the word modules to MySword first then to UB.  Alternatively, you or someone else is always welcome to contribute the coding to add this feature.
