### ISSUE TITLE
Add ability to share Bibles notes across computers

### ISSUE THREAD

**Issue by otseng** [eliranwong/UniqueBible#90]
I have UBA running on a Mac and a Linux laptop.  I'd like for a note created on the Mac to be also available on the Linux laptop and vice-versa.

**Comment by eliranwong** [comment]
are we using the same sqlite format for notes as we are using now.  I prefer to keep the current file format, otherwise, we do need to do migration of notes for users.  sqlite is also easy to be handled for sync and search.

also, one possible option to do the sync is to use gdown, which users already have if they install the app.

what do you think?

**Comment by otseng** [comment]
Format for the notes will remain the same.  The only difference is that it'll be stored in two locations, locally in the database and also somewhere in the cloud.  I'm thinking of using Github gist to store in the cloud.  One advantage of this is the possibility to view notes of others users and also comment on them.

**Comment by eliranwong** [comment]
Good.  I think github gist is better than google drive as general users in some countries, e.g. China, cannot use google service.

**Comment by eliranwong** [comment]
Does 25MB upload limit apply to github gist as well?

**Comment by otseng** [comment]
I found these:
https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota
https://docs.github.com/en/github/managing-large-files/working-with-large-files

As for storing notes, these should not apply, I'll be storing the notes individually.

**Comment by otseng** [comment]
Had to make a bunch of changes to do this.  I think it's best of some people can test this before merging to master.  I've created a branch with this code:

https://github.com/eliranwong/UniqueBible/tree/gist-synching

Here is documentation on notes and synching:

https://github.com/eliranwong/UniqueBible/wiki/Notes

**Comment by otseng** [comment]
I've completed basic testing and it's working. 

Feature is highly experimental so please backup your notes database prior to using this.

**Comment by otseng** [comment]
@eliranwong Go ahead and merge.  I'll create future PRs to add more features to this.

**Comment by eliranwong** [comment]
> @eliranwong Go ahead and merge. I'll create future PRs to add more features to this.

Got your message, will do.

**Comment by eliranwong** [comment]
@otseng merged.  thanks once again for helpful additions
