### ISSUE TITLE
After the last update bible windows not working 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#902]
After the restart except one tab every other tabs are empty . Tried to open bible using mini control and master control, but not opening bibles .
![image](https://user-images.githubusercontent.com/48617390/154428785-51d5b491-33ca-45dc-9a9b-d68a0b09a90b.png)

config file still has tab history 
![image](https://user-images.githubusercontent.com/48617390/154429292-df61f445-d729-48ba-ac3a-feafde175b5d.png)
![image](https://user-images.githubusercontent.com/48617390/154429735-2475448a-dc6e-4be5-95d6-7e2bbd31621e.png)

updated from version 26. => 28.04

**Comment by eliranwong** [comment]
can you try updating to the latest one and see.  I updated a bit earlier today.

**Comment by eliranwong** [comment]
did you ever set to use git pull for download, which is more reliable?

I guess some files are not properly updated.  The latest version is running very good.  The history records are loaded correctly on my side.

I just take a screenshot here.
<img width="1440" alt="Screenshot 2022-02-18 at 19 09 09" src="https://user-images.githubusercontent.com/25262722/154747249-adf94293-eaab-43aa-9461-04d4d688b3d1.png">

I suggest you may backup the marvelData folder and reinstall the latest version.  It is better to set git pull for updates.

**Comment by onegladiator4u** [comment]
> It is better to set git pull for updates.

Can you guide me how to do it?
Is it through GitHub desktop app?

**Comment by otseng** [comment]
Can you run an update now?  I've added version 28.08 that will redownload all the most recent file changes.

**Comment by eliranwong** [comment]
> > It is better to set git pull for updates.
> 
> Can you guide me how to do it? Is it through GitHub desktop app?

@otseng may help? I am not familiar with GitHub desktop

**Comment by onegladiator4u** [comment]
@eliranwong i cloned and ran it using uba.py in github app it gave error
![image](https://user-images.githubusercontent.com/48617390/154806676-56073520-05b2-4901-9b63-31b273f816b0.png)

**Comment by onegladiator4u** [comment]
same problem in old one. just checked 
![image](https://user-images.githubusercontent.com/48617390/154806762-da8b2079-8839-423b-8211-8c7e9fe8c8c8.png)

**Comment by otseng** [comment]
It might have something to do with the space in the path...

**Comment by onegladiator4u** [comment]
i'm not sure about that because it was like that earlier too. but app ran well. app didn't run earlier once because of space , but you fixed it if remember correctly. even though error occurs it works . if you see my issue on https://github.com/eliranwong/UniqueBible/issues/831 same error can be seen

**Comment by otseng** [comment]
Can you send your entire config.py file?

**Comment by onegladiator4u** [comment]
[config.zip](https://github.com/eliranwong/UniqueBible/files/8104033/config.zip)

**Comment by otseng** [comment]
I don't have a Bible names "MOV".  But once I renamed it to "MOB", it loaded for me.  Here's the part of the config.py I changed:
```
tabHistory = {'main': {'0': 'COMPARE:::ESV_MOB:::Prov 17:1',
          '1': 'BIBLE:::MOB:::Mark 13:1',
          '2': 'COMPARE:::ESV_MOB:::Prov 17:1',
          '3': 'COMPARE:::ESV_MOB:::Prov 17:1',
          '4': 'COMPARE:::ESV_MOB:::Prov 17:1'},
 'study': {'0': 'OPENVERSENOTE:::Prov 17:1',
           '1': 'COMMENTARY:::Matt 23:1',
           '2': 'COMMENTARY:::Matt 22:1',
           '3': 'COMMENTARY:::Matt 22:1',
           '4': 'COMMENTARY:::Prov 17:1'}}
```

**Comment by onegladiator4u** [comment]
Hi @otseng i changed it to ISV but problem persists. i got this error while trying to change book
![image](https://user-images.githubusercontent.com/48617390/154896793-241b5cf2-6c68-45de-98fe-53c74efe0cb8.png)

**Comment by otseng** [comment]
I recently got a Windows laptop and tried it on that and it also works for me.

Can you look in the bibles folder and check the file sizes of the files?  One of them might be corrupted and have a small file size.

**Comment by onegladiator4u** [comment]
Wow. yes there was a new bible named `ALL.bible`. Just deleted it. Its working now. I don't remember seeing that at all in bibles.
Thanks brothers @otseng @eliranwong
