### ISSUE TITLE
Three changes for gTTS

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#904]
1. I would like verses being read to not include the verse number
2. Can we have the language for gTTS default to the user's default language
3. Can we have the reading not pause when there is bracketed text, such as [something]. Currently there is a noticable pause on the first bracket.

**Comment by otseng** [comment]
The menu plugin "Toggle Verse Reference" can hide the verse numbers.

**Comment by eliranwong** [comment]
1. <<< answered by @otseng 
2. <<< can do and will probably do
3. will do, not difficult

**Comment by darrelwright** [comment]
I am having a problem with Toggle Verse Option.
I open UBA with all tabs cleared and focus set on tab Bible 7. I click Plugins and select Bible Reading Plan and then entry 51. Then I open it by clicking "Open in Tabs"
![Plan1](https://user-images.githubusercontent.com/11500764/155104172-3d065787-38bc-407b-bed9-8247af9a833a.png)

Next I click on tab 1 (which contains Exo 27:1), then Plugins Toggle Verse References. It changes tab 1 to Ps 24:1 and still shows verse numbers! If I understand correctly tab 1 should still show Exo 27:1 but should not be showing verse numbers.
![Plan2](https://user-images.githubusercontent.com/11500764/155105030-e168d5d6-37a6-4d72-8c91-c22480e3323e.png)

Am I not understanding something?

**Comment by otseng** [comment]
Yeah, it won't support that scenario.  UBA acts on the most recently active verse, regardless which window is being viewed.  So, it's not like a browser with many tabs that can act independently.

**Comment by darrelwright** [comment]
Any chance of having that changed? Otherwise how can one select a 
reading list, have verse numbers removed and have those verses read?

**Comment by darrelwright** [comment]
I think I understand what you're saying that uba does not have 
independent tabs. Thanks for clarifying for me.

**Comment by eliranwong** [comment]
> * <<< answered by @otseng
> * <<< can do and will probably do
> * will do, not difficult

gTTS features added to version 28.12; issue is closing now; please open new issue if something else.  thanks.
