### ISSUE TITLE
Fullscreen problem

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#919]
After clicking new full screen mode menu items won't appear visibly after clicking it. Same with mini control and main control. it's going behind the window.
i accidentally clicking About ->info without seeing the menu item inside fullscreen. i couldn't get back out of fullscreen. there was error sound wherever i click because i was inside `info` window. i couldn't see it's window and close it. Tried plug in my keyboard and `ctrl + alt + tab` and most shortcuts . couldn't close it. So i had to shutdown computer.
Also it would be better if we come out of full screen to normal maximize window. its becoming a small window like this. 
![image](https://user-images.githubusercontent.com/48617390/155499678-4c070d2f-e916-4724-83ca-7606eff5ac33.png)

we have to maximize again .

**Comment by otseng** [comment]
@onegladiator4u is this still an issue?

**Comment by onegladiator4u** [comment]
coming out of full screen now shows maximized window , that worked . Menu items and other windows like mini control won't show in front.

**Comment by otseng** [comment]
Can you send your config.py?

**Comment by onegladiator4u** [comment]
[config.zip](https://github.com/eliranwong/UniqueBible/files/9183296/config.zip)

**Comment by otseng** [comment]
On Linux, it's working fine.  I'll check it on Windows later...

**Comment by otseng** [comment]
I tried your config on Windows 11 and it seems to work fine for me.  In full screen mode, I can access the master and mini controls normally.
![Screenshot (1)](https://user-images.githubusercontent.com/806056/181859740-1506c0cb-a1e4-45ea-bb8d-d4ded3fa0ff3.png)
![Screenshot (2)](https://user-images.githubusercontent.com/806056/181859741-14163f98-78a2-4f8d-80aa-9b40b8fd72d8.png)
![Screenshot (3)](https://user-images.githubusercontent.com/806056/181859742-80192159-f0c2-40d8-93da-cb9effad76eb.png)

**Comment by onegladiator4u** [comment]
oh ok. Could that be because mine is windows 10?

**Comment by onegladiator4u** [comment]
i'll check it in my brother's lap also and i'll let you know

**Comment by onegladiator4u** [comment]
I think it's only on my PC. My brother has windows 8 and fullscreen works fine

**Comment by otseng** [comment]
Can also try updating your graphics driver.

**Comment by onegladiator4u** [comment]
> Can also try updating your graphics driver.

i'll try that .

**Comment by onegladiator4u** [comment]
My graphics is the latest one. just checked

**Comment by otseng** [comment]
On my windows computer (which is my latest computer purchase), I have the latest graphics driver, but whenever it goes to sleep, the screen constantly flickers.  So, I have to reboot every time I want to use it. In general, not too impressed with windoze.

**Comment by onegladiator4u** [comment]
Oh that's hard to hear it. I know windows is really messed up with bugs. I feel your pain. But i'm used to it and i'm comfortable with windows for more than 14 years. Whenever i run into problems like these i try to find the the problem and fix it. Answers will be somewhere for sure. It's also fun to solve problems 😄. Actually windows have too much on their hand than Mac because they have a lot of company products and devices and hardwares to deal with. In the case of Mac they have limited number of devices to troubleshoot. It's an excuse for windows but they really need to come up with fast updates.
My PC is 7 years old with old graphics card. I think they have stopped updates on it too. I'm not sure why this issue happens to me and don't know whether it's windows fault or apps fault. I just started learning Python now.

**Comment by otseng** [comment]
Yeah, there's way too many combinations to test for on Windows.  

I'm trying out an experiment of creating a binary release of UBA for Windows.  Could you test it and see if it works for you?  Details in this issue:  https://github.com/eliranwong/UniqueBible/issues/1167

**Comment by onegladiator4u** [comment]
> Yeah, there's way too many combinations to test for on Windows.
> 
> I'm trying out an experiment of creating a binary release of UBA for Windows. Could you test it and see if it works for you? Details in this issue: #1167

Yeah sure. It's power cut now here. I'll check when we have power and let you know.
Will any complications come to the other UBA app if I install this one on the same one ?

**Comment by otseng** [comment]
Sure thing, no hurry.  No complications will happen.  Everything will run from the unzipped directory.

**Comment by onegladiator4u** [comment]
Bitdefender gave an alert
![Uploading image.png…]()

**Comment by otseng** [comment]
Oh wow.  Apparently this is a known issue:
https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

Will need to see what I can do to fix this....

**Comment by onegladiator4u** [comment]
> Oh wow. Apparently this is a known issue: https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg
> 
> Will need to see what I can do to fix this....

ok ok, in the mean time i'll add it to whitelist
