### ISSUE TITLE
Verse numbers in formatted mode.

### ISSUE THREAD

**Issue by psuedochoco** [eliranwong/UniqueBible#920]
In formatted mode displaying Strong's numbers, how can I enable each verse to appear on a separate line like they do in simple mode?

**Comment by eliranwong** [comment]
Is the button switching to simple mode not working in your case?  What module are you using?  Is it possible you send me a copy for check?

**Comment by otseng** [comment]
> In formatted mode displaying Strong's numbers, how can I enable each verse to appear on a separate line like they do in simple mode?

What is your particular use case?  The purpose of simple mode is to display verses in a separate line and in formatted mode to display in paragraph mode.

**Comment by eliranwong** [comment]
I guess I understand what you mean.  If you want to display Strong numbers in simple mode, you need to select this option in the conversion process.

**Comment by psuedochoco** [comment]
I am using an KJV with Strong's numbers. In formatted mode  the text is continuous and the verse numbers are "impossible" to distinguish. I just need the verses to display on separate lines.

> I guess I understand what you mean. If you want to display Strong numbers in simple mode, you need to select this option in the conversion process.

Hi. I haven't a clue what you mean by 'conversion process'.

**Comment by psuedochoco** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/46863620/156381272-33f74d33-1a7d-4a91-8d03-cfb82a2ae564.png)

**Comment by psuedochoco** [comment]
> I guess I understand what you mean. If you want to display Strong numbers in simple mode, you need to select this option in the conversion process.

Ok I will try.
