### ISSUE TITLE
add optional speaker icon next to verse and chapter number for direct access of tts feature

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#927]
add optional speaker icon next to verse and chapter number for direct access of tts feature to read verse or whole chapter

**Comment by eliranwong** [comment]
may use &#9835; or &#9836; as icon

**Comment by eliranwong** [comment]
<img width="287" alt="Screenshot 2022-03-10 at 21 10 21" src="https://user-images.githubusercontent.com/25262722/157769945-e8f13e26-0f38-4a0c-b1df-45623beb8e1a.png">

**Comment by eliranwong** [comment]
added in https://github.com/eliranwong/UniqueBible/commit/c7cd0e4153be921be586505f2352482f9f55812e

**Comment by darrelwright** [comment]
Well, I downloaded NET fresh, downloaded the language files, restarted UBA, but I do not have the musical note showing!

![musical note](https://user-images.githubusercontent.com/11500764/157800909-dc897a08-c54e-4c9c-b121-d3eb48816814.png)

Am I missing something? I am running the desktop version on Linux Mint 20.3

**Comment by otseng** [comment]
I just added the ability to download NET MP3 from the menu.  Use this method instead.

**Comment by darrelwright** [comment]
I downloaded the mp3 files, I can play a verse with 
"READBIBLE:::NET:::Ps 23:1-6". I did a fresh download of the net bible, 
but I do not have the musical symbols shown in Eliran's post. How do I 
get those to show?
