### ISSUE TITLE
Dark theme color may need adjustment

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#94]
@otseng You may check colours of some dictionary entry with dark theme when you have time.

I ran this command:

> EXLB:::exlbp:::BP1349

and found lots of white color sections and text inside is not clear for reading.

**Comment by otseng** [comment]
Will take a look...

**Comment by eliranwong** [comment]
another example the boundaries of QComboBox and checkboxs cannot be seen clearly unless I magnify like these screenshot.

![Screenshot_20210206_235616](https://user-images.githubusercontent.com/25262722/107132543-dd00b300-68d7-11eb-91b4-dce44572b232.jpg)
![Screenshot_20210206_235735](https://user-images.githubusercontent.com/25262722/107132544-dd994980-68d7-11eb-9fad-7e29eeaccfaf.jpg)

**Comment by eliranwong** [comment]
another example.  it is the result of DIFF::: command

![Screenshot 2021-02-07 at 5 38 02 PM](https://user-images.githubusercontent.com/25262722/107154560-6e6d3500-696b-11eb-8808-134514ddf0c0.png)

**Comment by otseng** [comment]
Fixed the issues except for the MasterControl window.  I was not able to open it.

**Comment by eliranwong** [comment]
@otseng thanks very much for the fix.

MasterControl window is accessible if you edit config.py and set developer = True

then there will be an extra column "developer" on classical menu.  you can click "testing" to open master window.

![Screenshot 2021-02-10 at 7 50 02 AM](https://user-images.githubusercontent.com/25262722/107480787-11dd6600-6b75-11eb-8efa-39c1946ec5e6.png)

**Comment by otseng** [comment]
On Mac, it looks OK...

<img width="578" alt="Screen Shot 2021-02-10 at 8 27 28 AM" src="https://user-images.githubusercontent.com/806056/107516122-f2950780-6b79-11eb-88dc-0b4e9429e393.png">
<img width="465" alt="Screen Shot 2021-02-10 at 8 27 38 AM" src="https://user-images.githubusercontent.com/806056/107516126-f3c63480-6b79-11eb-80c1-d27ad70d8ffb.png">
<img width="562" alt="Screen Shot 2021-02-10 at 8 27 52 AM" src="https://user-images.githubusercontent.com/806056/107516128-f3c63480-6b79-11eb-9cbe-bebe6af1b68d.png">

**Comment by eliranwong** [comment]
@otseng thanks for the screenshots, are these screenshots taken with qt-material enabled or not?

**Comment by otseng** [comment]
Yes, qt-material is enabled.  Here are a few more screenshots.

<img width="783" alt="Screen Shot 2021-02-10 at 10 13 30 AM" src="https://user-images.githubusercontent.com/806056/107529376-ce8cf280-6b88-11eb-8486-1fe46d2df348.png">
<img width="1318" alt="Screen Shot 2021-02-10 at 10 14 04 AM" src="https://user-images.githubusercontent.com/806056/107529381-cfbe1f80-6b88-11eb-98be-ffacd0273d5d.png">

**Comment by otseng** [comment]
Thinking about it, shouldn't qt-material override dark mode theme?

**Comment by eliranwong** [comment]
> Thinking about it, shouldn't qt-material override dark mode theme?

@otseng  when qt-material is applied, it overrides:

- window style (which I newly added to classical menu)
- built-in "default" or "dark" theme "PARTLY"

"PARTLY" because the app still uses your css files for displaying html content.
if a dark qt-material theme is applied, dark.css is used
if a light qt-material theme is applied, default.css is used

it is good to have qt-material as an optional feature, users who do not have python version 3.7 can still use built-in default / dark theme.

**Comment by eliranwong** [comment]
@otseng in addition, from screenshots you given above, you may notice some buttons on Aleph Menu Layout become wider or fat after applying a qt-material theme.

because I don't like they occupy too many space, I fix the button width on classical menu layout.  You can compare button size (standard one, not full size one) on both Aleph and Classical menu layout on the same device.

**Comment by eliranwong** [comment]
@otseng  below is how your dark.css is used when a qt-material theme is applied, you may check file main.py 712-717:

# Apply theme style
if config.qtMaterial and config.qtMaterialTheme:
    apply_stylesheet(app, theme=config.qtMaterialTheme)
    config.theme = "dark" if config.qtMaterialTheme.startswith("dark_") else "default"
else:
    app.setPalette(Themes.getPalette())

Even you install qt-material, you can disable it by unchecking qt-material with "Select more" dialog
