### ISSUE TITLE
It is not nice the app freezes while downloading youtube video / audio

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#95]
It is not nice the app freezes while downloading youtube video / audio

Users cannot use the app while waiting for the download to complete.

I will try to separate the download process.

**Comment by otseng** [comment]
Or if it just had a spinner popup while it's downloading would also work.

**Comment by eliranwong** [comment]
> Or if it just had a spinner popup while it's downloading would also work.

sometimes, the file is to be downloaded is so large, and it takes too long to wait before I can continue reading, so I put in a separate process.  Users can still use the app while downloading.  After file is downloaded, the video / music folder is opened to notify users.

I just upload the fix: https://github.com/eliranwong/UniqueBible/commit/0b0fe6456dc48689281d9a38404ae592b941b887
