### ISSUE TITLE
audio/bibles/ does not cross platform, esp Windows

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#952]
I found path audio/bibles/ in some codes

It does not cross platform, esp Windows

I will try to fix, so Windows users can use audio bible features

**Comment by eliranwong** [comment]
@otseng  I fixed some, but in FileUtil file, there are some occurrences that I am afraid I may mess up your codes if I fix them.  can you take a look and fix them?  Thanks.

**Comment by otseng** [comment]
Will also fix icon showing up twice.
