### ISSUE TITLE
Hebrew chapters MP3

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#957]
https://www.sermon-online.com/contents/1327

A zip file of 718MB is available for download in the link above.

@otseng is it easy to integrate this to UBA for chapter-based audio bible?

**Comment by otseng** [comment]
Yes, it can be done.  I'll work on that.

**Comment by eliranwong** [comment]
Thank you.

**Comment by otseng** [comment]
What Bible should I associate it with?  OHGB?

**Comment by eliranwong** [comment]
> What Bible should I associate it with? OHGB?

WLC, the reading is on WLC (e.g. openScriptures uses WLC: https://github.com/openscriptures/morphhb).

OHGB uses BHS5, I will associate OHGB verse-by-verse to BHS5

**Comment by otseng** [comment]
Added WLC and WLCx Bibles and added WLC MP3 to downloads.
