### ISSUE TITLE
UBA not opening 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#96]
I couldn't open app again today by the shortcut or command line. I think I didn't restart after my last update yesterday .
When I open today, no response. So I run in powershell by `python .\main.py`
This is the result
![image](https://user-images.githubusercontent.com/48617390/107009682-61a9df00-67bb-11eb-80f3-4b01dcf01b4b.png)
What to do

**Comment by eliranwong** [comment]
@onegladiator4u 

From your screenshot, I guess the issue is nothing to do with the latest code.  Instead, I guess you have at least a file corrupted.  

First, try to manually download HebrewTransliteration.py from https://github.com/eliranwong/UniqueBible/blob/master/HebrewTransliteration.py and replace the one in your UniqueBible folder, i.e. C:\Users\John\Documents\UniqueBible

Please kindly let me know if it works again.

**Comment by onegladiator4u** [comment]
I replaced it bro. But line number only changed
![image](https://user-images.githubusercontent.com/48617390/107030864-49e05400-67d7-11eb-8fd6-abfffa011c8f.png)

**Comment by otseng** [comment]
Using a text editor, open the HebrewTransliteration.py file.

On the first line, it should be:
`import sys, re`

If not, the file has not been downloaded correctly.

**Comment by onegladiator4u** [comment]
Yes there's no first line like that. I downloaded the file from your link by right clicking and save link as.
I couldn't find a way to download it. Can you tell me how to download it properly? Thanks

**Comment by otseng** [comment]
Right click on this and save it:

https://raw.githubusercontent.com/eliranwong/UniqueBible/master/HebrewTransliteration.py

**Comment by otseng** [comment]
Right click on this and save it:

https://raw.githubusercontent.com/eliranwong/UniqueBible/master/HebrewTransliteration.py

**Comment by onegladiator4u** [comment]
That file is OK now I think but,
![image](https://user-images.githubusercontent.com/48617390/107034943-726b4c80-67dd-11eb-9815-24eeb996d2fc.png)

**Comment by onegladiator4u** [comment]
Should I clone whole app again?

**Comment by eliranwong** [comment]
> Should I clone whole app again?

It looks like some files in your venv folder not working.  If you don't want to set up everything again, you may try this first:

> pip uninstall python-docx

> pip install python-docx

**Comment by onegladiator4u** [comment]
Just did it bro. Same error occurs. Do I have to do these commands in Powershell Admin ?

**Comment by onegladiator4u** [comment]
My pip is outdated too. Is that ok?

**Comment by eliranwong** [comment]
> My pip is outdated too. Is that ok?

from your last screenshot, it looks like you file some files located in venv folder not working.  

it may take time to figure out which files not working.

it may be quicker to set up this folder again and have a fresh start.

I advise not to use Powershell Admin, use user Powershell

DELETE your venv folder FIRST

run in Powershell

> cd .\UniqueBible\

> python -m venv venv

> .\venv\Scripts\activate

> pip3 install -r requirements.txt

**Comment by onegladiator4u** [comment]
Ok. I'll try that

**Comment by onegladiator4u** [comment]
Thanks @eliranwong and @otseng .
It's working now.
