### ISSUE TITLE
integrate verse-by-verse MP3 on Open Hebrew Greek Bible

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#962]
integrate verse-by-verse MP3 on Open Hebrew Greek Bible

**Comment by eliranwong** [comment]
done!  created 2 sets of MP3 audio on Open Hebrew Greek Bible

https://github.com/eliranwong/MP3_OpenHebrewGreekBible_fast

https://github.com/eliranwong/MP3_OpenHebrewGreekBible_slow

**Comment by otseng** [comment]
Very nice!

**Comment by eliranwong** [comment]
Another sets of unique resources.
