### ISSUE TITLE
config missing listed in fileutils.py

### ISSUE THREAD

**Issue by dalpeh** [eliranwong/UniqueBible#966]
Hi
I see the update to fileutils was 20 hours ago, looks like something was missed ?? can't install error is below

PS C:\Users\dalpe\Bible> python .\UniqueBible\uba.py
PS C:\Users\dalpe\Bible> Traceback (most recent call last):
  File "C:\Users\dalpe\Bible\UniqueBible\main.py", line 9, in <module>
    from util.FileUtil import FileUtil
  File "C:\Users\dalpe\Bible\UniqueBible\util\FileUtil.py", line 1, in <module>
    import os, glob, config
ModuleNotFoundError: No module named 'config'

**Comment by otseng** [comment]
Fixed.

Can you run `python download.py util/FileUtil.py` and restart?

**Comment by dalpeh** [comment]
Hi - it is running now and it is installing the missing modules as your example in the notes shows 
Thank you for making this available
cheers
Donny

**Comment by dalpeh** [comment]
The Win 10 desktop app is up and running now
This is awesome 
Be  blessed
D

**Comment by dalpeh** [comment]
Just a note  - I had python on my system and github was installed via a windows based installer so I did not use your method with 

Get chocolatey ready!

Right-click Windows Icon, located at left lower corner

Select and open "Windows PowerShell (Admin)"

Enter the following command (copied from https://chocolatey.org/install):

Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

I used to do stuff like this and I should have been more detailed  :D
