### ISSUE TITLE
Improve interface: bible navigation

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#97]
At the moment, after bible version / passage button is click, a html page is displayed for bible navigation & features.

I think it may be nicer to have a dialog window instead of html page, so that the current chapter can remain on screen when users access bible navigation options / features.

It may also be quicker to navigate if drop down menus for versions/book/chapter/verse replacing current buttons.  I will try that on classic menu layout.

**Comment by eliranwong** [comment]
some progress

![Screenshot 2021-02-05 at 2 25 57 PM](https://user-images.githubusercontent.com/25262722/107046138-383e8280-67be-11eb-92e8-e6dc2e12591d.png)

**Comment by eliranwong** [comment]
more to play now ... you can try if you turn on developer option

![Screenshot 2021-02-06 at 4 32 06 PM](https://user-images.githubusercontent.com/25262722/107124628-ecaed600-689c-11eb-8c73-c4e7dbb34f4e.png)

**Comment by eliranwong** [comment]
What do you think about this one?  This will replace the current html menu

![Screenshot 2021-02-06 at 10 08 42 PM](https://user-images.githubusercontent.com/25262722/107130685-03b6ed80-68c8-11eb-8a83-2e9171a551ca.png)

**Comment by otseng** [comment]
Looks good.  The only change I can think of now is to say "Note" instead of "Notes".

**Comment by eliranwong** [comment]
they will come together in next upgrade

![Screenshot 2021-02-08 at 9 42 37 PM](https://user-images.githubusercontent.com/25262722/107285230-c2a11380-6a56-11eb-8368-1d219cbbf966.png)

**Comment by eliranwong** [comment]
Added a library tab

![Screenshot 2021-02-10 at 11 42 46 AM](https://user-images.githubusercontent.com/25262722/107506054-74def500-6b95-11eb-9cc2-01bbb5eaac65.png)

**Comment by eliranwong** [comment]
available from version 21.27
