### ISSUE TITLE
READBIBLE::: command issue, e.g. READBIBLE:::NET:::Ps 1:1-6:::default

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#973]
READBIBLE::: command issue, 

e.g. READBIBLE:::NET:::Ps 1:1-6:::default

when audio is played, sometimes Ps 1:2 is missed, sometimes Ps 1:3 is missed , ... even though all audio files are in place.

not consistent ...

@otseng can you take a look at this issue?  Thanks.

currently, I use READBIBLE::: command to do the read through the rest of the chapter feature.  if this command does not work, I may need to change.

**Comment by eliranwong** [comment]
strange ... I cannot reproduce it now ... closing this issue now

**Comment by eliranwong** [comment]
unfortunately, the issue reappears again.  don't know why, not consistent ... cannot always reproduce.

**Comment by eliranwong** [comment]
"Read through the rest of the chapter" now use READCHAPTER::: command instead.  see https://github.com/eliranwong/UniqueBible/commit/901b8d24f941af8a6e3751cfc3089a7d98d3835d

**Comment by otseng** [comment]
I could not reproduce in Mac.  There's an issue on Ubuntu and verse reading icon doesn't work at all.  
On Windows, it's a bit strange.  It doesn't skip verses for me, but it cuts off the ending of each verse.
