### ISSUE TITLE
create MP3 audio of every single Hebrew / Greek words of OHGB and integrate into MIB / dictionary

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#985]
create MP3 audio of every single Hebrew / Greek words of OHGB and integrate into MIB / dictionary

**Comment by eliranwong** [comment]
a screenshot

![Uploading Hebrew_word-by-word.png…]()

**Comment by eliranwong** [comment]
Hebrew word-by-word audio is available from version 28.61.

**Comment by eliranwong** [comment]
Greek word-by-word audio is coming soon ...

<img width="1440" alt="Greek_word-by-word" src="https://user-images.githubusercontent.com/25262722/161863284-e4a777de-5974-4de8-a5bf-8635c8efd97f.png">

**Comment by eliranwong** [comment]
Integrated into marvel bibles, such as MIB:

<img width="1440" alt="word-by-word_Hebrew_audio" src="https://user-images.githubusercontent.com/25262722/162021782-8a54c72a-0900-403f-bc45-6b7b59f4c3d1.png">
<img width="1440" alt="word-by-word_Greek_audio" src="https://user-images.githubusercontent.com/25262722/162021799-0e7f66fe-9dfd-4896-a48d-64dd422915b0.png">

**Comment by eliranwong** [comment]
uploaded; available from version 28.62

**Comment by otseng** [comment]
Very nice!
