### ISSUE TITLE
Mini Control on webtop

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#986]
The mini Control always opens in lower right corner on Linux. How do I get it to behave as on the desktop where I can resize and center on the screen? Here's how it looks:

![mini](https://user-images.githubusercontent.com/11500764/161479714-5c1d4cf7-bdb5-4e8c-a246-e44bf70d02b7.png)

**Comment by eliranwong** [comment]
I think you can resize in via config.py
